.\" man page create by R# package system.
.TH FBA 1 2000-Jan "lpsolve" "lpsolve"
.SH NAME
lpsolve \- Solve a FBA matrix model
.SH SYNOPSIS
\fIlpsolve(\fBmodel\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
Solve a FBA matrix model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.SH SEE ALSO
FBA
.SH FILES
.PP
simulators.dll
.PP
