.\" man page create by R# package system.
.TH FBA 1 2000-01-01 "matrix" "matrix"
.SH NAME
matrix \- create FBA model matrix
.SH SYNOPSIS
\fImatrix(\fBmodel\fR as any, 
\fBterms\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create FBA model matrix
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
FBA
.SH FILES
.PP
simulators.dll
.PP
