.\" man page create by R# package system.
.TH MODELS 4 2000-Jan "as.graph" "as.graph"
.SH NAME
as.graph \- 
.SH SYNOPSIS
\fIas.graph(\fBmodel\fR as any, 
\fBpropertyNames\fR as any = ["label","class","group.category","group.category.color"], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
cytoscape.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
