.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "bayes_abundance" "bayes_abundance"
.SH NAME
bayes_abundance \- 
.SH SYNOPSIS
\fIbayes_abundance(\fBdb\fR as <generic> DatabaseReader, 
\fBbayes\fR as <generic> AbundanceEstimate, 
\fBreads\fR as any, 
\fBrank\fR as any = ["genus","family","order","class","phylum","species"], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
