.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "bloom_filters" "bloom_filters"
.SH NAME
bloom_filters \- 
.SH SYNOPSIS
\fIbloom_filters(\fBrepo\fR as any, 
\fBncbi_taxonomy\fR as <generic> NcbiTaxonomyTree, 
\fBmin_supports\fR as double = 0.35, 
\fBcoverage\fR as double = 0.5, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
