.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "kraken_data" "kraken_data"
.SH NAME
kraken_data \- extract the kraken2 quantify result data
.SH SYNOPSIS
\fIkraken_data(\fBkraken_output\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
extract the kraken2 quantify result data
.PP
.SH OPTIONS
.PP
\fBkraken_output\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
