.\" man page create by R# package system.
.TH KEGG 1 2000-01-01 "write.keggReaction.rds" "write.keggReaction.rds"
.SH NAME
write.keggReaction.rds \- 
.SH SYNOPSIS
\fIwrite.keggReaction.rds(\fBreactions\fR as <generic> Object, 
\fBsaveRDS\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kegg
.SH FILES
.PP
bioconductor.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC genomics. 2020
