.\" man page create by R# package system.
.TH KEGG 1 2000-01-01 "write.keggMap.rds" "write.keggMap.rds"
.SH NAME
write.keggMap.rds \- 
.SH SYNOPSIS
\fIwrite.keggMap.rds(\fBmaps\fR as <generic> Object, 
\fBsaveRDS\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kegg
.SH FILES
.PP
bioconductor.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC genomics. 2020
