'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("xMPAlignment.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''	&lt;meta charset=&quot;utf-8&quot; /&gt;
        '''	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        '''	
        '''	&lt;title&gt;{TitleHere}&lt;/title&gt;
        '''
        '''	&lt;link rel=&quot;stylesheet&quot; href=&quot;./assets/style.css&quot;&gt;
        '''	&lt;link rel=&quot;stylesheet&quot; href=&quot;./assets/materialize.css&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body style=&quot;font-family:Microsoft YaHei&quot;&gt;
        '''	&lt;br /&gt;
        '''	&lt;br /&gt;
        '''	&lt;br /&gt;
        '''	&lt;br /&gt;
        '''	&lt;br /&gt;
        '''	&lt;div class=&quot;container about&quot;&gt;
        '''	{ContentHere}
        '''    &lt;/div&gt;
        '''
        '''	&lt;footer&gt;
        '''		&lt;div class=&quot;f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property index() As String
            Get
                Return ResourceManager.GetString("index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        ''' * Materialize v0.95.3 (http://materializecss.com)
        ''' * Copyright 2014-2015 Materialize
        ''' * MIT License (https://raw.githubusercontent.com/Dogfalo/materialize/master/LICENSE)
        ''' */
        '''.materialize-red.lighten-5 {
        '''  background-color: #fdeaeb !important; }
        '''
        '''.materialize-red-text.text-lighten-5 {
        '''  color: #fdeaeb !important; }
        '''
        '''.materialize-red.lighten-4 {
        '''  background-color: #f8c1c3 !important; }
        '''
        '''.materialize-red-text.text-lighten-4 {
        '''  color: #f8c1c3 !important; }
        '''
        '''.materialize-red.lighten-3 {
        '''  background-colo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property materialize() As String
            Get
                Return ResourceManager.GetString("materialize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to body, html
        '''{
        '''	background-color: #EDEDED !important;
        '''}
        '''
        '''.dark-primary-color    { background: #689F38; }
        '''.default-primary-color { background: #8BC34A; }
        '''.light-primary-color   { background: #DCEDC8; }
        '''.text-primary-color    { color: #212121; }
        '''.accent-color          { background: #FF9800; }
        '''.primary-text-color    { color: #212121; }
        '''.secondary-text-color  { color: #727272; }
        '''.divider-color         { border-color: #B6B6B6; }
        '''
        '''.intro
        '''{
        '''	text-align: center;
        '''	padding-top: 13%;
        '''	padding-bottom: 13%;
        '''	margin-bottom [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property style() As String
            Get
                Return ResourceManager.GetString("style", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
