.\" man page create by R# package system.
.TH UPSETPLOT 1 2000-01-01 "as.upsetData" "as.upsetData"
.SH NAME
as.upsetData \- 
.SH SYNOPSIS
\fIas.upsetData(\fBvennSet\fR as <generic> IntersectionData, 
\fBdesc\fR as boolean = TRUE, 
\fBintersectionCut\fR as integer = 0);\fR
.SH SEE ALSO
upsetPlot
.SH FILES
.PP
visualkit.dll
.PP
