.\" man page create by R# package system.
.TH UTILS 1 2020-10-29 "clear" "clear"
.SH NAME
clear \- Clears the console buffer and corresponding console window of display information.
.SH SYNOPSIS
\fIclear();\fR
.SH DESCRIPTION
.PP
Clears the console buffer and corresponding console window of display information.
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
