.\" man page create by R# package system.
.TH UTILS 1 2020-12-15 "debug" "debug"
.SH NAME
debug \- Debug an Expression
.SH SYNOPSIS
\fIdebug(\fBexpr\fR as <generic> Expression, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Debug an Expression
 
 apply for debug in Visual Studio, like a script breakpoint
.PP
.SH OPTIONS
.PP
\fBexpr\fB \fR\- any interpreted R expression.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
