.\" man page create by R# package system.
.TH UTILS 1 2020-10-29 "sleep" "sleep"
.SH NAME
sleep \- Suspends the current thread for the specified number of seconds.
.SH SYNOPSIS
\fIsleep(\fBsec\fR as integer);\fR
.SH DESCRIPTION
.PP
Suspends the current thread for the specified number of seconds.
.PP
.SH OPTIONS
.PP
\fBsec\fB \fR\- -
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
