.\" man page create by R# package system.
.TH UTILS 1 2020-11-09 "wget" "wget"
.SH NAME
wget \- http/ftp file download
.SH SYNOPSIS
\fIwget(\fBurl\fR as string, 
\fBsave\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
http/ftp file download
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- -
.PP
.PP
\fBsave\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
