.\" man page create by R# package system.
.TH R.GRDEVICES 1 2000-01-01 "bmp" "bmp"
.SH NAME
bmp \- 
.SH SYNOPSIS
\fIbmp(\fBplot\fR as string, 
\fBfilename\fR as string, 
\fBwidth\fR as integer = 480, 
\fBheight\fR as integer = 480, 
\fBunits\fR as string = "px", 
\fBpointsize\fR as integer = 12, 
\fBbg\fR as string = "white", 
\fBres\fR as string = "NA", 
\fBfamily\fR as string = "", 
\fBrestoreConsole\fR as boolean = TRUE, 
\fBtype\fR as string = "c("windows", "cairo")");\fR
.SH OPTIONS
.PP
\fBplot\fB \fR\- 画图的语句
.PP
.PP
\fBfilename\fB \fR\- the name Of the output file, up To 511 characters. The page number Is substituted If a C Integer format Is included In the character String, As In the Default, And tilde-expansion Is performed (see path.expand). (The result must be less than 600 characters Long. See postscript For further details.)
.PP
.PP
\fBwidth\fB \fR\- -
.PP
.PP
\fBheight\fB \fR\- -
.PP
.PP
\fBunits\fB \fR\- -
.PP
.PP
\fBpointsize\fB \fR\- -
.PP
.PP
\fBbg\fB \fR\- -
.PP
.PP
\fBres\fB \fR\- -
.PP
.PP
\fBfamily\fB \fR\- -
.PP
.PP
\fBrestoreConsole\fB \fR\- -
.PP
.SH SEE ALSO
R.grDevices
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH AUTHOR
Written by \fBamethyst.asuka@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2015
