.\" man page create by R# package system.
.TH R.GRDEVICES 1 2000-01-01 "png" "png"
.SH NAME
png \- 
.SH SYNOPSIS
\fIpng(\fBplot\fR as string, 
\fBfilename\fR as string, 
\fBwidth\fR as integer = 480, 
\fBheight\fR as integer = 480, 
\fBunits\fR as string = "px", 
\fBpointsize\fR as integer = 12, 
\fBbg\fR as string = "white", 
\fBres\fR as string = "NA", 
\fBfamily\fR as string = "", 
\fBrestoreConsole\fR as boolean = TRUE, 
\fBtype\fR as string = "c("windows", "cairo", "cairo-png")");\fR
.SH OPTIONS
.PP
\fBplot\fB \fR\- 画图的语句
.PP
.PP
\fBfilename\fB \fR\- -
.PP
.PP
\fBwidth\fB \fR\- -
.PP
.PP
\fBheight\fB \fR\- -
.PP
.PP
\fBunits\fB \fR\- -
.PP
.PP
\fBpointsize\fB \fR\- -
.PP
.PP
\fBbg\fB \fR\- -
.PP
.PP
\fBres\fB \fR\- -
.PP
.PP
\fBfamily\fB \fR\- -
.PP
.PP
\fBrestoreConsole\fB \fR\- -
.PP
.SH SEE ALSO
R.grDevices
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH AUTHOR
Written by \fBamethyst.asuka@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2015
