.\" man page create by R# package system.
.TH R.GRDEVICES 1 2000-01-01 "Write" "Write"
.SH NAME
Write \- Execute the statement that comes from the function @\fBM:RDotNET.Extensions.VisualBasic.SymbolBuilder.packages.Graphics.GraphicsDevice.bmp(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32,System.String,System.String,System.String,System.Boolean,System.String)\fR,
.SH SYNOPSIS
\fIWrite(\fBplot\fR as string);\fR
.SH DESCRIPTION
.PP
Execute the statement that comes from the function @\fBM:RDotNET.Extensions.VisualBasic.SymbolBuilder.packages.Graphics.GraphicsDevice.bmp(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32,System.String,System.String,System.String,System.Boolean,System.String)\fR,
 @\fBM:RDotNET.Extensions.VisualBasic.SymbolBuilder.packages.Graphics.GraphicsDevice.jpeg(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32,System.Int32,System.String,System.String,System.String,System.Boolean,System.String)\fR,
 @\fBM:RDotNET.Extensions.VisualBasic.SymbolBuilder.packages.Graphics.GraphicsDevice.png(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32,System.String,System.String,System.String,System.Boolean,System.String)\fR,
 @\fBM:RDotNET.Extensions.VisualBasic.SymbolBuilder.packages.Graphics.GraphicsDevice.tiff(System.String,System.String,System.Int32,System.Int32,System.String,System.Int32,System.String,System.String,System.String,System.String,System.Boolean,System.String)\fR
.PP
.SH OPTIONS
.PP
\fBplot\fB \fR\- -
.PP
.SH SEE ALSO
R.grDevices
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH AUTHOR
Written by \fBamethyst.asuka@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2015
