.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "find_motifs" "find_motifs"
.SH NAME
find_motifs \- find possible motifs of the given sequence collection
.SH SYNOPSIS
\fIfind_motifs(\fBfasta\fR as any, 
\fBminw\fR as integer = 8, 
\fBmaxw\fR as integer = 20, 
\fBnmotifs\fR as integer = -1, 
\fBnoccurs\fR as integer = 12, 
\fBseedingCutoff\fR as double = 0.65, 
\fBscanMinW\fR as integer = 6, 
\fBscanCutoff\fR as double = 0.8, 
\fBcleanMotif\fR as double = 0.5, 
\fBsignificant_sites\fR as integer = 4, 
\fBseeds\fR as any = \fB<NULL>\fR, 
\fBdebug\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
find possible motifs of the given sequence collection
.PP
.SH OPTIONS
.PP
\fBfasta\fB \fR\- 
 a fasta sequence collection for make the motif discovery, which should 
 contains multiple sequence.
. 
.PP
.PP
\fBminw%\fB \fR\- 
 the minimum motif width in chars.
. 
.PP
.PP
\fBmaxw%\fB \fR\- 
 the maximum motif width in chars.
. 
.PP
.PP
\fBnmotifs\fB \fR\- 
 A number for limit the number of motif outputs:
 
 + negative integer/zero: no limits[default]
 + positive value: top motifs with score desc
. 
.PP
.PP
\fBnoccurs%\fB \fR\- 
 the minimum occurrence number of the motif sites in the input sequence 
 collection for keep a motif.
. 
.PP
.PP
\fBseedingCutoff\fB \fR\- 
 the similarity cutoff threshold value for build the seed clusters.
. 
.PP
.PP
\fBscanMinW\fB \fR\- 
 the minimum width of the seed scan region.
. 
.PP
.PP
\fBscanCutoff\fB \fR\- 
 the similarity score cutoff threshold value of the seed scan.
. 
.PP
.PP
\fBcleanMotif\fB \fR\- 
 the motif cleaning threshold value for remove the low score motif 
 sites from the generated motif model.
. 
.PP
.PP
\fBsignificant_sites\fB \fR\- 
 the minimum number of the significant sites for keep a seed.
. 
.PP
.PP
\fBseeds\fB \fR\- 
 the pre-computed seed data for make the motifs, which can be a 
 [ScanFile](cref:T:SMRUCC.genomics.Analysis.SequenceTools.SequencePatterns.Motif.ScanFile) object that is created by the \fBcreate.seeds\fR 
 api, or a collection of the [HSP](cref:T:SMRUCC.genomics.Analysis.SequenceAlignment.BestLocalAlignment.HSP) seed object. If this 
 parameter is not specified, then the seeds will be discovered from the 
 input sequence data automatically.
. 
.PP
.PP
\fBdebug\fB \fR\- 
 print the debug log message of the motif discovery progress?
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the [SequenceMotif](cref:T:SMRUCC.genomics.Analysis.SequenceTools.SequencePatterns.SequenceMotif) motif object that 
 discovered from the given sequence collection, which is sorted by the 
 average motif site score in descending order.
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
