.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "find_motifs" "find_motifs"
.SH NAME
find_motifs \- 
.SH SYNOPSIS
\fIfind_motifs(\fBfasta\fR as any, 
\fBminw\fR as integer = 8, 
\fBmaxw\fR as integer = 20, 
\fBnmotifs\fR as integer = -1, 
\fBnoccurs\fR as integer = 12, 
\fBseedingCutoff\fR as double = 0.65, 
\fBscanMinW\fR as integer = 6, 
\fBscanCutoff\fR as double = 0.8, 
\fBcleanMotif\fR as double = 0.5, 
\fBsignificant_sites\fR as integer = 4, 
\fBseeds\fR as any = \fB<NULL>\fR, 
\fBdebug\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
