.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "motif.find_sites" "motif.find_sites"
.SH NAME
motif.find_sites \- 
.SH SYNOPSIS
\fImotif.find_sites(\fBmotif\fR as any, 
\fBtarget\fR as any, 
\fBcutoff\fR as double = 0.6, 
\fBminW\fR as double = 8, 
\fBidentities\fR as double = 0.85, 
\fBpvalue\fR as double = 0.05, 
\fBparallel\fR as boolean = FALSE, 
\fBmotif_name\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
