.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "top_sites" "top_sites"
.SH NAME
top_sites \- 
.SH SYNOPSIS
\fItop_sites(\fBsites\fR as <generic> MotifMatch[], 
\fBidentities\fR as <generic> Double = \fB<NULL>\fR, 
\fBpvalue\fR as <generic> Double = \fB<NULL>\fR, 
\fBminW\fR as <generic> Int32 = \fB<NULL>\fR);\fR
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
