.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "toPWM" "toPWM"
.SH NAME
toPWM \- convert the meme document to motif PWM model object
.SH SYNOPSIS
\fItoPWM(\fBmeme\fR as <generic> MEMEXml);\fR
.SH DESCRIPTION
.PP
convert the meme document to motif PWM model object
.PP
.SH OPTIONS
.PP
\fBmeme\fB \fR\- 
 a [MEMEXml](cref:T:SMRUCC.genomics.Interops.NBCR.MEME_Suite.DocumentFormat.XmlOutput.MEME.MEMEXml) meme document object that is read by the 
 \fBread.meme_xml\fR api.
. 
.PP
.SH VALUE
.PP
a vector of the PWM clr object.
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
