#' Fetch Protein Data from UniProt via REST API
#'
#' @description
#' Queries the UniProt database for protein information based on a search term
#' and an optional taxonomy ID. This function acts as a wrapper around the
#' UniProt REST API, allowing for the retrieval of either raw query results
#' or formatted protein sequences in FASTA format.
#'
#' @param q Character. The query term used to search UniProt. 
#'   This can be a protein name, gene name, UniProt accession, or any valid
#'   UniProt query string (e.g., "insulin", "P12345").
#'
#' @param tax_id Character or Integer. An optional NCBI taxonomy identifier 
#'   to restrict the search to a specific organism (e.g., 9606 for humans). 
#'   If NULL (default), the search is performed across all organisms.
#'
#' @param as_fasta Logical. Determines the format of the output.
#'   \itemize{
#'     \item If \code{TRUE} (default), the function extracts and returns 
#'       protein sequences in FASTA format.
#'     \item If \code{FALSE}, the raw result object from the REST query 
#'       is returned.
#'   }
#'
#' @return 
#' The return value depends on the \code{as_fasta} argument:
#' \itemize{
#'   \item If \code{as_fasta = TRUE}: Returns the protein sequences in FASTA 
#'     format (typically as a character vector or raw text).
#'   \item If \code{as_fasta = FALSE}: Returns the raw response object from 
#'     \code{UniProt::rest_query}.
#' }
#'
#' @examples
#' \dontrun{
#' # Search for insulin protein sequences in humans (TaxID: 9606)
#' fasta_seqs <- download_proteins(q = "insulin", tax_id = 9606)
#'
#' # Search for a specific accession and get the raw result object
#' raw_data <- download_proteins(q = "P69905", as_fasta = FALSE)
#' }
#'
#' @export
const download_proteins = function(q, tax_id = NULL, as_fasta = TRUE) {
    imports "UniProt" from "annotationKit";

    let result = UniProt::rest_query(q, tax_id);

    if (as_fasta) {
        UniProt::extract_fasta(result);
    } else {
        result;
    }
}

#' Make a KEGG GSEA background from UniProt protein tables and KEGG KO links
#'
#' @description
#' `uniprot_background` builds a GSEA background model by integrating:
#' \itemize{
#'   \item A protein table exported from UniProt (e.g. via the “proteinTable” tool).
#'   \item KEGG gene–KO mappings obtained from the KEGG REST API `link/ko` endpoint.
#' }
#' The function maps proteins (rows in `proteinTable`) to KEGG Orthology (KO) identifiers,
#' then to KEGG reference pathways, and finally constructs a background object suitable
#' for enrichment analysis with the `gseakit` framework.
#'
#' @param proteinTable Data frame. A protein table exported from UniProt.
#'   It should contain at least the following columns (names may vary):
#'   \itemize{
#'     \item A gene/protein identifier column specified by `id_key`.
#'     \item `name`: protein name.
#'     \item `geneName`: gene symbol or primary gene name.
#'     \item `KEGG`: KEGG cross-reference identifiers (optional but recommended).
#'   }
#'   If `id_key = "row.names"` or `"0"`, the row names of `proteinTable` are used
#'   as the gene identifier for linking to KO mappings.
#'
#' @param ko_maps Either a data frame or a directory path:
#'   \itemize{
#'     \item If a data frame: must contain columns `kegg_id` and `KO`, representing
#'       mappings between KEGG gene identifiers (e.g. `taes:803091`) and KO identifiers
#'       (e.g. `ko:K01810`). This is the expected format after parsing KEGG `link/ko`
#'       results with columns named `c("kegg_id", "KO")`.
#'     \item If a directory path: the directory is assumed to contain text files
#'       generated by previous calls to `link_ko` (or directly to the KEGG REST API
#'       `https://rest.kegg.jp/link/ko/...`) . Each file should be a tab-delimited
#'       table with two columns: KEGG gene ID and KO ID. These files are read and
#'       combined into a single `kegg_id`–`KO` mapping data frame.
#'   }
#'
#' @param id_key Character. Name of the column in `proteinTable` that contains the
#'   gene/protein identifier used to link to the KO mappings. Special values:
#'   \itemize{
#'     \item `"row.names"` or `"0"`: the row names of `proteinTable` are used as
#'       identifiers; a new column `id_key` is created with these row names.
#'   }
#'
#' @return An object of class `Background` from the `gseakit` framework, which
#'   represents a GSEA background model (see `as.background`). Conceptually, the
#'   returned object is a collection of clusters, where each cluster corresponds
#'   to a KEGG pathway or map, and each cluster entry contains protein-level
#'   annotations (identifier, name, alias, KEGG, UniProt) for the genes in that
#'   pathway.
#'
#' @details
#' The function performs the following steps:
#' \enumerate{
#'   \item If `ko_maps` is a directory, reads all `.txt` files inside it, expecting
#'     them to be KEGG `link/ko` results (tab-delimited: `kegg_id` \t `KO`), and
#'     combines them into a single data frame.
#'   \item Loads a standard reference KO set via `background::KO_reference()` and
#'     converts it to a gene set list using `as.geneSet`.
#'   \item Groups the `kegg_id`–`KO` mapping by KO and creates a lookup list from
#'     each KO to its associated KEGG gene IDs.
#'   \item Normalizes `proteinTable` into a data frame and ensures the identifier
#'     column specified by `id_key` exists (using row names if requested).
#'   \item For each KEGG reference pathway (cluster):
#'     \itemize{
#'       \item Parses the pathway ID and name from the cluster identifier
#'         (expected format `"pathway_id - pathway_name"`).
#'       \item Retrieves the set of KO identifiers associated with that pathway.
#'       \item Uses these KO identifiers to look up the corresponding KEGG gene IDs
#'         from the `ko_maps` lookup.
#'       \item Maps those KEGG gene IDs to rows in `proteinTable` and builds a
#'         data frame with columns:
#'         `xref` (gene identifier), `name`, `alias`, `KEGG`, `uniprot`.
#'       \item Wraps this data frame as a `gsea_cluster` object.
#'     }
#'   \item Collects all non-NULL clusters and converts them into a `Background`
#'     object via `as.background`.
#' }
#'
#' @examples
#' \dontrun{
#' # Example: build background from a UniProt protein table and a directory of
#' # KEGG link/ko results
#'
#' # 1) UniProt protein table (exported via the UniProt "proteinTable" tool)
#' prot_tbl <- read.delim("uniprot_proteins.tsv")
#'
#' # 2) Directory containing files from link_ko or direct KEGG REST calls, e.g.
#' # https://rest.kegg.jp/link/ko/taes:803091+taes:803092+taes:123456
#' ko_dir <- "./kegg_ko_links"
#'
#' # 3) Build background model
#' bg <- uniprot_background(
#'   proteinTable = prot_tbl,
#'   ko_maps      = ko_dir,
#'   id_key       = "row.names"   # use row names of prot_tbl as identifiers
#' )
#'
#' # Inspect the background object
#' str(bg)
#' }
#'
#' @seealso
#' \code{\link{link_ko}} for generating KEGG `link/ko` result files;
#' \code{\link{as.background}} and the `gseakit` framework for the
#' `Background` class.
#'
#' @export
const uniprot_background = function(proteinTable, ko_maps, id_key = "row.names") {
    imports "background" from "gseakit";

    if (!is.data.frame(ko_maps)) {
        # load gene_id map to KO dataframe from local repository directory files
        message("load document files of link ko from a local directory...");

        ko_maps = list.files(ko_maps, pattern = "*.txt");
        ko_maps = lapply(tqdm(ko_maps), file => {
            let link_ko = read.table(
                file, row.names = NULL, header = FALSE, 
                check.names= FALSE, 
                sep = "\t"
            );
            
            if (ncol(link_ko) != 2) {
                NULL;
            } else {
                colnames(link_ko) = c("kegg_id","KO");
                link_ko;
            }
        });
        ko_maps = bind_rows(ko_maps);
    }

    # load standard reference KO map as background
    let ko = background::KO_reference();
    let koSet = as.geneSet(ko);

    message("inspect of the reference KO set:");
    str(koSet);

    ko_maps = ko_maps
    |> groupBy("KO") 
    |> lapply(link => link$kegg_id)
    ;

    # message("inspect of the gene id to ko mapping:");
    # str(ko_maps);

    proteinTable = as.data.frame(proteinTable);
    
    # id_key is the gene id of the ko_maps
    if (id_key == "row.names" || id_key == "0") {
        id_key = "id_key";
        proteinTable[,"id_key"] = rownames(proteinTable);
    } else {
        proteinTable[,"xref_id"] = rownames(proteinTable);
    }

    proteinTable = proteinTable |> groupBy(id_key);

    message("processing background gene cluster models...");

    let clusters = as.list(names(koSet), names = names(koSet)) 
    |> tqdm()
    |> lapply(function(map_id) {
        # map_id is string in pattern:
        # pathway_id - pathway_name
        # parsed as tagged value with - as delimiter
        # 
        # $pathway_id
        # [1] pathway_name
        let map_info = tagvalue(map_id, "-", as.list = TRUE);
        # get a list of reference ko in current reference map
        let ko_ids   = `ko:${koSet[[map_id]]}`;
        # get gene id set from ko_maps via reference ko id list
        let geneset  = ko_maps[ko_ids];

        if (length(geneset) == 0) {
            return(NULL);
        } else {
            # get protein information from proteinTable list
            # via the mapped gene id
            geneset = unique(unlist(geneset));
            geneset = proteinTable[geneset];

            if (length(geneset) > 0) {
                # combined groupped dataframe partitions as dataframe
                geneset = bind_rows(geneset);
                geneset = data.frame(
                    xref = geneset[,"xref_id"],
                    name = geneset$name,
                    alias = geneset$geneName,
                    KEGG = geneset$KEGG,
                    fullName = geneset$fullName,
                    EC_number = geneset$EC_number
                );

                return(gsea_cluster(
                    x = geneset,
                    clusterId = names(map_info), 
                    clusterName = unlist(map_info)
                ));
            } else {
                return(NULL);
            }
        }
    }) |> which(c -> !is.null(c));

    # cast the gene cluster collection to gsea background model
    as.background(clusters);
}

