.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-1月 "motif_search" "motif_search"
.SH NAME
motif_search \- 
.SH SYNOPSIS
\fImotif_search(\fBdb\fR as <generic> PWMDatabase, 
\fBsearch_regions\fR as any, 
\fBfamily\fR as any = \fB<NULL>\fR, 
\fBidentities_cutoff\fR as double = 0.8, 
\fBminW\fR as double = 0.85, 
\fBtop\fR as integer = 3, 
\fBpermutation\fR as integer = 2500, 
\fBtqdm_bar\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
TRNtoolkit.dll
.PP
