.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-1月 "read.footprints" "read.footprints"
.SH NAME
read.footprints \- read a footprint site model data file
.SH SYNOPSIS
\fIread.footprints(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read a footprint site model data file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path of the footprint site csv table file, which contains the 
 motif site location data and the downstream gene information of each site.
. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.Data.Regprecise.FootprintSite\fR object that is loaded from the 
 given csv table file.
.PP
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
TRNtoolkit.dll
.PP
