.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-1月 "read.regulations" "read.regulations"
.SH NAME
read.regulations \- read a regulation prediction result file
.SH SYNOPSIS
\fIread.regulations(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read a regulation prediction result file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path of the regulation footprint csv table file, which could be 
 created by the \fBwrite.regulations\fR api.
. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.Data.Regprecise.RegulationFootprint\fR 
 object that is loaded from the given csv table file, each object is a 
 regulation network edge of the regulator to its regulated target gene.
.PP
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
TRNtoolkit.dll
.PP
