.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-1月 "regulation.footprint" "regulation.footprint"
.SH NAME
regulation.footprint \- 
.SH SYNOPSIS
\fIregulation.footprint(\fBregulators\fR as any, 
\fBmotifLocis\fR as <generic> FootprintSite[], 
\fBregprecise\fR as <generic> TranscriptionFactors, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
TRNtoolkit.dll
.PP
