.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-1月 "write.regulations" "write.regulations"
.SH NAME
write.regulations \- 
.SH SYNOPSIS
\fIwrite.regulations(\fBregulationFootprints\fR as any, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
TRNtoolkit.dll
.PP
