.\" man page create by R# package system.
.TH BASE 4 2020-11-09 "impute" "impute"
.SH NAME
impute \- impute for missing values
.SH SYNOPSIS
\fIimpute(\fBrawMatrix\fR as <generic> DataSet[], 
\fBbyRow\fR as boolean = TRUE, 
\fBinfer\fR as <integer> InferMethods = [Average]);\fR
.SH DESCRIPTION
.PP
impute for missing values
.PP
.SH OPTIONS
.PP
\fBrawMatrix\fB \fR\- -
.PP
.PP
\fBbyRow\fB \fR\- -
.PP
.PP
\fBinfer\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
R.base.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
