.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "seq.dist" "seq.dist"
.SH NAME
seq.dist \- Create a distance matrix for a given sequence collection
.SH SYNOPSIS
\fIseq.dist(\fBseqs\fR as any);\fR
.SH DESCRIPTION
.PP
Create a distance matrix for a given sequence collection
.PP
.SH OPTIONS
.PP
\fBseqs\fB \fR\- -. 
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
