.\" man page create by R# package system.
.TH STRINGWEBAPI 1 2000-1月 "downloads.gene_ids.interaction" "downloads.gene_ids.interaction"
.SH NAME
downloads.gene_ids.interaction \- 
.SH SYNOPSIS
\fIdownloads.gene_ids.interaction(\fBidList\fR as <generic> IEnumerable`1, 
\fBEXPORT\fR as string = "./");\fR
.SH OPTIONS
.PP
\fBidList\fB \fR\- -. 
.PP
.SH VALUE
.PP
返回成功的个数
.PP
.SH DETAILS
.PP
http://string-db.org/api/psi-mi/interactions?identifier=XC_1184
.PP
.SH SEE ALSO
stringWebApi
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
