.\" man page create by R# package system.
.TH CIRCOS 2 2000-01-01 "save" "save"
.SH NAME
save \- Save the circos plots configuration object as the default
.SH SYNOPSIS
\fIsave(\fBcircos\fR as <generic> CircosConfig, 
\fBdirectory\fR as string);\fR
.SH DESCRIPTION
.PP
Save the circos plots configuration object as the default 
 configuration file: \fBcircos.conf\fR.
 
 this function will always save the entire circos document into
 the given directory location.
.PP
.SH OPTIONS
.PP
\fBcircos\fB \fR\- -
.PP
.PP
\fBdirectory\fB \fR\- 
 a required directory location for save the entire circos documents.

.PP
.SH SEE ALSO
circos
.SH FILES
.PP
circoskit.dll
.PP
.SH AUTHOR
Written by \fBmartink@bcgsc.ca\fR
.SH COPYRIGHT
Copyright ©  2019
