.\" man page create by R# package system.
.TH BIOSEQ.BLAST 1 2000-01-01 "align.smith_waterman" "align.smith_waterman"
.SH NAME
align.smith_waterman \- Do sequence pairwise alignment
.SH SYNOPSIS
\fIalign.smith_waterman(\fBquery\fR as <generic> FastaSeq, 
\fBref\fR as <generic> FastaSeq, 
\fBblosum\fR as <generic> Blosum = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Do sequence pairwise alignment
.PP
.SH OPTIONS
.PP
\fBquery\fB \fR\- -. 
.PP
.PP
\fBref\fB \fR\- -. 
.PP
.PP
\fBblosum\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.blast
.SH FILES
.PP
seqtoolkit.dll
.PP
