.\" man page create by R# package system.
.TH BIOSEQ.BLAST 1 2000-01-01 "blosum" "blosum"
.SH NAME
blosum \- Parse blosum from the given file data
.SH SYNOPSIS
\fIblosum(\fBfile\fR as string = "Blosum-62");\fR
.SH DESCRIPTION
.PP
Parse blosum from the given file data
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- The blosum text data or text file path.. 
.PP
.SH SEE ALSO
bioseq.blast
.SH FILES
.PP
seqtoolkit.dll
.PP
