.\" man page create by R# package system.
.TH BIOSEQ.BLAST 1 2000-1月 "HSP" "HSP"
.SH NAME
HSP \- 
.SH SYNOPSIS
\fIHSP(\fBalign\fR as <generic> SmithWaterman, 
\fBcutoff\fR as double, 
\fBminW\fR as integer);\fR
.SH OPTIONS
.PP
\fBalign\fB \fR\- -. 
.PP
.PP
\fBcutoff\fB \fR\- [0,1] threshold. 
.PP
.PP
\fBminW\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.blast
.SH FILES
.PP
seqtoolkit.dll
.PP
