.\" man page create by R# package system.
.TH PTFKIT 1 2000-01-01 "as.uniprot_id" "as.uniprot_id"
.SH NAME
as.uniprot_id \- Try to unify all protein id to uniprot id
.SH SYNOPSIS
\fIas.uniprot_id(\fBptf\fR as <generic> Object, 
\fBproteins\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Try to unify all protein id to uniprot id
.PP
.SH OPTIONS
.PP
\fBptf\fB \fR\- -
.PP
.PP
\fBproteins\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
ptfKit
.SH FILES
.PP
proteomics_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
