.\" man page create by R# package system.
.TH PTFKIT 1 2000-01-01 "protein.annotations" "protein.annotations"
.SH NAME
protein.annotations \- export protein annotations
.SH SYNOPSIS
\fIprotein.annotations(\fBptf\fR as <generic> Object, 
\fBgeneIDs\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
export protein annotations
.PP
.SH SEE ALSO
ptfKit
.SH FILES
.PP
proteomics_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
