.\" man page create by R# package system.
.TH PTFKIT 1 2000-01-01 "uniprot.ptf" "uniprot.ptf"
.SH NAME
uniprot.ptf \- Create the unify protein annotation models from a given uniprot database entries.
.SH SYNOPSIS
\fIuniprot.ptf(\fBuniprot\fR as <generic> Object, 
\fBincludesNCBITaxonomy\fR as boolean = FALSE, 
\fBscientificName\fR as boolean = FALSE, 
\fBkeys\fR as <generic> Object = ["KEGG,KO,GO,Pfam,RefSeq,EC,InterPro,BioCyc,eggNOG"], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create the unify protein annotation models from a given uniprot database entries.
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- -
.PP
.PP
\fBincludesNCBITaxonomy\fB \fR\- -
.PP
.PP
\fBkeys\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
ptfKit
.SH FILES
.PP
proteomics_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
