.\" man page create by R# package system.
.TH PTFKIT 1 2000-01-01 "uniprot.ptf" "uniprot.ptf"
.SH NAME
uniprot.ptf \- 
.SH SYNOPSIS
\fIuniprot.ptf(\fBuniprot\fR as <generic> Object, 
\fBincludesNCBITaxonomy\fR as boolean = FALSE, 
\fBkeys\fR as <generic> Object = ["KEGG,KO,GO,Pfam,RefSeq,EC,InterPro,BioCyc,eggNOG"], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ptfKit
.SH FILES
.PP
proteomics_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
