<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  
   
    <OutputType>Library</OutputType>

    <RootNamespace>SMRUCC.genomics.Visualize.Circos</RootNamespace>
    <AssemblyName>SMRUCC.genomics.Visualize.Circos.Core</AssemblyName>
 
    <Platforms>AnyCPU;x64;x86;ARM64</Platforms>
	</PropertyGroup>
	</Project>