.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "cdhit_clusters" "cdhit_clusters"
.SH NAME
cdhit_clusters \- 
.SH SYNOPSIS
\fIcdhit_clusters(\fBx\fR as any, 
\fBk\fR as integer = 12, 
\fBidentities\fR as double = 0.8, 
\fBn_threads\fR as <generic> Int32 = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBidentities\fB \fR\- -. 
.PP
.PP
\fBn_threads\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a tuple list that contains the data slots:
 
 - family: @\fBT:SMRUCC.genomics.Model.MotifGraph.ProteinStructure.FamilyExports\fR
 - sequence: @\fBT:SMRUCC.genomics.Model.MotifGraph.ProteinStructure.SequenceCluster\fR
 - clusters: @\fBT:SMRUCC.genomics.Analysis.SequenceAlignment.SimilarHit\fR
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
seqtoolkit.dll
.PP
