.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "kmers_matrix" "kmers_matrix"
.SH NAME
kmers_matrix \- generate sequence k-mer count data matrix
.SH SYNOPSIS
\fIkmers_matrix(\fBx\fR as any, 
\fBk\fR as integer = 3, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
generate sequence k-mer count data matrix
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
seqtoolkit.dll
.PP
