.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "kmers" "kmers"
.SH NAME
kmers \- Create kmers from a given sequence
.SH SYNOPSIS
\fIkmers(\fBseq\fR as string, 
\fBk\fR as integer);\fR
.SH DESCRIPTION
.PP
Create kmers from a given sequence
.PP
.SH OPTIONS
.PP
\fBseq\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
seqtoolkit.dll
.PP
