.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "onehot_vectorizer" "onehot_vectorizer"
.SH NAME
onehot_vectorizer \- 
.SH SYNOPSIS
\fIonehot_vectorizer(\fBx\fR as any, 
\fBtype\fR as <integer> SeqTypes = [Protein], 
\fBk\fR as integer = 6, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
seqtoolkit.dll
.PP
