.\" man page create by R# package system.
.TH RAWXML 4 2000-1月 "entity.names" "entity.names"
.SH NAME
entity.names \- 
.SH SYNOPSIS
\fIentity.names(\fBraw\fR as <generic> Reader, 
..., 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBraw\fB \fR\- -. 
.PP
.PP
\fBstream\fB \fR\- 
 module descripting of the stream content to read, should be a list of content type mapping:
 list element name could be: "transcriptome", "proteome", "metabolome"
 element content type could be: mass_profile, activity, flux_size
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
rawXML
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBgg.xie@bionovogene.com\fR
