.\" man page create by R# package system.
.TH RAWXML 4 2000-1月 "frame.matrix" "frame.matrix"
.SH NAME
frame.matrix \- 
.SH SYNOPSIS
\fIframe.matrix(\fBraw\fR as string, 
\fBtick\fR as integer, 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
rawXML
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBgg.xie@bionovogene.com\fR
