.\" man page create by R# package system.
.TH RAWXML 4 2000-1月 "open.vcellXml" "open.vcellXml"
.SH NAME
open.vcellXml \- 
.SH SYNOPSIS
\fIopen.vcellXml(\fBfile\fR as string, 
\fBmode\fR as string = "read", 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
rawXML
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBgg.xie@bionovogene.com\fR
