.\" man page create by R# package system.
.TH WGCNA 1 2000-Jan "shapeTRN" "shapeTRN"
.SH NAME
shapeTRN \- filter regulation network by WGCNA result weights
.SH SYNOPSIS
\fIshapeTRN(\fBg\fR as <generic> NetworkGraph, 
\fBWGCNA\fR as <generic> WGCNAWeight, 
\fBthreshold\fR as double = 0.3);\fR
.SH DESCRIPTION
.PP
filter regulation network by WGCNA result weights
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBWGCNA\fB \fR\- -. 
.PP
.PP
\fBthreshold\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
visualkit.dll
.PP
