.\" man page create by R# package system.
.TH MODELLER 4 2000-1月 "read.vcell" "read.vcell"
.SH NAME
read.vcell \- read the virtual cell model file
.SH SYNOPSIS
\fIread.vcell(\fBpath\fR as string);\fR
.SH DESCRIPTION
.PP
read the virtual cell model file
.PP
.SH OPTIONS
.PP
\fBpath\fB \fR\- 
 the model file extension could be:
 
 xml - small virtual cell model in a xml file
 zip - large virtual cell model file save as multiple components in a zip file
 json - large virtual cell model file save as json stream file
. 
.PP
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
