.\" man page create by R# package system.
.TH UNIPROT 1 2000-Jan "keyword_profiles" "keyword_profiles"
.SH NAME
keyword_profiles \- create uniprot keyword ontology result
.SH SYNOPSIS
\fIkeyword_profiles(\fBenrichment\fR as <generic> EnrichmentResult[], 
\fBkeywords\fR as <generic> dataframe, 
\fBtop\fR as integer = 4);\fR
.SH DESCRIPTION
.PP
create uniprot keyword ontology result
.PP
.SH OPTIONS
.PP
\fBenrichment\fB \fR\- -. 
.PP
.PP
\fBkeywords\fB \fR\- -. 
.PP
.PP
\fBtop\fB \fR\- -. 
.PP
.SH SEE ALSO
UniProt
.SH FILES
.PP
gseakit.dll
.PP
