.\" man page create by R# package system.
.TH UNIPROT 1 2000-1月 "subcellular_location" "subcellular_location"
.SH NAME
subcellular_location \- extract the sub-cellular location information as background model
.SH SYNOPSIS
\fIsubcellular_location(\fBuniprot\fR as any, 
\fBdb_xref\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
extract the sub-cellular location information as background model
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
UniProt
.SH FILES
.PP
gseakit.dll
.PP
