.\" man page create by R# package system.
.TH UNIPROT 1 2000-1月 "uniprot_keywords" "uniprot_keywords"
.SH NAME
uniprot_keywords \- Create a gsea background model for uniprot keywords based
.SH SYNOPSIS
\fIuniprot_keywords(\fBuniprot\fR as any, 
\fBdb_xref\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a gsea background model for uniprot keywords based
 on the given uniprot database assembly data
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
UniProt
.SH FILES
.PP
gseakit.dll
.PP
