.\" man page create by R# package system.
.TH ENZYMATIC 1 2000-Jan "read.rhea" "read.rhea"
.SH NAME
read.rhea \- read the rhea database file
.SH SYNOPSIS
\fIread.rhea(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the rhea database file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
enzymatic
.SH FILES
.PP
vcellkit.dll
.PP
