.\" man page create by R# package system.
.TH AUTOMATION 1 2000-01-01 "layouts" "layouts"
.SH NAME
layouts \- GET list of layout algorithms
.SH SYNOPSIS
\fIlayouts(\fBversion\fR as string = "v1", 
\fBport\fR as integer = 1234, 
\fBhost\fR as string = "localhost");\fR
.SH DESCRIPTION
.PP
GET list of layout algorithms
.PP
.SH OPTIONS
.PP
\fBversion$\fB \fR\- -. 
.PP
.PP
\fBport%\fB \fR\- -. 
.PP
.PP
\fBhost$\fB \fR\- -. 
.PP
.SH SEE ALSO
automation
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
