.\" man page create by R# package system.
.TH AUTOMATION 1 2000-Jan "networkView" "networkView"
.SH NAME
networkView \- 
.SH SYNOPSIS
\fInetworkView(\fBnetworkId\fR as any, 
\fBviewId\fR as any, 
\fBversion\fR as string = "v1", 
\fBport\fR as integer = 1234, 
\fBhost\fR as string = "localhost", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
automation
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
