.\" man page create by R# package system.
.TH AUTOMATION 1 2000-1月 "put_network" "put_network"
.SH NAME
put_network \- 
.SH SYNOPSIS
\fIput_network(\fBnetwork\fR as any, 
\fBcollection\fR as string = \fB<NULL>\fR, 
\fBtitle\fR as string = \fB<NULL>\fR, 
\fBversion\fR as string = "v1", 
\fBport\fR as integer = 1234, 
\fBhost\fR as string = "localhost", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
automation
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
