<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>test</RootNamespace> 
    <TargetFrameworks>net10.0</TargetFrameworks>
       <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;LipidSearch;mzkit;NPSearch;Rsharp_app_release;mzkit_win32;gcmodeller_desktop</Configurations>
    <UseApplicationFramework>False</UseApplicationFramework>
    <StartupObject>test.kgml_test</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\runtime\sciBASIC#\Data\DataFrame\dataframework-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\biocore-netcore5.vbproj" />
  </ItemGroup>

</Project>
