.\" man page create by R# package system.
.TH GENE_QUANTIFICATION 1 2000-1月 "convert_to_tpm" "convert_to_tpm"
.SH NAME
convert_to_tpm \- 
.SH SYNOPSIS
\fIconvert_to_tpm(\fBcounts\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBcounts\fB \fR\- A collection of the gene @\fBT:SMRUCC.genomics.SequenceModel.SAM.featureCount.featureCounts\fR data.. 
.PP
.PP
\fBenv\fB \fR\- The R environment.. 
.PP
.SH VALUE
.PP
A collection of gene expression data in TPM format.
.PP
.SH SEE ALSO
gene_quantification
.SH FILES
.PP
rnaseq.dll
.PP
