.\" man page create by R# package system.
.TH GENE_QUANTIFICATION 1 2000-1月 "edgeR_norm" "edgeR_norm"
.SH NAME
edgeR_norm \- Apply of the edgeR TMM factor normalization method to the raw counts matrix
.SH SYNOPSIS
\fIedgeR_norm(\fBcounts\fR as <generic> Matrix, 
\fBtrimFractionM\fR as double = 0.3, 
\fBtrimFractionA\fR as double = 0.05);\fR
.SH DESCRIPTION
.PP
Apply of the edgeR TMM factor normalization method to the raw counts matrix
.PP
.SH OPTIONS
.PP
\fBcounts\fB \fR\- -. 
.PP
.SH SEE ALSO
gene_quantification
.SH FILES
.PP
rnaseq.dll
.PP
