.\" man page create by R# package system.
.TH GENE_QUANTIFICATION 1 2000-1月 "read_featureCounts" "read_featureCounts"
.SH NAME
read_featureCounts \- read feature counts tsv table file
.SH SYNOPSIS
\fIread_featureCounts(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read feature counts tsv table file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
gene_quantification
.SH FILES
.PP
rnaseq.dll
.PP
