.\" man page create by R# package system.
.TH RAWXML 4 2000-01-01 "frame.index" "frame.index"
.SH NAME
frame.index \- [debug api]
.SH SYNOPSIS
\fIframe.index(\fBraw\fR as <generic> Reader);\fR
.SH DESCRIPTION
.PP
[debug api]
.PP
.SH OPTIONS
.PP
\fBraw\fB \fR\- -. 
.PP
.SH SEE ALSO
rawXML
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBgg.xie@bionovogene.com\fR
