.\" man page create by R# package system.
.TH RAWXML 4 2000-1月 "open.vcellPack" "open.vcellPack"
.SH NAME
open.vcellPack \- open the simulation data storage driver
.SH SYNOPSIS
\fIopen.vcellPack(\fBfile\fR as string, 
\fBmode\fR as string = "read", 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open the simulation data storage driver
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path to the storage data
. 
.PP
.PP
\fBmode\fB \fR\- 
 the binary file open mode for the data storage driver, should be \fBread\fR/\fBwrite\fR.
. 
.PP
.PP
\fBargs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
rawXML
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBgg.xie@bionovogene.com\fR
