.\" man page create by R# package system.
.TH VISUALSTUDIO.DEVKIT 1 2020-07-19 "AssemblyInfo" "AssemblyInfo"
.SH NAME
AssemblyInfo \- Get .NET library module assembly information data.
.SH SYNOPSIS
\fIAssemblyInfo(\fBdllfile\fR as string);\fR
.SH DESCRIPTION
.PP
Get .NET library module assembly information data.
.PP
.SH OPTIONS
.PP
\fBdllfile\fB \fR\- -
.PP
.SH SEE ALSO
VisualStudio.devkit
.SH FILES
.PP
devkit.dll
.PP
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
