.\" man page create by R# package system.
.TH VISUALSTUDIO 4 2020-07-26 "il" "il"
.SH NAME
il \- show IL assembly code of the given R# api
.SH SYNOPSIS
\fIil(\fBapi\fR as <closure> RMethodInfo);\fR
.SH DESCRIPTION
.PP
show IL assembly code of the given R# api
.PP
.SH OPTIONS
.PP
\fBapi\fB \fR\- 
 a R# api function symbol object

.PP
.SH SEE ALSO
VisualStudio
.SH FILES
.PP
devkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
