.\" man page create by R# package system.
.TH VISUALSTUDIO 4 2020-07-26 "svn.log" "svn.log"
.SH NAME
svn.log \- 
.SH SYNOPSIS
\fIsvn.log(\fBfile\fR as string);\fR
.SH SEE ALSO
VisualStudio
.SH FILES
.PP
devkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
