.\" man page create by R# package system.
.TH MIXOMICS 1 2000-1月 "cclasso" "cclasso"
.SH NAME
cclasso \- CC lasso analysis
.SH SYNOPSIS
\fIcclasso(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix, 
\fBlam_min_ratio\fR as double = 0.001, 
\fBnfold\fR as integer = 5, 
\fBn_bootstraps\fR as integer = 500, 
\fBstrict\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
CC lasso analysis
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBlam_min_ratio\fB \fR\- -. 
.PP
.PP
\fBnfold\fB \fR\- -. 
.PP
.PP
\fBn_bootstraps\fB \fR\- -. 
.PP
.PP
\fBstrict\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mixOmics
.SH FILES
.PP
phenotype_kit.dll
.PP
