.\" man page create by R# package system.
.TH MIXOMICS 1 2000-1月 "cclasso" "cclasso"
.SH NAME
cclasso \- 
.SH SYNOPSIS
\fIcclasso(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix, 
\fBlam_min_ratio\fR as double = 0.001, 
\fBnfold\fR as integer = 5, 
\fBn_bootstraps\fR as integer = 500, 
\fBstrict\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
mixOmics
.SH FILES
.PP
phenotype_kit.dll
.PP
