.\" man page create by R# package system.
.TH MIXOMICS 1 2000-1月 "mine" "mine"
.SH NAME
mine \- Spearman + MIC
.SH SYNOPSIS
\fImine(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
Spearman + MIC
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.SH SEE ALSO
mixOmics
.SH FILES
.PP
phenotype_kit.dll
.PP
