.\" man page create by R# package system.
.TH MIXOMICS 1 2000-1月 "sparcc" "sparcc"
.SH NAME
sparcc \- SparCC correlation analysis
.SH SYNOPSIS
\fIsparcc(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix, 
\fBstrict\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
SparCC correlation analysis
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBstrict\fB \fR\- -. 
.PP
.SH SEE ALSO
mixOmics
.SH FILES
.PP
phenotype_kit.dll
.PP
