.\" man page create by R# package system.
.TH BLAST+ 1 2000-1月 "blastn" "blastn"
.SH NAME
blastn \- Nucleotide-Nucleotide BLAST
.SH SYNOPSIS
\fIblastn();\fR
.SH DESCRIPTION
.PP
Nucleotide-Nucleotide BLAST
.PP
.SH DETAILS
.PP
this api is not implemented at this moment.
.PP
.SH SEE ALSO
blast+
.SH FILES
.PP
seqtoolkit.dll
.PP
