.\" man page create by R# package system.
.TH BLAST+ 1 2000-1月 "blastx" "blastx"
.SH NAME
blastx \- Translated Query Vs. Protein Database
.SH SYNOPSIS
\fIblastx();\fR
.SH DESCRIPTION
.PP
Translated Query Vs. Protein Database
.PP
.SH DETAILS
.PP
this api is not implemented at this moment.
.PP
.SH SEE ALSO
blast+
.SH FILES
.PP
seqtoolkit.dll
.PP
