'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Analysis.CellPhenotype.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 imports Analysis_Tools.Phenotype.Regulations
        '''imports Framework.Extensions
        '''
        '''$dir
        '''$gene
        '''
        '''csv &lt;- $dir -&gt; expressionmatrix.create
        '''$csv &gt; ./Export/$gene.MAT.csv
        '''  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ExpressionMAT() As String
            Get
                Return ResourceManager.GetString("ExpressionMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Imports Analysis_Tools.Phenotype.Regulations
        '''Imports MEME.app.genome_Footprints
        '''Imports GCModeller.Compiler.GCML.Csvx
        '''Imports IO_Device.Csv
        '''Imports GCModeller.Assembly.File.IO
        '''
        '''# This script file is using for running the GCModeller DFL binary network engine kernel.
        '''
        '''# ----------------------------------------------------------------------------------------------------------
        '''#         Script file input parameters
        '''# ------------------------------------------------------------------------------------- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property KernelDriver() As String
            Get
                Return ResourceManager.GetString("KernelDriver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Imports Analysis_Tools.Phenotype.Regulations
        '''Imports MEME.app.genome_Footprints
        '''Imports GCModeller.Compiler.GCML.Csvx
        '''Imports IO_Device.Csv
        '''Imports GCModeller.Assembly.File.IO
        '''
        '''# This script file is using for running the GCModeller DFL binary network engine kernel.
        '''
        '''# ----------------------------------------------------------------------------------------------------------
        '''#         Script file input parameters
        '''# ------------------------------------------------------------------------------------- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property KernelDriver___GeneMutation__MonteCarlo() As String
            Get
                Return ResourceManager.GetString("KernelDriver___GeneMutation__MonteCarlo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 imports assemblyfile.io
        '''imports analysis.chipdata
        '''imports pfsnet
        '''imports kegg
        '''
        '''$chipdata
        '''$save
        '''pathways &lt;- &quot;[pathways]&quot;
        '''java_filter &lt;- &quot;[java_filter]&quot;
        '''
        '''$pathways ~ read.csv.kegg_pathways
        '''
        '''call pfsnet session.initialize $java_filter
        '''
        '''chipdata &lt;- read.chipdata $chipdata
        '''
        '''experiment1 &lt;- try_parse_string_vector &quot;1,2,3,4,5,6,7,8,9,10&quot;
        '''experiment2 &lt;- try_parse_string_vector &quot;11,12,13,14,15,16,17,18,19,20&quot;
        '''
        '''geneidlist &lt;- pathway_genelist.create_from pathwaydata $pathways
        '''file1 &lt;- expression_mat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property pfsnet_kegg_pathways() As String
            Get
                Return ResourceManager.GetString("pfsnet_kegg_pathways", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Imports PfsNET
        '''
        '''# Set up data files in the program with String.Format function
        '''  MAT1 &lt;- {0}
        '''  MAT2 &lt;- {1} 
        '''   NET &lt;- {2}
        '''
        '''# PfsNET evaluation parameters   
        ''' $Beta
        ''' $t1
        ''' $t2
        ''' $n
        '''
        '''Call Session.Initialize
        ''' 
        '''# Invoke the PfsNET evaluation and save data to file
        '''Result &lt;- PfsNET.Evaluate File1 $MAT1 File2 $MAT2 File3 $NET b $Beta t1 $t1 t2 $t2 n $n
        '''$Result &gt; {3}/{4}.xml 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property PfsNETCellularNetwork() As String
            Get
                Return ResourceManager.GetString("PfsNETCellularNetwork", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
