.\" man page create by R# package system.
.TH CHARTS 4 2000-01-01 "barplot" "barplot"
.SH NAME
barplot \- 
.SH SYNOPSIS
\fIbarplot(\fBdata\fR as <generic> dataframe, 
\fBcategory\fR as string = "item", 
\fBvalue\fR as string = "value", 
\fBcolor\fR as string = "color", 
\fBmin\fR as string = "min", 
\fBmax\fR as string = "max", 
\fBtitle\fR as string = "Histogram Plot", 
\fBxlab\fR as string = "X", 
\fBylab\fR as string = "Y", 
\fBbg\fR as <generic> Object = "white", 
\fBsize\fR as <generic> Object = "1920,1080", 
\fBpadding\fR as <generic> Object = "padding:100px 100px 100px 100px;", 
\fBshow_grid\fR as boolean = TRUE, 
\fBshow_legend\fR as boolean = TRUE);\fR
.SH SEE ALSO
charts
.SH FILES
.PP
R.plot.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
