.\" man page create by R# package system.
.TH CHARTS 4 2000-01-01 "serial" "serial"
.SH NAME
serial \- create a new serial for scatter plot
.SH SYNOPSIS
\fIserial(\fBx\fR as <generic> Array, 
\fBy\fR as <generic> Array, 
\fBname\fR as string = "data serial", 
\fBcolor\fR as <generic> Object = "black", 
\fBalpha\fR as integer = 255, 
\fBptSize\fR as integer = 5);\fR
.SH DESCRIPTION
.PP
create a new serial for scatter plot
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -
.PP
.PP
\fBy\fB \fR\- -
.PP
.PP
\fBname$\fB \fR\- -
.PP
.PP
\fBcolor\fB \fR\- -
.PP
.SH SEE ALSO
charts
.SH FILES
.PP
R.plot.dll
.PP
.SH AUTHOR
Written by xie.guigang@gmail.com
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
