.\" man page create by R# package system.
.TH UTILS.DOCS 1 2020-07-19 "makehtml.docs" "makehtml.docs"
.SH NAME
makehtml.docs \- Create html help document for the specific package module
.SH SYNOPSIS
\fImakehtml.docs(\fBpackage\fR as string, 
\fBtemplate\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create html help document for the specific package module
.PP
.SH OPTIONS
.PP
\fBpackage\fB \fR\- The package name
.PP
.PP
\fBglobalEnv\fB \fR\- -
.PP
.SH DETAILS
.PP
This method create a single html help page file for generates pdf help manual file.
.PP
.SH SEE ALSO
utils.docs
.SH FILES
.PP
devkit.dll
.PP
.SH AUTHOR
Written by \fBI@xieguigang.me\fR
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
