.\" man page create by R# package system.
.TH UTILS.DOCS 1 2020-07-19 "markdown.docs" "markdown.docs"
.SH NAME
markdown.docs \- 
.SH SYNOPSIS
\fImarkdown.docs(\fBpackage\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
utils.docs
.SH FILES
.PP
devkit.dll
.PP
.SH AUTHOR
Written by \fBI@xieguigang.me\fR
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
