.\" man page create by R# package system.
.TH ANALYSIS 1 2000-1月 "compound.names" "compound.names"
.SH NAME
compound.names \- set compound names for the kegg metabolites
.SH SYNOPSIS
\fIcompound.names(\fBmetabolites\fR as <generic> DataSet[], 
\fBnames\fR as list[string]);\fR
.SH DESCRIPTION
.PP
set compound names for the kegg metabolites
.PP
.SH OPTIONS
.PP
\fBmetabolites\fB \fR\- -. 
.PP
.PP
\fBnames\fB \fR\- -. 
.PP
.SH SEE ALSO
analysis
.SH FILES
.PP
vcellkit.dll
.PP
