.\" man page create by R# package system.
.TH ANALYSIS 1 2000-1月 "union.matrix" "union.matrix"
.SH NAME
union.matrix \- 
.SH SYNOPSIS
\fIunion.matrix(\fBresult\fR as string, 
\fBsetName\fR as string = "mass\metabolome.json", 
\fBtrim\fR as boolean = TRUE);\fR
.SH SEE ALSO
analysis
.SH FILES
.PP
vcellkit.dll
.PP
