.\" man page create by R# package system.
.TH ANALYSIS 1 2000-1月 "vcell.graph" "vcell.graph"
.SH NAME
vcell.graph \- Export the cellular graph data from the virtual cell simulation engine
.SH SYNOPSIS
\fIvcell.graph(\fBvcell\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Export the cellular graph data from the virtual cell simulation engine
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
analysis
.SH FILES
.PP
vcellkit.dll
.PP
