.\" man page create by R# package system.
.TH VISUALKIT.PLOTS 1 2000-01-01 "plot.expression_patterns" "plot.expression_patterns"
.SH NAME
plot.expression_patterns \- 
.SH SYNOPSIS
\fIplot.expression_patterns(\fBmatrix\fR as <generic> Matrix, 
\fBdim\fR as <generic> Object = "3,3");\fR
.SH SEE ALSO
visualkit.plots
.SH FILES
.PP
visualkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
