.\" man page create by R# package system.
.TH VISUALKIT.PLOTS 2 2000-01-01 "volcano.plot" "volcano.plot"
.SH NAME
volcano.plot \- 
.SH SYNOPSIS
\fIvolcano.plot(\fBgenes\fR as <generic> DEP_iTraq[], 
\fBsize\fR as <generic> Object = "2400,2700", 
\fBpadding\fR as <generic> Object = "padding:150px 150px 300px 300px;", 
\fBbg\fR as <generic> Object = "white");\fR
.SH SEE ALSO
visualkit.plots
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2019
