.\" man page create by R# package system.
.TH BIOM_KIT 1 2000-1月 "biom.taxonomy" "biom.taxonomy"
.SH NAME
biom.taxonomy \- get the taxonomy information from the BIOM matrix
.SH SYNOPSIS
\fIbiom.taxonomy(\fBbiom\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get the taxonomy information from the BIOM matrix
.PP
.SH OPTIONS
.PP
\fBbiom\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
BIOM_kit
.SH FILES
.PP
metagenomics_kit.dll
.PP
