.\" man page create by R# package system.
.TH BIOM_KIT 1 2000-1月 "read.matrix" "read.matrix"
.SH NAME
read.matrix \- read matrix data from a given BIOM file.
.SH SYNOPSIS
\fIread.matrix(\fBfile\fR as any, 
\fBdenseMatrix\fR as boolean = TRUE, 
\fBsuppressErr\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read matrix data from a given BIOM file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
BIOM_kit
.SH FILES
.PP
metagenomics_kit.dll
.PP
