.\" man page create by R# package system.
.TH MAGNITUDE 4 2000-Jan "encode.seqPack" "encode.seqPack"
.SH NAME
encode.seqPack \- tag samples in matrix as sequence profiles
.SH SYNOPSIS
\fIencode.seqPack(\fBmat\fR as <generic> Matrix, 
\fBbriefSet\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
tag samples in matrix as sequence profiles
.PP
.SH OPTIONS
.PP
\fBmat\fB \fR\- -. 
.PP
.SH SEE ALSO
magnitude
.SH FILES
.PP
phenotype_kit.dll
.PP
