.\" man page create by R# package system.
.TH MAGNITUDE 4 2000-Jan "profiles" "profiles"
.SH NAME
profiles \- 
.SH SYNOPSIS
\fIprofiles(\fBselector\fR as string, 
\fBfoldchange\fR as double, 
\fBbase\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
magnitude
.SH FILES
.PP
phenotype_kit.dll
.PP
