.\" man page create by R# package system.
.TH MAGNITUDE 4 2000-1月 "TrIQ.apply" "TrIQ.apply"
.SH NAME
TrIQ.apply \- Apply @\fBT:Microsoft.VisualBasic.Math.Distributions.TrIQ\fR cutoff for each sample
.SH SYNOPSIS
\fITrIQ.apply(\fBmat\fR as <generic> Matrix, 
\fBq\fR as double = 0.8, 
\fBaxis\fR as integer = 1);\fR
.SH DESCRIPTION
.PP
Apply @\fBT:Microsoft.VisualBasic.Math.Distributions.TrIQ\fR cutoff for each sample
.PP
.SH OPTIONS
.PP
\fBmat\fB \fR\- -. 
.PP
.PP
\fBq\fB \fR\- -. 
.PP
.PP
\fBaxis\fB \fR\- 
 default value \fB1\fR means apply the cutoff for each sample column data,
 alternative value \fB2\fR means apply the cutoff for each gene data row. 
. 
.PP
.SH SEE ALSO
magnitude
.SH FILES
.PP
phenotype_kit.dll
.PP
