.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS_CONTEXT 2 2000-Jan "context" "context"
.SH NAME
context \- Create a new context model of a specific genomics feature site.
.SH SYNOPSIS
\fIcontext(\fBloci\fR as any, 
\fBdistance\fR as integer, 
\fBnote\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a new context model of a specific genomics feature site.
.PP
.SH OPTIONS
.PP
\fBloci\fB \fR\- -. 
.PP
.PP
\fBdistance\fB \fR\- -. 
.PP
.PP
\fBnote\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
