.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS_CONTEXT 2 2000-1月 "is.forward" "is.forward"
.SH NAME
is.forward \- the given nucleotide location is in forward direction
.SH SYNOPSIS
\fIis.forward(\fBloci\fR as <generic> NucleotideLocation);\fR
.SH DESCRIPTION
.PP
the given nucleotide location is in forward direction
.PP
.SH OPTIONS
.PP
\fBloci\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
