.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS_CONTEXT 2 2000-01-01 "offset" "offset"
.SH NAME
offset \- do offset of the given location
.SH SYNOPSIS
\fIoffset(\fBloci\fR as <generic> NucleotideLocation, 
\fBoffset\fR as integer);\fR
.SH DESCRIPTION
.PP
do offset of the given location
.PP
.SH OPTIONS
.PP
\fBloci\fB \fR\- -. 
.PP
.PP
\fBoffset\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
