.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS_CONTEXT 2 2000-01-01 "relationship" "relationship"
.SH NAME
relationship \- get the segment relationship of two location
.SH SYNOPSIS
\fIrelationship(\fBa\fR as any, 
\fBb\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get the segment relationship of two location
.PP
.SH OPTIONS
.PP
\fBa\fB \fR\- -. 
.PP
.PP
\fBb\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
