.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS_CONTEXT 2 2000-1月 "strand.filter" "strand.filter"
.SH NAME
strand.filter \- filter genes by given strand direction
.SH SYNOPSIS
\fIstrand.filter(\fBgenes\fR as any, 
\fBstrand\fR as any = "+", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
filter genes by given strand direction
.PP
.SH OPTIONS
.PP
\fBgenes\fB \fR\- -. 
.PP
.PP
\fBstrand\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
