.\" man page create by R# package system.
.TH REACTOME 1 2000-1月 "pathway_list" "pathway_list"
.SH NAME
pathway_list \- get reactome pathway list
.SH SYNOPSIS
\fIpathway_list(\fBtaxname\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
get reactome pathway list
.PP
.SH OPTIONS
.PP
\fBtaxname\fB \fR\- -. 
.PP
.SH SEE ALSO
Reactome
.SH FILES
.PP
annotationKit.dll
.PP
