.\" man page create by R# package system.
.TH BLAST+ 1 2000-01-01 "blastp" "blastp"
.SH NAME
blastp \- Protein-Protein BLAST
.SH SYNOPSIS
\fIblastp(\fBquery\fR as string, 
\fBsubject\fR as string, 
\fBoutput\fR as string, 
\fBevalue\fR as double = 0.001, 
\fBn_threads\fR as integer = 2, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Protein-Protein BLAST
.PP
.SH SEE ALSO
blast+
.SH FILES
.PP
seqtoolkit.dll
.PP
