.\" man page create by R# package system.
.TH BLAST+ 1 2000-1月 "makeblastdb" "makeblastdb"
.SH NAME
makeblastdb \- Application to create BLAST databases
.SH SYNOPSIS
\fImakeblastdb(\fBin\fR as string, 
\fBdbtype\fR as any = ["nucl","prot"], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Application to create BLAST databases
.PP
.SH OPTIONS
.PP
\fB[in]\fB \fR\- Input file/database name. 
.PP
.PP
\fBdbtype\fB \fR\- Molecule type of target db. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
blast+
.SH FILES
.PP
seqtoolkit.dll
.PP
