require(GCModeller);

import {FastQ} from "rnaseq";

var assem = FastQ.assemble([
	"AACAAATGAGACGCTGTGCAATTGCTGA",
	"AACAAATGAGACGCTGTGCAATTGCTGA",
	"CAAATGAGACGCTGTGCAATTGCTGAGT",
	"GAAATGATACGCTGTGCAATTGCTGAGA",
	"ATGAGACGCTGTGCAATTGCTGAGTACC",
	"CTGTGCAATTGCTGAGTACCGTAGGTAG",
	"CTGTGCAATTGCTGAGTACCGTAGGTAG"
])

console.log(assem)
console.table(assem)