.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "environment" "environment"
.SH NAME
environment \- config the symbol environment for S-system kernel
.SH SYNOPSIS
\fIenvironment(\fBkernel\fR as <generic> Kernel, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
config the symbol environment for S-system kernel
.PP
.SH OPTIONS
.PP
\fBkernel\fB \fR\- -. 
.PP
.PP
\fBsymbols\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
