.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "kernel" "kernel"
.SH NAME
kernel \- create a new S-system dynamics kernel module
.SH SYNOPSIS
\fIkernel(\fBsnapshot\fR as <generic> DataSnapshot, 
\fBmodel\fR as <generic> Model = \fB<NULL>\fR, 
\fBstrict\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
create a new S-system dynamics kernel module
.PP
.SH OPTIONS
.PP
\fBsnapshot\fB \fR\- -. 
.PP
.PP
\fBmodel\fB \fR\- -. 
.PP
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
