.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-Jan "run" "run"
.SH NAME
run \- run simulator
.SH SYNOPSIS
\fIrun(\fBkernel\fR as <generic> Kernel, 
\fBticks\fR as integer = 100, 
\fBresolution\fR as double = 0.1);\fR
.SH DESCRIPTION
.PP
run simulator
.PP
.SH OPTIONS
.PP
\fBkernel\fB \fR\- -. 
.PP
.PP
\fBticks\fB \fR\- -. 
.PP
.PP
\fBresolution\fB \fR\- -. 
.PP
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
