.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-Jan "S.script" "S.script"
.SH NAME
S.script \- create a new empty model for run S-system simulation
.SH SYNOPSIS
\fIS.script(\fBtitle\fR as string = "unnamed model", 
\fBdescription\fR as string = "");\fR
.SH DESCRIPTION
.PP
create a new empty model for run S-system simulation
.PP
.SH OPTIONS
.PP
\fBtitle$\fB \fR\- -. 
.PP
.PP
\fBdescription$\fB \fR\- -. 
.PP
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
