.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-1月 "s.system" "s.system"
.SH NAME
s.system \- load S-system into the dynamics simulators kernel module
.SH SYNOPSIS
\fIs.system(\fBkernel\fR as <generic> Kernel, 
\fBssystem\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load S-system into the dynamics simulators kernel module
.PP
.SH OPTIONS
.PP
\fBkernel\fB \fR\- -. 
.PP
.PP
\fBssystem\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
