.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "snapshot" "snapshot"
.SH NAME
snapshot \- create a symbol data snapshot device for write data into file
.SH SYNOPSIS
\fIsnapshot(\fBfile\fR as string = \fB<NULL>\fR, 
\fBsymbols\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
create a symbol data snapshot device for write data into file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBsymbols\fB \fR\- -. 
.PP
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
