.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "multiple_genome_alignment" "multiple_genome_alignment"
.SH NAME
multiple_genome_alignment \- 
.SH SYNOPSIS
\fImultiple_genome_alignment(\fBaligns\fR as any, 
\fBsep\fR as string = ".", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
