.\" man page create by R# package system.
.TH TAXONOMY_KIT 1 2000-01-01 "Ncbi.taxonomy_tree" "Ncbi.taxonomy_tree"
.SH NAME
Ncbi.taxonomy_tree \- 
.SH SYNOPSIS
\fINcbi.taxonomy_tree(\fBrepo\fR as string);\fR
.SH SEE ALSO
taxonomy_kit
.SH FILES
.PP
metagenomics_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
