#Region "Microsoft.VisualBasic::24eee4da6e1e41c4fb96b0ddf49ad167, core\Bio.Assembly\Resources\KEGG\Reactions\KEGGReactions.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 154
    '    Code Lines: 55 (35.71%)
    ' Comment Lines: 86 (55.84%)
    '    - Xml Docs: 9.30%
    ' 
    '   Blank Lines: 13 (8.44%)
    '     File Size: 7.30 KB


    '     Class KEGGReactions
    ' 
    '         Properties: br08201, br08202, br08203, br08204, Culture
    '                     ResourceManager
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class KEGGReactions
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.KEGGReactions", GetType(KEGGReactions).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +E	Reaction
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/brite.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Enzymatic Reactions&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;1. Oxidoreductase reactions&lt;/b&gt;
        '''B  1.1  Acting on the CH-OH group of donors
        '''C    1.1.1  With NAD+ or NADP+ as acceptor
        '''D      1.1.1.1
        '''E        R00623  Primary alcohol + NAD+ &lt;=&gt; Aldehyde + NADH + H+
        '''E        R00624  Secondary alcohol + NAD+ &lt;=&gt; Ketone + NADH + H+
        '''E        R00754  Ethanol + NAD+ &lt;=&gt; Acetaldehyde + NADH + H+
        '''E        R02124  Retinol + NAD+ &lt;=&gt; Retinal +  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property br08201() As String
            Get
                Return ResourceManager.GetString("br08201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +D	Reaction	Substrate	Product	Substrate2	Product2
        '''%&lt;!-- w=200,300,300,300 --&gt;
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/brite.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; IUBMB Reaction Hierarchy&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;1. Oxidoreductase reactions&lt;/b&gt;
        '''B  1.1.1.1
        '''C    R00623	C00226  Primary alcohol	C00071  Aldehyde
        '''D      R00754	C00469  Ethanol	C00084  Acetaldehyde
        '''D      R02124	C00473  Retinol	C00376  Retinal
        '''D      R02878	C00756  1-Octanol	C01545  Octanal
        '''D      R04805	C05444  3alpha,7alpha,26-Trihydroxy-5beta-cho [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property br08202() As String
            Get
                Return ResourceManager.GetString("br08202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +B	Glycosyltransferase reaction
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/brite.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Glycosyltransferase Reactions&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Glucosyltransferase reactions&lt;/b&gt;
        '''B  R06264  Glc a1-2 Glc [KO:K03850] [PATH:rn00510]
        '''B  R05164  Glc a1-2 Glc [KO:K13677] [PATH:rn00561]
        '''B  R03118  Glc a1-3 Glc [KO:K00706] [PATH:rn00500]
        '''B  R06263  Glc a1-3 Glc [KO:K03849] [PATH:rn00510]
        '''B  R06045  Glc a1-3 Glc [KO:K00749]
        '''B  R06018  Glc b1-3 Glc
        '''B  R06051  Glc a1-4 Glc [KO:K00693 K00750 K [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property br08203() As String
            Get
                Return ResourceManager.GetString("br08203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +E	RClass
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/brite.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Reaction Class&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;1. Oxidoreductase reactions&lt;/b&gt;
        '''B  1.1  Acting on the CH-OH group of donors
        '''C    1.1.1  With NAD+ or NADP+ as acceptor
        '''D      1.1.1.1
        '''E        RC00050
        '''E        RC00087
        '''E        RC00088
        '''E        RC00099
        '''E        RC00116
        '''E        RC00170
        '''E        RC00649
        '''E        RC00955
        '''E        RC01734
        '''E        RC02273
        '''D      1.1.1.2
        '''E        RC00050
        '''E        RC00087
        '''E        RC00088
        '''E        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property br08204() As String
            Get
                Return ResourceManager.GetString("br08204", resourceCulture)
            End Get
        End Property
    End Class
End Namespace

