.\" man page create by R# package system.
.TH MODELS 4 2000-1月 "get.sessionInfo" "get.sessionInfo"
.SH NAME
get.sessionInfo \- 
.SH SYNOPSIS
\fIget.sessionInfo(\fBcys\fR as <generic> CysSessionFile);\fR
.SH SEE ALSO
models
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
