.\" man page create by R# package system.
.TH MODELS 4 2000-01-01 "get.network_graph" "get.network_graph"
.SH NAME
get.network_graph \- 
.SH SYNOPSIS
\fIget.network_graph(\fBcys\fR as <generic> CysSessionFile, 
\fBcollection\fR as string = \fB<NULL>\fR, 
\fBname\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
models
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
