.\" man page create by R# package system.
.TH MODELS 4 2000-Jan "list.networks" "list.networks"
.SH NAME
list.networks \- 
.SH SYNOPSIS
\fIlist.networks(\fBcys\fR as <generic> CysSessionFile);\fR
.SH SEE ALSO
models
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
