.\" man page create by R# package system.
.TH MODELS 4 2000-01-01 "sif" "sif"
.SH NAME
sif \- 
.SH SYNOPSIS
\fIsif(\fBsource\fR as any, 
\fBinteraction\fR as any, 
\fBtarget\fR as any);\fR
.SH SEE ALSO
models
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
