.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "as_tabular" "as_tabular"
.SH NAME
as_tabular \- 
.SH SYNOPSIS
\fIas_tabular(\fBgbff\fR as <generic> File, 
\fBORF\fR as boolean = TRUE);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
