.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "as_tabular" "as_tabular"
.SH NAME
as_tabular \- extract all gene features from genbank and cast to tabular data
.SH SYNOPSIS
\fIas_tabular(\fBgbff\fR as <generic> File, 
\fBORF\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
extract all gene features from genbank and cast to tabular data
.PP
.SH OPTIONS
.PP
\fBgbff\fB \fR\- 
 a [File](cref:T:SMRUCC.genomics.Assembly.NCBI.GenBank.GBFF.File) ncbi genbank assembly object for extract its 
 gene features.
. 
.PP
.PP
\fBORF\fB \fR\- 
 export the gene features with its ORF region data?
. 
.PP
.SH VALUE
.PP
a vector of the [GeneTable](cref:T:SMRUCC.genomics.ComponentModel.Annotation.GeneTable) gene table record object.
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
