.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "export_geneNt_fasta" "export_geneNt_fasta"
.SH NAME
export_geneNt_fasta \- 
.SH SYNOPSIS
\fIexport_geneNt_fasta(\fBgb\fR as <generic> File, 
\fBtitle\fR as string = "<gb_asm_id>.<locus_tag> <nucl_loc> <product>|<lineage>", 
\fBkey\fR as any = ["gene","CDS"], 
\fBrequired\fR as string = \fB<NULL>\fR, 
\fBunique_names\fR as boolean = FALSE);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
