.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "feature" "feature"
.SH NAME
feature \- create new feature site
.SH SYNOPSIS
\fIfeature(\fBkeyName\fR as string, 
\fBlocation\fR as <generic> NucleotideLocation, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create new feature site
.PP
.SH OPTIONS
.PP
\fBkeyName\fB \fR\- 
 the feature key name, example as \fBgene\fR, \fBCDS\fR or \fBtRNA\fR.
. 
.PP
.PP
\fBlocation\fB \fR\- 
 the location region of the target feature site.
. 
.PP
.PP
\fBdata\fB \fR\- 
 a R# list object of the feature qualifiers data: the name of each list 
 element is the qualifier name, and the element value is a character 
 vector of the qualifier value.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a new [Feature](cref:T:SMRUCC.genomics.Assembly.NCBI.GenBank.GBFF.Keywords.FEATURES.Feature) genbank feature site object.
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
