.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "featureMeta" "featureMeta"
.SH NAME
featureMeta \- extract the feature metadata from a genbank clr feature object
.SH SYNOPSIS
\fIfeatureMeta(\fBfeatures\fR as any, 
\fBattrName\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
extract the feature metadata from a genbank clr feature object
.PP
.SH OPTIONS
.PP
\fBfeatures\fB \fR\- 
 a collection of the genbank feature object for extract its metadata 
 information.
. 
.PP
.PP
\fBattrName$\fB \fR\- 
 the qualifier name of the target metadata. If this parameter is not 
 specified, then all of the metadata of the target features will be 
 returned.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a named list of the feature metadata or a character vector of the 
 specific qualifier value;
 
 this function returns a R# error message object if the input features 
 data can not be cast to a collection of the genbank feature object.
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
