.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "getRNA.fasta" "getRNA.fasta"
.SH NAME
getRNA.fasta \- get all of the RNA gene its gene sequence in fasta sequence format.
.SH SYNOPSIS
\fIgetRNA.fasta(\fBgb\fR as <generic> File);\fR
.SH DESCRIPTION
.PP
get all of the RNA gene its gene sequence in fasta sequence format.
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
