.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "protein_seqs" "protein_seqs"
.SH NAME
protein_seqs \- 
.SH SYNOPSIS
\fIprotein_seqs(\fBgb\fR as <generic> File, 
\fBproteins\fR as any = \fB<NULL>\fR, 
\fBtitle\fR as string = \fB<NULL>\fR, 
\fBfilter_empty\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
