.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "read.genbank" "read.genbank"
.SH NAME
read.genbank \- read the given genbank assembly file.
.SH SYNOPSIS
\fIread.genbank(\fBfile\fR as string, 
\fBrepliconTable\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read the given genbank assembly file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- the file path of the given genbank assembly file.. 
.PP
.PP
\fBrepliconTable\fB \fR\- 
 read the replicon table data of the genbank assembly file?
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a [File](cref:T:SMRUCC.genomics.Assembly.NCBI.GenBank.GBFF.File) ncbi genbank assembly object that read from 
 the given genbank assembly file;
 
 this function returns a R# error message object if the given file is 
 not exists.
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
