.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "read.genbank" "read.genbank"
.SH NAME
read.genbank \- 
.SH SYNOPSIS
\fIread.genbank(\fBfile\fR as string, 
\fBrepliconTable\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
