.\" man page create by R# package system.
.TH QC 1 2000-1月 "nano_plot" "nano_plot"
.SH NAME
nano_plot \- make stats of the reads and export the nano plot formated stats result
.SH SYNOPSIS
\fInano_plot(\fBreads\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make stats of the reads and export the nano plot formated stats result
.PP
.SH OPTIONS
.PP
\fBreads\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
QC
.SH FILES
.PP
rnaseq.dll
.PP
