.\" man page create by R# package system.
.TH QC 1 2000-1月 "nano_report" "nano_report"
.SH NAME
nano_report \- generates the fastq reads QC summary text
.SH SYNOPSIS
\fInano_report(\fBnanoplot\fR as <generic> NanoPlotResult, 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
generates the fastq reads QC summary text
.PP
.SH OPTIONS
.PP
\fBnanoplot\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
QC
.SH FILES
.PP
rnaseq.dll
.PP
