.\" man page create by R# package system.
.TH VCELLKIT.SIMULATOR 2 2020-10-29 "dynamics.default" "dynamics.default"
.SH NAME
dynamics.default \- Create the default cell dynamics parameters
.SH SYNOPSIS
\fIdynamics.default();\fR
.SH DESCRIPTION
.PP
Create the default cell dynamics parameters
.PP
.SH SEE ALSO
vcellkit.simulator
.SH FILES
.PP
vcellkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
