.\" man page create by R# package system.
.TH VCELLKIT.SIMULATOR 2 2020-07-19 "vcell.mass.index" "vcell.mass.index"
.SH NAME
vcell.mass.index \- 
.SH SYNOPSIS
\fIvcell.mass.index(\fBvcell\fR as <generic> CellularModule);\fR
.SH SEE ALSO
vcellkit.simulator
.SH FILES
.PP
vcellkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
