.\" man page create by R# package system.
.TH VCELLKIT.SIMULATOR 2 2020-07-26 "vcell.mass.kegg" "vcell.mass.kegg"
.SH NAME
vcell.mass.kegg \- Create a new status profile data object with unify mass contents.
.SH SYNOPSIS
\fIvcell.mass.kegg(\fBvcell\fR as <generic> VirtualCell, 
\fBmass\fR as double = 5000);\fR
.SH DESCRIPTION
.PP
Create a new status profile data object with unify mass contents.
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -
.PP
.PP
\fBmass#\fB \fR\- -
.PP
.SH SEE ALSO
vcellkit.simulator
.SH FILES
.PP
vcellkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
