.\" man page create by R# package system.
.TH VCELLKIT.SIMULATOR 2 2020-07-22 "vcell.flux.index" "vcell.flux.index"
.SH NAME
vcell.flux.index \- 
.SH SYNOPSIS
\fIvcell.flux.index(\fBvcell\fR as <generic> CellularModule);\fR
.SH SEE ALSO
vcellkit.simulator
.SH FILES
.PP
vcellkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
