.\" man page create by R# package system.
.TH R.UTILS.READ 1 2000-01-01 "read.csv" "read.csv"
.SH NAME
read.csv \- Read a csv file and then returns a temp variable
.SH SYNOPSIS
\fIread.csv(\fBfile\fR as string, 
\fBheader\fR as boolean = TRUE, 
\fBsep\fR as string = ",", 
\fBquote\fR as string = "\"", 
\fBdec\fR as string = ".", 
\fBfill\fR as boolean = TRUE, 
\fBcommentChar\fR as string = "");\fR
.SH DESCRIPTION
.PP
Read a csv file and then returns a temp variable
.PP
.SH OPTIONS
.PP
\fBfile$\fB \fR\- -
.PP
.PP
\fBheader\fB \fR\- -
.PP
.PP
\fBsep$\fB \fR\- -
.PP
.PP
\fBquote$\fB \fR\- -
.PP
.PP
\fBdec$\fB \fR\- -
.PP
.PP
\fBfill\fB \fR\- -
.PP
.PP
\fBcommentChar$\fB \fR\- -
.PP
.SH SEE ALSO
R.utils.read
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH COPYRIGHT
Copyright ©  2015
