.\" man page create by R# package system.
.TH BASE 1 2020-10-29 "append" "append"
.SH NAME
append \- 
.SH SYNOPSIS
\fIappend(\fBx\fR as <generic> Object, 
\fBvalues\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
