.\" man page create by R# package system.
.TH BASE 1 2020-11-09 "auto" "auto"
.SH NAME
auto \- 
.SH SYNOPSIS
\fIauto(\fBx\fR as <generic> Object, 
\fBdispose\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- @\fBT:Microsoft.VisualBasic.ComponentModel.ISaveHandle\fR object or any other object.
.PP
.PP
\fBdispose\fB \fR\- 
 the dispose handler, for type of parameter x is @\fBT:Microsoft.VisualBasic.ComponentModel.ISaveHandle\fR,
 this parameter value should be a file path. for other type, this parameter
 value should be a function object.

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
