.\" man page create by R# package system.
.TH BASE 1 2020-11-09 "exit" "exit"
.SH NAME
exit \- force quit of current R# session without confirm
.SH SYNOPSIS
\fIexit(\fBstatus\fR as integer);\fR
.SH DESCRIPTION
.PP
force quit of current R# session without confirm
.PP
.SH OPTIONS
.PP
\fBstatus\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
