.\" man page create by R# package system.
.TH BASE 1 2020-11-09 "getOption" "getOption"
.SH NAME
getOption \- 
.SH SYNOPSIS
\fIgetOption(\fBname\fR as string, 
\fBdefaultVal\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
