.\" man page create by R# package system.
.TH BASE 1 2020-10-29 "invisible" "invisible"
.SH NAME
invisible \- Change the Print Mode to Invisible
.SH SYNOPSIS
\fIinvisible(\fBx\fR as <generic> Object);\fR
.SH DESCRIPTION
.PP
Change the Print Mode to Invisible
 
 Return a (temporarily) invisible copy of an object.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- an arbitrary R object.
.PP
.SH VALUE
.PP
This function can be useful when it is desired to have functions 
 return values which can be assigned, but which do not print when 
 they are not assigned.
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
