.\" man page create by R# package system.
.TH BASE 1 2020-12-15 "is.na" "is.na"
.SH NAME
is.na \- ‘Not Available’ / Missing Values
.SH SYNOPSIS
\fIis.na(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
‘Not Available’ / Missing Values
 
 NA is a logical constant of length 1 which contains a missing value indicator. 
 NA can be coerced to any other vector type except raw. There are also constants 
 NA_integer_, NA_real_, NA_complex_ and NA_character_ of the other atomic vector 
 types which support missing values: all of these are reserved words in the R 
 language.
 
 The generic Function Is.na indicates which elements are missing.
 The generic Function Is.na<- sets elements To NA.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- an R object to be tested: the default method for is.na and anyNA handle atomic vectors, lists, pairlists, and NULL.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH VALUE
.PP
The default method for is.na applied to an atomic vector returns a logical vector 
 of the same length as its argument x, containing TRUE for those elements marked NA 
 or, for numeric or complex vectors, NaN, and FALSE otherwise. (A complex value is 
 regarded as NA if either its real or imaginary part is NA or NaN.) dim, dimnames 
 and names attributes are copied to the result.

 The Default methods also work For lists And pairlists
 
 For Is.na, elementwise the result Is false unless that element Is a length-one atomic 
 vector And the single element of that vector Is regarded as NA Or NaN (note that any 
 Is.na method for the class of the element Is ignored).
 
 anyNA(recursive = FALSE) works the same way as Is.na; anyNA(recursive = TRUE) applies 
 anyNA (with method dispatch) to each element.

 The data frame method For Is.na returns a logical matrix With the same dimensions As 
 the data frame, And With dimnames taken from the row And column names Of the data 
 frame.

 anyNA(NULL) Is false; Is.na(NULL) Is logical(0) (no longer warning since R version 3.5.0).
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
