.\" man page create by R# package system.
.TH BASE 1 2020-11-02 "list" "list"
.SH NAME
list \- Lists – Generic and Dotted Pairs
.SH SYNOPSIS
\fIlist(..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Lists – Generic and Dotted Pairs
 
 Functions to construct, coerce and check for both kinds of \fBR#\fR lists.
.PP
.SH OPTIONS
.PP
\fBslots\fB \fR\- objects, possibly named.
.PP
.PP
\fBenvir\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
