.\" man page create by R# package system.
.TH BASE 1 2020-11-09 "nrow" "nrow"
.SH NAME
nrow \- The Number of Rows/Columns of an Array
.SH SYNOPSIS
\fInrow(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
The Number of Rows/Columns of an Array
 
 nrow and ncol return the number of rows or columns present in x.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a vector, array, data frame, or NULL.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH VALUE
.PP
an integer of length 1 or NULL, the latter only for ncol and nrow.
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
