.\" man page create by R# package system.
.TH BASE 1 2020-11-09 "print" "print"
.SH NAME
print \- Print Values
.SH SYNOPSIS
\fIprint(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Print Values
 
 print prints its argument and returns it invisibly (via invisible(x)). 
 It is a generic function which means that new printing methods can be 
 easily added for new classes.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- an object used to select a method.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
