.\" man page create by R# package system.
.TH BASE 1 2020-11-02 "q" "q"
.SH NAME
q \- Terminate an R Session
.SH SYNOPSIS
\fIq(\fBsave\fR as string = "default", 
\fBstatus\fR as integer = 0, 
\fBrunLast\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Terminate an R Session
 
 The function \fBquit\fR or its alias \fBq\fR terminate the current R session.
.PP
.SH OPTIONS
.PP
\fBsave\fB \fR\- 
 a character string indicating whether the environment (workspace) should be saved, 
 one of \fB"no"\fR, \fB"yes"\fR, \fB"ask"\fR or \fB"default"\fR.

.PP
.PP
\fBstatus\fB \fR\- 
 the (numerical) error status to be returned to the operating system, where relevant. 
 Conventionally 0 indicates successful completion.

.PP
.PP
\fBrunLast\fB \fR\- 
 should \fB.Last()\fR be executed?

.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
