.\" man page create by R# package system.
.TH BASE 1 2020-10-29 "rbind" "rbind"
.SH NAME
rbind \- 
.SH SYNOPSIS
\fIrbind(\fBd\fR as <generic> dataframe, 
\fBrow\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
