.\" man page create by R# package system.
.TH BASE 1 2020-11-09 "stop" "stop"
.SH NAME
stop \- 
.SH SYNOPSIS
\fIstop(\fBmessage\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBmessage\fB \fR\- 
 @\fBT:System.String\fR array or @\fBT:System.Exception\fR

.PP
.PP
\fBenvir\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
