.\" man page create by R# package system.
.TH BASE 1 2020-12-15 "summary" "summary"
.SH NAME
summary \- Object Summaries
.SH SYNOPSIS
\fIsummary(\fBobject\fR as <generic> Object, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Object Summaries
 
 summary is a generic function used to produce result summaries of 
 the results of various model fitting functions. The function 
 invokes particular methods which depend on the class of the first 
 argument.
.PP
.SH OPTIONS
.PP
\fBobject\fB \fR\- 
 an object for which a summary is desired.

.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
