.\" man page create by R# package system.
.TH BASE 1 2020-10-29 "unit" "unit"
.SH NAME
unit \- get or set unit to a given vector
.SH SYNOPSIS
\fIunit(\fBx\fR as <generic> Object, 
\fBunit\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get or set unit to a given vector
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -
.PP
.PP
\fBunit\fB \fR\- -
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
