#Region "Microsoft.VisualBasic::2e4978b3d639c05e11a6cc6083334412, markdown2pdf\JavaScript\font-awesome\Icons.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:

    ' Enum icons
    ' 
    '     [Stop], _500px, AccessibleIcon, Accusoft, AddressBook
    '     AddressCard, Adjust, Adn, Adversal, Affiliatetheme
    '     Algolia, AlignCenter, AlignJustify, AlignLeft, AlignRight
    '     Amazon, AmazonPay, Ambulance, AmericanSignLanguageInterpreting, Amilia
    '     Anchor, Android, Angellist, AngleDoubleDown, AngleDoubleLeft
    '     AngleDoubleRight, AngleDoubleUp, AngleDown, AngleLeft, AngleRight
    '     AngleUp, Angrycreative, Angular, Apper, Apple
    '     ApplePay, AppStore, AppStoreIos, Archive, ArrowAltCircleDown
    '     ArrowAltCircleLeft, ArrowAltCircleRight, ArrowAltCircleUp, ArrowCircleDown, ArrowCircleLeft
    '     ArrowCircleRight, ArrowCircleUp, ArrowDown, ArrowLeft, ArrowRight
    '     ArrowsAlt, ArrowsAltH, ArrowsAltV, ArrowUp, AssistiveListeningSystems
    '     Asterisk, Asymmetrik, At, Audible, AudioDescription
    '     Autoprefixer, Avianex, Aviato, Aws, Backward
    '     BalanceScale, Ban, BandAid, Bandcamp, Barcode
    '     Bars, BaseballBall, BasketballBall, Bath, BatteryEmpty
    '     BatteryFull, BatteryHalf, BatteryQuarter, BatteryThreeQuarters, Bed
    '     Beer, Behance, BehanceSquare, Bell, BellSlash
    '     Bicycle, Bimobject, Binoculars, BirthdayCake, Bitbucket
    '     Bitcoin, Bity, Blackberry, BlackTie, Blind
    '     Blogger, BloggerB, Bluetooth, BluetoothB, Bold
    '     Bolt, Bomb, Book, Bookmark, BowlingBall
    '     Box, Boxes, Braille, Briefcase, Btc
    '     Bug, Building, Bullhorn, Bullseye, Buromobelexperte
    '     Bus, Buysellads, Calculator, Calendar, CalendarAlt
    '     CalendarCheck, CalendarMinus, CalendarPlus, CalendarTimes, Camera
    '     CameraRetro, Car, CaretDown, CaretLeft, CaretRight
    '     CaretSquareDown, CaretSquareLeft, CaretSquareRight, CaretSquareUp, CaretUp
    '     CartArrowDown, CartPlus, CcAmazonPay, CcAmex, CcApplePay
    '     CcDinersClub, CcDiscover, CcJcb, CcMastercard, CcPaypal
    '     CcStripe, CcVisa, Centercode, Certificate, ChartArea
    '     ChartBar, ChartLine, ChartPie, Check, CheckCircle
    '     CheckSquare, Chess, ChessBishop, ChessBoard, ChessKing
    '     ChessKnight, ChessPawn, ChessQueen, ChessRook, ChevronCircleDown
    '     ChevronCircleLeft, ChevronCircleRight, ChevronCircleUp, ChevronDown, ChevronLeft
    '     ChevronRight, ChevronUp, Child, Chrome, Circle
    '     CircleNotch, Clipboard, ClipboardCheck, ClipboardList, Clock
    '     Clone, ClosedCaptioning, Cloud, CloudDownloadAlt, Cloudscale
    '     Cloudsmith, CloudUploadAlt, Cloudversify, Code, CodeBranch
    '     Codepen, Codiepie, Coffee, Cog, Cogs
    '     Columns, Comment, CommentAlt, Comments, Compass
    '     Compress, Connectdevelop, Contao, Copy, Copyright
    '     Cpanel, CreativeCommons, CreditCard, Crop, Crosshairs
    '     Css3, Css3Alt, Cube, Cubes, Cut
    '     Cuttlefish, DAndD, Dashcube, Database, Deaf
    '     Delicious, Deploydog, Deskpro, Desktop, Deviantart
    '     Digg, DigitalOcean, Discord, Discourse, Dna
    '     Dochub, Docker, DollarSign, Dolly, DollyFlatbed
    '     DotCircle, Download, Draft2digital, Dribbble, DribbbleSquare
    '     Dropbox, Drupal, Dyalog, Earlybirds, Edge
    '     Edit, Eject, Elementor, EllipsisH, EllipsisV
    '     Ember, Empire, Envelope, EnvelopeOpen, EnvelopeSquare
    '     Envira, Eraser, Erlang, Ethereum, Etsy
    '     EuroSign, ExchangeAlt, Exclamation, ExclamationCircle, ExclamationTriangle
    '     Expand, ExpandArrowsAlt, Expeditedssl, ExternalLinkAlt, ExternalLinkSquareAlt
    '     Eye, EyeDropper, EyeSlash, Facebook, FacebookF
    '     FacebookMessenger, FacebookSquare, FastBackward, FastForward, Fax
    '     Female, FighterJet, File, FileAlt, FileArchive
    '     FileAudio, FileCode, FileExcel, FileImage, FilePdf
    '     FilePowerpoint, FileVideo, FileWord, Film, Filter
    '     Fire, FireExtinguisher, Firefox, FirstAid, Firstdraft
    '     FirstOrder, Flag, FlagCheckered, Flask, Flickr
    '     Flipboard, Fly, Folder, FolderOpen, Font
    '     FontAwesome, FontAwesomeAlt, FontAwesomeFlag, Fonticons, FonticonsFi
    '     FootballBall, FortAwesome, FortAwesomeAlt, Forumbee, Forward
    '     Foursquare, Freebsd, FreeCodeCamp, Frown, Futbol
    '     Gamepad, Gavel, Gem, Genderless, GetPocket
    '     Gg, GgCircle, Gift, Git, Github
    '     GithubAlt, GithubSquare, Gitkraken, Gitlab, GitSquare
    '     Gitter, GlassMartini, Glide, GlideG, Globe
    '     Gofore, GolfBall, Goodreads, GoodreadsG, Google
    '     GoogleDrive, GooglePlay, GooglePlus, GooglePlusG, GooglePlusSquare
    '     GoogleWallet, GraduationCap, Gratipay, Grav, Gripfire
    '     Grunt, Gulp, HackerNews, HackerNewsSquare, HandLizard
    '     HandPaper, HandPeace, HandPointDown, HandPointer, HandPointLeft
    '     HandPointRight, HandPointUp, HandRock, HandScissors, Handshake
    '     HandSpock, Hashtag, Hdd, Heading, Headphones
    '     Heart, Heartbeat, Hips, HireAHelper, History
    '     HockeyPuck, Home, Hooli, Hospital, HospitalSymbol
    '     Hotjar, Hourglass, HourglassEnd, HourglassHalf, HourglassStart
    '     Houzz, HSquare, Html5, Hubspot, ICursor
    '     IdBadge, IdCard, Image, Images, Imdb
    '     Inbox, Indent, Industry, Info, InfoCircle
    '     Instagram, InternetExplorer, Ioxhost, Italic, Itunes
    '     ItunesNote, Jenkins, Joget, Joomla, Js
    '     Jsfiddle, JsSquare, Key, Keyboard, Keycdn
    '     Kickstarter, KickstarterK, Korvue, Language, Laptop
    '     Laravel, Lastfm, LastfmSquare, Leaf, Leanpub
    '     Lemon, Less, LevelDownAlt, LevelUpAlt, LifeRing
    '     Lightbulb, Line, Link, Linkedin, LinkedinIn
    '     Linode, Linux, LiraSign, List, ListAlt
    '     ListOl, ListUl, LocationArrow, Lock, LockOpen
    '     LongArrowAltDown, LongArrowAltLeft, LongArrowAltRight, LongArrowAltUp, LowVision
    '     Lyft, Magento, Magic, Magnet, Male
    '     Map, MapMarker, MapMarkerAlt, MapPin, MapSigns
    '     Mars, MarsDouble, MarsStroke, MarsStrokeH, MarsStrokeV
    '     Maxcdn, Medapps, Medium, MediumM, Medkit
    '     Medrt, Meetup, Meh, Mercury, Microchip
    '     Microphone, MicrophoneSlash, Microsoft, Minus, MinusCircle
    '     MinusSquare, Mix, Mixcloud, Mizuni, Mobile
    '     MobileAlt, Modx, Monero, MoneyBillAlt, Moon
    '     Motorcycle, MousePointer, Music, Napster, Neuter
    '     Newspaper, NintendoSwitch, Node, NodeJs, Npm
    '     Ns8, Nutritionix, ObjectGroup, ObjectUngroup, Odnoklassniki
    '     OdnoklassnikiSquare, Opencart, Openid, Opera, OptinMonster
    '     Osi, Outdent, Page4, Pagelines, PaintBrush
    '     Palfed, Pallet, Paperclip, PaperPlane, Paragraph
    '     Paste, Patreon, Pause, PauseCircle, Paw
    '     Paypal, PencilAlt, PenSquare, Percent, Periscope
    '     Phabricator, PhoenixFramework, Phone, PhoneSquare, PhoneVolume
    '     Php, PiedPiper, PiedPiperAlt, PiedPiperPp, Pills
    '     Pinterest, PinterestP, PinterestSquare, Plane, Play
    '     PlayCircle, Playstation, Plug, Plus, PlusCircle
    '     PlusSquare, Podcast, PoundSign, PowerOff, Print
    '     ProductHunt, Pushed, PuzzlePiece, Python, Qq
    '     Qrcode, Question, QuestionCircle, Quidditch, Quinscape
    '     Quora, QuoteLeft, QuoteRight, Random, Ravelry
    '     React, Rebel, Recycle, Reddit, RedditAlien
    '     RedditSquare, Redo, RedoAlt, RedRiver, Registered
    '     Rendact, Renren, Reply, ReplyAll, Replyd
    '     Resolving, Retweet, Road, Rocket, Rocketchat
    '     Rockrms, Rss, RssSquare, RubleSign, RupeeSign
    '     Safari, Sass, Save, Schlix, Scribd
    '     Search, Searchengin, SearchMinus, SearchPlus, Sellcast
    '     Sellsy, Server, Servicestack, Share, ShareAlt
    '     ShareAltSquare, ShareSquare, ShekelSign, ShieldAlt, Ship
    '     ShippingFast, Shirtsinbulk, ShoppingBag, ShoppingBasket, ShoppingCart
    '     Shower, Signal, SignInAlt, SignLanguage, SignOutAlt
    '     Simplybuilt, Sistrix, Sitemap, Skyatlas, Skype
    '     Slack, SlackHash, SlidersH, Slideshare, Smile
    '     Snapchat, SnapchatGhost, SnapchatSquare, Snowflake, Sort
    '     SortAlphaDown, SortAlphaUp, SortAmountDown, SortAmountUp, SortDown
    '     SortNumericDown, SortNumericUp, SortUp, Soundcloud, SpaceShuttle
    '     Speakap, Spinner, Spotify, Square, SquareFull
    '     StackExchange, StackOverflow, Star, StarHalf, Staylinked
    '     Steam, SteamSquare, SteamSymbol, StepBackward, StepForward
    '     Stethoscope, StickerMule, StickyNote, StopCircle, Stopwatch
    '     Strava, StreetView, Strikethrough, Stripe, StripeS
    '     Studiovinari, Stumbleupon, StumbleuponCircle, Subscript, Subway
    '     Suitcase, Sun, Superpowers, Superscript, Supple
    '     Sync, SyncAlt, Syringe, Table, Tablet
    '     TabletAlt, TableTennis, TachometerAlt, Tag, Tags
    '     Tasks, Taxi, Telegram, TelegramPlane, TencentWeibo
    '     Terminal, TextHeight, TextWidth, Th, Themeisle
    '     Thermometer, ThermometerEmpty, ThermometerFull, ThermometerHalf, ThermometerQuarter
    '     ThermometerThreeQuarters, ThLarge, ThList, ThumbsDown, ThumbsUp
    '     Thumbtack, TicketAlt, Times, TimesCircle, Tint
    '     ToggleOff, ToggleOn, Trademark, Train, Transgender
    '     TransgenderAlt, Trash, TrashAlt, Tree, Trello
    '     Tripadvisor, Trophy, Truck, Tty, Tumblr
    '     TumblrSquare, Tv, Twitch, Twitter, TwitterSquare
    '     Typo3, Uber, Uikit, Umbrella, Underline
    '     Undo, UndoAlt, Uniregistry, UniversalAccess, University
    '     Unlink, Unlock, UnlockAlt, Untappd, Upload
    '     Usb, User, UserCircle, UserMd, UserPlus
    '     Users, UserSecret, UserTimes, Ussunnah, Utensils
    '     UtensilSpoon, Vaadin, Venus, VenusDouble, VenusMars
    '     Viacoin, Viadeo, ViadeoSquare, Viber, Video
    '     Vimeo, VimeoSquare, VimeoV, Vine, Vk
    '     Vnv, VolleyballBall, VolumeDown, VolumeOff, VolumeUp
    '     Vuejs, Warehouse, Weibo, Weight, Weixin
    '     Whatsapp, WhatsappSquare, Wheelchair, Whmcs, Wifi
    '     WikipediaW, WindowClose, WindowMaximize, WindowMinimize, WindowRestore
    '     Windows, WonSign, Wordpress, WordpressSimple, Wpbeginner
    '     Wpexplorer, Wpforms, Wrench, Xbox, Xing
    '     XingSquare, Yahoo, Yandex, YandexInternational, YCombinator
    '     Yelp, YenSign, Yoast, Youtube, YoutubeSquare
    ' 
    '  
    ' 
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports System.ComponentModel

Public Enum icons
    <Content("\f26e")>
    <Description("500px")>
    _500px
    <Content("\f368")>
    <Description("accessible-icon")>
    AccessibleIcon
    <Content("\f369")>
    <Description("accusoft")>
    Accusoft
    <Content("\f2b9")>
    <Description("address-book")>
    AddressBook
    <Content("\f2bb")>
    <Description("address-card")>
    AddressCard
    <Content("\f042")>
    <Description("adjust")>
    Adjust
    <Content("\f170")>
    <Description("adn")>
    Adn
    <Content("\f36a")>
    <Description("adversal")>
    Adversal
    <Content("\f36b")>
    <Description("affiliatetheme")>
    Affiliatetheme
    <Content("\f36c")>
    <Description("algolia")>
    Algolia
    <Content("\f037")>
    <Description("align-center")>
    AlignCenter
    <Content("\f039")>
    <Description("align-justify")>
    AlignJustify
    <Content("\f036")>
    <Description("align-left")>
    AlignLeft
    <Content("\f038")>
    <Description("align-right")>
    AlignRight
    <Content("\f270")>
    <Description("amazon")>
    Amazon
    <Content("\f42c")>
    <Description("amazon-pay")>
    AmazonPay
    <Content("\f0f9")>
    <Description("ambulance")>
    Ambulance
    <Content("\f2a3")>
    <Description("american-sign-language-interpreting")>
    AmericanSignLanguageInterpreting
    <Content("\f36d")>
    <Description("amilia")>
    Amilia
    <Content("\f13d")>
    <Description("anchor")>
    Anchor
    <Content("\f17b")>
    <Description("android")>
    Android
    <Content("\f209")>
    <Description("angellist")>
    Angellist
    <Content("\f103")>
    <Description("angle-double-down")>
    AngleDoubleDown
    <Content("\f100")>
    <Description("angle-double-left")>
    AngleDoubleLeft
    <Content("\f101")>
    <Description("angle-double-right")>
    AngleDoubleRight
    <Content("\f102")>
    <Description("angle-double-up")>
    AngleDoubleUp
    <Content("\f107")>
    <Description("angle-down")>
    AngleDown
    <Content("\f104")>
    <Description("angle-left")>
    AngleLeft
    <Content("\f105")>
    <Description("angle-right")>
    AngleRight
    <Content("\f106")>
    <Description("angle-up")>
    AngleUp
    <Content("\f36e")>
    <Description("angrycreative")>
    Angrycreative
    <Content("\f420")>
    <Description("angular")>
    Angular
    <Content("\f371")>
    <Description("apper")>
    Apper
    <Content("\f179")>
    <Description("apple")>
    Apple
    <Content("\f415")>
    <Description("apple-pay")>
    ApplePay
    <Content("\f36f")>
    <Description("app-store")>
    AppStore
    <Content("\f370")>
    <Description("app-store-ios")>
    AppStoreIos
    <Content("\f187")>
    <Description("archive")>
    Archive
    <Content("\f358")>
    <Description("arrow-alt-circle-down")>
    ArrowAltCircleDown
    <Content("\f359")>
    <Description("arrow-alt-circle-left")>
    ArrowAltCircleLeft
    <Content("\f35a")>
    <Description("arrow-alt-circle-right")>
    ArrowAltCircleRight
    <Content("\f35b")>
    <Description("arrow-alt-circle-up")>
    ArrowAltCircleUp
    <Content("\f0ab")>
    <Description("arrow-circle-down")>
    ArrowCircleDown
    <Content("\f0a8")>
    <Description("arrow-circle-left")>
    ArrowCircleLeft
    <Content("\f0a9")>
    <Description("arrow-circle-right")>
    ArrowCircleRight
    <Content("\f0aa")>
    <Description("arrow-circle-up")>
    ArrowCircleUp
    <Content("\f063")>
    <Description("arrow-down")>
    ArrowDown
    <Content("\f060")>
    <Description("arrow-left")>
    ArrowLeft
    <Content("\f061")>
    <Description("arrow-right")>
    ArrowRight
    <Content("\f0b2")>
    <Description("arrows-alt")>
    ArrowsAlt
    <Content("\f337")>
    <Description("arrows-alt-h")>
    ArrowsAltH
    <Content("\f338")>
    <Description("arrows-alt-v")>
    ArrowsAltV
    <Content("\f062")>
    <Description("arrow-up")>
    ArrowUp
    <Content("\f2a2")>
    <Description("assistive-listening-systems")>
    AssistiveListeningSystems
    <Content("\f069")>
    <Description("asterisk")>
    Asterisk
    <Content("\f372")>
    <Description("asymmetrik")>
    Asymmetrik
    <Content("\f1fa")>
    <Description("at")>
    At
    <Content("\f373")>
    <Description("audible")>
    Audible
    <Content("\f29e")>
    <Description("audio-description")>
    AudioDescription
    <Content("\f41c")>
    <Description("autoprefixer")>
    Autoprefixer
    <Content("\f374")>
    <Description("avianex")>
    Avianex
    <Content("\f421")>
    <Description("aviato")>
    Aviato
    <Content("\f375")>
    <Description("aws")>
    Aws
    <Content("\f04a")>
    <Description("backward")>
    Backward
    <Content("\f24e")>
    <Description("balance-scale")>
    BalanceScale
    <Content("\f05e")>
    <Description("ban")>
    Ban
    <Content("\f462")>
    <Description("band-aid")>
    BandAid
    <Content("\f2d5")>
    <Description("bandcamp")>
    Bandcamp
    <Content("\f02a")>
    <Description("barcode")>
    Barcode
    <Content("\f0c9")>
    <Description("bars")>
    Bars
    <Content("\f433")>
    <Description("baseball-ball")>
    BaseballBall
    <Content("\f434")>
    <Description("basketball-ball")>
    BasketballBall
    <Content("\f2cd")>
    <Description("bath")>
    Bath
    <Content("\f244")>
    <Description("battery-empty")>
    BatteryEmpty
    <Content("\f240")>
    <Description("battery-full")>
    BatteryFull
    <Content("\f242")>
    <Description("battery-half")>
    BatteryHalf
    <Content("\f243")>
    <Description("battery-quarter")>
    BatteryQuarter
    <Content("\f241")>
    <Description("battery-three-quarters")>
    BatteryThreeQuarters
    <Content("\f236")>
    <Description("bed")>
    Bed
    <Content("\f0fc")>
    <Description("beer")>
    Beer
    <Content("\f1b4")>
    <Description("behance")>
    Behance
    <Content("\f1b5")>
    <Description("behance-square")>
    BehanceSquare
    <Content("\f0f3")>
    <Description("bell")>
    Bell
    <Content("\f1f6")>
    <Description("bell-slash")>
    BellSlash
    <Content("\f206")>
    <Description("bicycle")>
    Bicycle
    <Content("\f378")>
    <Description("bimobject")>
    Bimobject
    <Content("\f1e5")>
    <Description("binoculars")>
    Binoculars
    <Content("\f1fd")>
    <Description("birthday-cake")>
    BirthdayCake
    <Content("\f171")>
    <Description("bitbucket")>
    Bitbucket
    <Content("\f379")>
    <Description("bitcoin")>
    Bitcoin
    <Content("\f37a")>
    <Description("bity")>
    Bity
    <Content("\f37b")>
    <Description("blackberry")>
    Blackberry
    <Content("\f27e")>
    <Description("black-tie")>
    BlackTie
    <Content("\f29d")>
    <Description("blind")>
    Blind
    <Content("\f37c")>
    <Description("blogger")>
    Blogger
    <Content("\f37d")>
    <Description("blogger-b")>
    BloggerB
    <Content("\f293")>
    <Description("bluetooth")>
    Bluetooth
    <Content("\f294")>
    <Description("bluetooth-b")>
    BluetoothB
    <Content("\f032")>
    <Description("bold")>
    Bold
    <Content("\f0e7")>
    <Description("bolt")>
    Bolt
    <Content("\f1e2")>
    <Description("bomb")>
    Bomb
    <Content("\f02d")>
    <Description("book")>
    Book
    <Content("\f02e")>
    <Description("bookmark")>
    Bookmark
    <Content("\f436")>
    <Description("bowling-ball")>
    BowlingBall
    <Content("\f466")>
    <Description("box")>
    Box
    <Content("\f468")>
    <Description("boxes")>
    Boxes
    <Content("\f2a1")>
    <Description("braille")>
    Braille
    <Content("\f0b1")>
    <Description("briefcase")>
    Briefcase
    <Content("\f15a")>
    <Description("btc")>
    Btc
    <Content("\f188")>
    <Description("bug")>
    Bug
    <Content("\f1ad")>
    <Description("building")>
    Building
    <Content("\f0a1")>
    <Description("bullhorn")>
    Bullhorn
    <Content("\f140")>
    <Description("bullseye")>
    Bullseye
    <Content("\f37f")>
    <Description("buromobelexperte")>
    Buromobelexperte
    <Content("\f207")>
    <Description("bus")>
    Bus
    <Content("\f20d")>
    <Description("buysellads")>
    Buysellads
    <Content("\f1ec")>
    <Description("calculator")>
    Calculator
    <Content("\f133")>
    <Description("calendar")>
    Calendar
    <Content("\f073")>
    <Description("calendar-alt")>
    CalendarAlt
    <Content("\f274")>
    <Description("calendar-check")>
    CalendarCheck
    <Content("\f272")>
    <Description("calendar-minus")>
    CalendarMinus
    <Content("\f271")>
    <Description("calendar-plus")>
    CalendarPlus
    <Content("\f273")>
    <Description("calendar-times")>
    CalendarTimes
    <Content("\f030")>
    <Description("camera")>
    Camera
    <Content("\f083")>
    <Description("camera-retro")>
    CameraRetro
    <Content("\f1b9")>
    <Description("car")>
    Car
    <Content("\f0d7")>
    <Description("caret-down")>
    CaretDown
    <Content("\f0d9")>
    <Description("caret-left")>
    CaretLeft
    <Content("\f0da")>
    <Description("caret-right")>
    CaretRight
    <Content("\f150")>
    <Description("caret-square-down")>
    CaretSquareDown
    <Content("\f191")>
    <Description("caret-square-left")>
    CaretSquareLeft
    <Content("\f152")>
    <Description("caret-square-right")>
    CaretSquareRight
    <Content("\f151")>
    <Description("caret-square-up")>
    CaretSquareUp
    <Content("\f0d8")>
    <Description("caret-up")>
    CaretUp
    <Content("\f218")>
    <Description("cart-arrow-down")>
    CartArrowDown
    <Content("\f217")>
    <Description("cart-plus")>
    CartPlus
    <Content("\f42d")>
    <Description("cc-amazon-pay")>
    CcAmazonPay
    <Content("\f1f3")>
    <Description("cc-amex")>
    CcAmex
    <Content("\f416")>
    <Description("cc-apple-pay")>
    CcApplePay
    <Content("\f24c")>
    <Description("cc-diners-club")>
    CcDinersClub
    <Content("\f1f2")>
    <Description("cc-discover")>
    CcDiscover
    <Content("\f24b")>
    <Description("cc-jcb")>
    CcJcb
    <Content("\f1f1")>
    <Description("cc-mastercard")>
    CcMastercard
    <Content("\f1f4")>
    <Description("cc-paypal")>
    CcPaypal
    <Content("\f1f5")>
    <Description("cc-stripe")>
    CcStripe
    <Content("\f1f0")>
    <Description("cc-visa")>
    CcVisa
    <Content("\f380")>
    <Description("centercode")>
    Centercode
    <Content("\f0a3")>
    <Description("certificate")>
    Certificate
    <Content("\f1fe")>
    <Description("chart-area")>
    ChartArea
    <Content("\f080")>
    <Description("chart-bar")>
    ChartBar
    <Content("\f201")>
    <Description("chart-line")>
    ChartLine
    <Content("\f200")>
    <Description("chart-pie")>
    ChartPie
    <Content("\f00c")>
    <Description("check")>
    Check
    <Content("\f058")>
    <Description("check-circle")>
    CheckCircle
    <Content("\f14a")>
    <Description("check-square")>
    CheckSquare
    <Content("\f439")>
    <Description("chess")>
    Chess
    <Content("\f43a")>
    <Description("chess-bishop")>
    ChessBishop
    <Content("\f43c")>
    <Description("chess-board")>
    ChessBoard
    <Content("\f43f")>
    <Description("chess-king")>
    ChessKing
    <Content("\f441")>
    <Description("chess-knight")>
    ChessKnight
    <Content("\f443")>
    <Description("chess-pawn")>
    ChessPawn
    <Content("\f445")>
    <Description("chess-queen")>
    ChessQueen
    <Content("\f447")>
    <Description("chess-rook")>
    ChessRook
    <Content("\f13a")>
    <Description("chevron-circle-down")>
    ChevronCircleDown
    <Content("\f137")>
    <Description("chevron-circle-left")>
    ChevronCircleLeft
    <Content("\f138")>
    <Description("chevron-circle-right")>
    ChevronCircleRight
    <Content("\f139")>
    <Description("chevron-circle-up")>
    ChevronCircleUp
    <Content("\f078")>
    <Description("chevron-down")>
    ChevronDown
    <Content("\f053")>
    <Description("chevron-left")>
    ChevronLeft
    <Content("\f054")>
    <Description("chevron-right")>
    ChevronRight
    <Content("\f077")>
    <Description("chevron-up")>
    ChevronUp
    <Content("\f1ae")>
    <Description("child")>
    Child
    <Content("\f268")>
    <Description("chrome")>
    Chrome
    <Content("\f111")>
    <Description("circle")>
    Circle
    <Content("\f1ce")>
    <Description("circle-notch")>
    CircleNotch
    <Content("\f328")>
    <Description("clipboard")>
    Clipboard
    <Content("\f46c")>
    <Description("clipboard-check")>
    ClipboardCheck
    <Content("\f46d")>
    <Description("clipboard-list")>
    ClipboardList
    <Content("\f017")>
    <Description("clock")>
    Clock
    <Content("\f24d")>
    <Description("clone")>
    Clone
    <Content("\f20a")>
    <Description("closed-captioning")>
    ClosedCaptioning
    <Content("\f0c2")>
    <Description("cloud")>
    Cloud
    <Content("\f381")>
    <Description("cloud-download-alt")>
    CloudDownloadAlt
    <Content("\f383")>
    <Description("cloudscale")>
    Cloudscale
    <Content("\f384")>
    <Description("cloudsmith")>
    Cloudsmith
    <Content("\f382")>
    <Description("cloud-upload-alt")>
    CloudUploadAlt
    <Content("\f385")>
    <Description("cloudversify")>
    Cloudversify
    <Content("\f121")>
    <Description("code")>
    Code
    <Content("\f126")>
    <Description("code-branch")>
    CodeBranch
    <Content("\f1cb")>
    <Description("codepen")>
    Codepen
    <Content("\f284")>
    <Description("codiepie")>
    Codiepie
    <Content("\f0f4")>
    <Description("coffee")>
    Coffee
    <Content("\f013")>
    <Description("cog")>
    Cog
    <Content("\f085")>
    <Description("cogs")>
    Cogs
    <Content("\f0db")>
    <Description("columns")>
    Columns
    <Content("\f075")>
    <Description("comment")>
    Comment
    <Content("\f27a")>
    <Description("comment-alt")>
    CommentAlt
    <Content("\f086")>
    <Description("comments")>
    Comments
    <Content("\f14e")>
    <Description("compass")>
    Compass
    <Content("\f066")>
    <Description("compress")>
    Compress
    <Content("\f20e")>
    <Description("connectdevelop")>
    Connectdevelop
    <Content("\f26d")>
    <Description("contao")>
    Contao
    <Content("\f0c5")>
    <Description("copy")>
    Copy
    <Content("\f1f9")>
    <Description("copyright")>
    Copyright
    <Content("\f388")>
    <Description("cpanel")>
    Cpanel
    <Content("\f25e")>
    <Description("creative-commons")>
    CreativeCommons
    <Content("\f09d")>
    <Description("credit-card")>
    CreditCard
    <Content("\f125")>
    <Description("crop")>
    Crop
    <Content("\f05b")>
    <Description("crosshairs")>
    Crosshairs
    <Content("\f13c")>
    <Description("css3")>
    Css3
    <Content("\f38b")>
    <Description("css3-alt")>
    Css3Alt
    <Content("\f1b2")>
    <Description("cube")>
    Cube
    <Content("\f1b3")>
    <Description("cubes")>
    Cubes
    <Content("\f0c4")>
    <Description("cut")>
    Cut
    <Content("\f38c")>
    <Description("cuttlefish")>
    Cuttlefish
    <Content("\f38d")>
    <Description("d-and-d")>
    DAndD
    <Content("\f210")>
    <Description("dashcube")>
    Dashcube
    <Content("\f1c0")>
    <Description("database")>
    Database
    <Content("\f2a4")>
    <Description("deaf")>
    Deaf
    <Content("\f1a5")>
    <Description("delicious")>
    Delicious
    <Content("\f38e")>
    <Description("deploydog")>
    Deploydog
    <Content("\f38f")>
    <Description("deskpro")>
    Deskpro
    <Content("\f108")>
    <Description("desktop")>
    Desktop
    <Content("\f1bd")>
    <Description("deviantart")>
    Deviantart
    <Content("\f1a6")>
    <Description("digg")>
    Digg
    <Content("\f391")>
    <Description("digital-ocean")>
    DigitalOcean
    <Content("\f392")>
    <Description("discord")>
    Discord
    <Content("\f393")>
    <Description("discourse")>
    Discourse
    <Content("\f471")>
    <Description("dna")>
    Dna
    <Content("\f394")>
    <Description("dochub")>
    Dochub
    <Content("\f395")>
    <Description("docker")>
    Docker
    <Content("\f155")>
    <Description("dollar-sign")>
    DollarSign
    <Content("\f472")>
    <Description("dolly")>
    Dolly
    <Content("\f474")>
    <Description("dolly-flatbed")>
    DollyFlatbed
    <Content("\f192")>
    <Description("dot-circle")>
    DotCircle
    <Content("\f019")>
    <Description("download")>
    Download
    <Content("\f396")>
    <Description("draft2digital")>
    Draft2digital
    <Content("\f17d")>
    <Description("dribbble")>
    Dribbble
    <Content("\f397")>
    <Description("dribbble-square")>
    DribbbleSquare
    <Content("\f16b")>
    <Description("dropbox")>
    Dropbox
    <Content("\f1a9")>
    <Description("drupal")>
    Drupal
    <Content("\f399")>
    <Description("dyalog")>
    Dyalog
    <Content("\f39a")>
    <Description("earlybirds")>
    Earlybirds
    <Content("\f282")>
    <Description("edge")>
    Edge
    <Content("\f044")>
    <Description("edit")>
    Edit
    <Content("\f052")>
    <Description("eject")>
    Eject
    <Content("\f430")>
    <Description("elementor")>
    Elementor
    <Content("\f141")>
    <Description("ellipsis-h")>
    EllipsisH
    <Content("\f142")>
    <Description("ellipsis-v")>
    EllipsisV
    <Content("\f423")>
    <Description("ember")>
    Ember
    <Content("\f1d1")>
    <Description("empire")>
    Empire
    <Content("\f0e0")>
    <Description("envelope")>
    Envelope
    <Content("\f2b6")>
    <Description("envelope-open")>
    EnvelopeOpen
    <Content("\f199")>
    <Description("envelope-square")>
    EnvelopeSquare
    <Content("\f299")>
    <Description("envira")>
    Envira
    <Content("\f12d")>
    <Description("eraser")>
    Eraser
    <Content("\f39d")>
    <Description("erlang")>
    Erlang
    <Content("\f42e")>
    <Description("ethereum")>
    Ethereum
    <Content("\f2d7")>
    <Description("etsy")>
    Etsy
    <Content("\f153")>
    <Description("euro-sign")>
    EuroSign
    <Content("\f362")>
    <Description("exchange-alt")>
    ExchangeAlt
    <Content("\f12a")>
    <Description("exclamation")>
    Exclamation
    <Content("\f06a")>
    <Description("exclamation-circle")>
    ExclamationCircle
    <Content("\f071")>
    <Description("exclamation-triangle")>
    ExclamationTriangle
    <Content("\f065")>
    <Description("expand")>
    Expand
    <Content("\f31e")>
    <Description("expand-arrows-alt")>
    ExpandArrowsAlt
    <Content("\f23e")>
    <Description("expeditedssl")>
    Expeditedssl
    <Content("\f35d")>
    <Description("external-link-alt")>
    ExternalLinkAlt
    <Content("\f360")>
    <Description("external-link-square-alt")>
    ExternalLinkSquareAlt
    <Content("\f06e")>
    <Description("eye")>
    Eye
    <Content("\f1fb")>
    <Description("eye-dropper")>
    EyeDropper
    <Content("\f070")>
    <Description("eye-slash")>
    EyeSlash
    <Content("\f09a")>
    <Description("facebook")>
    Facebook
    <Content("\f39e")>
    <Description("facebook-f")>
    FacebookF
    <Content("\f39f")>
    <Description("facebook-messenger")>
    FacebookMessenger
    <Content("\f082")>
    <Description("facebook-square")>
    FacebookSquare
    <Content("\f049")>
    <Description("fast-backward")>
    FastBackward
    <Content("\f050")>
    <Description("fast-forward")>
    FastForward
    <Content("\f1ac")>
    <Description("fax")>
    Fax
    <Content("\f182")>
    <Description("female")>
    Female
    <Content("\f0fb")>
    <Description("fighter-jet")>
    FighterJet
    <Content("\f15b")>
    <Description("file")>
    File
    <Content("\f15c")>
    <Description("file-alt")>
    FileAlt
    <Content("\f1c6")>
    <Description("file-archive")>
    FileArchive
    <Content("\f1c7")>
    <Description("file-audio")>
    FileAudio
    <Content("\f1c9")>
    <Description("file-code")>
    FileCode
    <Content("\f1c3")>
    <Description("file-excel")>
    FileExcel
    <Content("\f1c5")>
    <Description("file-image")>
    FileImage
    <Content("\f1c1")>
    <Description("file-pdf")>
    FilePdf
    <Content("\f1c4")>
    <Description("file-powerpoint")>
    FilePowerpoint
    <Content("\f1c8")>
    <Description("file-video")>
    FileVideo
    <Content("\f1c2")>
    <Description("file-word")>
    FileWord
    <Content("\f008")>
    <Description("film")>
    Film
    <Content("\f0b0")>
    <Description("filter")>
    Filter
    <Content("\f06d")>
    <Description("fire")>
    Fire
    <Content("\f134")>
    <Description("fire-extinguisher")>
    FireExtinguisher
    <Content("\f269")>
    <Description("firefox")>
    Firefox
    <Content("\f479")>
    <Description("first-aid")>
    FirstAid
    <Content("\f3a1")>
    <Description("firstdraft")>
    Firstdraft
    <Content("\f2b0")>
    <Description("first-order")>
    FirstOrder
    <Content("\f024")>
    <Description("flag")>
    Flag
    <Content("\f11e")>
    <Description("flag-checkered")>
    FlagCheckered
    <Content("\f0c3")>
    <Description("flask")>
    Flask
    <Content("\f16e")>
    <Description("flickr")>
    Flickr
    <Content("\f44d")>
    <Description("flipboard")>
    Flipboard
    <Content("\f417")>
    <Description("fly")>
    Fly
    <Content("\f07b")>
    <Description("folder")>
    Folder
    <Content("\f07c")>
    <Description("folder-open")>
    FolderOpen
    <Content("\f031")>
    <Description("font")>
    Font
    <Content("\f2b4")>
    <Description("font-awesome")>
    FontAwesome
    <Content("\f35c")>
    <Description("font-awesome-alt")>
    FontAwesomeAlt
    <Content("\f425")>
    <Description("font-awesome-flag")>
    FontAwesomeFlag
    <Content("\f280")>
    <Description("fonticons")>
    Fonticons
    <Content("\f3a2")>
    <Description("fonticons-fi")>
    FonticonsFi
    <Content("\f44e")>
    <Description("football-ball")>
    FootballBall
    <Content("\f286")>
    <Description("fort-awesome")>
    FortAwesome
    <Content("\f3a3")>
    <Description("fort-awesome-alt")>
    FortAwesomeAlt
    <Content("\f211")>
    <Description("forumbee")>
    Forumbee
    <Content("\f04e")>
    <Description("forward")>
    Forward
    <Content("\f180")>
    <Description("foursquare")>
    Foursquare
    <Content("\f3a4")>
    <Description("freebsd")>
    Freebsd
    <Content("\f2c5")>
    <Description("free-code-camp")>
    FreeCodeCamp
    <Content("\f119")>
    <Description("frown")>
    Frown
    <Content("\f1e3")>
    <Description("futbol")>
    Futbol
    <Content("\f11b")>
    <Description("gamepad")>
    Gamepad
    <Content("\f0e3")>
    <Description("gavel")>
    Gavel
    <Content("\f3a5")>
    <Description("gem")>
    Gem
    <Content("\f22d")>
    <Description("genderless")>
    Genderless
    <Content("\f265")>
    <Description("get-pocket")>
    GetPocket
    <Content("\f260")>
    <Description("gg")>
    Gg
    <Content("\f261")>
    <Description("gg-circle")>
    GgCircle
    <Content("\f06b")>
    <Description("gift")>
    Gift
    <Content("\f1d3")>
    <Description("git")>
    Git
    <Content("\f09b")>
    <Description("github")>
    Github
    <Content("\f113")>
    <Description("github-alt")>
    GithubAlt
    <Content("\f092")>
    <Description("github-square")>
    GithubSquare
    <Content("\f3a6")>
    <Description("gitkraken")>
    Gitkraken
    <Content("\f296")>
    <Description("gitlab")>
    Gitlab
    <Content("\f1d2")>
    <Description("git-square")>
    GitSquare
    <Content("\f426")>
    <Description("gitter")>
    Gitter
    <Content("\f000")>
    <Description("glass-martini")>
    GlassMartini
    <Content("\f2a5")>
    <Description("glide")>
    Glide
    <Content("\f2a6")>
    <Description("glide-g")>
    GlideG
    <Content("\f0ac")>
    <Description("globe")>
    Globe
    <Content("\f3a7")>
    <Description("gofore")>
    Gofore
    <Content("\f450")>
    <Description("golf-ball")>
    GolfBall
    <Content("\f3a8")>
    <Description("goodreads")>
    Goodreads
    <Content("\f3a9")>
    <Description("goodreads-g")>
    GoodreadsG
    <Content("\f1a0")>
    <Description("google")>
    Google
    <Content("\f3aa")>
    <Description("google-drive")>
    GoogleDrive
    <Content("\f3ab")>
    <Description("google-play")>
    GooglePlay
    <Content("\f2b3")>
    <Description("google-plus")>
    GooglePlus
    <Content("\f0d5")>
    <Description("google-plus-g")>
    GooglePlusG
    <Content("\f0d4")>
    <Description("google-plus-square")>
    GooglePlusSquare
    <Content("\f1ee")>
    <Description("google-wallet")>
    GoogleWallet
    <Content("\f19d")>
    <Description("graduation-cap")>
    GraduationCap
    <Content("\f184")>
    <Description("gratipay")>
    Gratipay
    <Content("\f2d6")>
    <Description("grav")>
    Grav
    <Content("\f3ac")>
    <Description("gripfire")>
    Gripfire
    <Content("\f3ad")>
    <Description("grunt")>
    Grunt
    <Content("\f3ae")>
    <Description("gulp")>
    Gulp
    <Content("\f1d4")>
    <Description("hacker-news")>
    HackerNews
    <Content("\f3af")>
    <Description("hacker-news-square")>
    HackerNewsSquare
    <Content("\f258")>
    <Description("hand-lizard")>
    HandLizard
    <Content("\f256")>
    <Description("hand-paper")>
    HandPaper
    <Content("\f25b")>
    <Description("hand-peace")>
    HandPeace
    <Content("\f0a7")>
    <Description("hand-point-down")>
    HandPointDown
    <Content("\f25a")>
    <Description("hand-pointer")>
    HandPointer
    <Content("\f0a5")>
    <Description("hand-point-left")>
    HandPointLeft
    <Content("\f0a4")>
    <Description("hand-point-right")>
    HandPointRight
    <Content("\f0a6")>
    <Description("hand-point-up")>
    HandPointUp
    <Content("\f255")>
    <Description("hand-rock")>
    HandRock
    <Content("\f257")>
    <Description("hand-scissors")>
    HandScissors
    <Content("\f2b5")>
    <Description("handshake")>
    Handshake
    <Content("\f259")>
    <Description("hand-spock")>
    HandSpock
    <Content("\f292")>
    <Description("hashtag")>
    Hashtag
    <Content("\f0a0")>
    <Description("hdd")>
    Hdd
    <Content("\f1dc")>
    <Description("heading")>
    Heading
    <Content("\f025")>
    <Description("headphones")>
    Headphones
    <Content("\f004")>
    <Description("heart")>
    Heart
    <Content("\f21e")>
    <Description("heartbeat")>
    Heartbeat
    <Content("\f452")>
    <Description("hips")>
    Hips
    <Content("\f3b0")>
    <Description("hire-a-helper")>
    HireAHelper
    <Content("\f1da")>
    <Description("history")>
    History
    <Content("\f453")>
    <Description("hockey-puck")>
    HockeyPuck
    <Content("\f015")>
    <Description("home")>
    Home
    <Content("\f427")>
    <Description("hooli")>
    Hooli
    <Content("\f0f8")>
    <Description("hospital")>
    Hospital
    <Content("\f47e")>
    <Description("hospital-symbol")>
    HospitalSymbol
    <Content("\f3b1")>
    <Description("hotjar")>
    Hotjar
    <Content("\f254")>
    <Description("hourglass")>
    Hourglass
    <Content("\f253")>
    <Description("hourglass-end")>
    HourglassEnd
    <Content("\f252")>
    <Description("hourglass-half")>
    HourglassHalf
    <Content("\f251")>
    <Description("hourglass-start")>
    HourglassStart
    <Content("\f27c")>
    <Description("houzz")>
    Houzz
    <Content("\f0fd")>
    <Description("h-square")>
    HSquare
    <Content("\f13b")>
    <Description("html5")>
    Html5
    <Content("\f3b2")>
    <Description("hubspot")>
    Hubspot
    <Content("\f246")>
    <Description("i-cursor")>
    ICursor
    <Content("\f2c1")>
    <Description("id-badge")>
    IdBadge
    <Content("\f2c2")>
    <Description("id-card")>
    IdCard
    <Content("\f03e")>
    <Description("image")>
    Image
    <Content("\f302")>
    <Description("images")>
    Images
    <Content("\f2d8")>
    <Description("imdb")>
    Imdb
    <Content("\f01c")>
    <Description("inbox")>
    Inbox
    <Content("\f03c")>
    <Description("indent")>
    Indent
    <Content("\f275")>
    <Description("industry")>
    Industry
    <Content("\f129")>
    <Description("info")>
    Info
    <Content("\f05a")>
    <Description("info-circle")>
    InfoCircle
    <Content("\f16d")>
    <Description("instagram")>
    Instagram
    <Content("\f26b")>
    <Description("internet-explorer")>
    InternetExplorer
    <Content("\f208")>
    <Description("ioxhost")>
    Ioxhost
    <Content("\f033")>
    <Description("italic")>
    Italic
    <Content("\f3b4")>
    <Description("itunes")>
    Itunes
    <Content("\f3b5")>
    <Description("itunes-note")>
    ItunesNote
    <Content("\f3b6")>
    <Description("jenkins")>
    Jenkins
    <Content("\f3b7")>
    <Description("joget")>
    Joget
    <Content("\f1aa")>
    <Description("joomla")>
    Joomla
    <Content("\f3b8")>
    <Description("js")>
    Js
    <Content("\f1cc")>
    <Description("jsfiddle")>
    Jsfiddle
    <Content("\f3b9")>
    <Description("js-square")>
    JsSquare
    <Content("\f084")>
    <Description("key")>
    Key
    <Content("\f11c")>
    <Description("keyboard")>
    Keyboard
    <Content("\f3ba")>
    <Description("keycdn")>
    Keycdn
    <Content("\f3bb")>
    <Description("kickstarter")>
    Kickstarter
    <Content("\f3bc")>
    <Description("kickstarter-k")>
    KickstarterK
    <Content("\f42f")>
    <Description("korvue")>
    Korvue
    <Content("\f1ab")>
    <Description("language")>
    Language
    <Content("\f109")>
    <Description("laptop")>
    Laptop
    <Content("\f3bd")>
    <Description("laravel")>
    Laravel
    <Content("\f202")>
    <Description("lastfm")>
    Lastfm
    <Content("\f203")>
    <Description("lastfm-square")>
    LastfmSquare
    <Content("\f06c")>
    <Description("leaf")>
    Leaf
    <Content("\f212")>
    <Description("leanpub")>
    Leanpub
    <Content("\f094")>
    <Description("lemon")>
    Lemon
    <Content("\f41d")>
    <Description("less")>
    Less
    <Content("\f3be")>
    <Description("level-down-alt")>
    LevelDownAlt
    <Content("\f3bf")>
    <Description("level-up-alt")>
    LevelUpAlt
    <Content("\f1cd")>
    <Description("life-ring")>
    LifeRing
    <Content("\f0eb")>
    <Description("lightbulb")>
    Lightbulb
    <Content("\f3c0")>
    <Description("line")>
    Line
    <Content("\f0c1")>
    <Description("link")>
    Link
    <Content("\f08c")>
    <Description("linkedin")>
    Linkedin
    <Content("\f0e1")>
    <Description("linkedin-in")>
    LinkedinIn
    <Content("\f2b8")>
    <Description("linode")>
    Linode
    <Content("\f17c")>
    <Description("linux")>
    Linux
    <Content("\f195")>
    <Description("lira-sign")>
    LiraSign
    <Content("\f03a")>
    <Description("list")>
    List
    <Content("\f022")>
    <Description("list-alt")>
    ListAlt
    <Content("\f0cb")>
    <Description("list-ol")>
    ListOl
    <Content("\f0ca")>
    <Description("list-ul")>
    ListUl
    <Content("\f124")>
    <Description("location-arrow")>
    LocationArrow
    <Content("\f023")>
    <Description("lock")>
    Lock
    <Content("\f3c1")>
    <Description("lock-open")>
    LockOpen
    <Content("\f309")>
    <Description("long-arrow-alt-down")>
    LongArrowAltDown
    <Content("\f30a")>
    <Description("long-arrow-alt-left")>
    LongArrowAltLeft
    <Content("\f30b")>
    <Description("long-arrow-alt-right")>
    LongArrowAltRight
    <Content("\f30c")>
    <Description("long-arrow-alt-up")>
    LongArrowAltUp
    <Content("\f2a8")>
    <Description("low-vision")>
    LowVision
    <Content("\f3c3")>
    <Description("lyft")>
    Lyft
    <Content("\f3c4")>
    <Description("magento")>
    Magento
    <Content("\f0d0")>
    <Description("magic")>
    Magic
    <Content("\f076")>
    <Description("magnet")>
    Magnet
    <Content("\f183")>
    <Description("male")>
    Male
    <Content("\f279")>
    <Description("map")>
    Map
    <Content("\f041")>
    <Description("map-marker")>
    MapMarker
    <Content("\f3c5")>
    <Description("map-marker-alt")>
    MapMarkerAlt
    <Content("\f276")>
    <Description("map-pin")>
    MapPin
    <Content("\f277")>
    <Description("map-signs")>
    MapSigns
    <Content("\f222")>
    <Description("mars")>
    Mars
    <Content("\f227")>
    <Description("mars-double")>
    MarsDouble
    <Content("\f229")>
    <Description("mars-stroke")>
    MarsStroke
    <Content("\f22b")>
    <Description("mars-stroke-h")>
    MarsStrokeH
    <Content("\f22a")>
    <Description("mars-stroke-v")>
    MarsStrokeV
    <Content("\f136")>
    <Description("maxcdn")>
    Maxcdn
    <Content("\f3c6")>
    <Description("medapps")>
    Medapps
    <Content("\f23a")>
    <Description("medium")>
    Medium
    <Content("\f3c7")>
    <Description("medium-m")>
    MediumM
    <Content("\f0fa")>
    <Description("medkit")>
    Medkit
    <Content("\f3c8")>
    <Description("medrt")>
    Medrt
    <Content("\f2e0")>
    <Description("meetup")>
    Meetup
    <Content("\f11a")>
    <Description("meh")>
    Meh
    <Content("\f223")>
    <Description("mercury")>
    Mercury
    <Content("\f2db")>
    <Description("microchip")>
    Microchip
    <Content("\f130")>
    <Description("microphone")>
    Microphone
    <Content("\f131")>
    <Description("microphone-slash")>
    MicrophoneSlash
    <Content("\f3ca")>
    <Description("microsoft")>
    Microsoft
    <Content("\f068")>
    <Description("minus")>
    Minus
    <Content("\f056")>
    <Description("minus-circle")>
    MinusCircle
    <Content("\f146")>
    <Description("minus-square")>
    MinusSquare
    <Content("\f3cb")>
    <Description("mix")>
    Mix
    <Content("\f289")>
    <Description("mixcloud")>
    Mixcloud
    <Content("\f3cc")>
    <Description("mizuni")>
    Mizuni
    <Content("\f10b")>
    <Description("mobile")>
    Mobile
    <Content("\f3cd")>
    <Description("mobile-alt")>
    MobileAlt
    <Content("\f285")>
    <Description("modx")>
    Modx
    <Content("\f3d0")>
    <Description("monero")>
    Monero
    <Content("\f3d1")>
    <Description("money-bill-alt")>
    MoneyBillAlt
    <Content("\f186")>
    <Description("moon")>
    Moon
    <Content("\f21c")>
    <Description("motorcycle")>
    Motorcycle
    <Content("\f245")>
    <Description("mouse-pointer")>
    MousePointer
    <Content("\f001")>
    <Description("music")>
    Music
    <Content("\f3d2")>
    <Description("napster")>
    Napster
    <Content("\f22c")>
    <Description("neuter")>
    Neuter
    <Content("\f1ea")>
    <Description("newspaper")>
    Newspaper
    <Content("\f418")>
    <Description("nintendo-switch")>
    NintendoSwitch
    <Content("\f419")>
    <Description("node")>
    Node
    <Content("\f3d3")>
    <Description("node-js")>
    NodeJs
    <Content("\f3d4")>
    <Description("npm")>
    Npm
    <Content("\f3d5")>
    <Description("ns8")>
    Ns8
    <Content("\f3d6")>
    <Description("nutritionix")>
    Nutritionix
    <Content("\f247")>
    <Description("object-group")>
    ObjectGroup
    <Content("\f248")>
    <Description("object-ungroup")>
    ObjectUngroup
    <Content("\f263")>
    <Description("odnoklassniki")>
    Odnoklassniki
    <Content("\f264")>
    <Description("odnoklassniki-square")>
    OdnoklassnikiSquare
    <Content("\f23d")>
    <Description("opencart")>
    Opencart
    <Content("\f19b")>
    <Description("openid")>
    Openid
    <Content("\f26a")>
    <Description("opera")>
    Opera
    <Content("\f23c")>
    <Description("optin-monster")>
    OptinMonster
    <Content("\f41a")>
    <Description("osi")>
    Osi
    <Content("\f03b")>
    <Description("outdent")>
    Outdent
    <Content("\f3d7")>
    <Description("page4")>
    Page4
    <Content("\f18c")>
    <Description("pagelines")>
    Pagelines
    <Content("\f1fc")>
    <Description("paint-brush")>
    PaintBrush
    <Content("\f3d8")>
    <Description("palfed")>
    Palfed
    <Content("\f482")>
    <Description("pallet")>
    Pallet
    <Content("\f0c6")>
    <Description("paperclip")>
    Paperclip
    <Content("\f1d8")>
    <Description("paper-plane")>
    PaperPlane
    <Content("\f1dd")>
    <Description("paragraph")>
    Paragraph
    <Content("\f0ea")>
    <Description("paste")>
    Paste
    <Content("\f3d9")>
    <Description("patreon")>
    Patreon
    <Content("\f04c")>
    <Description("pause")>
    Pause
    <Content("\f28b")>
    <Description("pause-circle")>
    PauseCircle
    <Content("\f1b0")>
    <Description("paw")>
    Paw
    <Content("\f1ed")>
    <Description("paypal")>
    Paypal
    <Content("\f303")>
    <Description("pencil-alt")>
    PencilAlt
    <Content("\f14b")>
    <Description("pen-square")>
    PenSquare
    <Content("\f295")>
    <Description("percent")>
    Percent
    <Content("\f3da")>
    <Description("periscope")>
    Periscope
    <Content("\f3db")>
    <Description("phabricator")>
    Phabricator
    <Content("\f3dc")>
    <Description("phoenix-framework")>
    PhoenixFramework
    <Content("\f095")>
    <Description("phone")>
    Phone
    <Content("\f098")>
    <Description("phone-square")>
    PhoneSquare
    <Content("\f2a0")>
    <Description("phone-volume")>
    PhoneVolume
    <Content("\f457")>
    <Description("php")>
    Php
    <Content("\f2ae")>
    <Description("pied-piper")>
    PiedPiper
    <Content("\f1a8")>
    <Description("pied-piper-alt")>
    PiedPiperAlt
    <Content("\f1a7")>
    <Description("pied-piper-pp")>
    PiedPiperPp
    <Content("\f484")>
    <Description("pills")>
    Pills
    <Content("\f0d2")>
    <Description("pinterest")>
    Pinterest
    <Content("\f231")>
    <Description("pinterest-p")>
    PinterestP
    <Content("\f0d3")>
    <Description("pinterest-square")>
    PinterestSquare
    <Content("\f072")>
    <Description("plane")>
    Plane
    <Content("\f04b")>
    <Description("play")>
    Play
    <Content("\f144")>
    <Description("play-circle")>
    PlayCircle
    <Content("\f3df")>
    <Description("playstation")>
    Playstation
    <Content("\f1e6")>
    <Description("plug")>
    Plug
    <Content("\f067")>
    <Description("plus")>
    Plus
    <Content("\f055")>
    <Description("plus-circle")>
    PlusCircle
    <Content("\f0fe")>
    <Description("plus-square")>
    PlusSquare
    <Content("\f2ce")>
    <Description("podcast")>
    Podcast
    <Content("\f154")>
    <Description("pound-sign")>
    PoundSign
    <Content("\f011")>
    <Description("power-off")>
    PowerOff
    <Content("\f02f")>
    <Description("print")>
    Print
    <Content("\f288")>
    <Description("product-hunt")>
    ProductHunt
    <Content("\f3e1")>
    <Description("pushed")>
    Pushed
    <Content("\f12e")>
    <Description("puzzle-piece")>
    PuzzlePiece
    <Content("\f3e2")>
    <Description("python")>
    Python
    <Content("\f1d6")>
    <Description("qq")>
    Qq
    <Content("\f029")>
    <Description("qrcode")>
    Qrcode
    <Content("\f128")>
    <Description("question")>
    Question
    <Content("\f059")>
    <Description("question-circle")>
    QuestionCircle
    <Content("\f458")>
    <Description("quidditch")>
    Quidditch
    <Content("\f459")>
    <Description("quinscape")>
    Quinscape
    <Content("\f2c4")>
    <Description("quora")>
    Quora
    <Content("\f10d")>
    <Description("quote-left")>
    QuoteLeft
    <Content("\f10e")>
    <Description("quote-right")>
    QuoteRight
    <Content("\f074")>
    <Description("random")>
    Random
    <Content("\f2d9")>
    <Description("ravelry")>
    Ravelry
    <Content("\f41b")>
    <Description("react")>
    React
    <Content("\f1d0")>
    <Description("rebel")>
    Rebel
    <Content("\f1b8")>
    <Description("recycle")>
    Recycle
    <Content("\f1a1")>
    <Description("reddit")>
    Reddit
    <Content("\f281")>
    <Description("reddit-alien")>
    RedditAlien
    <Content("\f1a2")>
    <Description("reddit-square")>
    RedditSquare
    <Content("\f01e")>
    <Description("redo")>
    Redo
    <Content("\f2f9")>
    <Description("redo-alt")>
    RedoAlt
    <Content("\f3e3")>
    <Description("red-river")>
    RedRiver
    <Content("\f25d")>
    <Description("registered")>
    Registered
    <Content("\f3e4")>
    <Description("rendact")>
    Rendact
    <Content("\f18b")>
    <Description("renren")>
    Renren
    <Content("\f3e5")>
    <Description("reply")>
    Reply
    <Content("\f122")>
    <Description("reply-all")>
    ReplyAll
    <Content("\f3e6")>
    <Description("replyd")>
    Replyd
    <Content("\f3e7")>
    <Description("resolving")>
    Resolving
    <Content("\f079")>
    <Description("retweet")>
    Retweet
    <Content("\f018")>
    <Description("road")>
    Road
    <Content("\f135")>
    <Description("rocket")>
    Rocket
    <Content("\f3e8")>
    <Description("rocketchat")>
    Rocketchat
    <Content("\f3e9")>
    <Description("rockrms")>
    Rockrms
    <Content("\f09e")>
    <Description("rss")>
    Rss
    <Content("\f143")>
    <Description("rss-square")>
    RssSquare
    <Content("\f158")>
    <Description("ruble-sign")>
    RubleSign
    <Content("\f156")>
    <Description("rupee-sign")>
    RupeeSign
    <Content("\f267")>
    <Description("safari")>
    Safari
    <Content("\f41e")>
    <Description("sass")>
    Sass
    <Content("\f0c7")>
    <Description("save")>
    Save
    <Content("\f3ea")>
    <Description("schlix")>
    Schlix
    <Content("\f28a")>
    <Description("scribd")>
    Scribd
    <Content("\f002")>
    <Description("search")>
    Search
    <Content("\f3eb")>
    <Description("searchengin")>
    Searchengin
    <Content("\f010")>
    <Description("search-minus")>
    SearchMinus
    <Content("\f00e")>
    <Description("search-plus")>
    SearchPlus
    <Content("\f2da")>
    <Description("sellcast")>
    Sellcast
    <Content("\f213")>
    <Description("sellsy")>
    Sellsy
    <Content("\f233")>
    <Description("server")>
    Server
    <Content("\f3ec")>
    <Description("servicestack")>
    Servicestack
    <Content("\f064")>
    <Description("share")>
    Share
    <Content("\f1e0")>
    <Description("share-alt")>
    ShareAlt
    <Content("\f1e1")>
    <Description("share-alt-square")>
    ShareAltSquare
    <Content("\f14d")>
    <Description("share-square")>
    ShareSquare
    <Content("\f20b")>
    <Description("shekel-sign")>
    ShekelSign
    <Content("\f3ed")>
    <Description("shield-alt")>
    ShieldAlt
    <Content("\f21a")>
    <Description("ship")>
    Ship
    <Content("\f48b")>
    <Description("shipping-fast")>
    ShippingFast
    <Content("\f214")>
    <Description("shirtsinbulk")>
    Shirtsinbulk
    <Content("\f290")>
    <Description("shopping-bag")>
    ShoppingBag
    <Content("\f291")>
    <Description("shopping-basket")>
    ShoppingBasket
    <Content("\f07a")>
    <Description("shopping-cart")>
    ShoppingCart
    <Content("\f2cc")>
    <Description("shower")>
    Shower
    <Content("\f012")>
    <Description("signal")>
    Signal
    <Content("\f2f6")>
    <Description("sign-in-alt")>
    SignInAlt
    <Content("\f2a7")>
    <Description("sign-language")>
    SignLanguage
    <Content("\f2f5")>
    <Description("sign-out-alt")>
    SignOutAlt
    <Content("\f215")>
    <Description("simplybuilt")>
    Simplybuilt
    <Content("\f3ee")>
    <Description("sistrix")>
    Sistrix
    <Content("\f0e8")>
    <Description("sitemap")>
    Sitemap
    <Content("\f216")>
    <Description("skyatlas")>
    Skyatlas
    <Content("\f17e")>
    <Description("skype")>
    Skype
    <Content("\f198")>
    <Description("slack")>
    Slack
    <Content("\f3ef")>
    <Description("slack-hash")>
    SlackHash
    <Content("\f1de")>
    <Description("sliders-h")>
    SlidersH
    <Content("\f1e7")>
    <Description("slideshare")>
    Slideshare
    <Content("\f118")>
    <Description("smile")>
    Smile
    <Content("\f2ab")>
    <Description("snapchat")>
    Snapchat
    <Content("\f2ac")>
    <Description("snapchat-ghost")>
    SnapchatGhost
    <Content("\f2ad")>
    <Description("snapchat-square")>
    SnapchatSquare
    <Content("\f2dc")>
    <Description("snowflake")>
    Snowflake
    <Content("\f0dc")>
    <Description("sort")>
    Sort
    <Content("\f15d")>
    <Description("sort-alpha-down")>
    SortAlphaDown
    <Content("\f15e")>
    <Description("sort-alpha-up")>
    SortAlphaUp
    <Content("\f160")>
    <Description("sort-amount-down")>
    SortAmountDown
    <Content("\f161")>
    <Description("sort-amount-up")>
    SortAmountUp
    <Content("\f0dd")>
    <Description("sort-down")>
    SortDown
    <Content("\f162")>
    <Description("sort-numeric-down")>
    SortNumericDown
    <Content("\f163")>
    <Description("sort-numeric-up")>
    SortNumericUp
    <Content("\f0de")>
    <Description("sort-up")>
    SortUp
    <Content("\f1be")>
    <Description("soundcloud")>
    Soundcloud
    <Content("\f197")>
    <Description("space-shuttle")>
    SpaceShuttle
    <Content("\f3f3")>
    <Description("speakap")>
    Speakap
    <Content("\f110")>
    <Description("spinner")>
    Spinner
    <Content("\f1bc")>
    <Description("spotify")>
    Spotify
    <Content("\f0c8")>
    <Description("square")>
    Square
    <Content("\f45c")>
    <Description("square-full")>
    SquareFull
    <Content("\f18d")>
    <Description("stack-exchange")>
    StackExchange
    <Content("\f16c")>
    <Description("stack-overflow")>
    StackOverflow
    <Content("\f005")>
    <Description("star")>
    Star
    <Content("\f089")>
    <Description("star-half")>
    StarHalf
    <Content("\f3f5")>
    <Description("staylinked")>
    Staylinked
    <Content("\f1b6")>
    <Description("steam")>
    Steam
    <Content("\f1b7")>
    <Description("steam-square")>
    SteamSquare
    <Content("\f3f6")>
    <Description("steam-symbol")>
    SteamSymbol
    <Content("\f048")>
    <Description("step-backward")>
    StepBackward
    <Content("\f051")>
    <Description("step-forward")>
    StepForward
    <Content("\f0f1")>
    <Description("stethoscope")>
    Stethoscope
    <Content("\f3f7")>
    <Description("sticker-mule")>
    StickerMule
    <Content("\f249")>
    <Description("sticky-note")>
    StickyNote
    <Content("\f04d")>
    <Description("stop")>
    [Stop]
    <Content("\f28d")>
    <Description("stop-circle")>
    StopCircle
    <Content("\f2f2")>
    <Description("stopwatch")>
    Stopwatch
    <Content("\f428")>
    <Description("strava")>
    Strava
    <Content("\f21d")>
    <Description("street-view")>
    StreetView
    <Content("\f0cc")>
    <Description("strikethrough")>
    Strikethrough
    <Content("\f429")>
    <Description("stripe")>
    Stripe
    <Content("\f42a")>
    <Description("stripe-s")>
    StripeS
    <Content("\f3f8")>
    <Description("studiovinari")>
    Studiovinari
    <Content("\f1a4")>
    <Description("stumbleupon")>
    Stumbleupon
    <Content("\f1a3")>
    <Description("stumbleupon-circle")>
    StumbleuponCircle
    <Content("\f12c")>
    <Description("subscript")>
    Subscript
    <Content("\f239")>
    <Description("subway")>
    Subway
    <Content("\f0f2")>
    <Description("suitcase")>
    Suitcase
    <Content("\f185")>
    <Description("sun")>
    Sun
    <Content("\f2dd")>
    <Description("superpowers")>
    Superpowers
    <Content("\f12b")>
    <Description("superscript")>
    Superscript
    <Content("\f3f9")>
    <Description("supple")>
    Supple
    <Content("\f021")>
    <Description("sync")>
    Sync
    <Content("\f2f1")>
    <Description("sync-alt")>
    SyncAlt
    <Content("\f48e")>
    <Description("syringe")>
    Syringe
    <Content("\f0ce")>
    <Description("table")>
    Table
    <Content("\f10a")>
    <Description("tablet")>
    Tablet
    <Content("\f3fa")>
    <Description("tablet-alt")>
    TabletAlt
    <Content("\f45d")>
    <Description("table-tennis")>
    TableTennis
    <Content("\f3fd")>
    <Description("tachometer-alt")>
    TachometerAlt
    <Content("\f02b")>
    <Description("tag")>
    Tag
    <Content("\f02c")>
    <Description("tags")>
    Tags
    <Content("\f0ae")>
    <Description("tasks")>
    Tasks
    <Content("\f1ba")>
    <Description("taxi")>
    Taxi
    <Content("\f2c6")>
    <Description("telegram")>
    Telegram
    <Content("\f3fe")>
    <Description("telegram-plane")>
    TelegramPlane
    <Content("\f1d5")>
    <Description("tencent-weibo")>
    TencentWeibo
    <Content("\f120")>
    <Description("terminal")>
    Terminal
    <Content("\f034")>
    <Description("text-height")>
    TextHeight
    <Content("\f035")>
    <Description("text-width")>
    TextWidth
    <Content("\f00a")>
    <Description("th")>
    Th
    <Content("\f2b2")>
    <Description("themeisle")>
    Themeisle
    <Content("\f491")>
    <Description("thermometer")>
    Thermometer
    <Content("\f2cb")>
    <Description("thermometer-empty")>
    ThermometerEmpty
    <Content("\f2c7")>
    <Description("thermometer-full")>
    ThermometerFull
    <Content("\f2c9")>
    <Description("thermometer-half")>
    ThermometerHalf
    <Content("\f2ca")>
    <Description("thermometer-quarter")>
    ThermometerQuarter
    <Content("\f2c8")>
    <Description("thermometer-three-quarters")>
    ThermometerThreeQuarters
    <Content("\f009")>
    <Description("th-large")>
    ThLarge
    <Content("\f00b")>
    <Description("th-list")>
    ThList
    <Content("\f165")>
    <Description("thumbs-down")>
    ThumbsDown
    <Content("\f164")>
    <Description("thumbs-up")>
    ThumbsUp
    <Content("\f08d")>
    <Description("thumbtack")>
    Thumbtack
    <Content("\f3ff")>
    <Description("ticket-alt")>
    TicketAlt
    <Content("\f00d")>
    <Description("times")>
    Times
    <Content("\f057")>
    <Description("times-circle")>
    TimesCircle
    <Content("\f043")>
    <Description("tint")>
    Tint
    <Content("\f204")>
    <Description("toggle-off")>
    ToggleOff
    <Content("\f205")>
    <Description("toggle-on")>
    ToggleOn
    <Content("\f25c")>
    <Description("trademark")>
    Trademark
    <Content("\f238")>
    <Description("train")>
    Train
    <Content("\f224")>
    <Description("transgender")>
    Transgender
    <Content("\f225")>
    <Description("transgender-alt")>
    TransgenderAlt
    <Content("\f1f8")>
    <Description("trash")>
    Trash
    <Content("\f2ed")>
    <Description("trash-alt")>
    TrashAlt
    <Content("\f1bb")>
    <Description("tree")>
    Tree
    <Content("\f181")>
    <Description("trello")>
    Trello
    <Content("\f262")>
    <Description("tripadvisor")>
    Tripadvisor
    <Content("\f091")>
    <Description("trophy")>
    Trophy
    <Content("\f0d1")>
    <Description("truck")>
    Truck
    <Content("\f1e4")>
    <Description("tty")>
    Tty
    <Content("\f173")>
    <Description("tumblr")>
    Tumblr
    <Content("\f174")>
    <Description("tumblr-square")>
    TumblrSquare
    <Content("\f26c")>
    <Description("tv")>
    Tv
    <Content("\f1e8")>
    <Description("twitch")>
    Twitch
    <Content("\f099")>
    <Description("twitter")>
    Twitter
    <Content("\f081")>
    <Description("twitter-square")>
    TwitterSquare
    <Content("\f42b")>
    <Description("typo3")>
    Typo3
    <Content("\f402")>
    <Description("uber")>
    Uber
    <Content("\f403")>
    <Description("uikit")>
    Uikit
    <Content("\f0e9")>
    <Description("umbrella")>
    Umbrella
    <Content("\f0cd")>
    <Description("underline")>
    Underline
    <Content("\f0e2")>
    <Description("undo")>
    Undo
    <Content("\f2ea")>
    <Description("undo-alt")>
    UndoAlt
    <Content("\f404")>
    <Description("uniregistry")>
    Uniregistry
    <Content("\f29a")>
    <Description("universal-access")>
    UniversalAccess
    <Content("\f19c")>
    <Description("university")>
    University
    <Content("\f127")>
    <Description("unlink")>
    Unlink
    <Content("\f09c")>
    <Description("unlock")>
    Unlock
    <Content("\f13e")>
    <Description("unlock-alt")>
    UnlockAlt
    <Content("\f405")>
    <Description("untappd")>
    Untappd
    <Content("\f093")>
    <Description("upload")>
    Upload
    <Content("\f287")>
    <Description("usb")>
    Usb
    <Content("\f007")>
    <Description("user")>
    User
    <Content("\f2bd")>
    <Description("user-circle")>
    UserCircle
    <Content("\f0f0")>
    <Description("user-md")>
    UserMd
    <Content("\f234")>
    <Description("user-plus")>
    UserPlus
    <Content("\f0c0")>
    <Description("users")>
    Users
    <Content("\f21b")>
    <Description("user-secret")>
    UserSecret
    <Content("\f235")>
    <Description("user-times")>
    UserTimes
    <Content("\f407")>
    <Description("ussunnah")>
    Ussunnah
    <Content("\f2e7")>
    <Description("utensils")>
    Utensils
    <Content("\f2e5")>
    <Description("utensil-spoon")>
    UtensilSpoon
    <Content("\f408")>
    <Description("vaadin")>
    Vaadin
    <Content("\f221")>
    <Description("venus")>
    Venus
    <Content("\f226")>
    <Description("venus-double")>
    VenusDouble
    <Content("\f228")>
    <Description("venus-mars")>
    VenusMars
    <Content("\f237")>
    <Description("viacoin")>
    Viacoin
    <Content("\f2a9")>
    <Description("viadeo")>
    Viadeo
    <Content("\f2aa")>
    <Description("viadeo-square")>
    ViadeoSquare
    <Content("\f409")>
    <Description("viber")>
    Viber
    <Content("\f03d")>
    <Description("video")>
    Video
    <Content("\f40a")>
    <Description("vimeo")>
    Vimeo
    <Content("\f194")>
    <Description("vimeo-square")>
    VimeoSquare
    <Content("\f27d")>
    <Description("vimeo-v")>
    VimeoV
    <Content("\f1ca")>
    <Description("vine")>
    Vine
    <Content("\f189")>
    <Description("vk")>
    Vk
    <Content("\f40b")>
    <Description("vnv")>
    Vnv
    <Content("\f45f")>
    <Description("volleyball-ball")>
    VolleyballBall
    <Content("\f027")>
    <Description("volume-down")>
    VolumeDown
    <Content("\f026")>
    <Description("volume-off")>
    VolumeOff
    <Content("\f028")>
    <Description("volume-up")>
    VolumeUp
    <Content("\f41f")>
    <Description("vuejs")>
    Vuejs
    <Content("\f494")>
    <Description("warehouse")>
    Warehouse
    <Content("\f18a")>
    <Description("weibo")>
    Weibo
    <Content("\f496")>
    <Description("weight")>
    Weight
    <Content("\f1d7")>
    <Description("weixin")>
    Weixin
    <Content("\f232")>
    <Description("whatsapp")>
    Whatsapp
    <Content("\f40c")>
    <Description("whatsapp-square")>
    WhatsappSquare
    <Content("\f193")>
    <Description("wheelchair")>
    Wheelchair
    <Content("\f40d")>
    <Description("whmcs")>
    Whmcs
    <Content("\f1eb")>
    <Description("wifi")>
    Wifi
    <Content("\f266")>
    <Description("wikipedia-w")>
    WikipediaW
    <Content("\f410")>
    <Description("window-close")>
    WindowClose
    <Content("\f2d0")>
    <Description("window-maximize")>
    WindowMaximize
    <Content("\f2d1")>
    <Description("window-minimize")>
    WindowMinimize
    <Content("\f2d2")>
    <Description("window-restore")>
    WindowRestore
    <Content("\f17a")>
    <Description("windows")>
    Windows
    <Content("\f159")>
    <Description("won-sign")>
    WonSign
    <Content("\f19a")>
    <Description("wordpress")>
    Wordpress
    <Content("\f411")>
    <Description("wordpress-simple")>
    WordpressSimple
    <Content("\f297")>
    <Description("wpbeginner")>
    Wpbeginner
    <Content("\f2de")>
    <Description("wpexplorer")>
    Wpexplorer
    <Content("\f298")>
    <Description("wpforms")>
    Wpforms
    <Content("\f0ad")>
    <Description("wrench")>
    Wrench
    <Content("\f412")>
    <Description("xbox")>
    Xbox
    <Content("\f168")>
    <Description("xing")>
    Xing
    <Content("\f169")>
    <Description("xing-square")>
    XingSquare
    <Content("\f19e")>
    <Description("yahoo")>
    Yahoo
    <Content("\f413")>
    <Description("yandex")>
    Yandex
    <Content("\f414")>
    <Description("yandex-international")>
    YandexInternational
    <Content("\f23b")>
    <Description("y-combinator")>
    YCombinator
    <Content("\f1e9")>
    <Description("yelp")>
    Yelp
    <Content("\f157")>
    <Description("yen-sign")>
    YenSign
    <Content("\f2b1")>
    <Description("yoast")>
    Yoast
    <Content("\f167")>
    <Description("youtube")>
    Youtube
    <Content("\f431")>
    <Description("youtube-square")>
    YoutubeSquare
End Enum
