#' Parallel Motif Site Scanning
#' 
#' Scans given upstream sequences against a motif Position Weight Matrix (PWM) database 
#' in parallel. The function processes motif families independently, performs motif 
#' matching with customizable statistical thresholds, and aggregates the results into 
#' a single dataframe.
#' 
#' @param db \code{character}. The file path to the motif PWM database.
#' @param seqs \code{character}. The file path to the FASTA file containing TSS upstream 
#'   sequences for motif site matching.
#' @param identities_cutoff \code{numeric}. The minimum identity/similarity cutoff 
#'   required for a valid motif match. Default is \code{0.8}.
#' @param minW \code{numeric}. The minimum weight or score threshold for a motif match. 
#'   Default is \code{0.85}.
#' @param top \code{integer}. The number of top matches to retain for each search 
#'   region or motif. Default is \code{3}.
#' @param permutation \code{integer}. The number of permutations to perform for 
#'   calculating the statistical significance (e.g., p-value) of the motif matches. 
#'   Default is \code{2500}.
#' @param workdir \code{character}. The working directory where intermediate files and 
#'   a \code{results/} subdirectory will be created. Default is \code{"./"}.
#' @param n_threads \code{integer}. The number of CPU threads to use for parallel 
#'   processing. Default is \code{8}.
#' 
#' @return A consolidated \code{data.frame} (or \code{tibble}) containing the motif 
#'   site match results from all motif families. The exact columns depend on the 
#'   output generated by the underlying \code{TRN.builder::motif_search} function.
#' 
#' @details 
#' The function executes in two main stages:
#' \enumerate{
#'   \item \strong{Parallel Search}: It first reads the motif families from the database. 
#'     Using a parallel backend (via \code{snowFall}), it distributes the search tasks 
#'     across \code{n_threads}. Each thread scans the upstream sequences for a specific 
#'     motif family and writes the intermediate results to individual CSV files in 
#'     \code{<workdir>/results/}.
#'   \item \strong{Aggregation}: After all parallel tasks complete, the function reads 
#'     all generated CSV files from the results directory and row-binds them into a 
#'     single unified dataframe using \code{dplyr::bind_rows}.
#' }
#' 
#' @examples
#' \dontrun{
#' # Define paths to your database and sequence file
#' motif_db <- "path/to/motif_database"
#' upstream_fasta <- "path/to/upstream_sequences.fasta"
#' 
#' # Run the parallel motif scanning
#' results <- scan_motifs(
#'   db = motif_db,
#'   seqs = upstream_fasta,
#'   identities_cutoff = 0.85,
#'   minW = 0.9,
#'   top = 5,
#'   permutation = 5000,
#'   workdir = "./motif_scan_workspace",
#'   n_threads = 16
#' )
#' 
#' head(results)
#' }
#' 
#' @export
#' @importFrom dplyr bind_rows
const scan_motifs = function(db, seqs, 
                             identities_cutoff = 0.8,
                             minW = 0.85,
                             top = 3,
                             permutation = 2500,             
                             workdir = "./", 
                             n_threads = 8) {

    imports "TRN.builder" from "TRNtoolkit";
    imports "Parallel" from "snowFall";
    imports "bioseq.fasta" from "seqtoolkit";

    let motifdb = TRN.builder::open_motifdb(db);
    let familyList = [motifdb]::FamilyList;
    let temp_work = normalizePath( workdir);

    close(motifdb );

    # run in parallel for production
    Parallel::parallel(family = familyList, n_threads = n_threads, 
            ignoreError = FALSE, 
            debug = FALSE,
            log_tmp = `${temp_work}/.local_debug/`,
            compress = FALSE) {

        require(GCModeller);

        imports "TRN.builder" from "TRNtoolkit";
        imports "bioseq.fasta" from "seqtoolkit";

        let family_name <- unlist(family);
        let upstream <- read.fasta(unlist(seqs));
        let outputdir <- unlist(temp_work);
        
        outputdir <- file.path(outputdir , "results");

        # view verbose debug echo 
        print("get motif family name for make search processing:");
        print(` -> ${family_name}`);                  

        TRN.builder::open_motifdb(db)
        |> motif_search(
            search_regions = upstream,
            family = family_name,
            identities_cutoff = identities_cutoff,
            minW = minW,
            top = top,
            permutation = permutation,
            tqdm_bar = FALSE
        ) 
        |> unlist()
        |> write.csv(file = file.path(outputdir, `${normalizeFileName(family_name)}.csv`));
    }

    let tmp_results = list.files(file.path(workdir, "results"), pattern = "*.csv");
    tmp_results = as.list(tmp_results, names = basename(tmp_results));
    tmp_results = lapply(tmp_results, path => read.csv(path, row.names = NULL, check.names = FALSE));
    tmp_results = bind_rows(tmp_results);

    return(tmp_results);
}