.\" man page create by R# package system.
.TH KEGG.PROFILES 1 2000-01-01 "compounds.pathway.index" "compounds.pathway.index"
.SH NAME
compounds.pathway.index \- 
.SH SYNOPSIS
\fIcompounds.pathway.index(\fBpathways\fR as <generic> PathwayMap[]);\fR
.SH SEE ALSO
kegg.profiles
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
