.\" man page create by R# package system.
.TH KEGG.PROFILES 0 2000-01-01 "kegg.category_profiles" "kegg.category_profiles"
.SH NAME
kegg.category_profiles \- 
.SH SYNOPSIS
\fIkegg.category_profiles(\fBprofiles\fR as list[integer]);\fR
.SH SEE ALSO
kegg.profiles
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
