.\" man page create by R# package system.
.TH KEGG.PROFILES 1 2000-01-01 "KO.map.profiles" "KO.map.profiles"
.SH NAME
KO.map.profiles \- 
.SH SYNOPSIS
\fIKO.map.profiles(\fBKO\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kegg.profiles
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
