.\" man page create by R# package system.
.TH SNP_TOOLKIT 1 2000-1月 "snp_scan" "snp_scan"
.SH NAME
snp_scan \- 
.SH SYNOPSIS
\fIsnp_scan(\fBnt\fR as <generic> FastaFile, 
\fBref_index\fR as string, 
\fBpureMode\fR as boolean = FALSE, 
\fBmonomorphic\fR as boolean = FALSE, 
\fBvcf_output_filename\fR as <generic> String& = \fB<NULL>\fR);\fR
.SH SEE ALSO
snp_toolkit
.SH FILES
.PP
seqtoolkit.dll
.PP
