.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "expr_cor" "expr_cor"
.SH NAME
expr_cor \- Get the correlation matrix of the given expression data matrix, and then calculate the correlation value and p-value of the given id1 and id2.
.SH SYNOPSIS
\fIexpr_cor(\fBexpr\fR as any, 
\fBid1\fR as any = \fB<NULL>\fR, 
\fBid2\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get the correlation matrix of the given expression data matrix, and then calculate the correlation value and p-value of the given id1 and id2.
.PP
.SH OPTIONS
.PP
\fBexpr\fB \fR\- -. 
.PP
.PP
\fBid1\fB \fR\- -. 
.PP
.PP
\fBid2\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
