.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "read_wgcna_edges" "read_wgcna_edges"
.SH NAME
read_wgcna_edges \- read network edges table which is save via igraph package
.SH SYNOPSIS
\fIread_wgcna_edges(\fBfile\fR as string, 
\fBcor_thres\fR as double = 0.65, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read network edges table which is save via igraph package
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBcor_thres\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
