.\" man page create by R# package system.
.TH DEBUGGER 2 2000-1月 "dump_core" "dump_core"
.SH NAME
dump_core \- dump core for debug
.SH SYNOPSIS
\fIdump_core(\fBcore\fR as <generic> Engine, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
dump core for debug
.PP
.SH OPTIONS
.PP
\fBcore\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
debugger
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
