.\" man page create by R# package system.
.TH DEBUGGER 2 2000-1月 "map.flux" "map.flux"
.SH NAME
map.flux \- create dynamics model from a kegg pathway map
.SH SYNOPSIS
\fImap.flux(\fBmap\fR as <generic> Map, 
\fBreactions\fR as <generic> ReactionRepository, 
\fBinit\fR as double = 1000);\fR
.SH DESCRIPTION
.PP
create dynamics model from a kegg pathway map
.PP
.SH OPTIONS
.PP
\fBmap\fB \fR\- -. 
.PP
.PP
\fBreactions\fB \fR\- -. 
.PP
.PP
\fBinit\fB \fR\- -. 
.PP
.SH SEE ALSO
debugger
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
