.\" man page create by R# package system.
.TH DEBUGGER 2 2000-1月 "set_symbols" "set_symbols"
.SH NAME
set_symbols \- 
.SH SYNOPSIS
\fIset_symbols(\fBdriver\fR as <generic> StorageDriver, 
\fBvcell\fR as <generic> VirtualCell);\fR
.SH SEE ALSO
debugger
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
