.\" man page create by R# package system.
.TH DEBUGGER 2 2000-Jan "test_network" "test_network"
.SH NAME
test_network \- run network dynamics
.SH SYNOPSIS
\fItest_network(\fBnetwork\fR as any, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run network dynamics
.PP
.SH OPTIONS
.PP
\fBnetwork\fB \fR\- 
 the target network graph model
. 
.PP
.PP
\fBinit0\fB \fR\- 
 the system initial conditions
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
debugger
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
