.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-11-09 "ANN.predict" "ANN.predict"
.SH NAME
ANN.predict \- 
.SH SYNOPSIS
\fIANN.predict(\fBmodel\fR as <generic> Object, 
\fBinput\fR as double, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
