.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-10-29 "ANN.training_model" "ANN.training_model"
.SH NAME
ANN.training_model \- create a new ANN training model
.SH SYNOPSIS
\fIANN.training_model(\fBinputSize\fR as integer, 
\fBoutputSize\fR as integer, 
\fBhiddenSize\fR as <generic> Object = [25,100,30], 
\fBlearnRate\fR as double = 0.1, 
\fBmomentum\fR as double = 0.9, 
\fBactive\fR as <generic> activation = 'hidden: Sigmoid(alpha:=2.0); output: Sigmoid(alpha:=2.0)', 
\fBweight0\fR as <generic> Object = "random", 
\fBlearnRateDecay\fR as double = 1E-10, 
\fBtruncate\fR as double = -1, 
\fBsplit\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
create a new ANN training model
.PP
.SH OPTIONS
.PP
\fBinputSize\fB \fR\- the number of nodes for the input layer
.PP
.PP
\fBoutputSize\fB \fR\- the number of nodes for the output layer
.PP
.PP
\fBhiddenSize\fB \fR\- the hiden size of nodes for each hidden layers
.PP
.PP
\fBlearnRate\fB \fR\- -
.PP
.PP
\fBmomentum\fB \fR\- -
.PP
.PP
\fBactive\fB \fR\- -
.PP
.PP
\fBweight0\fB \fR\- -
.PP
.PP
\fBlearnRateDecay\fB \fR\- -
.PP
.PP
\fBtruncate\fB \fR\- -
.PP
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
