.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-11-02 "as.ANN" "as.ANN"
.SH NAME
as.ANN \- 
.SH SYNOPSIS
\fIas.ANN(\fBmodel\fR as <generic> NeuralNetwork);\fR
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
