.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-07-26 "as.tabular" "as.tabular"
.SH NAME
as.tabular \- convert machine learning dataset to dataframe table.
.SH SYNOPSIS
\fIas.tabular(\fBx\fR as <generic> DataSet, 
\fBmarkOuput\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
convert machine learning dataset to dataframe table.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -
.PP
.PP
\fBmarkOuput\fB \fR\- -
.PP
.SH SEE ALSO
machineLearning
.SH FILES
.PP
R.math.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
