.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-12-15 "check.ML_model" "check.ML_model"
.SH NAME
check.ML_model \- check the errors that may exists in the dataset file.
.SH SYNOPSIS
\fIcheck.ML_model(\fBdataset\fR as <generic> DataSet);\fR
.SH DESCRIPTION
.PP
check the errors that may exists in the dataset file.
.PP
.SH OPTIONS
.PP
\fBdataset\fB \fR\- -
.PP
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
