.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-11-09 "create.normalize" "create.normalize"
.SH NAME
create.normalize \- Create normalization matrix data object for the given ANN training data model
.SH SYNOPSIS
\fIcreate.normalize(\fBdataset\fR as <generic> DataSet, 
\fBnames\fR as string = \fB<NULL>\fR, 
\fBestimateQuantile\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create normalization matrix data object for the given ANN training data model
.PP
.SH OPTIONS
.PP
\fBdataset\fB \fR\- -
.PP
.PP
\fBnames\fB \fR\- the names of the input dimensions
.PP
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
