.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-10-29 "load.parallel_ANN" "load.parallel_ANN"
.SH NAME
load.parallel_ANN \- 
.SH SYNOPSIS
\fIload.parallel_ANN(\fBdir\fR as string, 
\fBnormalize\fR as <generic> NormalizeMatrix, 
\fBmethod\fR as <integer> Methods = [NormalScaler]);\fR
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
