.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-10-29 "normalize" "normalize"
.SH NAME
normalize \- 
.SH SYNOPSIS
\fInormalize(\fBtrainingSet\fR as <generic> NormalizeMatrix, 
\fBinput\fR as double, 
\fBmethod\fR as <integer> Methods = [NormalScaler]);\fR
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
