.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-07-19 "open.debugger" "open.debugger"
.SH NAME
open.debugger \- open a file connection to the model debug file.
.SH SYNOPSIS
\fIopen.debugger(\fBANN\fR as <generic> Object, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open a file connection to the model debug file.
.PP
.SH OPTIONS
.PP
\fBANN\fB \fR\- -
.PP
.PP
\fBfile\fB \fR\- the file path to the debug file.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
machineLearning
.SH FILES
.PP
R.math.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
