.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-07-19 "set.trainingSet" "set.trainingSet"
.SH NAME
set.trainingSet \- 
.SH SYNOPSIS
\fIset.trainingSet(\fBann\fR as <generic> TrainingUtils, 
\fBtrainingSet\fR as <generic> DataSet, 
\fBnormalMethod\fR as <integer> Methods = [RelativeScaler]);\fR
.SH SEE ALSO
machineLearning
.SH FILES
.PP
R.math.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
