.\" man page create by R# package system.
.TH MACHINELEARNING 2 2020-11-09 "training" "training"
.SH NAME
training \- do ANN model training
.SH SYNOPSIS
\fItraining(\fBtraining\fR as <generic> ANNTrainer, 
\fBmaxIterations\fR as integer = 10000, 
\fBminErr\fR as double = 0.01, 
\fBparallel\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
do ANN model training
.PP
.SH OPTIONS
.PP
\fBtrainSet\fB \fR\- A dataset object that used for ANN model training.
.PP
.PP
\fBhiddenSize\fB \fR\- An integer vector for indicates the network size of the hidden layers in the ANN network.
.PP
.PP
\fBlearnRate\fB \fR\- -
.PP
.PP
\fBmomentum\fB \fR\- -
.PP
.PP
\fBweight0\fB \fR\- weight method for initialize the ANN network model.
.PP
.PP
\fBactive\fB \fR\- -
.PP
.PP
\fBnormalMethod\fB \fR\- -
.PP
.PP
\fBlearnRateDecay\fB \fR\- -
.PP
.PP
\fBtruncate\fB \fR\- -
.PP
.PP
\fBselectiveMode\fB \fR\- -
.PP
.PP
\fBmaxIterations\fB \fR\- -
.PP
.PP
\fBminErr\fB \fR\- -
.PP
.PP
\fBparallel\fB \fR\- -
.PP
.PP
\fBoutputSnapshot\fB \fR\- 
 this parameter will config the output object type. this function is returns the raw ANN model 
 by default, and you can change the output type to file model by set this parameter value to 
 \fBTRUE\fR. 

.PP
.PP
\fBattribute\fB \fR\- 
 run training for a single output or all of the result output.

.PP
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
