.\" man page create by R# package system.
.TH GSEA 2 2000-Jan "as.KOBAS_terms" "as.KOBAS_terms"
.SH NAME
as.KOBAS_terms \- Convert GSEA enrichment result from GCModeller output format to KOBAS output format
.SH SYNOPSIS
\fIas.KOBAS_terms(\fBenrichment\fR as <generic> EnrichmentResult[], 
\fBdatabase\fR as string = "n/a");\fR
.SH DESCRIPTION
.PP
Convert GSEA enrichment result from GCModeller output format to KOBAS output format
.PP
.SH OPTIONS
.PP
\fBenrichment\fB \fR\- -. 
.PP
.PP
\fBdatabase$\fB \fR\- -. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
