.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "cast_enrichs" "cast_enrichs"
.SH NAME
cast_enrichs \- convert dataset to gcmodeller enrichment result set
.SH SYNOPSIS
\fIcast_enrichs(\fBterm\fR as string, 
\fBname\fR as string, 
\fBpvalue\fR as double, 
\fBgeneIDs\fR as list = \fB<NULL>\fR, 
\fBdesc\fR as string = \fB<NULL>\fR, 
\fBscore\fR as double = \fB<NULL>\fR, 
\fBfdr\fR as double = \fB<NULL>\fR, 
\fBcluster\fR as integer = \fB<NULL>\fR, 
\fBenriched\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
convert dataset to gcmodeller enrichment result set
.PP
.SH OPTIONS
.PP
\fBterm\fB \fR\- -. 
.PP
.PP
\fBname\fB \fR\- -. 
.PP
.PP
\fBpvalue\fB \fR\- -. 
.PP
.PP
\fBgeneIDs\fB \fR\- -. 
.PP
.PP
\fBdesc\fB \fR\- -. 
.PP
.PP
\fBscore\fB \fR\- -. 
.PP
.PP
\fBfdr\fB \fR\- -. 
.PP
.PP
\fBcluster\fB \fR\- -. 
.PP
.PP
\fBenriched\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
