.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "cast_enrichs" "cast_enrichs"
.SH NAME
cast_enrichs \- 
.SH SYNOPSIS
\fIcast_enrichs(\fBterm\fR as string, 
\fBname\fR as string, 
\fBpvalue\fR as double, 
\fBgeneIDs\fR as list, 
\fBdesc\fR as string = \fB<NULL>\fR, 
\fBscore\fR as double = \fB<NULL>\fR, 
\fBfdr\fR as double = \fB<NULL>\fR, 
\fBcluster\fR as integer = \fB<NULL>\fR, 
\fBenriched\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
