.\" man page create by R# package system.
.TH GSEA 2 2000-Jan "enrichment.draw.go_dag" "enrichment.draw.go_dag"
.SH NAME
enrichment.draw.go_dag \- 
.SH SYNOPSIS
\fIenrichment.draw.go_dag(\fBgo_enrichment\fR as <generic> EnrichmentResult[], 
\fBgo\fR as <generic> GO_OBO);\fR
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
