.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "fisher" "fisher"
.SH NAME
fisher \- fisher enrichment test
.SH SYNOPSIS
\fIfisher(\fBlist\fR as string, 
\fBgeneSet\fR as string, 
\fBbackground\fR as any, 
\fBterm\fR as string = "unknown", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
fisher enrichment test
.PP
.SH OPTIONS
.PP
\fBlist\fB \fR\- -. 
.PP
.PP
\fBgeneSet\fB \fR\- -. 
.PP
.PP
\fBbackground\fB \fR\- 
 the background size information, it could be an integer value to 
 indicates that the total unique size of the enrichment background 
 or a unique id character vector that contains all member 
 information of the background.
. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
