.\" man page create by R# package system.
.TH GSEA 2 2000-Jan "read.enrichment" "read.enrichment"
.SH NAME
read.enrichment \- read the enrichment result table
.SH SYNOPSIS
\fIread.enrichment(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the enrichment result table
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
