.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "to_enrichment_terms" "to_enrichment_terms"
.SH NAME
to_enrichment_terms \- cast dataframe to CLR enrichmentt terms
.SH SYNOPSIS
\fIto_enrichment_terms(\fBx\fR as <generic> dataframe, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
cast dataframe to CLR enrichmentt terms
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
