.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "write.enrichment" "write.enrichment"
.SH NAME
write.enrichment \- save the enrichment analysis result
.SH SYNOPSIS
\fIwrite.enrichment(\fBenrichment\fR as any, 
\fBfile\fR as string, 
\fBformat\fR as <integer> EnrichmentTableFormat = [GCModeller], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the enrichment analysis result
.PP
.SH OPTIONS
.PP
\fBenrichment\fB \fR\- should be a set of the enrichment analysis result.. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBformat\fB \fR\- -. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
