.\" man page create by R# package system.
.TH MOTIF_TOOL 1 2000-1月 "read_meme" "read_meme"
.SH NAME
read_meme \- read meme motif text file
.SH SYNOPSIS
\fIread_meme(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read meme motif text file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- file path to the meme motif text file(*.meme). 
.PP
.SH SEE ALSO
motif_tool
.SH FILES
.PP
TRNtoolkit.dll
.PP
