.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-01-01 "read.id_maps" "read.id_maps"
.SH NAME
read.id_maps \- 
.SH SYNOPSIS
\fIread.id_maps(\fBfile\fR as string);\fR
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC/GCModeller 2020
