.\" man page create by R# package system.
.TH STATS.CLUSTERING 1 2020-07-22 "kmeans" "kmeans"
.SH NAME
kmeans \- K-Means Clustering
.SH SYNOPSIS
\fIkmeans(\fBdataset\fR as <generic> Object, 
\fBcenters\fR as integer = 3, 
\fBparallel\fR as boolean = TRUE, 
\fBdebug\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
K-Means Clustering
.PP
.SH OPTIONS
.PP
\fBdataset\fB \fR\- 
 numeric matrix of data, or an object that can be coerced 
 to such a matrix (such as a numeric vector or a data 
 frame with all numeric columns).

.PP
.PP
\fBcenters\fB \fR\- 
 either the number of clusters, say k, or a set of initial 
 (distinct) cluster centres. If a number, a random set of 
 (distinct) rows in x is chosen as the initial centres.

.PP
.PP
\fBparallel\fB \fR\- -
.PP
.PP
\fBdebug\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stats.clustering
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
