.\" man page create by R# package system.
.TH RINTEROP.BASE 1 2000-01-01 "assign" "assign"
.SH NAME
assign \- 
.SH SYNOPSIS
\fIassign(\fBx\fR as string, 
\fBvalue\fR as string, 
\fBpos\fR as integer = -1, 
\fBenvir\fR as string = "as.environment({$pos})", 
\fBinherits\fR as boolean = FALSE, 
\fBimmediate\fR as boolean = TRUE);\fR
.SH SEE ALSO
Rinterop.base
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH COPYRIGHT
Copyright ©  2015
