.\" man page create by R# package system.
.TH CYTOSCAPE.KEGG 2 2000-Jan "pathway_class" "pathway_class"
.SH NAME
pathway_class \- assign pathway map id to the nodes in the given network graph
.SH SYNOPSIS
\fIpathway_class(\fBgraph\fR as <generic> NetworkGraph, 
\fBmaps\fR as <generic> Map[], 
\fBtop3\fR as boolean = TRUE, 
\fBexcludesGlobalAndOverviewMaps\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
assign pathway map id to the nodes in the given network graph
.PP
.SH OPTIONS
.PP
\fBgraph\fB \fR\- 
 the node vertex in this network graph object its label value 
 could be one of: glycan, compound, kegg ortholog or reaction id 
. 
.PP
.PP
\fBmaps\fB \fR\- -. 
.PP
.PP
\fBtop3\fB \fR\- -. 
.PP
.SH SEE ALSO
cytoscape.kegg
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
