.\" man page create by R# package system.
.TH MIRNA 1 2000-1月 "parse_blastn" "parse_blastn"
.SH NAME
parse_blastn \- 
.SH SYNOPSIS
\fIparse_blastn(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
miRNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
