.\" man page create by R# package system.
.TH MODELLER 4 2000-1月 "apply.kinetics" "apply.kinetics"
.SH NAME
apply.kinetics \- apply the kinetics parameters from the sabio-rk database.
.SH SYNOPSIS
\fIapply.kinetics(\fBvcell\fR as <generic> VirtualCell, 
\fBcache\fR as string = "./.cache");\fR
.SH DESCRIPTION
.PP
apply the kinetics parameters from the sabio-rk database.
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
