.\" man page create by R# package system.
.TH MODELLER 4 2000-01-01 "cacheOf.enzyme_kinetics" "cacheOf.enzyme_kinetics"
.SH NAME
cacheOf.enzyme_kinetics \- create data repository from the sabio-rk database
.SH SYNOPSIS
\fIcacheOf.enzyme_kinetics(\fBexport\fR as string = "./", 
\fBko01000\fR as string = "ko01000");\fR
.SH DESCRIPTION
.PP
create data repository from the sabio-rk database
.PP
.SH OPTIONS
.PP
\fBexport$\fB \fR\- -. 
.PP
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
