.\" man page create by R# package system.
.TH MODELLER 4 2000-Jan "kinetics_lambda" "kinetics_lambda"
.SH NAME
kinetics_lambda \- 
.SH SYNOPSIS
\fIkinetics_lambda(\fBkinetics\fR as <generic> Kinetics);\fR
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
