.\" man page create by R# package system.
.TH MODELLER 4 2000-Jan "kinetics" "kinetics"
.SH NAME
kinetics \- create dynamics kinetics
.SH SYNOPSIS
\fIkinetics(\fBexpr\fR as string, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create dynamics kinetics
.PP
.SH OPTIONS
.PP
\fBexpr\fB \fR\- -. 
.PP
.PP
\fBparameters\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
