.\" man page create by R# package system.
.TH MODELLER 4 2000-1月 "write.zip" "write.zip"
.SH NAME
write.zip \- save the virtual cell model as zip archive file
.SH SYNOPSIS
\fIwrite.zip(\fBvcell\fR as <generic> VirtualCell, 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
save the virtual cell model as zip archive file
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
