.\" man page create by R# package system.
.TH MODELLER 4 2000-1月 "write.json_model" "write.json_model"
.SH NAME
write.json_model \- save the virtual cell model as a large json file
.SH SYNOPSIS
\fIwrite.json_model(\fBvcell\fR as <generic> VirtualCell, 
\fBfile\fR as string, 
\fBindent\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
save the virtual cell model as a large json file
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
