.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "fasta.headers" "fasta.headers"
.SH NAME
fasta.headers \- 
.SH SYNOPSIS
\fIfasta.headers(\fBfa\fR as <generic> FastaSeq, 
\fBheaders\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
