.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "mass" "mass"
.SH NAME
mass \- 
.SH SYNOPSIS
\fImass(\fBseqs\fR as any, 
\fBtype\fR as <integer> SeqTypes = [Unknown], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
