.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "read_assembly" "read_assembly"
.SH NAME
read_assembly \- 
.SH SYNOPSIS
\fIread_assembly(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
