.\" man page create by R# package system.
.TH PRIMERS 1 2000-1月 "primer_regions" "primer_regions"
.SH NAME
primer_regions \- 
.SH SYNOPSIS
\fIprimer_regions(\fBblastHits\fR as any, 
\fBmaxCoreSpan\fR as integer = 1000000, 
\fBeval_cutoff\fR as double = 1, 
\fBprimerIds\fR as any = \fB<NULL>\fR, 
\fBgenome\fR as <generic> GFFTable = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
primers
.SH FILES
.PP
seqtoolkit.dll
.PP
