.\" man page create by R# package system.
.TH XLSX 4 2020-11-02 "createSheet" "createSheet"
.SH NAME
createSheet \- create a new worksheet for a given xlsx file
.SH SYNOPSIS
\fIcreateSheet(\fBwb\fR as <generic> File, 
\fBsheetName\fR as string = "Sheet1");\fR
.SH DESCRIPTION
.PP
create a new worksheet for a given xlsx file
.PP
.SH OPTIONS
.PP
\fBwb\fB \fR\- -
.PP
.PP
\fBsheetName$\fB \fR\- -
.PP
.SH SEE ALSO
xlsx
.SH FILES
.PP
R.base.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
