.\" man page create by R# package system.
.TH XLSX 4 2020-12-15 "read.xlsx" "read.xlsx"
.SH NAME
read.xlsx \- read a sheet table in xlsx file as a \fBdataframe\fR object.
.SH SYNOPSIS
\fIread.xlsx(\fBfile\fR as <generic> Object, 
\fBsheetIndex\fR as string = "Sheet1", 
\fBrow_names\fR as <generic> Object = \fB<NULL>\fR, 
\fBraw\fR as boolean = FALSE, 
\fBcheck_names\fR as boolean = TRUE, 
\fBcheck_modes\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read a sheet table in xlsx file as a \fBdataframe\fR object.
.PP
.SH OPTIONS
.PP
\fBsheetIndex\fB \fR\- 
 the data sheet index or name for read data

.PP
.SH SEE ALSO
xlsx
.SH FILES
.PP
R.base.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
