.\" man page create by R# package system.
.TH XLSX 4 2020-11-09 "write.xlsx" "write.xlsx"
.SH NAME
write.xlsx \- 
.SH SYNOPSIS
\fIwrite.xlsx(\fBx\fR as <generic> Object, 
\fBfile\fR as string, 
\fBsheetName\fR as string = "Sheet1");\fR
.SH SEE ALSO
xlsx
.SH FILES
.PP
R.base.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
