.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS 2 2000-01-01 "as.tabular" "as.tabular"
.SH NAME
as.tabular \- 
.SH SYNOPSIS
\fIas.tabular(\fBgenes\fR as <generic> GeneBrief[], 
\fBtitle\fR as string = "n/a", 
\fBsize\fR as integer = 0, 
\fBformat\fR as string = "PTT|GFF|GTF", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.genomics
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
