.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS 2 2000-Jan "genes_features" "genes_features"
.SH NAME
genes_features \- Extract all gene features from a given genomics context assembly data
.SH SYNOPSIS
\fIgenes_features(\fBgenome\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Extract all gene features from a given genomics context assembly data
.PP
.SH OPTIONS
.PP
\fBgenome\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.genomics
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
