.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS 2 2000-01-01 "genome.genes" "genome.genes"
.SH NAME
genome.genes \- 
.SH SYNOPSIS
\fIgenome.genes(\fBgenome\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.genomics
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
