.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS 2 2000-Jan "write.PTT_tabular" "write.PTT_tabular"
.SH NAME
write.PTT_tabular \- 
.SH SYNOPSIS
\fIwrite.PTT_tabular(\fBgenomics\fR as any, 
\fBfile\fR as string = \fB<NULL>\fR, 
\fBencoding\fR as <integer> Encodings = [ASCII], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.genomics
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
