.\" man page create by R# package system.
.TH KEGG 1 2000-1月 "kegg_category_annotation" "kegg_category_annotation"
.SH NAME
kegg_category_annotation \- 
.SH SYNOPSIS
\fIkegg_category_annotation(\fBkegg\fR as <generic> Background, 
\fBanno\fR as <generic> dataframe, 
\fBkegg_id\fR as string = "kegg_id", 
\fBclass_field\fR as string = "kegg_class", 
\fBcategory_field\fR as string = "kegg_category", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kegg
.SH FILES
.PP
gseakit.dll
.PP
