.\" man page create by R# package system.
.TH MESH 1 2000-1月 "mesh_category" "mesh_category"
.SH NAME
mesh_category \- get mesh category values that assign to current mesh term
.SH SYNOPSIS
\fImesh_category(\fBterm\fR as <generic> Term);\fR
.SH DESCRIPTION
.PP
get mesh category values that assign to current mesh term
.PP
.SH OPTIONS
.PP
\fBterm\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
kb.dll
.PP
