.\" man page create by R# package system.
.TH MESH 1 2000-1月 "mesh_background" "mesh_background"
.SH NAME
mesh_background \- build background model for enrichment based on ncbi mesh terms
.SH SYNOPSIS
\fImesh_background(\fBtree\fR as <generic> Tree`1, 
\fBcategory\fR as <integer> MeshCategory, 
\fBlevels\fR as integer = 1);\fR
.SH DESCRIPTION
.PP
build background model for enrichment based on ncbi mesh terms
.PP
.SH OPTIONS
.PP
\fBtree\fB \fR\- -. 
.PP
.PP
\fBcategory\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
kb.dll
.PP
