.\" man page create by R# package system.
.TH MESH 1 2000-1月 "read.mesh_tree" "read.mesh_tree"
.SH NAME
read.mesh_tree \- read the tree of mesh terms
.SH SYNOPSIS
\fIread.mesh_tree(\fBfile\fR as any, 
\fBas_tree\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read the tree of mesh terms
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path to the ncbi mesh term file, usually be the \fBdata/mtrees2024.txt\fR.
. 
.PP
.PP
\fBas_tree\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
kb.dll
.PP
