.\" man page create by R# package system.
.TH SUMMARY 1 2000-01-01 "profileSelector" "profileSelector"
.SH NAME
profileSelector \- 
.SH SYNOPSIS
\fIprofileSelector(\fBprofiles\fR as <generic> CatalogProfiles, 
\fBselects\fR as string = "Q3");\fR
.SH SEE ALSO
summary
.SH FILES
.PP
proteomics_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
