.\" man page create by R# package system.
.TH SUMMARY 1 2000-01-01 "proteins.GO" "proteins.GO"
.SH NAME
proteins.GO \- 
.SH SYNOPSIS
\fIproteins.GO(\fBannotations\fR as <generic> Object, 
\fBgoDb\fR as <generic> GO_OBO, 
\fBlevel\fR as integer = -1, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
summary
.SH FILES
.PP
proteomics_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
