.\" man page create by R# package system.
.TH OBO 1 2000-1月 "filter_direct_parent" "filter_direct_parent"
.SH NAME
filter_direct_parent \- removes terms that associated with the given terms id directly
.SH SYNOPSIS
\fIfilter_direct_parent(\fBobo\fR as <generic> GO_OBO, 
\fBdirect_parent\fR as string);\fR
.SH DESCRIPTION
.PP
removes terms that associated with the given terms id directly
.PP
.SH OPTIONS
.PP
\fBobo\fB \fR\- -. 
.PP
.PP
\fBdirect_parent\fB \fR\- reference id collection that will be filtered and filter theirs direct associations. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
