.\" man page create by R# package system.
.TH OBO 1 2000-1月 "ontologyNodes" "ontologyNodes"
.SH NAME
ontologyNodes \- 
.SH SYNOPSIS
\fIontologyNodes(\fBtree\fR as <generic> TermTree`1);\fR
.SH OPTIONS
.PP
\fBtree\fB \fR\- 
 \fB[DAGTree.dag](cref:P:SMRUCC.genomics.Data.GeneOntology.obographs.DAGTree.dag)\fR which could be build from the \fBontologyTree\fR function.
. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
