.\" man page create by R# package system.
.TH OBO 1 2000-1月 "set_propertyValue" "set_propertyValue"
.SH NAME
set_propertyValue \- set property_value list to a term or obo file headers
.SH SYNOPSIS
\fIset_propertyValue(\fBx\fR as any, 
\fBappend\fR as boolean = TRUE, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set property_value list to a term or obo file headers
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBproperty_value\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
