.\" man page create by R# package system.
.TH SIGNAL_KIT 1 2000-01-01 "as.signal" "as.signal"
.SH NAME
as.signal \- 
.SH SYNOPSIS
\fIas.signal(\fBmeasure\fR as <generic> vector, 
\fBsignals\fR as <generic> vector, 
\fBtitle\fR as string = "general signal", 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
signal_kit
.SH FILES
.PP
signalKit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
