.\" man page create by R# package system.
.TH SIGNAL_KIT 1 2000-01-01 "signal.matrix" "signal.matrix"
.SH NAME
signal.matrix \- 
.SH SYNOPSIS
\fIsignal.matrix(\fBsignals\fR as <generic> Object, 
\fBsignalId\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBsignals\fB \fR\- -
.PP
.PP
\fBsignalId\fB \fR\- 
 if this parameter is not empty, then it means one of the 
 property data in @\fBP:Microsoft.VisualBasic.Math.SignalProcessing.GeneralSignal.meta\fR will be 
 used as signal id. the @\fBP:Microsoft.VisualBasic.Math.SignalProcessing.GeneralSignal.reference\fR
 is used as signal id by default.

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
signal_kit
.SH FILES
.PP
signalKit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
