.\" man page create by R# package system.
.TH SIGNAL_KIT 1 2000-01-01 "writeCDF" "writeCDF"
.SH NAME
writeCDF \- 
.SH SYNOPSIS
\fIwriteCDF(\fBsignals\fR as <generic> Object, 
\fBfile\fR as string, 
\fBdescription\fR as string = "no description", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
signal_kit
.SH FILES
.PP
signalKit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
