.\" man page create by R# package system.
.TH GRAPHICS2D.LABELER 1 2020-11-02 "d3js.labeler" "d3js.labeler"
.SH NAME
d3js.labeler \- 
.SH SYNOPSIS
\fId3js.labeler(\fBmaxMove\fR as double = 5, 
\fBmaxAngle\fR as double = 0.5, 
\fBw_len\fR as double = 0.2, 
\fBw_inter\fR as double = 1, 
\fBw_lab2\fR as double = 30, 
\fBw_lab_anc\fR as double = 30, 
\fBw_orient\fR as double = 3);\fR
.SH OPTIONS
.PP
\fBmaxMove\fB \fR\- -
.PP
.PP
\fBmaxAngle\fB \fR\- -
.PP
.PP
\fBw_len\fB \fR\- leader line length
.PP
.PP
\fBw_inter\fB \fR\- leader line intersection
.PP
.PP
\fBw_lab2\fB \fR\- label-label overlap
.PP
.PP
\fBw_lab_anc\fB \fR\- label-anchor overlap
.PP
.PP
\fBw_orient\fB \fR\- orientation bias
.PP
.SH SEE ALSO
graphics2D.labeler
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
