.\" man page create by R# package system.
.TH GRAPHICS2D.LABELER 1 2020-11-09 "labels" "labels"
.SH NAME
labels \- 
.SH SYNOPSIS
\fIlabels(\fBlabeler\fR as <generic> Labeler, 
\fBlabels\fR as <generic> Label[]);\fR
.SH SEE ALSO
graphics2D.labeler
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
