.\" man page create by R# package system.
.TH GRAPHICS2D.LABELER 1 2020-12-15 "start" "start"
.SH NAME
start \- 
.SH SYNOPSIS
\fIstart(\fBlabeler\fR as <generic> Labeler, 
\fBnsweeps\fR as integer = 2000, 
\fBT\fR as double = 1, 
\fBinitialT\fR as double = 1, 
\fBrotate\fR as double = 0.5, 
\fBshowProgress\fR as boolean = TRUE);\fR
.SH SEE ALSO
graphics2D.labeler
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
