#Region "Microsoft.VisualBasic::7f600c99f14264b1cbfe9ebfa0d8b7e4, GCModeller\core\Bio.Resources\My Project\Resources.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 513
    '    Code Lines: 137
    ' Comment Lines: 347
    '   Blank Lines: 29
    '     File Size: 24.83 KB


    '     Module Resources
    ' 
    '         Properties: br08601, br08610, br08901, br08902, br08904
    '                     Culture, KEGG_Organism_Complete_Genomes, ko00001, ko00002, ko00003
    '                     ko01000, ko02000, ko02022, ko02035, ko02042
    '                     ko02044, ko02048, ko03200, ko04040, ko04147
    '                     ko04812, ResourceManager, SID_Map_KEGG
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Resources.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +E	KEGG Organism
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt; &amp;nbsp; KEGG Organisms&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Eukaryotes&lt;/b&gt; (536)
        '''B
        '''B  &lt;b&gt;Animals&lt;/b&gt; (252)
        '''C    Vertebrates (148)
        '''D      Mammals (68)
        '''E        hsa  Homo sapiens (human)
        '''E        ptr  Pan troglodytes (chimpanzee)
        '''E        pps  Pan paniscus (bonobo)
        '''E        ggo  Gorilla gorilla gorilla (western lowland gorilla)
        '''E        pon  Pongo abelii (Sumatran orangutan)
        '''E        nle  Nomascus leucogenys (northe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property br08601() As String
            Get
                Return ResourceManager.GetString("br08601", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +U
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; KEGG Organisms in the NCBI Taxonomy&lt;/h2&gt;
        '''#&lt;!---
        '''#ENTRY       br08610
        '''#DEFINITION  KEGG Organisms in the NCBI taxonomy
        '''#---&gt;
        '''!
        '''AEukaryota
        '''B  Metazoa
        '''C    Chordata
        '''D      Craniata
        '''E        Vertebrata
        '''F          Euteleostomi
        '''G            Mammalia
        '''H              Eutheria
        '''I                Euarchontoglires
        '''J                  Primates
        '''K                    Haplorrhini
        '''L                      Catarrh [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property br08610() As String
            Get
                Return ResourceManager.GetString("br08610", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Map number
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; KEGG Pathway Maps&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Metabolism&lt;/b&gt;
        '''B  Global and overview maps
        '''C    01100  Metabolic pathways
        '''C    01110  Biosynthesis of secondary metabolites
        '''C    01120  Microbial metabolism in diverse environments
        '''C    01200  Carbon metabolism
        '''C    01210  2-Oxocarboxylic acid metabolism
        '''C    01212  Fatty acid metabolism
        '''C    01230  Biosynthesis of amino acids
        '''C    01220  Degradation of aro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property br08901() As String
            Get
                Return ResourceManager.GetString("br08901", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Br number
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; BRITE Hierarchy Files&lt;/h2&gt;
        '''#&lt;!---
        '''#ENTRY       br08902
        '''#NAME        Brite
        '''#DEFINITION  BRITE hierarchy files
        '''#---&gt;
        '''!
        '''A&lt;b&gt;Pathways and Ontologies&lt;/b&gt;
        '''B  Pathways
        '''C    br08901  KEGG pathway maps
        '''B  Functional classifications
        '''C    br08902  BRITE hierarchy files
        '''C    br08904  BRITE table files
        '''#
        '''A&lt;b&gt;Genes and Proteins&lt;/b&gt;
        '''B  Orthologs and modules
        '''C    ko00001  KEGG Orthology (KO)
        '''C    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property br08902() As String
            Get
                Return ResourceManager.GetString("br08902", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Br number
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; BRITE Table Files&lt;/h2&gt;
        '''#&lt;!---
        '''#ENTRY       br08904
        '''#NAME        Brite
        '''#DEFINITION  BRITE table files
        '''#---&gt;
        '''!
        '''A&lt;b&gt;Genes and Proteins&lt;/b&gt;
        '''B  Annotation guide
        '''C    br06001  Enzymes of 2-oxocarboxylic acid metabolism
        '''C    br06002  Dioxygenases
        '''C    br06010  Ribosomal proteins
        '''C    br06011  RNA polymerases
        '''C    br06020  Photosynthetic and chemosynthetic capacities
        '''C    br06021  Signaling  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property br08904() As String
            Get
                Return ResourceManager.GetString("br08904", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE=html&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        '''&lt;title&gt;KEGG Organisms: Complete Genomes&lt;/title&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;/css/kegg2.css&quot; type=&quot;text/css&quot; media=&quot;all&quot;&gt;
        '''&lt;script type=&quot;text/javascript&quot; src=&quot;https://www.kegg.jp/js/jquery-3.1.0.min.js&quot;&gt;&lt;/script&gt;
        '''&lt;script type=&quot;text/javascript&quot; src=&quot;https://www.kegg.jp/kegg/js/colorid.js&quot;&gt;&lt;/script&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body onload=&quot;colorid();&quot;&gt;
        '''
        '''&lt;table width=&quot;700&quot;&gt;
        '''&lt;tr&gt;
        '''  &lt;td width=&quot;180&quot; align=&quot;center&quot; rowsp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property KEGG_Organism_Complete_Genomes() As String
            Get
                Return ResourceManager.GetString("KEGG_Organism_Complete_Genomes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +D	KO
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt; &amp;nbsp; KEGG Orthology (KO)&lt;/h2&gt;
        '''!
        '''A09100 Metabolism
        '''B
        '''B  09101 Carbohydrate metabolism
        '''C    00010 Glycolysis / Gluconeogenesis [PATH:ko00010]
        '''D      K00844  HK; hexokinase [EC:2.7.1.1]
        '''D      K12407  GCK; glucokinase [EC:2.7.1.2]
        '''D      K00845  glk; glucokinase [EC:2.7.1.2]
        '''D      K01810  GPI, pgi; glucose-6-phosphate isomerase [EC:5.3.1.9]
        '''D      K06859  pgi1; glucose-6-phosphate isomerase, archaeal [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko00001() As String
            Get
                Return ResourceManager.GetString("ko00001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +E	Module
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; KEGG Modules&lt;/h2&gt;
        '''#&lt;!---
        '''#ENTRY       ko00002
        '''#NAME        Module
        '''#DEFINITION  KEGG modules
        '''#---&gt;
        '''!
        '''A&lt;b&gt;Pathway module&lt;/b&gt;
        '''B
        '''B  &lt;b&gt;Energy metabolism&lt;/b&gt;
        '''C    Carbon fixation
        '''D      M00165  Reductive pentose phosphate cycle (Calvin cycle) [PATH:map01200 map00710]
        '''E        K00855  PRK, prkB; phosphoribulokinase [EC:2.7.1.19]
        '''E        K01601  rbcL; ribulose-bisphosphate carboxylase large ch [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko00002() As String
            Get
                Return ResourceManager.GetString("ko00002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +D	RModule
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; KEGG Reaction Modules&lt;/h2&gt;
        '''#&lt;!---
        '''#ENTRY       ko00003
        '''#NAME        RModule
        '''#DEFINITION  KEGG reaction modules
        '''#---&gt;
        '''!
        '''A&lt;b&gt;Carboxylic acid metabolism&lt;/b&gt;
        '''B  2-Oxocarboxylic acid chain extension
        '''C    RM001  2-Oxocarboxylic acid chain extension by tricarboxylic acid pathway
        '''D      M00010  Citrate cycle, first carbon oxidation, oxaloacetate =&gt; 2-oxoglutarate
        '''D      M00433  Lysine biosynthesi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko00003() As String
            Get
                Return ResourceManager.GetString("ko00003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +E	Enzyme
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Enzymes&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;1. Oxidoreductases&lt;/b&gt;
        '''B  1.1  Acting on the CH-OH group of donors
        '''C    1.1.1  With NAD+ or NADP+ as acceptor
        '''D      1.1.1.1  alcohol dehydrogenase
        '''E        K00001  E1.1.1.1, adh; alcohol dehydrogenase [EC:1.1.1.1]
        '''E        K00121  frmA, ADH5, adhC; S-(hydroxymethyl)glutathione dehydrogenase / alcohol dehydrogenase [EC:1.1.1.284 1.1.1.1]
        '''E        K04072  adhE; acetaldehyde  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko01000() As String
            Get
                Return ResourceManager.GetString("ko01000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +E
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Transporters&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;ABC Transporters, Eukaryotic Type&lt;/b&gt;
        '''B  ABCA (ABC1) subfamily
        '''C    ABCA1, 2, 3, 4, 7, 12, 13 subgroups
        '''D      K05641  ABCA1; ATP-binding cassette, subfamily A (ABC1), member 1
        '''D      K05642  ABCA2; ATP-binding cassette, subfamily A (ABC1), member 2
        '''D      K05643  ABCA3; ATP-binding cassette, subfamily A (ABC1), member 3
        '''D      K05644  ABCA4; ATP-binding cassette, subfamily A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko02000() As String
            Get
                Return ResourceManager.GetString("ko02000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Two-component system
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Two-Component System&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;OmpR family&lt;/b&gt;
        '''B  PhoR-PhoB (phosphate starvation response)
        '''C    K07636  phoR; two-component system, OmpR family, phosphate regulon sensor histidine kinase PhoR [EC:2.7.13.3]
        '''C    K07657  phoB; two-component system, OmpR family, phosphate regulon response regulator PhoB
        '''C    K07658  phoB1, phoP; two-component system, OmpR family, alkaline phosphata [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko02022() As String
            Get
                Return ResourceManager.GetString("ko02022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +D	Bacterial motility proteins
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Bacterial Motility Proteins&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Flagellar system&lt;/b&gt;
        '''B  Chemotaxis proteins
        '''C    Two component system proteins
        '''D      K03407  cheA; two-component system, chemotaxis family, sensor kinase CheA [EC:2.7.13.3]
        '''D      K03408  cheW; purine-binding chemotaxis protein CheW
        '''D      K03409  cheX; chemotaxis protein CheX
        '''D      K03410  cheC; chemotaxis protein CheC
        '''D      K03 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko02035() As String
            Get
                Return ResourceManager.GetString("ko02035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +D	Bacterial toxins
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Bacterial Toxins&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Type III toxins: Intracellular toxins&lt;/b&gt;
        '''B  ADP-ribosyltransferase
        '''C    Diphtheria toxin (DT)
        '''D      K00776  tox; NAD-diphthamide ADP-ribosyltransferase [EC:2.4.2.36]
        '''C    Cholera toxin/Heat-labile enterotoxin
        '''D      K10928  ctxA; cholera enterotoxin subunit A [EC:2.4.2.36]
        '''D      K10929  ctxB; cholera enterotoxin subunit B
        '''C    Exototoxin-A (ETA)
        '''D    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko02042() As String
            Get
                Return ResourceManager.GetString("ko02042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Secretion system
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Secretion System&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Type I secretion system&lt;/b&gt;
        '''B  alpha-Hemolysin/cyclolysin transporter
        '''C    K11004  hlyB, cyaB; ATP-binding cassette, subfamily B, bacterial HlyB/CyaB
        '''C    K11003  hlyD, cyaD; hemolysin D
        '''C    K12340  tolC; outer membrane protein
        '''B  RTX toxin transporter
        '''C    K12530  rtxB, fitA; ATP-binding cassette, subfamily B, bacterial RtxB
        '''C    K12531  rtxE, fitC; AT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko02044() As String
            Get
                Return ResourceManager.GetString("ko02044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +D	Messenger RNA Biogenesis
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Prokaryotic Defense System&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;CRISPR-Cas system&lt;/b&gt;
        '''B  Universal Cas proteins
        '''C    K15342  cas1; CRISP-associated protein Cas1
        '''C    K09951  cas2; CRISPR-associated protein Cas2
        '''B  Type I CRISPR-Cas system
        '''C    Type I signiture cas proteins
        '''D      K07012  cas3; CRISPR-associated endonuclease/helicase Cas3 [EC:3.1.-.- 3.6.4.-]
        '''D      K07475  cas3; CRISPR-associated en [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko02048() As String
            Get
                Return ResourceManager.GetString("ko02048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Viral protein
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Viral Proteins&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;dsDNA-RT viruses&lt;/b&gt;
        '''B  Hepatitis B virus
        '''C    K23128  S; HBV large envelope protein
        '''C    K23129  C; HBV capsid protein
        '''C    K21854  X; HBV protein X
        '''C    K21037  P; Hepadnavirus DNA polymerase / reverse transcriptase / RNase H [EC:2.7.7.7 2.7.7.49 3.1.26.4]
        '''#
        '''A&lt;b&gt;ssRNA-RT viruses&lt;/b&gt;
        '''B  Human T-cell leukemia virus
        '''C    K23017  gag; HTLV-1 gag polyprotein
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko03200() As String
            Get
                Return ResourceManager.GetString("ko03200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Channel
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Ion Channels&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Ligand-gated channels&lt;/b&gt;
        '''B  GABA-A
        '''C    K05175  GABRA; gamma-aminobutyric acid receptor subunit alpha
        '''C    K05181  GABRB; gamma-aminobutyric acid receptor subunit beta
        '''C    K05184  GABRD; gamma-aminobutyric acid receptor subunit delta
        '''C    K05185  GABRE; gamma-aminobutyric acid receptor subunit epsilon
        '''C    K05186  GABRG; gamma-aminobutyric acid receptor subunit gamm [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko04040() As String
            Get
                Return ResourceManager.GetString("ko04040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +C	Exosome
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Exosome&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Exosomal proteins&lt;/b&gt;
        '''B  Proteins found in most exosomes
        '''C    K06751  MHC1; MHC class I antigen
        '''C    K06460  CD9, TSPAN29; CD9 antigen
        '''C    K06497  CD63, MLA1, TSPAN30; CD63 antigen
        '''C    K06508  CD81, TAPA1, TSPAN28; CD81 antigen
        '''C    K05719  ITGB1, CD29; integrin beta 1
        '''C    K17253  MFGE8; lactadherin
        '''C    K06490  ICAM1, CD54; intercellular adhesion molecule 1
        '''C    K05 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko04147() As String
            Get
                Return ResourceManager.GetString("ko04147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to +F	Cytoskeleton
        '''#&lt;h2&gt;&lt;a href=&quot;/kegg/kegg2.html&quot;&gt;&lt;img src=&quot;/Fig/bget/kegg3.gif&quot; align=&quot;middle&quot; border=0&gt;&lt;/a&gt;&amp;nbsp; Cytoskeleton proteins&lt;/h2&gt;
        '''!
        '''A&lt;b&gt;Eukaryotic cytoskeleton proteins&lt;/b&gt;
        '''B  Actin filaments / Microfilaments
        '''C    Actins
        '''D      Actins
        '''E        K10354  ACTA1; actin, alpha skeletal muscle
        '''E        K12313  ACTA2; actin, aortic smooth muscle
        '''E        K12314  ACTC1; actin, alpha cardiac muscle
        '''E        K12315  ACTG2; actin, gamma-enteric smooth muscle
        '''E        K05692  ACTB_G1; actin beta/ga [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ko04812() As String
            Get
                Return ResourceManager.GetString("ko04812", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3303	KEGG	C00001	962
        '''3304	KEGG	C00002	5957
        '''3305	KEGG	C00003	5893
        '''3306	KEGG	C00004	439153
        '''3307	KEGG	C00005	5884
        '''3308	KEGG	C00006	5886
        '''3309	KEGG	C00007	977
        '''3310	KEGG	C00008	6022
        '''3311	KEGG	C00009	1004
        '''3312	KEGG	C00010	87642
        '''3313	KEGG	C00011	280
        '''3314	KEGG	C00012
        '''3315	KEGG	C00013	1023
        '''3316	KEGG	C00014	222
        '''3317	KEGG	C00015	6031
        '''3318	KEGG	C00016	643975
        '''3319	KEGG	C00017
        '''3320	KEGG	C00018	1051
        '''3321	KEGG	C00019	34755
        '''3322	KEGG	C00020	6083
        '''3323	KEGG	C00021	439155
        '''3324	KEGG	C00022	1060
        '''3325	KEGG	C0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SID_Map_KEGG() As String
            Get
                Return ResourceManager.GetString("SID_Map_KEGG", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
