.\" man page create by R# package system.
.TH NETWORK.TRN 0 2000-01-01 "fpkm.connections" "fpkm.connections"
.SH NAME
fpkm.connections \- 
.SH SYNOPSIS
\fIfpkm.connections(\fBfpkm\fR as <generic> DataSet[], 
\fBcutoff\fR as double = 0.65);\fR
.SH SEE ALSO
network.TRN
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
