.\" man page create by R# package system.
.TH BIOCYC 1 2000-1月 "db_links" "db_links"
.SH NAME
db_links \- get external database cross reference id of current metabolite compound object
.SH SYNOPSIS
\fIdb_links(\fBmeta\fR as <generic> Model, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get external database cross reference id of current metabolite compound object
.PP
.SH OPTIONS
.PP
\fBmeta\fB \fR\- -. 
.PP
.SH SEE ALSO
BioCyc
.SH FILES
.PP
annotationKit.dll
.PP
