.\" man page create by R# package system.
.TH BIOCYC 1 2000-1月 "formula" "formula"
.SH NAME
formula \- get formula string of the given object model
.SH SYNOPSIS
\fIformula(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get formula string of the given object model
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 1. for [compounds](cref:T:SMRUCC.genomics.Data.BioCyc.compounds) model, get molecular formula string
 2. for [reactions](cref:T:SMRUCC.genomics.Data.BioCyc.reactions) model, get the reaction equation string.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
BioCyc
.SH FILES
.PP
annotationKit.dll
.PP
