.\" man page create by R# package system.
.TH BIOCYC 1 2000-1月 "getCompounds" "getCompounds"
.SH NAME
getCompounds \- get compounds list data from a given biocyc workspace context
.SH SYNOPSIS
\fIgetCompounds(\fBrepo\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get compounds list data from a given biocyc workspace context
.PP
.SH OPTIONS
.PP
\fBrepo\fB \fR\- 
 this repository data could be a opened biocyc workspace, target
 file path, or text content of the compounds data
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
BioCyc
.SH FILES
.PP
annotationKit.dll
.PP
