.\" man page create by R# package system.
.TH GO.ANNOTATION 1 2000-Jan "uniprot.ko2go" "uniprot.ko2go"
.SH NAME
uniprot.ko2go \- 
.SH SYNOPSIS
\fIuniprot.ko2go(\fBuniprot\fR as <generic> pipeline, 
\fBthreshold\fR as double = 0.8, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
go.annotation
.SH FILES
.PP
gokit.dll
.PP
