.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "connectivity" "connectivity"
.SH NAME
connectivity \- export a dataframe of the node information with connectivity value
.SH SYNOPSIS
\fIconnectivity(\fBx\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
export a dataframe of the node information with connectivity value
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
