.\" man page create by R# package system.
.TH R.PIECHART 1 2000-01-01 "Data.Frame" "Data.Frame"
.SH NAME
Data.Frame \- 
.SH SYNOPSIS
\fIData.Frame(\fBpath\fR as string);\fR
.SH SEE ALSO
R.PieChart
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH AUTHOR
Written by \fBamethyst.asuka@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2015
