<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Fluteway</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyTitle>A Simple Lightway .NET HTTP Server</AssemblyTitle>
    <AssemblyName>Fluteway</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\sciBASIC#\Data\DataFrame\dataframework-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\Flute\Flute.NET5.vbproj" />
  </ItemGroup>

</Project>
