.\" man page create by R# package system.
.TH XGMML 1 2000-01-01 "xgmml.graph" "xgmml.graph"
.SH NAME
xgmml.graph \- convert the cytoscape xgmml file to network graph model.
.SH SYNOPSIS
\fIxgmml.graph(\fBxgmml\fR as <generic> XGMMLgraph, 
\fBpropertyNames\fR as <generic> Object = ["label","class","group.category","group.category.color"]);\fR
.SH DESCRIPTION
.PP
convert the cytoscape xgmml file to network graph model.
.PP
.SH OPTIONS
.PP
\fBxgmml\fB \fR\- -
.PP
.PP
\fBpropertyNames\fB \fR\- -
.PP
.SH SEE ALSO
xgmml
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
