.\" man page create by R# package system.
.TH XGMML 0 2000-01-01 "xgmml.graph" "xgmml.graph"
.SH NAME
xgmml.graph \- 
.SH SYNOPSIS
\fIxgmml.graph(\fBxgmml\fR as <generic> XGMMLgraph, 
\fBpropertyNames\fR as <generic> Object = ["label","class","group.category","group.category.color"]);\fR
.SH SEE ALSO
xgmml
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
