.\" man page create by R# package system.
.TH GSVA 1 2000-1月 "matrix_to_diff" "matrix_to_diff"
.SH NAME
matrix_to_diff \- 
.SH SYNOPSIS
\fImatrix_to_diff(\fBdiff\fR as <generic> dataframe, 
\fBpathId\fR as string = "pathNames", 
\fBt\fR as string = "t", 
\fBpvalue\fR as string = "pvalue");\fR
.SH SEE ALSO
GSVA
.SH FILES
.PP
gseakit.dll
.PP
