.\" man page create by R# package system.
.TH VISUALSTUDIO 4 2020-12-15 "AssemblyInfo" "AssemblyInfo"
.SH NAME
AssemblyInfo \- Get .NET library module assembly information data.
.SH SYNOPSIS
\fIAssemblyInfo(\fBdllfile\fR as string);\fR
.SH DESCRIPTION
.PP
Get .NET library module assembly information data.
.PP
.SH OPTIONS
.PP
\fBdllfile\fB \fR\- -
.PP
.SH SEE ALSO
VisualStudio
.SH FILES
.PP
devkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
