.\" man page create by R# package system.
.TH VISUALSTUDIO 4 2020-12-15 "git.log" "git.log"
.SH NAME
git.log \- 
.SH SYNOPSIS
\fIgit.log(\fBfile\fR as string);\fR
.SH SEE ALSO
VisualStudio
.SH FILES
.PP
devkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
