'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Interops.NBCR.MEME_Suite.TMoD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property adviser_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("adviser_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property AlignACE_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AlignACE_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property BioProspector_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BioProspector_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property consensus_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("consensus_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property CreateBackgroundModel_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CreateBackgroundModel_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cyggcc_s_1_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cyggcc_s_1_dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cygstdc___6_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cygstdc___6_dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cygwin1_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cygwin1_dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property genomebg_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("genomebg_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Gibbs_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Gibbs_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property glam2_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("glam2_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property glam2format_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("glam2format_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property glam2mask_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("glam2mask_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property glam2scan_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("glam2scan_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property locator_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("locator_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property MatrixScanner_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MatrixScanner_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property MDscan_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MDscan_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property meme_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("meme_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property MotifSampler_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MotifSampler_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property purge_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("purge_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property SeSiMCMC_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SeSiMCMC_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ******************************************************************************
        '''SeSiMCMC. Looking - for - motifs by MCMC project. (c) A. Favorov 2001-2007
        '''Last change: $Date: 2009-01-03 01:45:23 $
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''
        '''****************************************************************************
        '''Synopsis
        '''****************************************************************************
        '''SeSiMCMC [options] [&lt;FastA]
        '''
        '''The program reads a set of sequenc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property SeSiMCMC_Readme() As String
            Get
                Return ResourceManager.GetString("SeSiMCMC_Readme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property weederlauncher_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("weederlauncher_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property weederTFBS_exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("weederTFBS_exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
