.\" man page create by R# package system.
.TH IGRAPH 2 2020-07-26 "add.nodes" "add.nodes"
.SH NAME
add.nodes \- a nodes by given label list.
.SH SYNOPSIS
\fIadd.nodes(\fBg\fR as <generic> NetworkGraph, 
\fBlabels\fR as string);\fR
.SH DESCRIPTION
.PP
a nodes by given label list.
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -
.PP
.PP
\fBlabels\fB \fR\- a character vector of the node labels
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
