.\" man page create by R# package system.
.TH IGRAPH 2 2020-11-09 "add.edge" "add.edge"
.SH NAME
add.edge \- add edge link into the given network graph
.SH SYNOPSIS
\fIadd.edge(\fBg\fR as <generic> NetworkGraph, 
\fBu\fR as string, 
\fBv\fR as string, 
\fBweight\fR as double = 0);\fR
.SH DESCRIPTION
.PP
add edge link into the given network graph
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -
.PP
.PP
\fBu\fB \fR\- -
.PP
.PP
\fBv\fB \fR\- -
.PP
.PP
\fBweight\fB \fR\- -
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
