.\" man page create by R# package system.
.TH IGRAPH 2 2020-07-26 "attrs" "attrs"
.SH NAME
attrs \- Set node attribute data
.SH SYNOPSIS
\fIattrs(\fBnodes\fR as <generic> Object, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Set node attribute data
.PP
.SH OPTIONS
.PP
\fBnodes\fB \fR\- -
.PP
.PP
\fBattrs\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
