.\" man page create by R# package system.
.TH IGRAPH 2 2020-11-02 "connected_graph" "connected_graph"
.SH NAME
connected_graph \- removes all of the isolated nodes.
.SH SYNOPSIS
\fIconnected_graph(\fBgraph\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
removes all of the isolated nodes.
.PP
.SH OPTIONS
.PP
\fBgraph\fB \fR\- -
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
