.\" man page create by R# package system.
.TH IGRAPH 2 2020-11-09 "getElementByID" "getElementByID"
.SH NAME
getElementByID \- get node elements by given id
.SH SYNOPSIS
\fIgetElementByID(\fBg\fR as <generic> NetworkGraph, 
\fBid\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get node elements by given id
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -
.PP
.PP
\fBid\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
