.\" man page create by R# package system.
.TH IGRAPH 2 2020-07-26 "groups" "groups"
.SH NAME
groups \- Make node groups by given type name
.SH SYNOPSIS
\fIgroups(\fBg\fR as <generic> NetworkGraph, 
\fBtype\fR as string, 
\fBnodes\fR as string);\fR
.SH DESCRIPTION
.PP
Make node groups by given type name
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -
.PP
.PP
\fBtype\fB \fR\- -
.PP
.PP
\fBnodes\fB \fR\- -
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
