.\" man page create by R# package system.
.TH IGRAPH 1 2020-06-11 "read.network" "read.network"
.SH NAME
read.network \- 
.SH SYNOPSIS
\fIread.network(\fBdirectory\fR as string, 
\fBdefaultNodeSize\fR as <generic> Object = "20,20");\fR
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
