.\" man page create by R# package system.
.TH IGRAPH 1 2020-05-31 "save.network" "save.network"
.SH NAME
save.network \- 
.SH SYNOPSIS
\fIsave.network(\fBg\fR as <generic> Object, 
\fBfile\fR as string, 
\fBproperties\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
