.\" man page create by R# package system.
.TH IGRAPH 2 2020-11-02 "trim.edges" "trim.edges"
.SH NAME
trim.edges \- removes duplicated edges in the network
.SH SYNOPSIS
\fItrim.edges(\fBg\fR as <generic> NetworkGraph, 
\fBdirectedGraph\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
removes duplicated edges in the network
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -
.PP
.PP
\fBdirectedGraph\fB \fR\- -
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
