.\" man page create by R# package system.
.TH GSEAKIT.DEG_SAMPLE 2 2000-01-01 "guess.sample_groups" "guess.sample_groups"
.SH NAME
guess.sample_groups \- 
.SH SYNOPSIS
\fIguess.sample_groups(\fBsample_names\fR as <generic> Array);\fR
.SH SEE ALSO
gseakit.DEG_sample
.SH FILES
.PP
gseakit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
