.\" man page create by R# package system.
.TH VCELLKIT.ANALYSIS 1 2020-07-19 "union.matrix" "union.matrix"
.SH NAME
union.matrix \- union of the profile snapshot list to a matrix dataset.
.SH SYNOPSIS
\fIunion.matrix(\fBresult\fR as string, 
\fBsetName\fR as string = "mass\metabolome.json", 
\fBtrim\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
union of the profile snapshot list to a matrix dataset.
.PP
.SH OPTIONS
.PP
\fBresult\fB \fR\- -
.PP
.PP
\fBsetName\fB \fR\- -
.PP
.PP
\fBtrim\fB \fR\- 
 Will delete all of the metabolites row that have no changes

.PP
.SH SEE ALSO
vcellkit.analysis
.SH FILES
.PP
vcellkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
