.TH __QUERY_MODULE 1 2025-Dec "" "__query_module"
.SH NAME
__query_module \- __query_module(mid,
    <i>fs.dir</i> = <span style='color: brown;'><strong>'/'</strong></span>,
    <i>cache.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fI__query_module(mid,
    <i>fs.dir</i> = <span style='color: brown;'><strong>'/'</strong></span>,
    <i>cache.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBmid\fB \fR\- . 
.PP
.PP
\fBfs.dir\fB \fR\- '/'. 
.PP
.PP
\fBcache.dir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__query_module at query_module.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
