.TH __QUERY_COMPOUNDS 1 2026-Jan "" "get query of the kegg compound"
.SH NAME
__query_compounds \- __query_compounds(compounds,
    <i>fs.dir</i> = <span style='color: brown;'><strong>'/'</strong></span>,
    <i>cache.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fI__query_compounds(compounds,
    <i>fs.dir</i> = <span style='color: brown;'><strong>'/'</strong></span>,
    <i>cache.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBcompounds\fB \fR\- . a dataframe object that contains the a set of
the kegg compounds for run data downloads, the two data fields:
name and text should be includes in this dataframe object.
.PP
.PP
\fBfs.dir\fB \fR\- '/'. 
.PP
.PP
\fBcache.dir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__query_compounds at query_compounds.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
