.TH AREA_TABLE 1 2023-Feb "" "generate table data of the area shape on the map"
.SH NAME
area_table \- area_table(list)
.SH SYNOPSIS
\fIarea_table(list)\fR
.SH OPTIONS
.PP
\fBlist\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.area_table at pathwayMap.R:line 31
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
