.TH COMPOUNDTRANSFORMPAIR 1 2022-05-19 "" "compoundTransformPair"
.SH NAME
compoundTransformPair \- compoundTransformPair(transforms)
.SH SYNOPSIS
\fIcompoundTransformPair(transforms)\fR
.SH OPTIONS
.PP
\fBtransforms\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.compoundTransformPair at reaction_class.R:line 38
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
