.TH COMPOUND_BRITES 1 2022-05-19 "" "brite list of kegg compounds"
.SH NAME
compound_brites \- compound_brites()
.SH SYNOPSIS
\fIcompound_brites()\fR
.SH DETAILS
.PP
this function returns a list of brite data of the kegg compounds
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.compound_brites at brite.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
