.TH ENUMERATEPATH 1 2023-Feb "" "Create resource file path"
.SH NAME
enumeratePath \- enumeratePath(brite, prefix,
    <i>maxChars</i> = 64)
.SH SYNOPSIS
\fIenumeratePath(brite, prefix,
    <i>maxChars</i> = 64)\fR
.SH OPTIONS
.PP
\fBbrite\fB \fR\- . a dataframe object that created from the ``brite::parse`` function.
.PP
.PP
\fBprefix\fB \fR\- . 
.PP
.PP
\fBmaxChars\fB \fR\- 64. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.enumeratePath at fs.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
