.TH ENUMERATEPATH 1 2021-05-26 "" "Create resource file path"
.SH NAME
enumeratePath \- enumeratePath(brite, prefix, maxChars = 64)
.SH SYNOPSIS
\fIenumeratePath(brite, prefix, maxChars = 64)\fR
.SH OPTIONS
.PP
\fBbrite\fB \fR\- 
.PP
.PP
\fBprefix\fB \fR\- 
.PP
.PP
\fBmaxChars\fB \fR\- 64
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.enumeratePath at brite.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
