.TH ENUMERATEPATH 1 2022-05-19 "" "Create resource file path"
.SH NAME
enumeratePath \- enumeratePath(brite, prefix, maxChars = 64)
.SH SYNOPSIS
\fIenumeratePath(brite, prefix, maxChars = 64)\fR
.SH OPTIONS
.PP
\fBbrite\fB \fR\- . a dataframe object that created from the ``brite::parse`` function.
.PP
.PP
\fBprefix\fB \fR\- . 
.PP
.PP
\fBmaxChars\fB \fR\- 64. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.enumeratePath at brite.R:line 48
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
