.TH FETCH_KO_DATA 1 2026-Jan "" "fetch_ko_data"
.SH NAME
fetch_ko_data \- fetch_ko_data(db, ko.id, species,
    <i>seqtype</i> = 'c'('ntseq', 'aaseq'))
.SH SYNOPSIS
\fIfetch_ko_data(db, ko.id, species,
    <i>seqtype</i> = 'c'('ntseq', 'aaseq'))\fR
.SH OPTIONS
.PP
\fBdb\fB \fR\- . 
.PP
.PP
\fBko.id\fB \fR\- . 
.PP
.PP
\fBspecies\fB \fR\- . 
.PP
.PP
\fBseqtype\fB \fR\- 'c'('ntseq', 'aaseq'). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.fetch_ko_data at ko_db.R:line 59
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
