.TH GET_GRAPH 1 2022-05-19 "" "get graphquery from internal resource file"
.SH NAME
get_graph \- get_graph(ref)
.SH SYNOPSIS
\fIget_graph(ref)\fR
.SH OPTIONS
.PP
\fBref\fB \fR\- . the relative file name of the internal graphquery file
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_graph at utils.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
