.TH GET_GRAPH 1 2021-05-22 "" "get graphquery from internal resource file"
.SH NAME
get_graph \- get_graph(ref)
.SH SYNOPSIS
\fIget_graph(ref)\fR
.SH OPTIONS
.PP
\fBref\fB \fR\- 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_graph at utils.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
