.TH GETHTML 1 2023-Feb "" "Http get html or from cache"
.SH NAME
getHtml \- getHtml(url,
    <i>interval</i> = 3)
.SH SYNOPSIS
\fIgetHtml(url,
    <i>interval</i> = 3)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . the url of the resource data on the remote server
.PP
.PP
\fBinterval\fB \fR\- 3. the time interval in seconds for sleep after request data from the remote server.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getHtml at http_query.R:line 80
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
