.TH GETHTML 1 2021-05-22 "" "Http get html or from cache"
.SH NAME
getHtml \- getHtml(url, interval = 5)
.SH SYNOPSIS
\fIgetHtml(url, interval = 5)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- 
.PP
.PP
\fBinterval\fB \fR\- 5
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getHtml at http_query.R:line 23
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
