.TH GETHTML 1 2021-06-21 "" "Http get html or from cache"
.SH NAME
getHtml \- getHtml(url, interval = 3)
.SH SYNOPSIS
\fIgetHtml(url, interval = 3)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- 
.PP
.PP
\fBinterval\fB \fR\- 3
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getHtml at http_query.R:line 75
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
