.TH GETIMAGE 1 2022-05-19 "" "Request image from remote server or local cache"
.SH NAME
getImage \- getImage(url, interval = 3)
.SH SYNOPSIS
\fIgetImage(url, interval = 3)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . image url
.PP
.PP
\fBinterval\fB \fR\- 3. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getImage at http_query.R:line 54
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
