.TH HTTP_GET 1 2022-05-19 "" "A general method for Http get request"
.SH NAME
http_get \- http_get(url, streamTo, interval = 3, filetype = html)
.SH SYNOPSIS
\fIhttp_get(url, streamTo, interval = 3, filetype = html)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . 
.PP
.PP
\fBstreamTo\fB \fR\- . A lambda function that accept a url and a parameter of file cache location. this parameter should run http get request from the remote server and then save file to local cache.
.PP
.PP
\fBinterval\fB \fR\- 3. 
.PP
.PP
\fBfiletype\fB \fR\- html. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.http_get at http_query.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
