.TH ISNULLSTRING 1 2021-06-22 "" "Does the given string is null or its string value represent null?"
.SH NAME
isNullString \- isNullString(str)
.SH SYNOPSIS
\fIisNullString(str)\fR
.SH OPTIONS
.PP
\fBstr\fB \fR\- 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.isNullString at utils.R:line 35
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
