.TH KEGG_REFERENCEDB 1 2026-Jan "" "workflow function for create the kegg reference database"
.SH NAME
kegg_referencedb \- kegg_referencedb(
    <i>db.file</i> = <span style='color: brown;'><strong>'./kegg.db'</strong></span>)
.SH SYNOPSIS
\fIkegg_referencedb(
    <i>db.file</i> = <span style='color: brown;'><strong>'./kegg.db'</strong></span>)\fR
.SH OPTIONS
.PP
\fBdb.file\fB \fR\- './kegg.db'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_referencedb at kegg_referencedb.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
