.TH KEGG_PATHWAY 1 2023-Feb "" "Query of kegg pathway"
.SH NAME
kegg_pathway \- kegg_pathway(id,
    <i>cache</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIkegg_pathway(id,
    <i>cache</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBid\fB \fR\- . the pathway entry id in kegg database
.PP
.PP
\fBcache\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_pathway at pathway.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
