.TH KEGG_COMPOUND 1 2026-2月 "" "kegg_compound"
.SH NAME
kegg_compound \- kegg_compound(id,
    <i>cache.dir</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIkegg_compound(id,
    <i>cache.dir</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBid\fB \fR\- . 
.PP
.PP
\fBcache.dir\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_compound at get.R:line 28
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
