.TH KEGG_PATHWAY 1 2021-08-11 "" "Query of kegg pathway"
.SH NAME
kegg_pathway \- kegg_pathway(url)
.SH SYNOPSIS
\fIkegg_pathway(url)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_pathway at pathway.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
