.TH KEGG_MODULE 1 2026-2月 "" "kegg_module"
.SH NAME
kegg_module \- kegg_module(id,
    <i>cache.dir</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIkegg_module(id,
    <i>cache.dir</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBid\fB \fR\- . 
.PP
.PP
\fBcache.dir\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_module at get.R:line 21
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
