.TH KEGG_COMPOUND 1 2022-05-19 "" "query data to gcmodeller object model"
.SH NAME
kegg_compound \- kegg_compound(url)
.SH SYNOPSIS
\fIkegg_compound(url)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . the resource url on remote server or local file path for debug
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_compound at compound.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
