.TH KEGG_PATHWAY 1 2022-11-16 "" "Query of kegg pathway"
.SH NAME
kegg_pathway \- kegg_pathway(url,
    <i>debug</i> = FALSE)
.SH SYNOPSIS
\fIkegg_pathway(url,
    <i>debug</i> = FALSE)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . the resource url on remote server or local file path for debug
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_pathway at pathway.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
