.TH KEGG_REACTION 1 2021-06-22 "" "Query of kegg reaction data"
.SH NAME
kegg_reaction \- kegg_reaction(url)
.SH SYNOPSIS
\fIkegg_reaction(url)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_reaction at reaction.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
