.TH KEYINDEX 1 2023-Feb "" "create indexed list from a key-value pair collection"
.SH NAME
keyIndex \- keyIndex(keyValues)
.SH SYNOPSIS
\fIkeyIndex(keyValues)\fR
.SH OPTIONS
.PP
\fBkeyValues\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.keyIndex at utils.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
