.TH KO_DB 1 2026-Jan "" "ko_db"
.SH NAME
ko_db \- ko_db(
    <i>db</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIko_db(
    <i>db</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBdb\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.ko_db at ko_db.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
