.TH LIST_PATHWAY 1 2025-Sep "" "list_pathway"
.SH NAME
list_pathway \- list_pathway(
    <i>org</i> = [<span style='color: brown;'><strong>'map'</strong></span>,<span style='color: brown;'><strong>'hsa'</strong></span>],
    <i>cache</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIlist_pathway(
    <i>org</i> = [<span style='color: brown;'><strong>'map'</strong></span>,<span style='color: brown;'><strong>'hsa'</strong></span>],
    <i>cache</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBorg\fB \fR\- ['ko', 'map', 'hsa']. 
.PP
.PP
\fBcache\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.list_pathway at web_api.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
