.TH LIST_PATHWAY 1 2023-Mar "" "list_pathway"
.SH NAME
list_pathway \- list_pathway(
    <i>org</i> = [ko, map, hsa],
    <i>cache</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIlist_pathway(
    <i>org</i> = [ko, map, hsa],
    <i>cache</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBorg\fB \fR\- [ko, map, hsa]. 
.PP
.PP
\fBcache\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.list_pathway at web_api.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
