.TH LITERATURE 1 2023-Feb "" "Create a literature dataframe"
.SH NAME
literature \- literature(reference, authors, title, journal)
.SH SYNOPSIS
\fIliterature(reference, authors, title, journal)\fR
.SH OPTIONS
.PP
\fBreference\fB \fR\- . 
.PP
.PP
\fBauthors\fB \fR\- . 
.PP
.PP
\fBtitle\fB \fR\- . 
.PP
.PP
\fBjournal\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.literature at pathway.R:line 36
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
