.TH LOAD_KO_INDEX 1 2026-Jan "" "load_ko_index"
.SH NAME
load_ko_index \- load_ko_index(db)
.SH SYNOPSIS
\fIload_ko_index(db)\fR
.SH OPTIONS
.PP
\fBdb\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_ko_index at ko_db.R:line 73
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
