.TH PARSEKEGGCODE 1 2022-05-19 "" "Parse organism kegg code"
.SH NAME
parseKeggCode \- parseKeggCode(name)
.SH SYNOPSIS
\fIparseKeggCode(name)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.SH VALUE
.PP
this function returns a list with ``code`` and ``name``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.parseKeggCode at pathway.R:line 66
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
