.TH PATHWAY_CATEGORY 1 2022-05-19 "" "get brite category data for KEGG pathway"
.SH NAME
pathway_category \- pathway_category()
.SH SYNOPSIS
\fIpathway_category()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.pathway_category at brite.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
