.TH PATHWAY_CATEGORY 1 2023-Mar "" "get brite category data for KEGG pathway"
.SH NAME
pathway_category \- pathway_category()
.SH SYNOPSIS
\fIpathway_category()\fR
.SH DETAILS
.PP
the pathway category data is parse from the ``br08901`` category dataset.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pathway_category at brite.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
