.TH TRIMLONGNAME 1 2022-03-11 "" "try to make the long name shorter"
.SH NAME
trimLongName \- trimLongName(longNames, maxChars = 64)
.SH SYNOPSIS
\fItrimLongName(longNames, maxChars = 64)\fR
.SH OPTIONS
.PP
\fBlongNames\fB \fR\- . 
.PP
.PP
\fBmaxChars\fB \fR\- 64. 
.PP
.SH DETAILS
.PP
the name in long length will caused the filesystem errors on windows system.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.trimLongName at brite.R:line 84
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
