.TH TRIMLONGNAME 1 2021-06-18 "" "trimLongName"
.SH NAME
trimLongName \- trimLongName(longNames, maxChars = 64)
.SH SYNOPSIS
\fItrimLongName(longNames, maxChars = 64)\fR
.SH OPTIONS
.PP
\fBlongNames\fB \fR\- 
.PP
.PP
\fBmaxChars\fB \fR\- 64
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.trimLongName at brite.R:line 46
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
