#Region "Microsoft.VisualBasic::ca40d41849ddadb1ad417abe24c8c6f2, G:/GCModeller/src/GCModeller/analysis/Motifs/PrimerDesigner//My Project/Resources.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 235
    '    Code Lines: 97
    ' Comment Lines: 117
    '   Blank Lines: 21
    '     File Size: 16.16 KB


    '     Module Resources
    ' 
    '         Properties: A, Ba_Bc, Bd_Bp, Bsa_Bso, Bsp_Bss
    '                     Bst_Bv, C_D, Culture, E_F, G_K
    '                     L_N, O_R, ResourceManager, S, T_Z
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Analysis.PrimerDesigner.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''AaaI,,Acetobacter aceti,5&apos; CGGCCG 3&apos; GCCGGC,5&apos; ---C GGCCG--- 3&apos; 3&apos; ---GCCGG C--- 5&apos;,&quot;BseX3I, BstZI, EagI, EclXI, Eco52I, SenPT16I, XmaIII&quot;
        '''AagI,,Achromobacter agile,5&apos; ATCGAT 3&apos; TAGCTA,5&apos; ---AT CGAT--- 3&apos; 3&apos; ---TAGC TA--- 5&apos;,&quot;BanIII, BavCI, Bsa29I, BseCI, BspDI, Bsu15I, BsuTUI, ClaI&quot;
        '''AanI,,Arthrobacter aurescens RFL2,5&apos; TTATAA 3&apos; AATATT,5&apos; ---TTA TAA--- 3&apos; 3&apos; ---AAT ATT--- 5&apos;,&quot;PsiI, Csp1BORF7380P&quot;
        '''AarI,,Arthrobacter aurescens SS2-322,5&apos; CACCTGC 3&apos; GTGGAC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property A() As String
            Get
                Return ResourceManager.GetString("A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''Bac36I,,Bacillus alcalophilus 36,5&apos; GGNCC 3&apos; CCNGG,5&apos; ---G GNCC--- 3&apos; 3&apos; ---CCNG G--- 5&apos;,&quot;AspS9I, AvcI, BavAII, Bce22I, Bsp1894I, Bsu54I, FmuI, NspIV&quot;
        '''BaeI,,Bacillus sphaericus,5&apos; ACN4GTAYC 3&apos; TGN4CATYG,5&apos; ---ACN4GTAYCN6NNNNNN --- 3&apos; 3&apos; ---TGN4CATYGN6N NNNNN--- 5&apos;,— None in May 2010 —
        '''BalI,,Brevibacterium albidum,5&apos; TGGCCA 3&apos; ACCGGT,5&apos; ---TGG CCA--- 3&apos; 3&apos; ---ACC GGT--- 5&apos;,
        '''Bal228I,,Bacillus alcalophilus 228,5&apos; GGNCC 3&apos; CCNGG,5&apos; ---G GNCC--- 3&apos; 3&apos; ---CCNG [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Ba_Bc() As String
            Get
                Return ResourceManager.GetString("Ba-Bc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''BdiI,,Brevibacterium divaricatum,5&apos; ATCGAT 3&apos; TAGCTA,5&apos; ---AT CGAT--- 3&apos; 3&apos; ---TAGC TA--- 5&apos;,&quot;BavCI, Bci29I, Bli41I, Bli86I, BseCI, BsuTUI, Rme21I, SpmI&quot;
        '''BdiSI,,Bacteroides distasonis,5&apos; CTRYAG 3&apos; GAYRTC,5&apos; ---C TRYAG--- 3&apos; 3&apos; ---GAYRT C--- 5&apos;,
        '''BecAII,,Brevibacterium sp. A,5&apos; GGCC 3&apos; CCGG,5&apos; ---GG CC--- 3&apos; 3&apos; ---CC GG--- 5&apos;,
        '''BepI,,Brevibacterium epidermidis,5&apos; CGCG 3&apos; GCGC,5&apos; ---CG CG--- 3&apos; 3&apos; ---GC GC--- 5&apos;,&quot;AccII, BepI, BspFNI, BstUI, Bsu1532I, BtkI, F [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Bd_Bp() As String
            Get
                Return ResourceManager.GetString("Bd-Bp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''BsaI,,Bacillus stearothermophilus 20241,5&apos; GGTCTC 3&apos; CCAGAG,5&apos; ---GGTCTCN NNNN--- 3&apos; 3&apos; ---CCAGAGNNNNN --- 5&apos;,&quot;Bso31I, BspTNI, Eco31I&quot;
        '''Bsa29I,,Bacillus sp. 29,5&apos; ATCGAT 3&apos; TAGCTA,5&apos; ---AT CGAT--- 3&apos; 3&apos; ---TAGC TA--- 5&apos;,&quot;AagI, BanIII, BavCI, BseCI, BspDI, Bsu15I, BsuTUI, ClaI, BbvAII&quot;
        '''BsaAI,,Bacillus stearothermophilus G668,5&apos; YACGTR 3&apos; RTGCAY,5&apos; ---YAC GTR--- 3&apos; 3&apos; ---RTG CAY--- 5&apos;,
        '''BsaBI,,Bacillus stearothermophilus B674,5&apos; GATN4ATC 3&apos; CTAN4TAG,5&apos; ---GA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Bsa_Bso() As String
            Get
                Return ResourceManager.GetString("Bsa-Bso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''Bsp6I,,Bacillus sp. RFL6,5&apos; GCNGC 3&apos; CGNCG,5&apos; ---GC NGC--- 3&apos; 3&apos; ---CGN CG--- 5&apos;,
        '''Bsp13I,,Bacillus sp. 13,5&apos; TCCGGA 3&apos; AGGCCT,5&apos; ---T CCGGA--- 3&apos; 3&apos; ---AGGCC T--- 5&apos;,&quot;AccIII, BbvAIII, BlfI, BsiMI, BspMII, Bsu23I, Kpn2I, PinBII&quot;
        '''Bsp19I,,Bacillus sp. 19,5&apos; CCATGG 3&apos; GGTACC,5&apos; ---C CATGG--- 3&apos; 3&apos; ---GGTAC C--- 5&apos;,
        '''Bsp24I,,Bacillus sp. 24,5&apos; GACN6TGG 3&apos; CTGN6ACC,5&apos; ---GACN6TGGN6NNNNNN --- 3&apos; 3&apos; ---CTGN6ACCN6N NNNNN--- 5&apos;,
        '''Bsp50I,,Bacillus sp. RFL50,5&apos; CGCG  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Bsp_Bss() As String
            Get
                Return ResourceManager.GetString("Bsp-Bss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''BstI,,Bacillus stearothermophilus 1503-4R,5&apos; GGATCC 3&apos; CCTAGG,5&apos; ---G GATCC--- 3&apos; 3&apos; ---CCTAG G--- 5&apos;,&quot;AccEBI, AliI, ApaCI, AsiI, BamHI, BnaI, BspAAIII, Nsp29132II&quot;
        '''Bst1I,,Bacillus stearothermophilus 1,5&apos; CCWGG 3&apos; GGWCC,5&apos; ---CC WGG--- 3&apos; 3&apos; ---GGW CC--- 5&apos;,&quot;AglI, BseBI, Bse17I, BstNI, CbrI, CthII, EcoRII, MvaI, SspAI, TaqXI&quot;
        '''Bst2I,,Bacillus stearothermophilus 2,5&apos; CCWGG 3&apos; GGWCC,5&apos; ---CC WGG--- 3&apos; 3&apos; ---GGW CC--- 5&apos;,&quot;AglI, BseBI, Bse17I, BstNI, BstOI, Bs [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Bst_Bv() As String
            Get
                Return ResourceManager.GetString("Bst-Bv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''CacI,,Clostridium acetobutylicum N1-4081,5&apos; GATC 3&apos; CTAG,5&apos; --- GATC--- 3&apos; 3&apos; ---CTAG --- 5&apos;,
        '''Cac8I,,Clostridium acetobutylicum ABKn8,5&apos; GCNNGC 3&apos; CGNNCG,5&apos; ---GCN NGC--- 3&apos; 3&apos; ---CGN NCG--- 5&apos;,
        '''CaiI,,Comamonas acidovarans Iti19-021,5&apos; CAGNNNCTG 3&apos; GTCNNNGAC,5&apos; ---CAGNNN CTG--- 3&apos; 3&apos; ---GTC NNNGAC--- 5&apos;,AlwNI
        '''CauI,,Chloroflexus aurantiacus,5&apos; GGWCC 3&apos; CCWGG,5&apos; ---G GWCC--- 3&apos; 3&apos; ---CCWG G--- 5&apos;,&quot;BamNxI, BcuAI, BsrAI, Eco47I, FspMSI, HgiCII, HgiJI, SmuEI&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property C_D() As String
            Get
                Return ResourceManager.GetString("C-D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''EacI,,Eubacterium acidaminophilum,5&apos; GGATC 3&apos; CCTAG,5&apos; ---GGATCNNNN N--- 3&apos; 3&apos; ---CCTAGNNNNN --- 5&apos;,&quot;AclWI, AlwI, BinI,&quot;
        '''FalI,,Flavobacterium aquatile Ob10,5&apos; AAGN5CTT 3&apos; TTCN5GAA,5&apos; ---AAGN5CTTN7NNNNNN --- 3&apos; 3&apos; ---TTCN5GAAN7N NNNNN--- 5&apos;,
        '''FalII,,Flavobacterium aquatile Ob10,5&apos; CGCG 3&apos; GCGC,5&apos; ---CG CG--- 3&apos; 3&apos; ---GC GC--- 5&apos;,&quot;BepI, BspFNI, Bsp123I, BspFNI, BstUI, BtkI, FalII, SelI, ThaI&quot;
        '''FaqI,,Flavobacterium aquatile RFL1,5&apos; GGGAC 3&apos; CCCTG,5&apos; ---GGGACN [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property E_F() As String
            Get
                Return ResourceManager.GetString("E-F", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''GalI,,Gluconobacter albidus,5&apos; CCGCGG 3&apos; GGCGCC,5&apos; ---CCGC GG--- 3&apos; 3&apos; ---GG CGCC--- 5&apos;,
        '''GceI,,Gluconobacter cerinus,5&apos; CCGCGG 3&apos; GGCGCC,5&apos; ---CCGC GG--- 3&apos; 3&apos; ---GG CGCC--- 5&apos;,
        '''GceGLI,,Gluconobacter cerinus,5&apos; CCGCGG 3&apos; GGCGCC,5&apos; ---CCGC GG--- 3&apos; 3&apos; ---GG CGCC--- 5&apos;,
        '''GdiI,,Gluconobacter dioxyacetonicus,5&apos; AGGCCT 3&apos; TCCGGA,5&apos; ---AGG CCT--- 3&apos; 3&apos; ---TCC GGA--- 5&apos;,&quot;AatI, AspMI, Eco147I, PceI, SarI, Sru30DI, SseBI, SteI, StuI&quot;
        '''GdiII,,Gluconobacter dioxyace [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property G_K() As String
            Get
                Return ResourceManager.GetString("G-K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''LcaI,,Lactobacillus casei,5&apos; ATCGAT 3&apos; TAGCTA,5&apos; ---AT CGAT--- 3&apos; 3&apos; ---TAGC TA--- 5&apos;,&quot;BdiI, Bli41I, Bsa29I, BscI, Bsp106I, BspDI, Bst28I, LplI, PgaI, ZhoI&quot;
        '''LlaAI,,Lactococcus lactis cremoris W9,5&apos; GATC 3&apos; CTAG,5&apos; --- GATC--- 3&apos; 3&apos; ---CTAG --- 5&apos;,&quot;Bme12I, Bsp67I, BstENII, ChaI, FnuEI, MgoI, NphI, RalF40I&quot;
        '''LlaBI,,Lactococcus lactis cremoris W56,5&apos; CTRYAG 3&apos; GAYRTC,5&apos; ---C TRYAG--- 3&apos; 3&apos; ---GAYRT C--- 5&apos;,
        '''LlaCI,,Lactococcus lactis W15,5&apos; AAGCTT 3&apos; TTCGAA,5 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property L_N() As String
            Get
                Return ResourceManager.GetString("L-N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''OfoI,,Oscillatoria foreaui A-1340,5&apos; CYCGRG 3&apos; GRGCYC,5&apos; ---C YCGRG--- 3&apos; 3&apos; ---GRGCY C--- 5&apos;,&quot;AquI, AvaI, Bse15I, BspLU4I, Eco27kI, Nli3877I, PlaAI, PunAI&quot;
        '''OkrAI,,Oceanospirillum kriegii,5&apos; GGATCC 3&apos; CCTAGG,5&apos; ---G GATCC--- 3&apos; 3&apos; ---CCTAG G--- 5&apos;,&quot;BamHI, Bce751I, BnaI, Bsp98I, BstI, OkrAI, SolI, Uba4009I&quot;
        '''OliI,,Oceanospirillum linum 4-5D,5&apos; CACN4GTG 3&apos; GTGN4CAC,5&apos; ---CACNN NNGTG--- 3&apos; 3&apos; ---GTGNN NNCAC--- 5&apos;,AleI
        '''OxaNI,,Oerskovia xanthineolytica N,5&apos; CC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property O_R() As String
            Get
                Return ResourceManager.GetString("O-R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''SacI,,Streptomyces achromogenes,5&apos; GAGCTC 3&apos; CTCGAG,5&apos; ---GAGCT C--- 3&apos; 3&apos; ---C TCGAG--- 5&apos;,
        '''SacII,,Streptomyces achromogenes,5&apos; CCGCGG 3&apos; GGCGCC,5&apos; ---CCGC GG--- 3&apos; 3&apos; ---GG CGCC--- 5&apos;,Cfr42I
        '''SacNI,,Streptomyces achromogenes N-J-H,5&apos; GRGCYC 3&apos; CYCGRG,5&apos; ---GRGCY C--- 3&apos; 3&apos; ---C YCGRG--- 5&apos;,
        '''SalI,,Streptomyces albus,5&apos; GTCGAC 3&apos; CAGCTG,5&apos; ---G TCGAC--- 3&apos; 3&apos; ---CAGCT G--- 5&apos;,
        '''SalPI,,Streptomyces albus,5&apos; CTGCAG 3&apos; GACGTC,5&apos; ---CTGCA G--- 3&apos; 3&apos; ---G ACGT [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property S() As String
            Get
                Return ResourceManager.GetString("S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 enzyme,pdb,organism,recognition,cut,isoschizomers
        '''TaaI,,Thermus aquaticus Vn 4-311,5&apos; ACNGT 3&apos; TGNCA,5&apos; ---ACN GT--- 3&apos; 3&apos; ---TG NCA--- 5&apos;,
        '''TaiI,,Thermus aquaticus cs1-331,5&apos; ACGT 3&apos; TGCA,5&apos; ---ACGT --- 3&apos; 3&apos; --- TGCA--- 5&apos;,
        '''TaqI,,Thermus aquaticus,5&apos; TCGA 3&apos; AGCT,5&apos; ---T CGA--- 3&apos; 3&apos; ---AGC T--- 5&apos;,
        '''TaqII,,Thermus aquaticus YTI,5&apos; GACCGA 3&apos; CTGGCT,5&apos; ---GACCGAN8NNN --- 3&apos; 3&apos; ---CTGGCTN8N NN--- 5&apos;,
        '''Taq52I,,Thermus aquaticus YS52,5&apos; GCWGC 3&apos; CGWCG,5&apos; ---G CWGC--- 3&apos; 3&apos; ---CGWC G--- 5&apos;,&quot;AceI, ApeKI, SuiI [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property T_Z() As String
            Get
                Return ResourceManager.GetString("T-Z", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
