.\" man page create by R# package system.
.TH OPERON 1 2000-1月 "operon_set" "operon_set"
.SH NAME
operon_set \- load operon set data from the ODB database
.SH SYNOPSIS
\fIoperon_set(\fBfile\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
load operon set data from the ODB database
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- dataset text file that download from https://operondb.jp/. 
.PP
.SH SEE ALSO
operon
.SH FILES
.PP
comparative_toolkit.dll
.PP
