.\" man page create by R# package system.
.TH CHART3D 1 2000-01-01 "serial3D" "serial3D"
.SH NAME
serial3D \- 
.SH SYNOPSIS
\fIserial3D(\fBx\fR as <generic> Array, 
\fBy\fR as <generic> Array, 
\fBz\fR as <generic> Array, 
\fBname\fR as string = "data serial", 
\fBcolor\fR as <generic> Object = "black", 
\fBshape\fR as <integer> LegendStyles = [Circle], 
\fBalpha\fR as integer = 255, 
\fBptSize\fR as integer = 5);\fR
.SH SEE ALSO
chart3D
.SH FILES
.PP
R.plot.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
