.\" man page create by R# package system.
.TH NCBI 1 2000-Jan "create_assemblyDb" "create_assemblyDb"
.SH NAME
create_assemblyDb \- create the index db
.SH SYNOPSIS
\fIcreate_assemblyDb(\fBfile\fR as string, 
\fBrepo_dir\fR as string);\fR
.SH DESCRIPTION
.PP
create the index db
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBrepo_dir\fB \fR\- -. 
.PP
.SH SEE ALSO
NCBI
.SH FILES
.PP
annotationKit.dll
.PP
