.\" man page create by R# package system.
.TH NCBI 1 2000-Jan "genbank_assemblyDb" "genbank_assemblyDb"
.SH NAME
genbank_assemblyDb \- load the index db
.SH SYNOPSIS
\fIgenbank_assemblyDb(\fBrepo_dir\fR as string, 
\fBqgram\fR as integer = 6, 
\fBin_memory\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
load the index db
.PP
.SH OPTIONS
.PP
\fBrepo_dir\fB \fR\- -. 
.PP
.PP
\fBqgram\fB \fR\- -. 
.PP
.SH SEE ALSO
NCBI
.SH FILES
.PP
annotationKit.dll
.PP
