.\" man page create by R# package system.
.TH NCBI 1 2000-Jan "genome_assembly_index" "genome_assembly_index"
.SH NAME
genome_assembly_index \- read ncbi ftp index of the genome assembly
.SH SYNOPSIS
\fIgenome_assembly_index(\fBfile\fR as string, 
\fBmake_accession_index\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
read ncbi ftp index of the genome assembly
.PP
.SH SEE ALSO
NCBI
.SH FILES
.PP
annotationKit.dll
.PP
