.\" man page create by R# package system.
.TH NCBI 1 2000-Jan "index_subset" "index_subset"
.SH NAME
index_subset \- make data subset via a given collection of the acession id
.SH SYNOPSIS
\fIindex_subset(\fBrepo\fR as <generic> AssemblySummaryGenbank, 
\fBaccession_ids\fR as any);\fR
.SH DESCRIPTION
.PP
make data subset via a given collection of the acession id
.PP
.SH OPTIONS
.PP
\fBrepo\fB \fR\- -. 
.PP
.PP
\fBaccession_ids\fB \fR\- -. 
.PP
.SH SEE ALSO
NCBI
.SH FILES
.PP
annotationKit.dll
.PP
