.\" man page create by R# package system.
.TH XGMML 1 2000-1月 "read.xgmml" "read.xgmml"
.SH NAME
read.xgmml \- read cytoscape xgmml file
.SH SYNOPSIS
\fIread.xgmml(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read cytoscape xgmml file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
xgmml
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
