.\" man page create by R# package system.
.TH XGMML 1 2000-01-01 "xgmml.render" "xgmml.render"
.SH NAME
xgmml.render \- render the cytoscape network graph model as image
.SH SYNOPSIS
\fIxgmml.render(\fBmodel\fR as any, 
\fBsize\fR as string = "10(A0)", 
\fBconvexHull\fR as string = \fB<NULL>\fR, 
\fBedgeBends\fR as boolean = FALSE, 
\fBaltStyle\fR as boolean = FALSE, 
\fBrewriteGroupCategoryColors\fR as string = "TSF", 
\fBenzymeColorSchema\fR as string = "Set1:c8", 
\fBcompoundColorSchema\fR as string = "Clusters", 
\fBreactionKOMapping\fR as list[string] = \fB<NULL>\fR, 
\fBcompoundNames\fR as list[string] = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
render the cytoscape network graph model as image
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- the network graph object or the cytoscape network model. 
.PP
.PP
\fBsize\fB \fR\- the size of the output image. 
.PP
.PP
\fBconvexHull$\fB \fR\- -. 
.PP
.PP
\fBedgeBends\fB \fR\- -. 
.PP
.PP
\fBaltStyle\fB \fR\- -. 
.PP
.PP
\fBrewriteGroupCategoryColors$\fB \fR\- -. 
.PP
.PP
\fBenzymeColorSchema$\fB \fR\- -. 
.PP
.PP
\fBcompoundColorSchema$\fB \fR\- -. 
.PP
.PP
\fBreactionKOMapping\fB \fR\- -. 
.PP
.PP
\fBcompoundNames\fB \fR\- -. 
.PP
.SH SEE ALSO
xgmml
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
