.\" man page create by R# package system.
.TH XGMML 1 2000-Jan "xgmml.render" "xgmml.render"
.SH NAME
xgmml.render \- 
.SH SYNOPSIS
\fIxgmml.render(\fBmodel\fR as any, 
\fBsize\fR as string = "10(A0)", 
\fBconvexHull\fR as string = \fB<NULL>\fR, 
\fBedgeBends\fR as boolean = FALSE, 
\fBaltStyle\fR as boolean = FALSE, 
\fBrewriteGroupCategoryColors\fR as string = "TSF", 
\fBenzymeColorSchema\fR as string = "Set1", 
\fBcompoundColorSchema\fR as string = "Clusters", 
\fBreactionKOMapping\fR as list[string] = \fB<NULL>\fR, 
\fBrenderStyle\fR as boolean = FALSE, 
\fBcompoundNames\fR as list[string] = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
xgmml
.SH FILES
.PP
cytoscape.dll
.PP
