.\" man page create by R# package system.
.TH DUNNART 1 2000-1月 "optmize" "optmize"
.SH NAME
optmize \- 
.SH SYNOPSIS
\fIoptmize(\fBtemplate\fR as <generic> NetworkGraph, 
\fBoptmize_iterations\fR as integer = 100, 
\fBlower_degrees\fR as integer = 3, 
\fBlower_adjcents\fR as integer = 2);\fR
.SH SEE ALSO
dunnart
.SH FILES
.PP
cytoscape.dll
.PP
