.\" man page create by R# package system.
.TH BIOMODELS.STRINGDB.PPI 1 2000-01-01 "as.network" "as.network"
.SH NAME
as.network \- export string-db interaction result set as graph
.SH SYNOPSIS
\fIas.network(\fBstringNetwork\fR as <generic> InteractExports[], 
\fBuniprot\fR as any, 
\fBcoordinates\fR as <generic> Coordinates[] = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
export string-db interaction result set as graph
.PP
.SH OPTIONS
.PP
\fBstringNetwork\fB \fR\- -. 
.PP
.PP
\fBuniprot\fB \fR\- \fBSTRING -> uniprot\fR. 
.PP
.PP
\fBcoordinates\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bioModels.stringdb.ppi
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
