.\" man page create by R# package system.
.TH BIOMODELS.STRINGDB.PPI 1 2000-01-01 "read.coordinates" "read.coordinates"
.SH NAME
read.coordinates \- 
.SH SYNOPSIS
\fIread.coordinates(\fBstring_network_coordinates\fR as string);\fR
.SH SEE ALSO
bioModels.stringdb.ppi
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
