.\" man page create by R# package system.
.TH VCELLKIT.MODELLER 4 2020-11-02 "zip" "zip"
.SH NAME
zip \- 
.SH SYNOPSIS
\fIzip(\fBvcell\fR as <generic> VirtualCell, 
\fBfile\fR as string);\fR
.SH SEE ALSO
vcellkit.modeller
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
