.\" man page create by R# package system.
.TH SYMBOLIC 2 2020-07-22 "parse" "parse"
.SH NAME
parse \- 
.SH SYNOPSIS
\fIparse(\fBexpressions\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
symbolic
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
