.\" man page create by R# package system.
.TH SYMBOLIC 2 2020-11-09 "parse" "parse"
.SH NAME
parse \- Parse a math formula
.SH SYNOPSIS
\fIparse(\fBexpressions\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Parse a math formula
.PP
.SH OPTIONS
.PP
\fBexpressions\fB \fR\- a list of character vector which are all represents some math formula expression.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
symbolic
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
