.\" man page create by R# package system.
.TH DBGET 1 2000-01-01 "fetch.pathwayMaps" "fetch.pathwayMaps"
.SH NAME
fetch.pathwayMaps \- 
.SH SYNOPSIS
\fIfetch.pathwayMaps(\fBsp\fR as string, 
\fBexport\fR as string = "./", 
\fBisKGML\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
dbget
.SH FILES
.PP
kegg_kit.dll
.PP
