.\" man page create by R# package system.
.TH DBGET 1 2000-Jan "getMap" "getMap"
.SH NAME
getMap \- get kegg map from the kegg web server
.SH SYNOPSIS
\fIgetMap(\fBid\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get kegg map from the kegg web server
.PP
.SH OPTIONS
.PP
\fBid\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
dbget
.SH FILES
.PP
kegg_kit.dll
.PP
