.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "cor_network" "cor_network"
.SH NAME
cor_network \- Create correlation network based on WGCNA method
.SH SYNOPSIS
\fIcor_network(\fBx\fR as any, 
\fBadjacency\fR as double = 0.6, 
\fBpca_layout\fR as boolean = TRUE, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create correlation network based on WGCNA method
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 should be an HTS expression matrix object of gene features in rows and sample id in columns or the adjacency matrix which is read via \fBread.adjacency\fR function.
. 
.PP
.PP
\fBadjacency\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- 
 additional parameters for create correlation network based on the adjacency matrix directly: \fBmembership\fR for gene to modulee membership correlation result.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
