.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "cor_network" "cor_network"
.SH NAME
cor_network \- Create correlation network based on WGCNA method
.SH SYNOPSIS
\fIcor_network(\fBx\fR as <generic> Matrix, 
\fBadjacency\fR as double = 0.6, 
\fBpca_layout\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create correlation network based on WGCNA method
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 should be an expression matrix object of gene features in rows and sample id in columns
. 
.PP
.PP
\fBadjacency\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
