.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "load_TOM_graph" "load_TOM_graph"
.SH NAME
load_TOM_graph \- load network graph from the WGCNA exportNetworkToCytoscape function exports
.SH SYNOPSIS
\fIload_TOM_graph(\fBedges\fR as string, 
\fBnodes\fR as string, 
\fBthreshold\fR as double = 0, 
\fBprefix\fR as string = \fB<NULL>\fR, 
\fBid_subset\fR as any = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
load network graph from the WGCNA exportNetworkToCytoscape function exports
.PP
.SH OPTIONS
.PP
\fBedges\fB \fR\- -. 
.PP
.PP
\fBnodes\fB \fR\- -. 
.PP
.PP
\fBthreshold\fB \fR\- -. 
.PP
.PP
\fBprefix$\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
