.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "read.weightMatrix" "read.weightMatrix"
.SH NAME
read.weightMatrix \- 
.SH SYNOPSIS
\fIread.weightMatrix(\fBfile\fR as string, 
\fBthreshold\fR as double = 0, 
\fBprefix\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
