.\" man page create by R# package system.
.TH WGCNA 1 2000-Jan "read.modules" "read.modules"
.SH NAME
read.modules \- load TOM module network nodes
.SH SYNOPSIS
\fIread.modules(\fBfile\fR as string, 
\fBprefix\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
load TOM module network nodes
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the TOM network nodes text file, should be a tsv file of the cytoscape network export result
. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
