.\" man page create by R# package system.
.TH WGCNA 1 2000-Jan "read.weight_matrix" "read.weight_matrix"
.SH NAME
read.weight_matrix \- read the TOM correlation network matrix file
.SH SYNOPSIS
\fIread.weight_matrix(\fBfile\fR as any, 
\fBthreshold\fR as double = 0, 
\fBprefix\fR as string = \fB<NULL>\fR, 
\fBas_matrix\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
read the TOM correlation network matrix file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBthreshold\fB \fR\- -. 
.PP
.PP
\fBprefix\fB \fR\- 
 a prefix to the fromNode and toNode id
. 
.PP
.SH DETAILS
.PP
imports a network edge table file that export from WGCNA TOM module, with data headers: 
 
 fromNode
 toNode
 weight
 direction
 fromAltName
 toAltName
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
phenotype_kit.dll
.PP
