.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "enzyme_description" "enzyme_description"
.SH NAME
enzyme_description \- Get the class description category data for EC number
.SH SYNOPSIS
\fIenzyme_description();\fR
.SH DESCRIPTION
.PP
Get the class description category data for EC number
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
