.\" man page create by R# package system.
.TH KEGG 1 2000-1月 "compound_set" "compound_set"
.SH NAME
compound_set \- gt kegg compound set from a kegg pathway map collection
.SH SYNOPSIS
\fIcompound_set(\fBmaps\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
gt kegg compound set from a kegg pathway map collection
.PP
.SH OPTIONS
.PP
\fBmaps\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kegg
.SH FILES
.PP
gseakit.dll
.PP
