.\" man page create by R# package system.
.TH CIRCOS 1 2000-1月 "genome_circle" "genome_circle"
.SH NAME
genome_circle \- Creates the circos gene circle from the PTT database which is defined
.SH SYNOPSIS
\fIgenome_circle(\fBPTT\fR as <generic> PTTDbLoader, 
\fBCOG\fR as any, 
\fBdefaultColor\fR as string = "blue", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Creates the circos gene circle from the PTT database which is defined 
 in the \fB*.ptt/*.rnt\fR file, and you can download this directory from 
 the NCBI FTP website.
.PP
.SH OPTIONS
.PP
\fBPTT\fB \fR\- -. 
.PP
.PP
\fBCOG\fB \fR\- -. 
.PP
.PP
\fBdefaultColor\fB \fR\- -. 
.PP
.SH SEE ALSO
circos
.SH FILES
.PP
visualkit.dll
.PP
