.\" man page create by R# package system.
.TH CIRCOS 1 2000-1月 "identity_colors" "identity_colors"
.SH NAME
identity_colors \- 
.SH SYNOPSIS
\fIidentity_colors(\fBmin\fR as double, 
\fBmax\fR as double, 
\fBdepth\fR as integer = 10, 
\fBdefault\fR as string = "Brown", 
\fBmapName\fR as string = "Jet");\fR
.SH SEE ALSO
circos
.SH FILES
.PP
visualkit.dll
.PP
