.\" man page create by R# package system.
.TH CIRCOS 1 2000-1月 "track_hits" "track_hits"
.SH NAME
track_hits \- 
.SH SYNOPSIS
\fItrack_hits(\fBsource\fR as any, 
\fBkaryotype\fR as <generic> KaryotypeSkeleton, 
\fBsteps\fR as integer = 2048, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
circos
.SH FILES
.PP
visualkit.dll
.PP
