.\" man page create by R# package system.
.TH SABIORK 1 2000-1月 "enzyme_info" "enzyme_info"
.SH NAME
enzyme_info \- get enzyme info of a given reaction model
.SH SYNOPSIS
\fIenzyme_info(\fBsbml\fR as <generic> SBMLInternalIndexer, 
\fBreaction\fR as <generic> SBMLReaction);\fR
.SH DESCRIPTION
.PP
get enzyme info of a given reaction model
.PP
.SH OPTIONS
.PP
\fBsbml\fB \fR\- -. 
.PP
.PP
\fBreaction\fB \fR\- -. 
.PP
.SH SEE ALSO
sabiork
.SH FILES
.PP
biosystem.dll
.PP
