.\" man page create by R# package system.
.TH GTK 1 2000-01-01 "selectFolder" "selectFolder"
.SH NAME
selectFolder \- 
.SH SYNOPSIS
\fIselectFolder(\fBdefault\fR as string = "", 
\fBdesc\fR as string = \fB<NULL>\fR, 
\fBnewFolder\fR as boolean = FALSE, 
\fBroot\fR as <integer> SpecialFolder = [MyDocuments]);\fR
.SH SEE ALSO
gtk
.SH FILES
.PP
Rstudio.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
