.\" man page create by R# package system.
.TH GTK 1 2000-01-01 "selectFiles" "selectFiles"
.SH NAME
selectFiles \- 
.SH SYNOPSIS
\fIselectFiles(\fBtitle\fR as string = \fB<NULL>\fR, 
\fBfilter\fR as <generic> Object = "*.*|*.*", 
\fBforSave\fR as boolean = FALSE);\fR
.SH SEE ALSO
gtk
.SH FILES
.PP
Rstudio.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
