.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "bnlearn" "bnlearn"
.SH NAME
bnlearn \- 
.SH SYNOPSIS
\fIbnlearn(\fBexprData\fR as <generic> Matrix, 
\fBpriorNet\fR as any = \fB<NULL>\fR, 
\fBmax_itrs\fR as integer = 500, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bnlearn
.SH FILES
.PP
phenotype_kit.dll
.PP
