.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "make_exports" "make_exports"
.SH NAME
make_exports \- 
.SH SYNOPSIS
\fImake_exports(\fBresults\fR as any, 
\fBdir\fR as string, 
\fBpathway_info\fR as list = \fB<NULL>\fR, 
\fBtop_n\fR as integer = 50, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bnlearn
.SH FILES
.PP
phenotype_kit.dll
.PP
