.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "prior_network" "prior_network"
.SH NAME
prior_network \- 
.SH SYNOPSIS
\fIprior_network(\fBTF\fR as any, 
\fBtarget_gene\fR as any, 
\fBregulation_type\fR as any, 
\fBconfidence\fR as any, 
\fBevidence\fR as any);\fR
.SH SEE ALSO
bnlearn
.SH FILES
.PP
phenotype_kit.dll
.PP
