.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "save_model" "save_model"
.SH NAME
save_model \- save bnlearn model
.SH SYNOPSIS
\fIsave_model(\fBbnlearn\fR as <generic> BNLearnWorkflow, 
\fBdir\fR as string);\fR
.SH DESCRIPTION
.PP
save bnlearn model
.PP
.SH OPTIONS
.PP
\fBbnlearn\fB \fR\- -. 
.PP
.PP
\fBdir\fB \fR\- -. 
.PP
.SH SEE ALSO
bnlearn
.SH FILES
.PP
phenotype_kit.dll
.PP
