#Region "Microsoft.VisualBasic::ec4ec3a80eee2b26812f409e8e0df82d, data\Reactome\My Project\Resources.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 107
    '    Code Lines: 42
    ' Comment Lines: 55
    '   Blank Lines: 10
    '     File Size: 4.89 KB


    '     Module Resources
    ' 
    '         Properties: Culture, ReactomePathways, ReactomePathwaysRelation, ResourceManager
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Data.Reactome.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 R-BTA-73843	5-Phosphoribose 1-diphosphate biosynthesis	Bos taurus
        '''R-BTA-1971475	A tetrasaccharide linker sequence is required for GAG synthesis	Bos taurus
        '''R-BTA-1369062	ABC transporters in lipid homeostasis	Bos taurus
        '''R-BTA-382556	ABC-family proteins mediated transport	Bos taurus
        '''R-BTA-9033807	ABO blood group biosynthesis	Bos taurus
        '''R-BTA-418592	ADP signalling through P2Y purinoceptor 1	Bos taurus
        '''R-BTA-392170	ADP signalling through P2Y purinoceptor 12	Bos taurus
        '''R-BTA-211163	AKT-mediated inactivation of FO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ReactomePathways() As String
            Get
                Return ResourceManager.GetString("ReactomePathways", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 R-BTA-109581	R-BTA-109606
        '''R-BTA-109581	R-BTA-169911
        '''R-BTA-109581	R-BTA-5357769
        '''R-BTA-109581	R-BTA-75153
        '''R-BTA-109582	R-BTA-140877
        '''R-BTA-109582	R-BTA-202733
        '''R-BTA-109582	R-BTA-418346
        '''R-BTA-109582	R-BTA-75205
        '''R-BTA-109582	R-BTA-75892
        '''R-BTA-109582	R-BTA-76002
        '''R-BTA-109582	R-BTA-983231
        '''R-BTA-109606	R-BTA-111452
        '''R-BTA-109606	R-BTA-111453
        '''R-BTA-109606	R-BTA-111471
        '''R-BTA-109606	R-BTA-114294
        '''R-BTA-109606	R-BTA-114452
        '''R-BTA-109606	R-BTA-75108
        '''R-BTA-109703	R-BTA-165160
        '''R-BTA-109704	R-BTA-109703
        '''R-BTA-109704	R-BTA-165 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ReactomePathwaysRelation() As String
            Get
                Return ResourceManager.GetString("ReactomePathwaysRelation", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
