.\" man page create by R# package system.
.TH GAST 1 2000-Jan "OTU.taxonomy" "OTU.taxonomy"
.SH NAME
OTU.taxonomy \- assign OTU its taxonomy result
.SH SYNOPSIS
\fIOTU.taxonomy(\fBblastn\fR as any, 
\fBOTUs\fR as list, 
\fBtaxonomy\fR as list, 
\fBmin_pct\fR as double = 0.97, 
\fBgast_consensus\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
assign OTU its taxonomy result
.PP
.SH SEE ALSO
gast
.SH FILES
.PP
metagenomics_kit.dll
.PP
