.\" man page create by R# package system.
.TH GAST 1 2000-Jan "parse.mothur_OTUs" "parse.mothur_OTUs"
.SH NAME
parse.mothur_OTUs \- parse the OTU data file
.SH SYNOPSIS
\fIparse.mothur_OTUs(\fBOTU_rep_fasta\fR as string, 
\fBremoves_lt\fR as double = 0.0001);\fR
.SH DESCRIPTION
.PP
parse the OTU data file
.PP
.SH OPTIONS
.PP
\fBOTU_rep_fasta\fB \fR\- 
 \fBOTU.rep.fasta\fR query source comes from the mothur workflow.
. 
.PP
.SH SEE ALSO
gast
.SH FILES
.PP
metagenomics_kit.dll
.PP
