.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-1月 "blasthit.sbh" "blasthit.sbh"
.SH NAME
blasthit.sbh \- Export single side besthit
.SH SYNOPSIS
\fIblasthit.sbh(\fBquery\fR as <generic> pipeline, 
\fBidetities\fR as double = 0.3, 
\fBcoverage\fR as double = 0.5, 
\fBtopBest\fR as boolean = FALSE, 
\fBkeepsRawName\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Export single side besthit
.PP
.SH OPTIONS
.PP
\fBquery\fB \fR\- the blast reader result from the \fBread.blast\fR iterator function.. 
.PP
.PP
\fBidetities\fB \fR\- 
 the minimum identity threshold value of the accepted hits.
. 
.PP
.PP
\fBcoverage\fB \fR\- 
 the minimum coverage threshold value of the accepted hits.
. 
.PP
.PP
\fBtopBest\fB \fR\- 
 only export the top best hit for each query?
. 
.PP
.PP
\fBkeepsRawName\fB \fR\- 
 keep the raw query name text in the exported best hit data?
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a lazy pipeline collection of the [BestHit](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.LocalBLAST.Application.BBH.BestHit) single side 
 best hit result;
 
 this function returns a R# error message object if the input query 
 pipeline data type is not the [Query](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.LocalBLAST.BLASTOutput.BlastPlus.Query) object.
.PP
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
