.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-1月 "blastn.maphit" "blastn.maphit"
.SH NAME
blastn.maphit \- export results of fastq reads mapping to genome sequence.
.SH SYNOPSIS
\fIblastn.maphit(\fBquery\fR as <generic> pipeline, 
\fBtop_best\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
export results of fastq reads mapping to genome sequence.
.PP
.SH OPTIONS
.PP
\fBquery\fB \fR\- 
 a lazy pipeline collection of the blast query hits result 
 ([Query](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.LocalBLAST.BLASTOutput.BlastPlus.Query)), which is created by the \fBread.blast\fR api.
. 
.PP
.PP
\fBtop_best\fB \fR\- 
 only export the top best mapping for each query?
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a lazy pipeline collection of the [BlastnMapping](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.LocalBLAST.Application.NtMapping.BlastnMapping) reads 
 mapping result;
 
 this function returns a R# error message object if the input query 
 pipeline data type is not the [Query](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.LocalBLAST.BLASTOutput.BlastPlus.Query) object.
.PP
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
