.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-1月 "remove_protein_suffix" "remove_protein_suffix"
.SH NAME
remove_protein_suffix \- removes protein suffix id
.SH SYNOPSIS
\fIremove_protein_suffix(\fBhits\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
removes protein suffix id
.PP
.SH OPTIONS
.PP
\fBhits\fB \fR\- a collection of the blast hits result or a character vector of the protein id.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
