.\" man page create by R# package system.
.TH PFSNET 2 2000-Jan "build.pathway_network" "build.pathway_network"
.SH NAME
build.pathway_network \- 
.SH SYNOPSIS
\fIbuild.pathway_network(\fBmaps\fR as <generic> Map[], 
\fBreactions\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
PFSNet
.SH FILES
.PP
phenotype_kit.dll
.PP
