.\" man page create by R# package system.
.TH PFSNET 2 2000-01-01 "pfsnet" "pfsnet"
.SH NAME
pfsnet \- Finding consistent disease subnetworks using PFSNet
.SH SYNOPSIS
\fIpfsnet(\fBexpr1o\fR as any, 
\fBexpr2o\fR as any, 
\fBggi\fR as <generic> GraphEdge[], 
\fBb\fR as double = 0.5, 
\fBt1\fR as double = 0.95, 
\fBt2\fR as double = 0.85, 
\fBn\fR as integer = 1000);\fR
.SH DESCRIPTION
.PP
Finding consistent disease subnetworks using PFSNet
.PP
.SH OPTIONS
.PP
\fBexpr1o\fB \fR\- -. 
.PP
.PP
\fBexpr2o\fB \fR\- -. 
.PP
.PP
\fBggi\fB \fR\- -. 
.PP
.PP
\fBb\fB \fR\- -. 
.PP
.PP
\fBt1\fB \fR\- -. 
.PP
.PP
\fBt2\fB \fR\- -. 
.PP
.PP
\fBn\fB \fR\- -. 
.PP
.SH SEE ALSO
PFSNet
.SH FILES
.PP
phenotype_kit.dll
.PP
