.\" man page create by R# package system.
.TH PFSNET 2 2000-1月 "save.pathway_network" "save.pathway_network"
.SH NAME
save.pathway_network \- 
.SH SYNOPSIS
\fIsave.pathway_network(\fBggi\fR as any, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
PFSNet
.SH FILES
.PP
phenotype_kit.dll
.PP
