.TH .CAST_CLR_METPA 1 2023-Feb "" "Create metpa background model from the .NET CLR object"
.SH NAME
.cast_CLR_metpa \- .cast_CLR_metpa(metpa)
.SH SYNOPSIS
\fI.cast_CLR_metpa(metpa)\fR
.SH OPTIONS
.PP
\fBmetpa\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..cast_CLR_metpa at metpa.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
