.TH .CAST_CLR_METPA 1 2026-Jan "" "Create metpa background model from the .NET clr object"
.SH NAME
.cast_CLR_metpa \- .cast_CLR_metpa(metpa)
.SH SYNOPSIS
\fI.cast_CLR_metpa(metpa)\fR
.SH OPTIONS
.PP
\fBmetpa\fB \fR\- . A GCModeller metpa clr object which is generated
from the ``background::metpa`` function.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..cast_CLR_metpa at read_clr.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
