.TH .READZIPSTREAM 1 2022-03-30 "" "Read zip stream data"
.SH NAME
.readZipStream \- .readZipStream(zipfile, entryName = NULL)
.SH SYNOPSIS
\fI.readZipStream(zipfile, entryName = NULL)\fR
.SH DESCRIPTION
.PP
this function open the given zip archive file and then load the first file as data stream object if the zip entry name is missing.
.PP
.SH OPTIONS
.PP
\fBzipfile\fB \fR\- . the file path of the target zip file to read data stream
.PP
.PP
\fBentryName\fB \fR\- NULL. the zip entry name.
.PP
.SH VALUE
.PP
A data steam object that read from the given zip archive file.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..readZipStream at kegg_repository.R:line 50
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2022
