.TH .SAFE_KEGG_URL_PARSER 1 2026-Jan "" "Parse the kegg object set that encoded inside the kegg url string"
.SH NAME
.safe_kegg_url_parser \- .safe_kegg_url_parser(url, compoundcolors, gene.highights)
.SH SYNOPSIS
\fI.safe_kegg_url_parser(url, compoundcolors, gene.highights)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . 
.PP
.PP
\fBcompoundcolors\fB \fR\- . color value for kegg compound
.PP
.PP
\fBgene.highights\fB \fR\- . 
.PP
.SH VALUE
.PP
this function will ensure that returns a tuple list that contains
the slot value ``objects`` always.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..safe_kegg_url_parser at url_decode.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
