.TH .URL_ENCODE 1 2026-Feb "" ".url_encode"
.SH NAME
.url_encode \- .url_encode(enrich,
    <i>data</i> = <span style='color: blue !important;'>NULL</span>,
    <i>log2FC</i> = <span style='color: brown;'><strong>'log2(FC)'</strong></span>,
    <i>id</i> = <span style='color: brown;'><strong>'kegg'</strong></span>)
.SH SYNOPSIS
\fI.url_encode(enrich,
    <i>data</i> = <span style='color: blue !important;'>NULL</span>,
    <i>log2FC</i> = <span style='color: brown;'><strong>'log2(FC)'</strong></span>,
    <i>id</i> = <span style='color: brown;'><strong>'kegg'</strong></span>)\fR
.SH OPTIONS
.PP
\fBenrich\fB \fR\- . 
.PP
.PP
\fBdata\fB \fR\- NULL. 
.PP
.PP
\fBlog2FC\fB \fR\- 'log2(FC)'. 
.PP
.PP
\fBid\fB \fR\- 'kegg'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..url_encode at url_encode.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
