.TH .WRITE_MSETLIST 1 2026-Jan "" ".write_msetList"
.SH NAME
.write_msetList \- .write_msetList(msetList)
.SH SYNOPSIS
\fI.write_msetList(msetList)\fR
.SH OPTIONS
.PP
\fBmsetList\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_msetList at read_clr.R:line 61
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
