.TH .WRITE_PATHIDS 1 2023-6月 "" ".write_pathIds"
.SH NAME
.write_pathIds \- .write_pathIds(pathIds)
.SH SYNOPSIS
\fI.write_pathIds(pathIds)\fR
.SH OPTIONS
.PP
\fBpathIds\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_pathIds at metpa.R:line 94
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
