.TH .WRITE_RBCLIST 1 2023-6月 "" ".write_rbcList"
.SH NAME
.write_rbcList \- .write_rbcList(rbcList)
.SH SYNOPSIS
\fI.write_rbcList(rbcList)\fR
.SH OPTIONS
.PP
\fBrbcList\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_rbcList at metpa.R:line 117
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
