.TH .WRITE_GRAPHLIST 1 2023-6月 "" ".write_graphList"
.SH NAME
.write_graphList \- .write_graphList(graphList)
.SH SYNOPSIS
\fI.write_graphList(graphList)\fR
.SH OPTIONS
.PP
\fBgraphList\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_graphList at metpa.R:line 62
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
