.TH .WRITE_PATHIDS 1 2025-Dec "" ".write_pathIds"
.SH NAME
.write_pathIds \- .write_pathIds(pathIds)
.SH SYNOPSIS
\fI.write_pathIds(pathIds)\fR
.SH OPTIONS
.PP
\fBpathIds\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_pathIds at read_clr.R:line 70
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
