.TH .WRITE_GRAPH 1 2023-Feb "" ".write_graph"
.SH NAME
.write_graph \- .write_graph(graph)
.SH SYNOPSIS
\fI.write_graph(graph)\fR
.SH OPTIONS
.PP
\fBgraph\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_graph at metpa.R:line 40
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
