.TH .WRITE_DGRLIST 1 2026-Jan "" ".write_dgrlist"
.SH NAME
.write_dgrlist \- .write_dgrlist(dgrList)
.SH SYNOPSIS
\fI.write_dgrlist(dgrList)\fR
.SH OPTIONS
.PP
\fBdgrList\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_dgrlist at read_clr.R:line 42
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
