.TH .WRITE_PATHSMPS 1 2025-Nov "" ".write_pathSmps"
.SH NAME
.write_pathSmps \- .write_pathSmps(pathSmps)
.SH SYNOPSIS
\fI.write_pathSmps(pathSmps)\fR
.SH OPTIONS
.PP
\fBpathSmps\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..write_pathSmps at read_clr.R:line 104
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
