.TH __HDS_COMPOUND_FILES 1 2026-Feb "" "get all kegg compound files inside a HDS stream"
.SH NAME
__hds_compound_files \- __hds_compound_files(kegg.db,
    <i>flag</i> = <span style='color: brown;'><strong>'compounds'</strong></span>,
    <i>what</i> = <span style='color: brown;'><strong>'kegg_compound'</strong></span>)
.SH SYNOPSIS
\fI__hds_compound_files(kegg.db,
    <i>flag</i> = <span style='color: brown;'><strong>'compounds'</strong></span>,
    <i>what</i> = <span style='color: brown;'><strong>'kegg_compound'</strong></span>)\fR
.SH OPTIONS
.PP
\fBkegg.db\fB \fR\- . 
.PP
.PP
\fBflag\fB \fR\- 'compounds'. 
.PP
.PP
\fBwhat\fB \fR\- 'kegg_compound'. 
.PP
.SH VALUE
.PP
a set of the kegg compound clr object models
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__hds_compound_files at kegg_compounds.R:line 39
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
