.TH __HDS_COMPOUND_FILES 1 2024-Feb "" "get all kegg compound files inside a HDS stream"
.SH NAME
__hds_compound_files \- __hds_compound_files(kegg.db)
.SH SYNOPSIS
\fI__hds_compound_files(kegg.db)\fR
.SH OPTIONS
.PP
\fBkegg.db\fB \fR\- . 
.PP
.SH VALUE
.PP
a set of the kegg compound clr object models
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__hds_compound_files at kegg_compounds.R:line 28
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2024
