.TH __HDS_COMPOUND_DIR 1 2026-Jan "" "__hds_compound_dir"
.SH NAME
__hds_compound_dir \- __hds_compound_dir(kegg.db, dir,
    <i>flag</i> = <span style='color: brown;'><strong>'compounds'</strong></span>,
    <i>what</i> = <span style='color: brown;'><strong>'kegg_compound'</strong></span>)
.SH SYNOPSIS
\fI__hds_compound_dir(kegg.db, dir,
    <i>flag</i> = <span style='color: brown;'><strong>'compounds'</strong></span>,
    <i>what</i> = <span style='color: brown;'><strong>'kegg_compound'</strong></span>)\fR
.SH OPTIONS
.PP
\fBkegg.db\fB \fR\- . 
.PP
.PP
\fBdir\fB \fR\- . 
.PP
.PP
\fBflag\fB \fR\- 'compounds'. 
.PP
.PP
\fBwhat\fB \fR\- 'kegg_compound'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__hds_compound_dir at kegg_compounds.R:line 51
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
