.TH __HDS_COMPOUND_DIR 1 2024-May "" "__hds_compound_dir"
.SH NAME
__hds_compound_dir \- __hds_compound_dir(kegg.db, dir,
    <i>flag</i> = compounds,
    <i>what</i> = kegg_compound)
.SH SYNOPSIS
\fI__hds_compound_dir(kegg.db, dir,
    <i>flag</i> = compounds,
    <i>what</i> = kegg_compound)\fR
.SH OPTIONS
.PP
\fBkegg.db\fB \fR\- . 
.PP
.PP
\fBdir\fB \fR\- . 
.PP
.PP
\fBflag\fB \fR\- compounds. 
.PP
.PP
\fBwhat\fB \fR\- kegg_compound. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__hds_compound_dir at kegg_compounds.R:line 40
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2024
