.TH __LOAD_KEGG_MAP 1 2026-2月 "" "this function try to unify the kegg map load method"
.SH NAME
__load_kegg_map \- __load_kegg_map(
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>,
    <i>raw.maps</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fI__load_kegg_map(
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>,
    <i>raw.maps</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBkegg.maps\fB \fR\- NULL. 
.PP
.PP
\fBraw.maps\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__load_kegg_map at map_loader.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
