.TH COMPOUNDNETWORK 1 2025-Aug "" "Create kegg compound network"
.SH NAME
CompoundNetwork \- CompoundNetwork(compoundsId,
    <i>make.pathway.cluster</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fICompoundNetwork(compoundsId,
    <i>make.pathway.cluster</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBcompoundsId\fB \fR\- . 
.PP
.PP
\fBmake.pathway.cluster\fB \fR\- TRUE. 
.PP
.SH VALUE
.PP
a network graph object model, which can be export as table file or run network visualization rendering in the downstream data analysis.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.CompoundNetwork at kegg_graph.R:line 20
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
