.TH DOWNLOAD_PROTEINS 1 2026-2月 "" "download_proteins"
.SH NAME
download_proteins \- download_proteins(q,
    <i>tax.id</i> = <span style='color: blue !important;'>NULL</span>,
    <i>as.fasta</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIdownload_proteins(q,
    <i>tax.id</i> = <span style='color: blue !important;'>NULL</span>,
    <i>as.fasta</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBq\fB \fR\- . 
.PP
.PP
\fBtax.id\fB \fR\- NULL. 
.PP
.PP
\fBas.fasta\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.download_proteins at uniprot.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
