.TH ECNUMBER_TO_KO 1 2025-Nov "" "A helper function for make conversion from the ec number list to ko id"
.SH NAME
ecnumber_to_ko \- ecnumber_to_ko(
    <i>ec.number</i> = <span style='color: brown;'><strong>'*'</strong></span>)
.SH SYNOPSIS
\fIecnumber_to_ko(
    <i>ec.number</i> = <span style='color: brown;'><strong>'*'</strong></span>)\fR
.SH OPTIONS
.PP
\fBec.number\fB \fR\- '*'. 
.PP
.SH VALUE
.PP
a dataframe object that mapping the ec number to the corresponding ko id, this dataframe object contains two data fields:
1. ec_number: the enzyme number from the parameter input
2. ko: the kegg ko id that the enzyme mapping to
3. symbol: the gene name of the enzyme
4. name: the gene function, or the full name
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.ecnumber_to_ko at ecnumber_to_ko.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
