.TH EXTRACT_REACTIONS 1 2026-Jan "" "extract reaction data from the reference database"
.SH NAME
extract_reactions \- extract_reactions()
.SH SYNOPSIS
\fIextract_reactions()\fR
.SH DETAILS
.PP
this function extract the reaction data which
has the pathway map association.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.extract_reactions at kegg_reactions.R:line 22
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
