.TH FETCH_GENBANK 1 2023-Jun "" "fetch_genbank"
.SH NAME
fetch_genbank \- fetch_genbank(accession.id,
    <i>annotations</i> = [GENOME_GBFF, GENOME_FASTA, GENOME_GFF, RNA_FASTA, CDS_FASTA, PROT_FASTA, SEQUENCE_REPORT])
.SH SYNOPSIS
\fIfetch_genbank(accession.id,
    <i>annotations</i> = [GENOME_GBFF, GENOME_FASTA, GENOME_GFF, RNA_FASTA, CDS_FASTA, PROT_FASTA, SEQUENCE_REPORT])\fR
.SH OPTIONS
.PP
\fBaccession.id\fB \fR\- . 
.PP
.PP
\fBannotations\fB \fR\- [GENOME_GBFF, GENOME_FASTA, GENOME_GFF, RNA_FASTA, CDS_FASTA, PROT_FASTA, SEQUENCE_REPORT]. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.fetch_genbank at get_genbank.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
