.TH FETCH_GENBANK 1 2023-May "" "fetch_genbank"
.SH NAME
fetch_genbank \- fetch_genbank(accession.id,
    <i>annotations</i> = genbank_annotation_flags)
.SH SYNOPSIS
\fIfetch_genbank(accession.id,
    <i>annotations</i> = genbank_annotation_flags)\fR
.SH OPTIONS
.PP
\fBaccession.id\fB \fR\- . 
.PP
.PP
\fBannotations\fB \fR\- genbank_annotation_flags. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.fetch_genbank at get_genbank.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
