.TH HSA_PATHWAYS 1 2025-Nov "" "read human kegg pathway list data"
.SH NAME
hsa_pathways \- hsa_pathways()
.SH SYNOPSIS
\fIhsa_pathways()\fR
.SH VALUE
.PP
a dataframe object that contains the human pathway list,
the data fields was includes this dataframe object:
+ ID: the pathway id
+ Definition: the pathway name
.PP
.SH DETAILS
.PP
read from the internal resource data files
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.hsa_pathways at pathways.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
