.TH KEGG_REACTIONS 1 2022-12-07 "" "Load internal kegg reaction repository"
.SH NAME
kegg_reactions \- kegg_reactions(
    <i>raw</i> = TRUE)
.SH SYNOPSIS
\fIkegg_reactions(
    <i>raw</i> = TRUE)\fR
.SH OPTIONS
.PP
\fBraw\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_reactions at kegg_repository.R:line 29
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2022
