.TH KEGG_MAPRENDER 1 2023-Apr "" "Do rendering of the kegg pathway maps"
.SH NAME
KEGG_MapRender \- KEGG_MapRender(enrich,
    <i>map.id</i> = KEGG,
    <i>pathway.links</i> = pathway_links,
    <i>outputdir</i> = ./,
    <i>kegg.maps</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIKEGG_MapRender(enrich,
    <i>map.id</i> = KEGG,
    <i>pathway.links</i> = pathway_links,
    <i>outputdir</i> = ./,
    <i>kegg.maps</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBenrich\fB \fR\- . the csv file path of the kegg pathway map enrichment result or the dataframe value it self
.PP
.PP
\fBmap.id\fB \fR\- KEGG. 
.PP
.PP
\fBpathway.links\fB \fR\- pathway_links. 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBkegg.maps\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.KEGG_MapRender at KEGG_render.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
