.TH KEGG_MAPS 1 2023-01-07 "" "Load internal kegg map repository"
.SH NAME
kegg_maps \- kegg_maps(
    <i>rawMaps</i> = <span style='color: blue;'>TRUE</span>)
.SH SYNOPSIS
\fIkegg_maps(
    <i>rawMaps</i> = <span style='color: blue;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBrawMaps\fB \fR\- TRUE. this parameter value determine the data type of the return value from this function. ``TRUE`` value of this parameter will returns a vector of map data object or a indexed map repository object if set the parameter value to value ``FALSE``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_maps at kegg_repository.R:line 19
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
