.TH KEGG_COLORS 1 2023-Jun "" "generate color map for do colorful encode of the kegg map url"
.SH NAME
kegg_colors \- kegg_colors(id, log2FC,
    <i>up</i> = red,
    <i>down</i> = blue)
.SH SYNOPSIS
\fIkegg_colors(id, log2FC,
    <i>up</i> = red,
    <i>down</i> = blue)\fR
.SH OPTIONS
.PP
\fBid\fB \fR\- . 
.PP
.PP
\fBlog2FC\fB \fR\- . 
.PP
.PP
\fBup\fB \fR\- red. 
.PP
.PP
\fBdown\fB \fR\- blue. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_colors at metpa_enrich.R:line 101
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
