.TH KEGG_MAPRENDER 1 2023-Mar "" "Do rendering of the kegg pathway maps"
.SH NAME
KEGG_MapRender \- KEGG_MapRender(enrich,
    <i>map.id</i> = KEGG,
    <i>pathway.links</i> = pathway_links,
    <i>outputdir</i> = ./)
.SH SYNOPSIS
\fIKEGG_MapRender(enrich,
    <i>map.id</i> = KEGG,
    <i>pathway.links</i> = pathway_links,
    <i>outputdir</i> = ./)\fR
.SH OPTIONS
.PP
\fBenrich\fB \fR\- . the csv file path of the kegg pathway map enrichment result or the dataframe value it self
.PP
.PP
\fBmap.id\fB \fR\- KEGG. 
.PP
.PP
\fBpathway.links\fB \fR\- pathway_links. 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.KEGG_MapRender at KEGG_render.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
