.TH KEGG_MAPRENDER 1 2025-Dec "" "Do rendering of the kegg pathway maps"
.SH NAME
KEGG_MapRender \- KEGG_MapRender(enrich,
    <i>map.id</i> = <span style='color: brown;'><strong>'KEGG'</strong></span>,
    <i>pathway.links</i> = <span style='color: brown;'><strong>'pathway_links'</strong></span>,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>min.objects</i> = <span style='color: green;'>0</span>,
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIKEGG_MapRender(enrich,
    <i>map.id</i> = <span style='color: brown;'><strong>'KEGG'</strong></span>,
    <i>pathway.links</i> = <span style='color: brown;'><strong>'pathway_links'</strong></span>,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>min.objects</i> = <span style='color: green;'>0</span>,
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBenrich\fB \fR\- . the csv file path of the kegg pathway map enrichment
result or the dataframe value it self
.PP
.PP
\fBmap.id\fB \fR\- 'KEGG'. 
.PP
.PP
\fBpathway.links\fB \fR\- 'pathway_links'. 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBmin.objects\fB \fR\- 0. 
.PP
.PP
\fBkegg.maps\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.KEGG_MapRender at KEGG_MapRender.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
