.TH KEGG_TAXONOMYINFO 1 2026-5月 "" "kegg_taxonomyinfo"
.SH NAME
kegg_taxonomyinfo \- kegg_taxonomyinfo(
    <i>code</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIkegg_taxonomyinfo(
    <i>code</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_taxonomyinfo at kegg_taxonomyinfo.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
