.TH KEGG_COMPOUNDS 1 2026-Feb "" "Load internal kegg compound repository"
.SH NAME
kegg_compounds \- kegg_compounds(
    <i>rawList</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>reference.set</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIkegg_compounds(
    <i>rawList</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>reference.set</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBrawList\fB \fR\- FALSE. 
.PP
.PP
\fBreference.set\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_compounds at kegg_compounds.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
