.TH KEGG_REACTIONS 1 2025-Dec "" "Load internal kegg reaction repository"
.SH NAME
kegg_reactions \- kegg_reactions(
    <i>raw</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIkegg_reactions(
    <i>raw</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBraw\fB \fR\- TRUE. 
.PP
.SH DETAILS
.PP
this function extract the reaction data both of associated
with the kegg pathway map or the reactions has no associations.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.kegg_reactions at kegg_reactions.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
