.TH LIST.TAXONOMIC_GROUP 1 2023-May "" "list.taxonomic_group"
.SH NAME
list.taxonomic_group \- list.taxonomic_group()
.SH SYNOPSIS
\fIlist.taxonomic_group()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.list.taxonomic_group at query.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
