.TH LOAD_KEGG_MAPS 1 2025-Dec "" "load_kegg_maps"
.SH NAME
load_kegg_maps \- load_kegg_maps(
    <i>raw.maps</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIload_kegg_maps(
    <i>raw.maps</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBraw.maps\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_kegg_maps at map_loader.R:line 29
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
