.TH LOAD_KOMAP 1 2026-3月 "" "load_komap"
.SH NAME
load_komap \- load_komap(ko.maps)
.SH SYNOPSIS
\fIload_komap(ko.maps)\fR
.SH OPTIONS
.PP
\fBko.maps\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_komap at link_ko.R:line 99
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
