.TH LOCALRENDERMAP 1 2026-2月 "" "Do rendering of the kegg pathway map"
.SH NAME
localRenderMap \- localRenderMap(KEGG.maps, pathwayList,
    <i>compoundcolors</i> = <span style='color: #FF0000;'><strong>'red'</strong></span>,
    <i>gene.highights</i> = <span style='color: #0000FF;'><strong>'blue'</strong></span>,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>min.objects</i> = <span style='color: green;'>0</span>)
.SH SYNOPSIS
\fIlocalRenderMap(KEGG.maps, pathwayList,
    <i>compoundcolors</i> = <span style='color: #FF0000;'><strong>'red'</strong></span>,
    <i>gene.highights</i> = <span style='color: #0000FF;'><strong>'blue'</strong></span>,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>min.objects</i> = <span style='color: green;'>0</span>)\fR
.SH OPTIONS
.PP
\fBKEGG.maps\fB \fR\- . 
.PP
.PP
\fBpathwayList\fB \fR\- . the list data of the kegg url for do rendering, this
parameter value should be a list of the key-value paire to the url
string data.
.PP
.PP
\fBcompoundcolors\fB \fR\- 'red'. 
.PP
.PP
\fBgene.highights\fB \fR\- 'blue'. 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBmin.objects\fB \fR\- 0. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.localRenderMap at localRenderMap.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
