.TH LOCALRENDERMAP 1 2023-7月 "" "Do rendering of the kegg pathway map"
.SH NAME
localRenderMap \- localRenderMap(KEGG.maps, pathwayList,
    <i>compoundcolors</i> = red,
    <i>gene.highights</i> = blue,
    <i>outputdir</i> = ./)
.SH SYNOPSIS
\fIlocalRenderMap(KEGG.maps, pathwayList,
    <i>compoundcolors</i> = red,
    <i>gene.highights</i> = blue,
    <i>outputdir</i> = ./)\fR
.SH OPTIONS
.PP
\fBKEGG.maps\fB \fR\- . 
.PP
.PP
\fBpathwayList\fB \fR\- . the list data of the kegg url for do rendering, this parameter value should be a list of the key-value paire to the url string data.
.PP
.PP
\fBcompoundcolors\fB \fR\- red. 
.PP
.PP
\fBgene.highights\fB \fR\- blue. 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.localRenderMap at localRenderMap.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
