.TH METPA_ENRICH_DATAFRAME 1 2024-Jan "" "metpa_enrich_dataframe"
.SH NAME
metpa_enrich_dataframe \- metpa_enrich_dataframe(data, metpa,
    <i>log2FC</i> = log2(FC),
    <i>id</i> = kegg)
.SH SYNOPSIS
\fImetpa_enrich_dataframe(data, metpa,
    <i>log2FC</i> = log2(FC),
    <i>id</i> = kegg)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBmetpa\fB \fR\- . 
.PP
.PP
\fBlog2FC\fB \fR\- log2(FC). 
.PP
.PP
\fBid\fB \fR\- kegg. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metpa_enrich_dataframe at metpa_enrich.R:line 46
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2024
