.TH METPA_ENRICH_DATAFRAME 1 2026-Jan "" "do enrichment based on the metpa background model"
.SH NAME
metpa_enrich_dataframe \- metpa_enrich_dataframe(data, metpa,
    <i>log2FC</i> = <span style='color: brown;'><strong>'log2(FC)'</strong></span>,
    <i>id</i> = <span style='color: brown;'><strong>'kegg'</strong></span>)
.SH SYNOPSIS
\fImetpa_enrich_dataframe(data, metpa,
    <i>log2FC</i> = <span style='color: brown;'><strong>'log2(FC)'</strong></span>,
    <i>id</i> = <span style='color: brown;'><strong>'kegg'</strong></span>)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . the kegg idset data, should be a dataframe object.
.PP
.PP
\fBmetpa\fB \fR\- . 
.PP
.PP
\fBlog2FC\fB \fR\- 'log2(FC)'. a character vector of the dataframe field name,
for get the log2 fold change value for rendering the colors
of the elements on the pathway map.
.PP
.PP
\fBid\fB \fR\- 'kegg'. a character vector of the dataframe field name, for
indicates that which column value should be used as the kegg
idset for run the enrichment analysis.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metpa_enrich_dataframe at metpa_enrich.R:line 56
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
