.TH METPA_BACKGROUND 1 2023-Feb "" "Create metpa background model for LCMS analysis"
.SH NAME
metpa_background \- metpa_background(metpa)
.SH SYNOPSIS
\fImetpa_background(metpa)\fR
.SH OPTIONS
.PP
\fBmetpa\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metpa_background at metpa.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
