.TH METPA_ENRICH_IDS 1 2026-Feb "" "metpa_enrich_ids"
.SH NAME
metpa_enrich_ids \- metpa_enrich_ids(data, metpa)
.SH SYNOPSIS
\fImetpa_enrich_ids(data, metpa)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBmetpa\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metpa_enrich_ids at metpa_enrich.R:line 33
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
