.TH NCBI_ASSEMBLY_FTP 1 2026-Feb "" "Do ftp download of the ncbi genbank assembly file."
.SH NAME
ncbi_assembly_ftp \- ncbi_assembly_ftp(ref,
    <i>download.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>overrides</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIncbi_assembly_ftp(ref,
    <i>download.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>overrides</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBref\fB \fR\- . 
.PP
.PP
\fBdownload.dir\fB \fR\- './'. 
.PP
.PP
\fBoverrides\fB \fR\- TRUE. overrides the local existed file.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.ncbi_assembly_ftp at ftp.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
