.TH NCBI_ASSEMBLY_FTP 1 2025-Jan "" "ncbi_assembly_ftp"
.SH NAME
ncbi_assembly_ftp \- ncbi_assembly_ftp(id)
.SH SYNOPSIS
\fIncbi_assembly_ftp(id)\fR
.SH OPTIONS
.PP
\fBid\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.ncbi_assembly_ftp at ftp.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
