.TH REFERENCE_GENOME 1 2026-Feb "" "get genbank reference genome accession id"
.SH NAME
reference_genome \- reference_genome(ncbi.taxid)
.SH SYNOPSIS
\fIreference_genome(ncbi.taxid)\fR
.SH OPTIONS
.PP
\fBncbi.taxid\fB \fR\- . 
.PP
.SH VALUE
.PP
a list of the reference assembly data list
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.reference_genome at get_genbank.R:line 55
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
