.TH SCAN_MOTIFS_INTERNAL 1 2026-7月 "" "scan_motifs_internal"
.SH NAME
scan_motifs_internal \- scan_motifs_internal(family.name, seqs,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>pval.cutoff</i> = <span style='color: green;'>0.05</span>,
    <i>minW</i> = <span style='color: green;'>0.85</span>,
    <i>top</i> = <span style='color: green;'>3</span>,
    <i>permutation</i> = <span style='color: green;'>2500</span>,
    <i>sequential</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIscan_motifs_internal(family.name, seqs,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>pval.cutoff</i> = <span style='color: green;'>0.05</span>,
    <i>minW</i> = <span style='color: green;'>0.85</span>,
    <i>top</i> = <span style='color: green;'>3</span>,
    <i>permutation</i> = <span style='color: green;'>2500</span>,
    <i>sequential</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBfamily.name\fB \fR\- . 
.PP
.PP
\fBseqs\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBpval.cutoff\fB \fR\- 0.05. 
.PP
.PP
\fBminW\fB \fR\- 0.85. 
.PP
.PP
\fBtop\fB \fR\- 3. 
.PP
.PP
\fBpermutation\fB \fR\- 2500. 
.PP
.PP
\fBsequential\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.scan_motifs_internal at scan_motifs.R:line 124
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
