.TH SCAN_MOTIFS 1 2026-4月 "" "Make motif site search in parallel"
.SH NAME
scan_motifs \- scan_motifs(db, seqs,
    <i>identities.cutoff</i> = <span style='color: green;'>0.8</span>,
    <i>minW</i> = <span style='color: green;'>0.85</span>,
    <i>top</i> = <span style='color: green;'>3</span>,
    <i>permutation</i> = <span style='color: green;'>2500</span>,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>)
.SH SYNOPSIS
\fIscan_motifs(db, seqs,
    <i>identities.cutoff</i> = <span style='color: green;'>0.8</span>,
    <i>minW</i> = <span style='color: green;'>0.85</span>,
    <i>top</i> = <span style='color: green;'>3</span>,
    <i>permutation</i> = <span style='color: green;'>2500</span>,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>)\fR
.SH OPTIONS
.PP
\fBdb\fB \fR\- . the file path to the motif PWM database
.PP
.PP
\fBseqs\fB \fR\- . the file path to the TSS upstream site for make motif site matches
.PP
.PP
\fBidentities.cutoff\fB \fR\- 0.8. 
.PP
.PP
\fBminW\fB \fR\- 0.85. 
.PP
.PP
\fBtop\fB \fR\- 3. 
.PP
.PP
\fBpermutation\fB \fR\- 2500. 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.SH VALUE
.PP
a dataframe of the motif site matches result
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.scan_motifs at scan_motifs.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
