.TH TAXONOMY_SEARCH 1 2026-Feb "" "get ncbi taxonomy id based on a given scientific name"
.SH NAME
taxonomy_search \- taxonomy_search(name)
.SH SYNOPSIS
\fItaxonomy_search(name)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . a character vector of the scientific name for
run taxonomy query.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.taxonomy_search at eutils.R:line 28
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
