.TH TAXONOMY_SEARCH 1 2023-May "" "taxonomy_search"
.SH NAME
taxonomy_search \- taxonomy_search(name)
.SH SYNOPSIS
\fItaxonomy_search(name)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.taxonomy_search at eutils.R:line 19
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
