.TH UNIFY_MAPID 1 2025-Dec "" "unify the kegg map id as reference map id"
.SH NAME
unify_mapid \- unify_mapid(x)
.SH SYNOPSIS
\fIunify_mapid(x)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . the kegg map id, maybe in organism species related pathway map id, example as ``hsaxxxxxx``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.unify_mapid at localRenderMap.R:line 78
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
