.TH UNION_RENDER 1 2025-Aug "" "visual plot of the multiple omics union data"
.SH NAME
union_render \- union_render(union.data,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>id</i> = <span style='color: brown;'><strong>'KEGG'</strong></span>,
    <i>compound</i> = <span style='color: brown;'><strong>'compound'</strong></span>,
    <i>gene</i> = <span style='color: brown;'><strong>'gene'</strong></span>,
    <i>protein</i> = <span style='color: brown;'><strong>'protein'</strong></span>,
    <i>text.color</i> = <span style='color: #FFFFFF;'><strong>'white'</strong></span>,
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIunion_render(union.data,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>id</i> = <span style='color: brown;'><strong>'KEGG'</strong></span>,
    <i>compound</i> = <span style='color: brown;'><strong>'compound'</strong></span>,
    <i>gene</i> = <span style='color: brown;'><strong>'gene'</strong></span>,
    <i>protein</i> = <span style='color: brown;'><strong>'protein'</strong></span>,
    <i>text.color</i> = <span style='color: #FFFFFF;'><strong>'white'</strong></span>,
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBunion.data\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBid\fB \fR\- 'KEGG'. specific the column name of the kegg id in the input dataframe
.PP
.PP
\fBcompound\fB \fR\- 'compound'. specific the column name of the metabolite highlights information in the input dataframe
.PP
.PP
\fBgene\fB \fR\- 'gene'. specific the column name of the gene highlights information in the input dataframe
.PP
.PP
\fBprotein\fB \fR\- 'protein'. specific the column name of the protein highliths information
.PP
.PP
\fBtext.color\fB \fR\- 'white'. set the label text color on the kegg pathway map
.PP
.PP
\fBkegg.maps\fB \fR\- NULL. 
.PP
.SH DETAILS
.PP
about the highlight information, seed the parser function [parse.highlight_tuples](https://gcmodeller.org/vignettes/kegg_kit/report.utils/parse.highlight_tuples.html).
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.union_render at union_render.R:line 15
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2025
