.TH UNION_RENDER 1 2024-May "" "visual plot of the multiple omics union data"
.SH NAME
union_render \- union_render(union.data,
    <i>outputdir</i> = ./,
    <i>id</i> = KEGG,
    <i>compound</i> = compound,
    <i>gene</i> = gene,
    <i>protein</i> = protein,
    <i>text.color</i> = white,
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIunion_render(union.data,
    <i>outputdir</i> = ./,
    <i>id</i> = KEGG,
    <i>compound</i> = compound,
    <i>gene</i> = gene,
    <i>protein</i> = protein,
    <i>text.color</i> = white,
    <i>kegg.maps</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBunion.data\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBid\fB \fR\- KEGG. 
.PP
.PP
\fBcompound\fB \fR\- compound. 
.PP
.PP
\fBgene\fB \fR\- gene. 
.PP
.PP
\fBprotein\fB \fR\- protein. 
.PP
.PP
\fBtext.color\fB \fR\- white. 
.PP
.PP
\fBkegg.maps\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.union_render at union_render.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2024
