.TH URL.SEARCH_TAXONOMY 1 2026-2月 "" "eutils web api"
.SH NAME
url.search_taxonomy \- url.search_taxonomy(name)
.SH SYNOPSIS
\fIurl.search_taxonomy(name)\fR
.SH DESCRIPTION
.PP
helper function for create the url for run taxonomy data query
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.url.search_taxonomy at eutils.R:line 19
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2026
