.TH URL.SEARCH_TAXONOMY 1 2023-6月 "" "url.search_taxonomy"
.SH NAME
url.search_taxonomy \- url.search_taxonomy(name)
.SH SYNOPSIS
\fIurl.search_taxonomy(name)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.url.search_taxonomy at eutils.R:line 15
.PP
.SH COPYRIGHT
Copyright © xieguigang, GPL3 Licensed 2023
