.\" man page create by R# package system.
.TH LINQ 1 2020-12-15 "all" "all"
.SH NAME
all \- Are All Values True?
.SH SYNOPSIS
\fIall(\fBtest\fR as <generic> Object, 
\fBnarm\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Are All Values True?
 
 Given a set of logical vectors, are all of the values true?
.PP
.SH OPTIONS
.PP
\fBtest\fB \fR\- zero or more logical vectors. Other objects of zero 
 length are ignored, and the rest are coerced to logical ignoring any 
 class.
.PP
.PP
\fBnarm\fB \fR\- 
 logical. If true NA values are removed before the result is computed.

.PP
.SH VALUE
.PP
The value is a logical vector of length one.

 Let x denote the concatenation of all the logical vectors in ... 
 (after coercion), after removing NAs if requested by na.rm = TRUE.

 The value returned Is True If all Of the values In x are True 
 (including If there are no values), And False If at least one Of 
 the values In x Is False. Otherwise the value Is NA (which can 
 only occur If na.rm = False And ... contains no False values And 
 at least one NA value).
.PP
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
