.\" man page create by R# package system.
.TH LINQ 1 2020-12-15 "groupBy" "groupBy"
.SH NAME
groupBy \- 
.SH SYNOPSIS
\fIgroupBy(\fBsequence\fR as <generic> Object, 
\fBgetKey\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBsequence\fB \fR\- -
.PP
.PP
\fBgetKey\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
