.\" man page create by R# package system.
.TH LINQ 1 2020-11-02 "projectAs" "projectAs"
.SH NAME
projectAs \- 
.SH SYNOPSIS
\fIprojectAs(\fBsequence\fR as <generic> Object, 
\fBproject\fR as <generic> RFunction, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
