.\" man page create by R# package system.
.TH LINQ 1 2020-10-29 "which.max" "which.max"
.SH NAME
which.max \- 
.SH SYNOPSIS
\fIwhich.max(\fBsequence\fR as <generic> Object, 
\fBeval\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
