.\" man page create by R# package system.
.TH LINQ 1 2020-11-02 "which" "which"
.SH NAME
which \- The which test filter
.SH SYNOPSIS
\fIwhich(\fBsequence\fR as <generic> Object, 
\fBtest\fR as <generic> Object = \fB<NULL>\fR, 
\fBpipelineFilter\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
The which test filter
.PP
.SH OPTIONS
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
