.\" man page create by R# package system.
.TH UNIPROT 1 2000-1月 "uniprot_keywords" "uniprot_keywords"
.SH NAME
uniprot_keywords \- 
.SH SYNOPSIS
\fIuniprot_keywords(\fBuniprot\fR as any, 
\fBdb_xref\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
UniProt
.SH FILES
.PP
gseakit.dll
.PP
