.\" man page create by R# package system.
.TH MIRNA 1 2000-1月 "blastn_filter" "blastn_filter"
.SH NAME
blastn_filter \- 
.SH SYNOPSIS
\fIblastn_filter(\fBblastn\fR as any, 
\fBeCutoff\fR as double = 5, 
\fBseedStart\fR as integer = 2, 
\fBseedEnd\fR as integer = 13, 
\fBmaxSeedMm\fR as integer = 2, 
\fBmaxTotalMm\fR as integer = 8, 
\fBmaxGu\fR as integer = 7, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
miRNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
