.\" man page create by R# package system.
.TH MIRNA 1 2000-1月 "intersect_targets" "intersect_targets"
.SH NAME
intersect_targets \- High-confidence intersection (psRNATarget ∩ TargetFinder)
.SH SYNOPSIS
\fIintersect_targets(\fBpsRNATarget\fR as any, 
\fBTargetFinder\fR as any, 
\fBsite_tolerance\fR as integer = 3, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
High-confidence intersection (psRNATarget ∩ TargetFinder)
.PP
.SH OPTIONS
.PP
\fBpsRNATarget\fB \fR\- -. 
.PP
.PP
\fBTargetFinder\fB \fR\- -. 
.PP
.PP
\fBsite_tolerance\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
miRNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
