.\" man page create by R# package system.
.TH MIRNA 1 2000-1月 "miRNA_targets" "miRNA_targets"
.SH NAME
miRNA_targets \- 
.SH SYNOPSIS
\fImiRNA_targets(\fBmapper\fR as <generic> miRNAMapper, 
\fBmiRNAs\fR as any, 
\fBtargets\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
miRNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
