.\" man page create by R# package system.
.TH MIRNA 1 2000-1月 "mirna_blastn" "mirna_blastn"
.SH NAME
mirna_blastn \- 
.SH SYNOPSIS
\fImirna_blastn(\fBmirna\fR as any, 
\fBgeneset\fR as any, 
\fBncbi_blast\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBmirna\fB \fR\- -. 
.PP
.PP
\fBgeneset\fB \fR\- -. 
.PP
.PP
\fBncbi_blast\fB \fR\- folder dir path for the ncbi blast+. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
miRNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
