.\" man page create by R# package system.
.TH RCONVERSION 1 2020-10-29 "as.character" "as.character"
.SH NAME
as.character \- 
.SH SYNOPSIS
\fIas.character(\fBobj\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
