.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-02 "as.Date" "as.Date"
.SH NAME
as.Date \- 
.SH SYNOPSIS
\fIas.Date(\fBobj\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
