.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-09 "as.list" "as.list"
.SH NAME
as.list \- Cast the raw dictionary object to R# list object
.SH SYNOPSIS
\fIas.list(\fBobj\fR as <generic> Object, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Cast the raw dictionary object to R# list object
.PP
.SH OPTIONS
.PP
\fBobj\fB \fR\- -
.PP
.PP
\fBargs\fB \fR\- 
 for dataframe type:
 
 + \fBbyrow\fR: logical, default is FALSE, means cast dataframe to list directly by column hash table values
 + \fBnames\fR: character, the column names that will be used as the list names

.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
