.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-02 "as.logical" "as.logical"
.SH NAME
as.logical \- 
.SH SYNOPSIS
\fIas.logical(\fBobj\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
