.\" man page create by R# package system.
.TH RCONVERSION 1 2020-12-15 "as.numeric" "as.numeric"
.SH NAME
as.numeric \- Numeric Vectors
.SH SYNOPSIS
\fIas.numeric(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Numeric Vectors
 
 Creates or coerces objects of type "numeric". is.numeric is a more 
 general test of an object being interpretable as numbers.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- object to be coerced or tested.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH DETAILS
.PP
\fBNULL\fR will be treated as ZERO based on the rule of VisualBasic runtime conversion.
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
