.\" man page create by R# package system.
.TH RCONVERSION 1 2020-10-29 "as.object" "as.object"
.SH NAME
as.object \- Cast .NET object to R# object
.SH SYNOPSIS
\fIas.object(\fBobj\fR as <generic> Object);\fR
.SH DESCRIPTION
.PP
Cast .NET object to R# object
.PP
.SH OPTIONS
.PP
\fBobj\fB \fR\- -
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
