.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-02 "as.pipeline" "as.pipeline"
.SH NAME
as.pipeline \- running pipeline function in linq pipeline mode
.SH SYNOPSIS
\fIas.pipeline(\fBseq\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
running pipeline function in linq pipeline mode
.PP
.SH OPTIONS
.PP
\fBseq\fB \fR\- any kind of object sequence in R# environment
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
