.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-09 "as.raw" "as.raw"
.SH NAME
as.raw \- cast any R# object to raw buffer
.SH SYNOPSIS
\fIas.raw(\fBobj\fR as <generic> Object, 
\fBencoding\fR as <integer> Encodings = [UTF8WithoutBOM], 
\fBnetworkByteOrder\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
cast any R# object to raw buffer
.PP
.SH OPTIONS
.PP
\fBobj\fB \fR\- numeric values or character vector
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
