.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-02 "ctype" "ctype"
.SH NAME
ctype \- try to cast type class of the given data sequence
.SH SYNOPSIS
\fIctype(\fBany\fR as <generic> Object, 
\fBtype\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
try to cast type class of the given data sequence
.PP
.SH OPTIONS
.PP
\fBany\fB \fR\- -
.PP
.PP
\fBtype\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
