.\" man page create by R# package system.
.TH RCONVERSION 1 2020-10-29 "is.character" "is.character"
.SH NAME
is.character \- 
.SH SYNOPSIS
\fIis.character(\fBobj\fR as <generic> Object);\fR
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
