.\" man page create by R# package system.
.TH RCONVERSION 1 2020-11-02 "is.character" "is.character"
.SH NAME
is.character \- Character Vectors
.SH SYNOPSIS
\fIis.character(\fBx\fR as <generic> Object);\fR
.SH DESCRIPTION
.PP
Character Vectors
 
 Create or test for objects of type "character".
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- object to be coerced or tested.
.PP
.SH VALUE
.PP
is.character returns TRUE or FALSE depending on 
 whether its argument is of character type or not.
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
