.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "as.abundance_matrix" "as.abundance_matrix"
.SH NAME
as.abundance_matrix \- 
.SH SYNOPSIS
\fIas.abundance_matrix(..., 
\fBnormalized\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
