.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "as.bloom_filter" "as.bloom_filter"
.SH NAME
as.bloom_filter \- cast the genomics sequence as kmer based bloom filter model
.SH SYNOPSIS
\fIas.bloom_filter(\fBgenomics\fR as any, 
\fBncbi_taxid\fR as integer = 0, 
\fBk\fR as integer = 35, 
\fBfpr\fR as double = 1E-05, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
cast the genomics sequence as kmer based bloom filter model
.PP
.SH OPTIONS
.PP
\fBgenomics\fB \fR\- -. 
.PP
.PP
\fBncbi_taxid\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBfpr\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
