.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "bayes_background" "bayes_background"
.SH NAME
bayes_background \- 
.SH SYNOPSIS
\fIbayes_background(\fBkmers_db\fR as any, 
\fBncbi_taxonomy\fR as <generic> NcbiTaxonomyTree, 
\fBseq_id\fR as <generic> SequenceCollection, 
\fBrank\fR as any = ["species","genus","family","order","class","phylum","superkingdom"], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
