.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "bayes_estimate" "bayes_estimate"
.SH NAME
bayes_estimate \- 
.SH SYNOPSIS
\fIbayes_estimate(\fBbackground\fR as <generic> KmerBackground, 
\fBtaxonomyDB\fR as <generic> NcbiTaxonomyTree, 
\fBseq_ids\fR as <generic> SequenceCollection);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
