.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "bayes_abundance" "bayes_abundance"
.SH NAME
bayes_abundance \- quantify of the metagenome community via kmers and bayes method
.SH SYNOPSIS
\fIbayes_abundance(\fBdb\fR as <generic> DatabaseReader, 
\fBbayes\fR as <generic> AbundanceEstimate, 
\fBreads\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
quantify of the metagenome community via kmers and bayes method
.PP
.SH OPTIONS
.PP
\fBdb\fB \fR\- -. 
.PP
.PP
\fBbayes\fB \fR\- -. 
.PP
.PP
\fBreads\fB \fR\- all reads data in one sample. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
