.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "bloom_filters" "bloom_filters"
.SH NAME
bloom_filters \- 
.SH SYNOPSIS
\fIbloom_filters(\fBrepo_dir\fR as string, 
\fBncbi_taxonomy\fR as <generic> NcbiTaxonomyTree, 
\fBmin_supports\fR as double = 0.35, 
\fBcoverage\fR as double = 0.5);\fR
.SH OPTIONS
.PP
\fBrepo_dir\fB \fR\- -. 
.PP
.PP
\fBncbi_taxonomy\fB \fR\- -. 
.PP
.PP
\fBmin_supports\fB \fR\- min supports for LCA, recommended 0.35 as threshold. 
.PP
.PP
\fBcoverage\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
