.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "filter_hostId" "filter_hostId"
.SH NAME
filter_hostId \- 
.SH SYNOPSIS
\fIfilter_hostId(\fBkraken_output\fR as any, 
\fBhost_id\fR as any, 
\fBcoverage\fR as double = 0.999, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBkraken_output\fB \fR\- 
 quantification table which could be read from file via the function: \fBparse_kraken_report\fR.
. 
.PP
.PP
\fBhost_id\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
