.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "filter_classification" "filter_classification"
.SH NAME
filter_classification \- 
.SH SYNOPSIS
\fIfilter_classification(\fBkraken_output\fR as any, 
\fBtaxids\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
