.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "filter_reads" "filter_reads"
.SH NAME
filter_reads \- usually be apply for host removal
.SH SYNOPSIS
\fIfilter_reads(\fBkraken_output\fR as any, 
\fBreads\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
usually be apply for host removal
.PP
.SH OPTIONS
.PP
\fBkraken_output\fB \fR\- host reads information data. 
.PP
.PP
\fBreads\fB \fR\- the raw reads fastq data. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
read result with host reads removals
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
