.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "host_classification" "host_classification"
.SH NAME
host_classification \- 
.SH SYNOPSIS
\fIhost_classification(\fBkraken_output\fR as any, 
\fBhost_taxids\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
