.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "kraken_seqs" "kraken_seqs"
.SH NAME
kraken_seqs \- extract gene/genomics sequences from genbank file for kraken2 sequence classification
.SH SYNOPSIS
\fIkraken_seqs(\fBgb\fR as any, 
\fBgeneset\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
extract gene/genomics sequences from genbank file for kraken2 sequence classification
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
