.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "make_classify" "make_classify"
.SH NAME
make_classify \- just make reads classify of the fastq reads based on the k-mer distribution
.SH SYNOPSIS
\fImake_classify(\fBdb\fR as <generic> DatabaseReader, 
\fBreads\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
just make reads classify of the fastq reads based on the k-mer distribution
.PP
.SH OPTIONS
.PP
\fBdb\fB \fR\- -. 
.PP
.PP
\fBreads\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
apply this method for do host sequence filter
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
