.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "make_vector" "make_vector"
.SH NAME
make_vector \- make vector embedding
.SH SYNOPSIS
\fImake_vector(\fBbloom\fR as <generic> BloomVectorizer, 
\fBx\fR as any, 
\fBfile\fR as any = \fB<NULL>\fR, 
\fBas_matrix\fR as boolean = FALSE, 
\fBtest\fR as integer = -1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make vector embedding
.PP
.SH OPTIONS
.PP
\fBbloom\fB \fR\- -. 
.PP
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
