.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "taxonomy_expression" "taxonomy_expression"
.SH NAME
taxonomy_expression \- 
.SH SYNOPSIS
\fItaxonomy_expression(\fBid\fR as any, 
\fBexpr\fR as any, 
\fBtaxdata\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
