.\" man page create by R# package system.
.TH KMERS 1 2000-Jan "write.kmers_background" "write.kmers_background"
.SH NAME
write.kmers_background \- 
.SH SYNOPSIS
\fIwrite.kmers_background(\fBbayes\fR as <generic> KmerBackground, 
\fBdirpath\fR as string);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
metagenomics_kit.dll
.PP
