.\" man page create by R# package system.
.TH DATAFRAME 4 2020-10-29 "append.row" "append.row"
.SH NAME
append.row \- 
.SH SYNOPSIS
\fIappend.row(\fBtable\fR as <generic> File, 
\fBrow\fR as <generic> RowObject);\fR
.SH SEE ALSO
dataframe
.SH FILES
.PP
R.base.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
