.\" man page create by R# package system.
.TH DATAFRAME 4 2020-10-29 "append.cells" "append.cells"
.SH NAME
append.cells \- 
.SH SYNOPSIS
\fIappend.cells(\fBrow\fR as <generic> RowObject, 
\fBcells\fR as <generic> Array);\fR
.SH SEE ALSO
dataframe
.SH FILES
.PP
R.base.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
