.\" man page create by R# package system.
.TH DATAFRAME 4 2020-12-15 "column" "column"
.SH NAME
column \- raw dataframe get column data by index
.SH SYNOPSIS
\fIcolumn(\fBfile\fR as <generic> File, 
\fBindex\fR as integer);\fR
.SH DESCRIPTION
.PP
raw dataframe get column data by index
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.PP
\fBindex\fB \fR\- -
.PP
.SH SEE ALSO
dataframe
.SH FILES
.PP
R.base.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
