.\" man page create by R# package system.
.TH HMMER 1 2000-1月 "hmmer_search" "hmmer_search"
.SH NAME
hmmer_search \- run the HMMER profile HMM search for protein function annotation
.SH SYNOPSIS
\fIhmmer_search(\fBhmmer\fR as <generic> ProteinAnnotator, 
\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run the HMMER profile HMM search for protein function annotation
.PP
.SH OPTIONS
.PP
\fBhmmer\fB \fR\- 
 a [ProteinAnnotator](cref:T:SMRUCC.genomics.Analysis.SequenceTools.HMMER.ProteinAnnotator) object that contains the loaded HMMER3 
 profile models, which is created by the \fBload_hmmer\fR api.
. 
.PP
.PP
\fBx\fB \fR\- 
 a protein fasta sequence collection for run the HMMER search, which can 
 be a [FastaFile](cref:T:SMRUCC.genomics.SequenceModel.FASTA.FastaFile) object, 
 a collection of the 
 [FastaSeq](cref:T:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq) object, or a 
 character vector of the raw sequence data.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a lazy pipeline collection of the [AnnotationResult](cref:T:SMRUCC.genomics.Analysis.SequenceTools.HMMER.AnnotationResult) domain 
 annotation result, one result element for each of the profile HMM hit 
 that found in the input protein sequence collection;
 
 this function returns NULL if the input sequence data can not be cast to 
 a fasta sequence collection.
.PP
.SH SEE ALSO
hmmer
.SH FILES
.PP
seqtoolkit.dll
.PP
