.\" man page create by R# package system.
.TH HMMER 1 2000-1月 "parse_kofamscan" "parse_kofamscan"
.SH NAME
parse_kofamscan \- Parse the kofamscan table output
.SH SYNOPSIS
\fIparse_kofamscan(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Parse the kofamscan table output
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the input source: a file path of the kofamscan annotation table output 
 file, or a file stream object of the target table file.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a lazy pipeline collection of the [KOFamScan](cref:T:SMRUCC.genomics.Analysis.SequenceTools.HMMER.KOFamScan) KEGG orthology 
 annotation result record object;
 
 this function returns a R# error message object if the given file can 
 not be opened for read.
.PP
.SH SEE ALSO
hmmer
.SH FILES
.PP
seqtoolkit.dll
.PP
