<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\runtime\sciBASIC#\Data_science\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\core\Bio.Assembly\biocore-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\engine\CompilerServices\CompilerServices.NET5.vbproj" />
    <ProjectReference Include="..\..\..\engine\IO\GCMarkupLanguage\GCMarkupXML.NET5.vbproj" />
    <ProjectReference Include="..\..\..\engine\Model\Model.Core.NET5.vbproj" />
    <ProjectReference Include="..\FBA.Core\FBA.Core.NET5.vbproj" />
  </ItemGroup>

</Project>
