.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "assembling.TRN" "assembling.TRN"
.SH NAME
assembling.TRN \- add transcription regulation network information for the virtual cell model
.SH SYNOPSIS
\fIassembling.TRN(\fBmodel\fR as <generic> CellularModule, 
\fBregulations\fR as <generic> RegulationFootprint[]);\fR
.SH DESCRIPTION
.PP
add transcription regulation network information for the virtual cell model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBregulations\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
