.\" man page create by R# package system.
.TH COMPILER 1 2000-Jan "assembling.genome" "assembling.genome"
.SH NAME
assembling.genome \- create genome framework for the virtual cell model
.SH SYNOPSIS
\fIassembling.genome(\fBreplicons\fR as list[<generic> File], 
\fBgeneKO\fR as list[string], 
\fBlociAsLocus_tag\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
create genome framework for the virtual cell model
.PP
.SH OPTIONS
.PP
\fBreplicons\fB \fR\- -. 
.PP
.PP
\fBgeneKO\fB \fR\- -. 
.PP
.PP
\fBlociAsLocus_tag\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
