.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "compile_biocyc" "compile_biocyc"
.SH NAME
compile_biocyc \- Build a specific organism metacyc database as virtual cell model
.SH SYNOPSIS
\fIcompile_biocyc(\fBbiocyc\fR as <generic> Workspace, 
\fBlogfile\fR as string = "./gcc.log");\fR
.SH DESCRIPTION
.PP
Build a specific organism metacyc database as virtual cell model
.PP
.SH OPTIONS
.PP
\fBbiocyc\fB \fR\- -. 
.PP
.PP
\fBlogfile\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
