.\" man page create by R# package system.
.TH COMPILER 1 2000-Jan "compile.biocyc" "compile.biocyc"
.SH NAME
compile.biocyc \- Build a specific organism metacyc database as virtual cell model
.SH SYNOPSIS
\fIcompile.biocyc(\fBbiocyc\fR as <generic> Workspace, 
\fBgenomes\fR as list[<generic> File], 
\fBlogfile\fR as string = "./gcc.log");\fR
.SH DESCRIPTION
.PP
Build a specific organism metacyc database as virtual cell model
.PP
.SH OPTIONS
.PP
\fBbiocyc\fB \fR\- -. 
.PP
.PP
\fBgenomes\fB \fR\- -. 
.PP
.PP
\fBlogfile\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
