.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "compile.biocyc" "compile.biocyc"
.SH NAME
compile.biocyc \- 
.SH SYNOPSIS
\fIcompile.biocyc(\fBbiocyc\fR as <generic> Workspace, 
\fBgenomes\fR as list[<generic> File], 
\fBlogfile\fR as string = "./gcc.log");\fR
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
