.\" man page create by R# package system.
.TH COMPILER 1 2000-01-01 "geneKO.maps" "geneKO.maps"
.SH NAME
geneKO.maps \- create a list that map gene id to KO id.
.SH SYNOPSIS
\fIgeneKO.maps(\fBdata\fR as any, 
\fBKOcol\fR as string = "KO", 
\fBgeneIDcol\fR as string = "ID", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a list that map gene id to KO id.
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- any kind of dataframe dataset.. 
.PP
.PP
\fBKOcol\fB \fR\- the column name for get KO term id. 
.PP
.PP
\fBgeneIDcol\fB \fR\- the column name for get gene id. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
