.\" man page create by R# package system.
.TH COMPILER 1 2000-Jan "kegg" "kegg"
.SH NAME
kegg \- create kegg repository arguments
.SH SYNOPSIS
\fIkegg(\fBcompounds\fR as string, 
\fBmaps\fR as string, 
\fBreactions\fR as string, 
\fBglycan2Cpd\fR as list[string]);\fR
.SH DESCRIPTION
.PP
create kegg repository arguments
.PP
.SH OPTIONS
.PP
\fBcompounds\fB \fR\- A directory path which the folder contains the compounds data models.. 
.PP
.PP
\fBmaps\fB \fR\- A directory path which the folder contains the kegg reference map data.. 
.PP
.PP
\fBreactions\fB \fR\- -. 
.PP
.PP
\fBglycan2Cpd\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
