.\" man page create by R# package system.
.TH COMPILER 1 2000-01-01 "open.biocyc" "open.biocyc"
.SH NAME
open.biocyc \- open a directory path as the biocyc workspace
.SH SYNOPSIS
\fIopen.biocyc(\fBrepo\fR as string);\fR
.SH DESCRIPTION
.PP
open a directory path as the biocyc workspace
.PP
.SH OPTIONS
.PP
\fBrepo\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
