.\" man page create by R# package system.
.TH COMPILER 1 2000-01-01 "vcell.markup" "vcell.markup"
.SH NAME
vcell.markup \- Save the virtual cell data model in XML file format.
.SH SYNOPSIS
\fIvcell.markup(\fBmodel\fR as <generic> CellularModule, 
\fBgenomes\fR as list[<generic> File], 
\fBKEGG\fR as <generic> RepositoryArguments, 
\fBregulations\fR as <generic> RegulationFootprint[], 
\fBlociAsLocus_tag\fR as boolean = FALSE, 
\fBlogfile\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Save the virtual cell data model in XML file format.
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBgenomes\fB \fR\- -. 
.PP
.PP
\fBKEGG\fB \fR\- -. 
.PP
.PP
\fBregulations\fB \fR\- -. 
.PP
.PP
\fBlociAsLocus_tag\fB \fR\- -. 
.PP
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
