.\" man page create by R# package system.
.TH ANNOTATION.GENBANK_KIT 4 2000-01-01 "populate.genbank" "populate.genbank"
.SH NAME
populate.genbank \- populate a list of genbank data objects from a given list of files or stream.
.SH SYNOPSIS
\fIpopulate.genbank(\fBfiles\fR as <generic> Object, 
\fBautoClose\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
populate a list of genbank data objects from a given list of files or stream.
.PP
.SH OPTIONS
.PP
\fBfiles\fB \fR\- a list of files or file stream
.PP
.PP
\fBautoClose\fB \fR\- 
 auto close of the @\fBT:System.IO.Stream\fR if the **`files`** contains stream object?

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
annotation.genbank_kit
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © SMRUCC/GCModeller 2020
