.\" man page create by R# package system.
.TH COMPARATIVE.PLASMID 1 2000-1月 "Plasmid.Partitioning" "Plasmid.Partitioning"
.SH NAME
Plasmid.Partitioning \- 
.SH SYNOPSIS
\fIPlasmid.Partitioning(\fBBesthits\fR as <generic> SpeciesBesthit, 
\fBCdsInfo\fR as <generic> GeneTable[], 
\fBFasta\fR as <generic> FastaSeq);\fR
.SH SEE ALSO
Comparative.Plasmid
.SH FILES
.PP
seqtoolkit.dll
.PP
