.\" man page create by R# package system.
.TH COMPARATIVE.PLASMID 1 2000-1月 "Plasmid.DeltaMatrix" "Plasmid.DeltaMatrix"
.SH NAME
Plasmid.DeltaMatrix \- 
.SH SYNOPSIS
\fIPlasmid.DeltaMatrix(\fBpartitions\fR as <generic> IEnumerable`1);\fR
.SH SEE ALSO
Comparative.Plasmid
.SH FILES
.PP
seqtoolkit.dll
.PP
