.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-01-01 "read.regprecise" "read.regprecise"
.SH NAME
read.regprecise \- load regprecise database from a given file.
.SH SYNOPSIS
\fIread.regprecise(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
load regprecise database from a given file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
phenotype_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
