.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-01-01 "write.regulations" "write.regulations"
.SH NAME
write.regulations \- save the regulation network data file.
.SH SYNOPSIS
\fIwrite.regulations(\fBregulationFootprints\fR as <generic> Object, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the regulation network data file.
.PP
.SH OPTIONS
.PP
\fBregulationFootprints\fB \fR\- -
.PP
.PP
\fBfile$\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
phenotype_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
