.\" man page create by R# package system.
.TH IMMO 1 2000-1月 "make_omics_impute" "make_omics_impute"
.SH NAME
make_omics_impute \- 
.SH SYNOPSIS
\fImake_omics_impute(\fBmodel\fR as <generic> IMMOModel, 
\fBpreparedData\fR as <generic> PreparedData);\fR
.SH SEE ALSO
IMMO
.SH FILES
.PP
phenotype_kit.dll
.PP
