.\" man page create by R# package system.
.TH TRN.BUILDER 1 2000-Jan "read.footprints" "read.footprints"
.SH NAME
read.footprints \- read a footprint site model data file
.SH SYNOPSIS
\fIread.footprints(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read a footprint site model data file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
TRN.builder
.SH FILES
.PP
visualkit.dll
.PP
