.\" man page create by R# package system.
.TH REGPRECISE 1 2000-Jan "motif.raw" "motif.raw"
.SH NAME
motif.raw \- 
.SH SYNOPSIS
\fImotif.raw(\fBregprecise\fR as <generic> TranscriptionFactors);\fR
.SH SEE ALSO
regprecise
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBPSNovichkov@lbl.gov; <br />
                        rodionov@burnham.org\fR
