.\" man page create by R# package system.
.TH REGPRECISE 1 2000-Jan "read.regulome" "read.regulome"
.SH NAME
read.regulome \- 
.SH SYNOPSIS
\fIread.regulome(\fBxml\fR as string);\fR
.SH SEE ALSO
regprecise
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBPSNovichkov@lbl.gov; <br />
                        rodionov@burnham.org\fR
