.\" man page create by R# package system.
.TH R.EXECUTABLE.LOADER 1 2000-01-01 "run" "run"
.SH NAME
run \- 
.SH SYNOPSIS
\fIrun(\fBbase64\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBbase64\fB \fR\- 
 base64 string

.PP
.SH SEE ALSO
R.executable.loader
.SH FILES
.PP
R.code.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
