.\" man page create by R# package system.
.TH REPORT.UTILS 1 2000-1月 "render_kgml" "render_kgml"
.SH NAME
render_kgml \- 
.SH SYNOPSIS
\fIrender_kgml(\fBkgml\fR as <generic> pathway, 
\fBimages\fR as <generic> NodeRepresentation, 
\fBsize\fR as any = [3000,3000], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
report.utils
.SH FILES
.PP
kegg_kit.dll
.PP
