.\" man page create by R# package system.
.TH PROFILES 1 2000-Jan "compounds.pathway.profiles" "compounds.pathway.profiles"
.SH NAME
compounds.pathway.profiles \- Do statistics of the KEGG pathway profiles based on the given kegg id
.SH SYNOPSIS
\fIcompounds.pathway.profiles(\fBpathways\fR as list[<generic> Index`1], 
\fBcompounds\fR as string);\fR
.SH DESCRIPTION
.PP
Do statistics of the KEGG pathway profiles based on the given kegg id
.PP
.SH OPTIONS
.PP
\fBpathways\fB \fR\- The pathway compound reference index data. 
.PP
.PP
\fBcompounds\fB \fR\- The kegg compound id. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
kegg_kit.dll
.PP
