.\" man page create by R# package system.
.TH PROFILES 1 2000-Jan "flux.map.profiles" "flux.map.profiles"
.SH NAME
flux.map.profiles \- 
.SH SYNOPSIS
\fIflux.map.profiles(\fBflux\fR as any, 
\fBmaps\fR as <generic> MapRepository, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
profiles
.SH FILES
.PP
kegg_kit.dll
.PP
