.\" man page create by R# package system.
.TH PROFILES 1 2000-Jan "getProfileMapping" "getProfileMapping"
.SH NAME
getProfileMapping \- 
.SH SYNOPSIS
\fIgetProfileMapping(\fBmap\fR as <generic> Map[], 
\fBmapping\fR as list, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
profiles
.SH FILES
.PP
kegg_kit.dll
.PP
