.\" man page create by R# package system.
.TH PROFILES 1 2000-1月 "kegg.category_profiles" "kegg.category_profiles"
.SH NAME
kegg.category_profiles \- create kegg catalog profiles data table
.SH SYNOPSIS
\fIkegg.category_profiles(\fBprofiles\fR as list[integer]);\fR
.SH DESCRIPTION
.PP
create kegg catalog profiles data table
.PP
.SH OPTIONS
.PP
\fBprofiles\fB \fR\- -. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
kegg_kit.dll
.PP
