.\" man page create by R# package system.
.TH PROFILES 1 2000-Jan "KO.map.profiles" "KO.map.profiles"
.SH NAME
KO.map.profiles \- create KEGG map prfiles via a given KO id list.
.SH SYNOPSIS
\fIKO.map.profiles(\fBKO\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create KEGG map prfiles via a given KO id list.
.PP
.SH OPTIONS
.PP
\fBKO\fB \fR\- a character vector of KO id list.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
kegg_kit.dll
.PP
