.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "assembling.metabolic" "assembling.metabolic"
.SH NAME
assembling.metabolic \- 
.SH SYNOPSIS
\fIassembling.metabolic(\fBcell\fR as <generic> CellularModule, 
\fBgeneKO\fR as list[string], 
\fBrepo\fR as <generic> RepositoryArguments);\fR
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
