.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "assembling.TRN" "assembling.TRN"
.SH NAME
assembling.TRN \- 
.SH SYNOPSIS
\fIassembling.TRN(\fBmodel\fR as <generic> CellularModule, 
\fBregulations\fR as <generic> RegulationFootprint[]);\fR
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
