.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "geneKO.maps" "geneKO.maps"
.SH NAME
geneKO.maps \- 
.SH SYNOPSIS
\fIgeneKO.maps(\fBdata\fR as any, 
\fBKOcol\fR as string = "KO", 
\fBgeneIDcol\fR as string = "ID", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
