.\" man page create by R# package system.
.TH COMPILER 1 2000-1月 "vcell.markup" "vcell.markup"
.SH NAME
vcell.markup \- 
.SH SYNOPSIS
\fIvcell.markup(\fBmodel\fR as <generic> CellularModule, 
\fBgenomes\fR as list[<generic> File], 
\fBKEGG\fR as <generic> RepositoryArguments, 
\fBregulations\fR as <generic> RegulationFootprint[], 
\fBlociAsLocus_tag\fR as boolean = FALSE, 
\fBlogfile\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
compiler
.SH FILES
.PP
vcellkit.dll
.PP
