.\" man page create by R# package system.
.TH DNA_COMPARATIVE 1 2000-01-01 "seq.dist" "seq.dist"
.SH NAME
seq.dist \- Create a distance matrix for a given sequence collection
.SH SYNOPSIS
\fIseq.dist(\fBseqs\fR as <generic> Object);\fR
.SH DESCRIPTION
.PP
Create a distance matrix for a given sequence collection
.PP
.SH OPTIONS
.PP
\fBseqs\fB \fR\- -
.PP
.SH SEE ALSO
DNA_Comparative
.SH FILES
.PP
comparative_genomics.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
