.\" man page create by R# package system.
.TH KEGG.REPOSITORY 0 2000-01-01 "fetch.kegg_organism" "fetch.kegg_organism"
.SH NAME
fetch.kegg_organism \- 
.SH SYNOPSIS
\fIfetch.kegg_organism(\fBresource\fR as string = "http://www.kegg.jp/kegg/catalog/org_list.html", 
\fBtype\fR as integer = 0);\fR
.SH OPTIONS
.PP
\fBresource$\fB \fR\- -
.PP
.PP
\fBtype\fB \fR\- 
 0. all
 1. prokaryote
 2. eukaryotes

.PP
.SH SEE ALSO
kegg.repository
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
