.\" man page create by R# package system.
.TH KEGG.REPOSITORY 1 2000-01-01 "load.reactions" "load.reactions"
.SH NAME
load.reactions \- load reaction data from the given kegg reaction data repository
.SH SYNOPSIS
\fIload.reactions(\fBrepository\fR as string);\fR
.SH DESCRIPTION
.PP
load reaction data from the given kegg reaction data repository
.PP
.SH OPTIONS
.PP
\fBrepository\fB \fR\- -
.PP
.SH SEE ALSO
kegg.repository
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
