.\" man page create by R# package system.
.TH KEGG.REPOSITORY 0 2000-01-01 "save.kegg_organism" "save.kegg_organism"
.SH NAME
save.kegg_organism \- 
.SH SYNOPSIS
\fIsave.kegg_organism(\fBorganism\fR as <generic> Prokaryote[], 
\fBfile\fR as string);\fR
.SH SEE ALSO
kegg.repository
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
