.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-Jan "category_profiles.plot" "category_profiles.plot"
.SH NAME
category_profiles.plot \- 
.SH SYNOPSIS
\fIcategory_profiles.plot(\fBprofiles\fR as <generic> CatalogProfiles, 
\fBtitle\fR as string = "KEGG Orthology Profiling", 
\fBaxis_title\fR as string = "Number Of Proteins", 
\fBsize\fR as any = "2300,2000", 
\fBtick\fR as double = -1, 
\fBcolors\fR as any = "#E41A1C,#377EB8,#4DAF4A,#984EA3,#FF7F00,#CECE00", 
\fBdpi\fR as integer = 300, 
\fBformat\fR as string = "F2", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
