.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-01-01 "category_profiles.heatmap" "category_profiles.heatmap"
.SH NAME
category_profiles.heatmap \- 
.SH SYNOPSIS
\fIcategory_profiles.heatmap(\fBprofile\fR as <generic> CatalogProfiles, 
\fBmatrix\fR as <generic> Matrix, 
\fBmapLevels\fR as integer = 64, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
