.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-Jan "classchange.plot" "classchange.plot"
.SH NAME
classchange.plot \- 
.SH SYNOPSIS
\fIclasschange.plot(\fBgenes\fR as any, 
\fBsize\fR as any = "3000,2400", 
\fBpadding\fR as any = "padding:250px 150px 300px 300px;", 
\fBbg\fR as any = "white", 
\fBcolorSet\fR as any = "Set1:c9", 
\fBshowLabel\fR as boolean = FALSE, 
\fBradius\fR as any = "15,50", 
\fBxlab\fR as string = "X", 
\fBorderByClass\fR as <integer> orders = [none], 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBgenes\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBpadding\fB \fR\- -. 
.PP
.PP
\fBbg\fB \fR\- -. 
.PP
.PP
\fBcolorSet\fB \fR\- -. 
.PP
.PP
\fBshowLabel\fB \fR\- -. 
.PP
.PP
\fBradius\fB \fR\- -. 
.PP
.PP
\fBxlab\fB \fR\- -. 
.PP
.PP
\fBorderByClass\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
