.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "color_bends" "color_bends"
.SH NAME
color_bends \- 
.SH SYNOPSIS
\fIcolor_bends(\fBmatrix\fR as <generic> Matrix, 
\fBcolorSet\fR as string = "RdYlGn:c8", 
\fBlevels\fR as integer = 25, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
