.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-01-01 "color_bends" "color_bends"
.SH NAME
color_bends \- map gene expressin data to color bends
.SH SYNOPSIS
\fIcolor_bends(\fBmatrix\fR as <generic> Matrix, 
\fBcolorSet\fR as string = "RdYlGn:c8", 
\fBlevels\fR as integer = 25, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
map gene expressin data to color bends
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- -. 
.PP
.PP
\fBcolorSet$\fB \fR\- -. 
.PP
.PP
\fBlevels\fB \fR\- -. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
