.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "dem.barplot" "dem.barplot"
.SH NAME
dem.barplot \- 
.SH SYNOPSIS
\fIdem.barplot(\fBsample\fR as any, 
\fBupName\fR as string = "up", 
\fBdownName\fR as string = "down", 
\fBsize\fR as any = "2700,2400", 
\fBpadding\fR as any = "padding:200px 350px 250px 200px;", 
\fBtitle\fR as string = "Statistic of Differently Expressed Metabolite", 
\fBheadN\fR as integer = 60, 
\fBppi\fR as integer = 300, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
