.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "go.enrichment.bubbles" "go.enrichment.bubbles"
.SH NAME
go.enrichment.bubbles \- plot of the Go enrichment in bubble plot style
.SH SYNOPSIS
\fIgo.enrichment.bubbles(\fBprofiles\fR as <generic> EnrichmentTerm[], 
\fBgoDb\fR as <generic> GO_OBO, 
\fBsize\fR as string = "2000,1600", 
\fBpvalue\fR as double = 0.05, 
\fBtopN\fR as integer = 10, 
\fBR\fR as string = "10,50");\fR
.SH DESCRIPTION
.PP
plot of the Go enrichment in bubble plot style
.PP
.SH OPTIONS
.PP
\fBprofiles\fB \fR\- -. 
.PP
.PP
\fBgoDb\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBpvalue\fB \fR\- -. 
.PP
.PP
\fBtopN\fB \fR\- -. 
.PP
.PP
\fBR\fB \fR\- -. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
