.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-Jan "kegg.enrichment.bubbles" "kegg.enrichment.bubbles"
.SH NAME
kegg.enrichment.bubbles \- plot kegg enrichment result in bubble plot
.SH SYNOPSIS
\fIkegg.enrichment.bubbles(\fBprofiles\fR as any, 
\fBsize\fR as any = "3800,2600", 
\fBpadding\fR as any = "padding:300px 1000px 300px 200px;", 
\fBunenrichColor\fR as string = "LightGray", 
\fBthemeColors\fR as string = "Set1:c8", 
\fBalpha\fR as double = 0.75, 
\fBdisplays\fR as integer = 5, 
\fBserialTopn\fR as boolean = FALSE, 
\fBbubbleRadius\fR as any = [7,40], 
\fBheatmap\fR as boolean = FALSE, 
\fBbubbleStyle\fR as boolean = FALSE, 
\fBtop_samples\fR as integer = 16, 
\fBppi\fR as integer = 300, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
plot kegg enrichment result in bubble plot
.PP
.SH OPTIONS
.PP
\fBprofiles\fB \fR\- 
 A dataframe object(or a set of the dataframe object in tuple list) 
 that contains the kegg pathway enrichment data, data fields is 
 required for generates the bubble data:
 
 + \fBRaw p\fR: pvalue of the enrichment term
 + \fBImpact\fR: x axis value
 + \fBHits\fR: the molecule hits number in current enrichment term
 + \fBpathway\fR: the kegg pathway id
 
. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBpadding\fB \fR\- -. 
.PP
.PP
\fBunenrichColor\fB \fR\- -. 
.PP
.PP
\fBppi\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
