.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-01-01 "kegg.enrichment.bubbles" "kegg.enrichment.bubbles"
.SH NAME
kegg.enrichment.bubbles \- plot kegg enrichment result in bubble plot
.SH SYNOPSIS
\fIkegg.enrichment.bubbles(\fBprofiles\fR as any, 
\fBsize\fR as any = "3800,2600", 
\fBpadding\fR as any = "padding:300px 1000px 300px 200px;", 
\fBunenrichColor\fR as string = "LightGray", 
\fBthemeColors\fR as string = "Set1:c8", 
\fBalpha\fR as double = 0.75, 
\fBdisplays\fR as integer = 5, 
\fBserialTopn\fR as boolean = FALSE, 
\fBbubbleRadius\fR as any = [12,64], 
\fBheatmap\fR as boolean = FALSE, 
\fBbubbleStyle\fR as boolean = FALSE, 
\fBppi\fR as integer = 300, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
plot kegg enrichment result in bubble plot
.PP
.SH OPTIONS
.PP
\fBprofiles\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBpadding\fB \fR\- -. 
.PP
.PP
\fBunenrichColor\fB \fR\- -. 
.PP
.PP
\fBppi\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
