.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "multiple_volcano" "multiple_volcano"
.SH NAME
multiple_volcano \- 
.SH SYNOPSIS
\fImultiple_volcano(\fBgroups\fR as list, 
\fBsize\fR as any = "3600,2100", 
\fBpadding\fR as any = "padding: 5% 10% 10% 10%", 
\fBbg\fR as any = "white", 
\fBtitle\fR as string = "Multiple Comparision Volcano", 
\fBpoint_size\fR as integer = 5, 
\fBdeg_class\fR as string = "sig", 
\fBdraw_label\fR as boolean = TRUE, 
\fBdraw_legend\fR as boolean = TRUE, 
\fBlabel_css\fR as string = "font-style: normal; font-size: 20; font-family: Bookman Old Style;", 
\fBlegend_css\fR as string = "font-style: normal; font-size: 32; font-family: Bookman Old Style;", 
\fBdpi\fR as integer = 100, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
