.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "plot.expression_patterns" "plot.expression_patterns"
.SH NAME
plot.expression_patterns \- 
.SH SYNOPSIS
\fIplot.expression_patterns(\fBmatrix\fR as <generic> ExpressionPattern, 
\fBsize\fR as any = "2400,2700", 
\fBpadding\fR as any = "padding:250px 150px 300px 300px;", 
\fBbg\fR as any = "white", 
\fBcolorSet\fR as string = "PiYG:c8", 
\fBlevels\fR as integer = 25, 
\fBclusterLabelStyle\fR as string = "font-style: normal; font-size: 20; font-family: Bookman Old Style;", 
\fBlegendTitleStyle\fR as string = "font-style: normal; font-size: 10; font-family: Microsoft YaHei;", 
\fBlegendTickStyle\fR as string = "font-style: normal; font-size: 10; font-family: Microsoft YaHei;", 
\fBaxisTickCSS\fR as string = "font-style: normal; font-size: 12; font-family: Segoe UI;", 
\fBaxisLabelCSS\fR as string = "font-style: normal; font-size: 12; font-family: Microsoft YaHei;", 
\fBdriver\fR as <integer> Drivers = [Default], 
\fBppi\fR as integer = 300, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
