.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-Jan "sample.color_bend" "sample.color_bend"
.SH NAME
sample.color_bend \- 
.SH SYNOPSIS
\fIsample.color_bend(\fBg\fR as <generic> IGraphics, 
\fBlayout\fR as <generic> RectangleF, 
\fBgeneExpression\fR as <generic> Color[], 
\fBhorizontal\fR as boolean = TRUE, 
\fBsampleNames\fR as string = \fB<NULL>\fR, 
\fBlabelFontCSS\fR as string = "font-style: normal; font-size: 16; font-family: Bookman Old Style;");\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
