.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-Jan "volcano" "volcano"
.SH NAME
volcano \- 
.SH SYNOPSIS
\fIvolcano(\fBgenes\fR as any, 
\fBsize\fR as any = "2400,2700", 
\fBpadding\fR as any = "padding:250px 150px 300px 300px;", 
\fBbg\fR as any = "white", 
\fBcolors\fR as any = CALL "LIST"("UP" <- "RED", "DOWN" <- "GREEN", "OTHER" <- "BLACK"), 
\fBpvalue\fR as double = 0.05, 
\fBlevel\fR as double = 1.5, 
\fBtitle\fR as string = "volcano plot", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
