.\" man page create by R# package system.
.TH MACHINELEARNING.VALIDATION 2 2020-07-19 "as.validation" "as.validation"
.SH NAME
as.validation \- 
.SH SYNOPSIS
\fIas.validation(\fBtrainingSet\fR as <generic> NormalizeMatrix, 
\fBinput\fR as double, 
\fBvalidate\fR as double, 
\fBmethod\fR as <integer> Methods = [NormalScaler]);\fR
.SH SEE ALSO
machineLearning.validation
.SH FILES
.PP
R.math.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
