.\" man page create by R# package system.
.TH REPORT.UTILS 1 2000-Jan "keggMap.highlights" "keggMap.highlights"
.SH NAME
keggMap.highlights \- generate the kegg pathway map highlight image render result
.SH SYNOPSIS
\fIkeggMap.highlights(\fBmap\fR as <generic> Map, 
\fBhighlights\fR as any, 
\fBtext_color\fR as string = "white", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
generate the kegg pathway map highlight image render result
.PP
.SH OPTIONS
.PP
\fBmap\fB \fR\- the blank template of the kegg map. 
.PP
.PP
\fBhighlights\fB \fR\- a list of object with color highlights, or url. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
report.utils
.SH FILES
.PP
kegg_kit.dll
.PP
