.\" man page create by R# package system.
.TH REPORT.UTILS 1 2000-01-01 "keggMap.reportHtml" "keggMap.reportHtml"
.SH NAME
keggMap.reportHtml \- generate the kegg pathway map highlight html report
.SH SYNOPSIS
\fIkeggMap.reportHtml(\fBmap\fR as <generic> Map, 
\fBhighlights\fR as any, 
\fBtext_color\fR as string = "white", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
generate the kegg pathway map highlight html report
.PP
.SH OPTIONS
.PP
\fBmap\fB \fR\- the blank template of the kegg map. 
.PP
.SH SEE ALSO
report.utils
.SH FILES
.PP
kegg_kit.dll
.PP
