.\" man page create by R# package system.
.TH REPORT.UTILS 1 2000-01-01 "loadMap" "loadMap"
.SH NAME
loadMap \- load a blank kegg pathway map template object from a given file object.
.SH SYNOPSIS
\fIloadMap(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load a blank kegg pathway map template object from a given file object.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- a given file object, it can be a file path or a file input stream.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
report.utils
.SH FILES
.PP
kegg_kit.dll
.PP
