.\" man page create by R# package system.
.TH REPORT.UTILS 1 2000-Jan "map.intersects" "map.intersects"
.SH NAME
map.intersects \- check object id that intersect with the current given map object.
.SH SYNOPSIS
\fImap.intersects(\fBmap\fR as <generic> Map, 
\fBlist\fR as string);\fR
.SH DESCRIPTION
.PP
check object id that intersect with the current given map object.
.PP
.SH OPTIONS
.PP
\fBmap\fB \fR\- a given kegg pathway map object model. 
.PP
.PP
\fBlist\fB \fR\- an object id list. 
.PP
.SH SEE ALSO
report.utils
.SH FILES
.PP
kegg_kit.dll
.PP
