.\" man page create by R# package system.
.TH REPORT.UTILS 1 2000-Jan "parseKeggUrl" "parseKeggUrl"
.SH NAME
parseKeggUrl \- 
.SH SYNOPSIS
\fIparseKeggUrl(\fBurl\fR as string, 
\fBcompound\fR as string = "blue", 
\fBgene\fR as string = "red", 
\fBreaction\fR as string = "green");\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- -. 
.PP
.PP
\fBcompound\fB \fR\- the default color string for kegg compounds. 
.PP
.PP
\fBgene\fB \fR\- the default color string for KO/gene. 
.PP
.PP
\fBreaction\fB \fR\- the default color string for kegg reactions. 
.PP
.SH SEE ALSO
report.utils
.SH FILES
.PP
kegg_kit.dll
.PP
