.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-01-01 "find_motifs" "find_motifs"
.SH NAME
find_motifs \- 
.SH SYNOPSIS
\fIfind_motifs(\fBfasta\fR as <generic> Object, 
\fBminw\fR as integer = 6, 
\fBmaxw\fR as integer = 20, 
\fBnmotifs\fR as integer = 25, 
\fBnoccurs\fR as integer = 6);\fR
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC/GCModeller 2020
