.\" man page create by R# package system.
.TH KEGG.BRITE 1 2000-01-01 "brite.parse" "brite.parse"
.SH NAME
brite.parse \- Do parse of the kegg brite text file.
.SH SYNOPSIS
\fIbrite.parse(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do parse of the kegg brite text file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 The file text content, brite id or its file path

.PP
.SH SEE ALSO
kegg.brite
.SH FILES
.PP
kegg_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
