.\" man page create by R# package system.
.TH IGRAPH.RENDER 1 2020-07-22 "edge.color" "edge.color"
.SH NAME
edge.color \- 
.SH SYNOPSIS
\fIedge.color(\fBg\fR as <generic> NetworkGraph, 
\fBcolors\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph.render
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
