.\" man page create by R# package system.
.TH IGRAPH.RENDER 1 2020-11-02 "render.Plot" "render.Plot"
.SH NAME
render.Plot \- Rendering png or svg image from a given network graph model.
.SH SYNOPSIS
\fIrender.Plot(\fBg\fR as <generic> NetworkGraph, 
\fBcanvasSize\fR as <generic> Object = "1024,768", 
\fBpadding\fR as <generic> Object = "padding:100px 100px 100px 100px;", 
\fBdefaultColor\fR as string = "skyblue", 
\fBminNodeSize\fR as double = 10, 
\fBminLinkWidth\fR as double = 2, 
\fBnodeSize\fR as <generic> Object = \fB<NULL>\fR, 
\fBnodeLabel\fR as <generic> Object = \fB<NULL>\fR, 
\fBnodeStroke\fR as <generic> Object = "stroke: black; stroke-width: 2px; stroke-dash: solid;", 
\fBnodeVisual\fR as <generic> Object = \fB<NULL>\fR, 
\fBhullPolygonGroups\fR as <generic> Object = \fB<NULL>\fR, 
\fBlabelFontSize\fR as <generic> Object = 20, 
\fBlabelerIterations\fR as integer = 100, 
\fBlabelColor\fR as <generic> Object = \fB<NULL>\fR, 
\fBlabelWordWrapWidth\fR as integer = -1, 
\fBtexture\fR as <generic> Object = \fB<NULL>\fR, 
\fBwidget\fR as <generic> Object = \fB<NULL>\fR, 
\fBshowLabelerProgress\fR as boolean = FALSE, 
\fBshowUntexture\fR as boolean = TRUE, 
\fBdefaultEdgeColor\fR as string = "lightgray", 
\fBdefaultLabelColor\fR as string = "black", 
\fBdrawEdgeDirection\fR as boolean = FALSE, 
\fBdriver\fR as <integer> Drivers = [GDI], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Rendering png or svg image from a given network graph model.
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -
.PP
.PP
\fBcanvasSize\fB \fR\- -
.PP
.PP
\fBtexture\fB \fR\- 
 get texture brush or color brush descriptor string.

.PP
.SH SEE ALSO
igraph.render
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
