.\" man page create by R# package system.
.TH FASTQ 1 2000-1月 "assemble" "assemble"
.SH NAME
assemble \- Do short reads assembling
.SH SYNOPSIS
\fIassemble(\fBreads\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do short reads assembling
.PP
.SH OPTIONS
.PP
\fBreads\fB \fR\- should be a set of the sequence data, example as a collection of @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR data.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
the short reads assembling result
.PP
.SH SEE ALSO
FastQ
.SH FILES
.PP
rnaseq.dll
.PP
