.\" man page create by R# package system.
.TH FASTQ 1 2000-1月 "random_expression_weights" "random_expression_weights"
.SH NAME
random_expression_weights \- generates the random expression weights
.SH SYNOPSIS
\fIrandom_expression_weights(\fBnames\fR as any);\fR
.SH DESCRIPTION
.PP
generates the random expression weights
.PP
.SH OPTIONS
.PP
\fBnames\fB \fR\- -. 
.PP
.SH SEE ALSO
FastQ
.SH FILES
.PP
rnaseq.dll
.PP
