.\" man page create by R# package system.
.TH FASTQ 1 2000-1月 "read.fastq" "read.fastq"
.SH NAME
read.fastq \- read the fastq file
.SH SYNOPSIS
\fIread.fastq(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the fastq file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
FastQ
.SH FILES
.PP
rnaseq.dll
.PP
