.\" man page create by R# package system.
.TH FASTQ 1 2000-Jan "simulate_reads" "simulate_reads"
.SH NAME
simulate_reads \- 
.SH SYNOPSIS
\fIsimulate_reads(\fBgenomes\fR as any, 
\fBn\fR as integer = 100000, 
\fBlen\fR as any = "200,350", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
FastQ
.SH FILES
.PP
rnaseq.dll
.PP
