.\" man page create by R# package system.
.TH HTML 4 2000-01-01 "markdown.html" "markdown.html"
.SH NAME
markdown.html \- Render markdown to html text
.SH SYNOPSIS
\fImarkdown.html(\fBmarkdown\fR as string);\fR
.SH DESCRIPTION
.PP
Render markdown to html text
.PP
.SH OPTIONS
.PP
\fBmarkdown\fB \fR\- -
.PP
.SH SEE ALSO
html
.SH FILES
.PP
reportKit.dll
.PP
.SH COPYRIGHT
Copyright © I@xieguigang.me 2020
