.\" man page create by R# package system.
.TH HTML 4 2000-01-01 "template" "template"
.SH NAME
template \- Create a html template model from the given template file
.SH SYNOPSIS
\fItemplate(\fBurl\fR as string);\fR
.SH DESCRIPTION
.PP
Create a html template model from the given template file
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- -
.PP
.SH SEE ALSO
html
.SH FILES
.PP
reportKit.dll
.PP
.SH COPYRIGHT
Copyright © I@xieguigang.me 2020
