.\" man page create by R# package system.
.TH RHEA 1 2000-1月 "open.rdf" "open.rdf"
.SH NAME
open.rdf \- open the rdf data pack of Rhea database
.SH SYNOPSIS
\fIopen.rdf(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
open the rdf data pack of Rhea database
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH DETAILS
.PP
https://ftp.expasy.org/databases/rhea/rdf/rhea.rdf.gz
.PP
.SH SEE ALSO
rhea
.SH FILES
.PP
annotationKit.dll
.PP
