.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS 2 2000-1月 "gff_features" "gff_features"
.SH NAME
gff_features \- get gff features by id reference
.SH SYNOPSIS
\fIgff_features(\fBgff\fR as <generic> GFFTable, 
\fBid\fR as any = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
get gff features by id reference
.PP
.SH OPTIONS
.PP
\fBgff\fB \fR\- 
 a [GFFTable](cref:T:SMRUCC.genomics.Annotation.Assembly.NCBI.GenBank.TabularFormat.GFF.GFFTable) genomics feature annotation table object for 
 query the feature data.
. 
.PP
.PP
\fBid\fB \fR\- 
 a character vector of the feature id for get the subset of the target 
 features. If this parameter is not specified, then all of the features 
 inside the given gff table will be returned.
. 
.PP
.SH VALUE
.PP
a vector of the [Feature](cref:T:SMRUCC.genomics.Annotation.Assembly.NCBI.GenBank.TabularFormat.GFF.Feature) genomics feature object.
.PP
.SH SEE ALSO
annotation.genomics
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
