.\" man page create by R# package system.
.TH ANNOTATION.GENOMICS 2 2000-1月 "read.nucmer" "read.nucmer"
.SH NAME
read.nucmer \- read the nucmer alignment delta format file
.SH SYNOPSIS
\fIread.nucmer(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the nucmer alignment delta format file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path of the nucmer alignment delta format file.
. 
.PP
.SH VALUE
.PP
a [DeltaFile](cref:T:SMRUCC.genomics.Visualize.SyntenyVisualize.DeltaFile) nucmer alignment result object that loaded 
 from the given delta file.
.PP
.SH SEE ALSO
annotation.genomics
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
