.\" man page create by R# package system.
.TH GA_TOOLKIT 1 2020-11-02 "ANN.training" "ANN.training"
.SH NAME
ANN.training \- Run ANN training under the GA framework
.SH SYNOPSIS
\fIANN.training(\fBANN\fR as <generic> Object, 
\fBtrainingSet\fR as <generic> DataSet, 
\fBmutationRate\fR as double = 0.2, 
\fBpopulationSize\fR as integer = 1000, 
\fBiterations\fR as integer = 10000, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Run ANN training under the GA framework
.PP
.SH OPTIONS
.PP
\fBtrainingSet\fB \fR\- -
.PP
.PP
\fBmutationRate#\fB \fR\- -
.PP
.PP
\fBpopulationSize%\fB \fR\- -
.PP
.PP
\fBiterations%\fB \fR\- -
.PP
.SH SEE ALSO
GA_toolkit
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
