.\" man page create by R# package system.
.TH GA_TOOLKIT 1 2020-11-09 "population" "population"
.SH NAME
population \- 
.SH SYNOPSIS
\fIpopulation(\fBancestor\fR as <generic> GeneralChromosome, 
\fBmutation_rate\fR as double = 0.2, 
\fBpopulation_size\fR as integer = 500, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GA_toolkit
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
