.\" man page create by R# package system.
.TH GA_TOOLKIT 1 2020-11-02 "template" "template"
.SH NAME
template \- create a new chromosome template.
.SH SYNOPSIS
\fItemplate(\fBseed\fR as <generic> Object, 
\fBcrossover\fR as <generic> RFunction, 
\fBmutate\fR as <generic> RFunction, 
\fBuniqueId\fR as <generic> RFunction, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a new chromosome template.
.PP
.SH OPTIONS
.PP
\fBseed\fB \fR\- -
.PP
.PP
\fBcrossover\fB \fR\- -
.PP
.PP
\fBmutate\fB \fR\- -
.PP
.PP
\fBuniqueId\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
GA_toolkit
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
