.\" man page create by R# package system.
.TH DIAGNOSTICS 1 2000-01-01 "view" "view"
.SH NAME
view \- A helper api for invoke a Data Viewer
.SH SYNOPSIS
\fIview(\fBsymbol\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
A helper api for invoke a Data Viewer
 
 Invoke a spreadsheet-style data viewer on a matrix-like R object.
.PP
.SH OPTIONS
.PP
\fBsymbol\fB \fR\- 
 an R object which can be coerced to a data frame with non-zero 
 numbers of rows and columns.

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH DETAILS
.PP
Object x is coerced (if possible) to a data frame, then columns 
 are converted to character using format.data.frame. The object 
 is then viewed in a spreadsheet-like data viewer, a read-only 
 version of data.entry.

 If there are row names On the data frame that are Not 1:nrow, 
 they are displayed in a separate first column called 
 \fBrow.names\fR.

 Objects with zero columns Or zero rows are Not accepted.

 The array Of cells can be navigated via the scrollbars And by 
 the cursor keys, Home, End, Page Up And Page Down.

 The initial size Of the data viewer window Is taken from the 
 Default dimensions Of a pager (see Rconsole), but adjusted 
 downwards To show a whole number Of rows And columns.
.PP
.SH SEE ALSO
diagnostics
.SH FILES
.PP
Rstudio.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
