.\" man page create by R# package system.
.TH NETWORK 1 2000-1月 "fromCompounds" "fromCompounds"
.SH NAME
fromCompounds \- create metabolism graph from a given set of compounds
.SH SYNOPSIS
\fIfromCompounds(\fBcompoundsId\fR as string, 
\fBgraph\fR as <generic> Reaction[], 
\fBcompounds\fR as <generic> CompoundRepository = \fB<NULL>\fR, 
\fBenzymeBridged\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
create metabolism graph from a given set of compounds
.PP
.SH OPTIONS
.PP
\fBcompoundsId\fB \fR\- -. 
.PP
.PP
\fBgraph\fB \fR\- -. 
.PP
.PP
\fBcompounds\fB \fR\- -. 
.PP
.PP
\fBenzymeBridged\fB \fR\- -. 
.PP
.SH SEE ALSO
network
.SH FILES
.PP
kegg_kit.dll
.PP
