.\" man page create by R# package system.
.TH NETWORK 1 2000-1月 "gsva_network" "gsva_network"
.SH NAME
gsva_network \- 
.SH SYNOPSIS
\fIgsva_network(\fBgsva\fR as any, 
\fBdiff_exprs\fR as any, 
\fBmodel\fR as <generic> Background, 
\fBcor\fR as <generic> WGCNAWeight = \fB<NULL>\fR, 
\fBmodules\fR as any = \fB<NULL>\fR, 
\fBnames\fR as list = \fB<NULL>\fR, 
\fBleave_blankName\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
network
.SH FILES
.PP
kegg_kit.dll
.PP
