Imports Microsoft.VisualBasic.Data.Framework
Imports Microsoft.VisualBasic.Text

Namespace SAM.featureCount

    ''' <summary>
    ''' BAM feature counts for multiple samples, as generated by the `featureCounts` tool from the Subread package.
    ''' </summary>
    Public Class featureCounts

        Public Property Geneid As String
        Public Property Chr As String
        Public Property Start As UInteger
        Public Property [End] As UInteger
        Public Property Strand As String
        Public Property Length As Integer
        Public Property SampleCounts As Dictionary(Of String, Integer)

        Public Shared Function ReadTable(file As String) As IEnumerable(Of featureCounts)
            Return file.LoadTsv(Of featureCounts)(encoding:=Encodings.UTF8, mute:=True, skipComments:=True)
        End Function

    End Class
End Namespace