Imports Microsoft.VisualBasic.ComponentModel.Collection.Generic
Imports Microsoft.VisualBasic.ComponentModel.DataSourceModel
Imports Microsoft.VisualBasic.Data.Framework
Imports Microsoft.VisualBasic.Text

Namespace SAM.featureCount

    ''' <summary>
    ''' BAM feature counts for multiple samples, as generated by the `featureCounts` tool from the Subread package.
    ''' </summary>
    Public Class featureCounts : Implements INamedValue, IDynamicMeta(Of Integer)

        Public Property Geneid As String Implements INamedValue.Key
        Public Property Chr As String
        Public Property Start As UInteger
        Public Property [End] As UInteger
        Public Property Strand As String
        Public Property Length As Integer
        Public Property SampleCounts As Dictionary(Of String, Integer) Implements IDynamicMeta(Of Integer).Properties

        Default Public ReadOnly Property Counts(sample_ids As IEnumerable(Of String)) As Integer()
            Get
                Return (From id As String In sample_ids Select SampleCounts.TryGetValue(id)).ToArray
            End Get
        End Property

        Public Function IndexStats(sample As String) As IndexStats
            Return New IndexStats With {
                .GeneID = Geneid,
                .Length = Length,
                .RawCount = SampleCounts.TryGetValue(sample),
                .UnmappedBases = 0
            }
        End Function

        Public Shared Function ReadTable(file As String) As IEnumerable(Of featureCounts)
            Return file.LoadTsv(Of featureCounts)(encoding:=Encodings.UTF8, mute:=True, skipComments:=True)
        End Function

    End Class
End Namespace