#Region "Microsoft.VisualBasic::b467b49fe4499524d03477f46bfa7f64, RNA-Seq\RNA-seq.Data\SAM\featureCount\featureCounts.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 41
    '    Code Lines: 31 (75.61%)
    ' Comment Lines: 3 (7.32%)
    '    - Xml Docs: 100.00%
    ' 
    '   Blank Lines: 7 (17.07%)
    '     File Size: 1.71 KB


    '     Class featureCounts
    ' 
    '         Properties: [End], Chr, Geneid, Length, SampleCounts
    '                     Start, Strand
    ' 
    '         Function: IndexStats, ReadTable
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Imports Microsoft.VisualBasic.ComponentModel.Collection.Generic
Imports Microsoft.VisualBasic.ComponentModel.DataSourceModel
Imports Microsoft.VisualBasic.Data.Framework
Imports Microsoft.VisualBasic.Text

Namespace SAM.featureCount

    ''' <summary>
    ''' BAM feature counts for multiple samples, as generated by the `featureCounts` tool from the Subread package.
    ''' </summary>
    Public Class featureCounts : Implements INamedValue, IDynamicMeta(Of Integer)

        Public Property Geneid As String Implements INamedValue.Key
        Public Property Chr As String
        Public Property Start As String
        Public Property [End] As String
        Public Property Strand As String
        Public Property Length As Integer
        Public Property SampleCounts As Dictionary(Of String, Integer) Implements IDynamicMeta(Of Integer).Properties

        Default Public ReadOnly Property Counts(sample_ids As IEnumerable(Of String)) As Integer()
            Get
                Return (From id As String In sample_ids Select SampleCounts.TryGetValue(id)).ToArray
            End Get
        End Property

        Public Function IndexStats(sample As String) As IndexStats
            Return New IndexStats With {
                .GeneID = Geneid,
                .Length = Length,
                .RawCount = SampleCounts.TryGetValue(sample),
                .UnmappedBases = 0
            }
        End Function

        Public Shared Function ReadTable(file As String) As IEnumerable(Of featureCounts)
            Return file.LoadTsv(Of featureCounts)(encoding:=Encodings.UTF8, mute:=True, skipComments:=True)
        End Function

    End Class
End Namespace
