.\" man page create by R# package system.
.TH OTU_TABLE 1 2000-1月 "as.OTU_table" "as.OTU_table"
.SH NAME
as.OTU_table \- convert the mothur rank tree as the OTU table
.SH SYNOPSIS
\fIas.OTU_table(\fBx\fR as any, 
\fBid\fR as string = "OTU_num", 
\fBtaxonomy\fR as string = "taxonomy", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
convert the mothur rank tree as the OTU table
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
OTU_table
.SH FILES
.PP
metagenomics_kit.dll
.PP
