.\" man page create by R# package system.
.TH SIMULATOR 2 2000-1月 "vcell.flux.index" "vcell.flux.index"
.SH NAME
vcell.flux.index \- get flux key reference index collection
.SH SYNOPSIS
\fIvcell.flux.index(\fBvcell\fR as <generic> CellularModule);\fR
.SH DESCRIPTION
.PP
get flux key reference index collection
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
