.\" man page create by R# package system.
.TH HMMER 1 2000-1月 "parse_kofamscan" "parse_kofamscan"
.SH NAME
parse_kofamscan \- Parse the kofamscan table output
.SH SYNOPSIS
\fIparse_kofamscan(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Parse the kofamscan table output
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
hmmer
.SH FILES
.PP
seqtoolkit.dll
.PP
