.\" man page create by R# package system.
.TH FBA 1 2000-1月 "objective" "objective"
.SH NAME
objective \- set lpp objective targets for FBA analysis
.SH SYNOPSIS
\fIobjective(\fBmatrix\fR as <generic> Matrix, 
\fBtarget\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set lpp objective targets for FBA analysis
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- -. 
.PP
.PP
\fBtarget\fB \fR\- 
 should be a character vector of the target reaction id 
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
FBA
.SH FILES
.PP
biosystem.dll
.PP
