.\" man page create by R# package system.
.TH GENE_QUANTIFICATION 1 2000-1月 "deseq2_norm" "deseq2_norm"
.SH NAME
deseq2_norm \- Apply DESeq2 Median of Ratios normalization method to the raw counts matrix.
.SH SYNOPSIS
\fIdeseq2_norm(\fBcounts\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
Apply DESeq2 Median of Ratios normalization method to the raw counts matrix.
.PP
.SH OPTIONS
.PP
\fBcounts\fB \fR\- The raw counts matrix.. 
.PP
.SH VALUE
.PP
The normalized counts matrix.
.PP
.SH SEE ALSO
gene_quantification
.SH FILES
.PP
rnaseq.dll
.PP
