'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Interops.ClustalOrg.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 * Clustal Omega:
        '''Fabian Sievers   UCD Dublin, Ireland
        '''Andreas Wilm     UCD Dublin, Ireland
        '''David Dineen     UCD Dublin, Ireland
        '''Johannes Söding  Gene Center Munich, Germany
        '''Michael Remmert  Gene Center Munich, Germany
        '''
        '''* Clustal 2
        '''Mark Larkin      UCD Dublin, Ireland
        '''
        '''* Clustal 1.X
        '''Toby Gibson      EMBL Heidelberg, Germany
        '''Des Higgins      UCC Cork, Ireland
        '''Julie Thompson   IGBMC Strasbourg, France
        '''
        '''* Contributors:
        '''Chenna Ramu      EMBL Heidelberg, Germany
        '''Nigel Brown      EMBL Heidelberg,  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AUTHORS() As String
            Get
                Return ResourceManager.GetString("AUTHORS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ChangeLog() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ChangeLog", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property clustalo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("clustalo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 2, June 1991
        '''
        ''' Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        ''' 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The licenses for most software are designed to take away your
        '''freedom to share and change it.  By contrast, the GNU General Publi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property COPYING() As String
            Get
                Return ResourceManager.GetString("COPYING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The impatient can try:
        '''
        '''$ ./configure
        '''$ make
        '''$ make install
        '''
        '''
        '''Clustal-Omega needs argtable2 (http://argtable.sourceforge.net/). If
        '''argtable2 is installed in a non-standard directory you might have to
        '''point configure to its installation directory. For example, if you are
        '''on a Mac and have argtable installed via MacPorts then you should use
        '''the following command line:
        '''
        '''$ ./configure CFLAGS=&apos;-I/opt/local/include&apos; LDFLAGS=&apos;-L/opt/local/lib&apos;
        '''
        '''ClustalO will automatically support multi-threading if  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property INSTALL() As String
            Get
                Return ResourceManager.GetString("INSTALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property libgcc_s_dw2_1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("libgcc_s_dw2_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property libgomp_1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("libgomp_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property libstdc___6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("libstdc___6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property mingwm10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mingwm10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property pthreadGC2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pthreadGC2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property README() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("README", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
