.\" man page create by R# package system.
.TH GEARS 1 2000-1月 "training_set" "training_set"
.SH NAME
training_set \- Set the training sample set
.SH SYNOPSIS
\fItraining_set(\fBgears\fR as <generic> GEARS, 
\fBx\fR as <generic> Matrix, 
\fBcontrols\fR as any, 
\fBperturbed\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Set the training sample set
.PP
.SH OPTIONS
.PP
\fBgears\fB \fR\- 
 a @\fBT:SMRUCC.genomics.Analysis.GEARS.GEARS\fR model object that is created by the \fBGEARS::new\fR 
 api.
. 
.PP
.PP
\fBx\fB \fR\- 
 the gene expression matrix object of the Perturb-seq experiment data, which 
 should contains both of the control sample columns and the perturbed sample 
 columns.
. 
.PP
.PP
\fBcontrols\fB \fR\- 
 a character vector of the control(wildtype) sample column names in the given 
 expression matrix: the mean value and the standard deviation of these control 
 sample columns will be used as the shared wildtype baseline of the model 
 training, at least two control sample columns are required.
. 
.PP
.PP
\fBperturbed\fB \fR\- 
 a collection of the @\fBT:SMRUCC.genomics.GCModeller.Workbench.ExperimentDesigner.SampleInfo\fR sample information data of the 
 perturbed samples: the \fBID\fR property of the sample data should be matched 
 with the sample column of the given expression matrix, the perturbed gene id 
 set of each sample is stored as a json string array in the \fBmetadata\fR 
 property via the \fBperturbed_genes\fR key, and the intervention mode of each 
 sample could be stored in the \fBmetadata\fR property via the 
 \fBintervention_mode\fR key(the value should be one of \fBKnockout\fR, 
 \fBKnockdown\fR, \fBOverexpression\fR or \fBCustom\fR).
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
the input @\fBT:SMRUCC.genomics.Analysis.GEARS.GEARS\fR model object that the training sample set has 
 been set;
 
 this function returns a R# error message object if the given perturbed sample 
 data can not be cast to a collection of the @\fBT:SMRUCC.genomics.GCModeller.Workbench.ExperimentDesigner.SampleInfo\fR data.
.PP
.SH DETAILS
.PP
the wildtype baseline(the mean and the standard deviation of each gene) of 
 the GEARS model will be recomputed from the given control sample columns, so 
 that this api should be called before the \fBtrain\fR api.
.PP
.SH SEE ALSO
GEARS
.SH FILES
.PP
biosystem.dll
.PP
