.\" man page create by R# package system.
.TH GEARS 1 2000-1月 "training_set" "training_set"
.SH NAME
training_set \- Set the training sample set
.SH SYNOPSIS
\fItraining_set(\fBgears\fR as <generic> GEARS, 
\fBx\fR as <generic> Matrix, 
\fBcontrols\fR as any, 
\fBperturbed\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Set the training sample set
.PP
.SH OPTIONS
.PP
\fBgears\fB \fR\- -. 
.PP
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBcontrols\fB \fR\- -. 
.PP
.PP
\fBperturbed\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GEARS
.SH FILES
.PP
biosystem.dll
.PP
