.\" man page create by R# package system.
.TH SABIORK 1 2000-1月 "metabolite_species" "metabolite_species"
.SH NAME
metabolite_species \- 
.SH SYNOPSIS
\fImetabolite_species(\fBsbml\fR as <generic> SBMLInternalIndexer, 
\fBreaction\fR as <generic> SBMLReaction);\fR
.SH SEE ALSO
sabiork
.SH FILES
.PP
biosystem.dll
.PP
