.\" man page create by R# package system.
.TH SABIORK 1 2000-Jan "parseSbml" "parseSbml"
.SH NAME
parseSbml \- 
.SH SYNOPSIS
\fIparseSbml(\fBdata\fR as string);\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- 
 the xml document text or the file path to the sbml xml document file.
. 
.PP
.SH SEE ALSO
sabiork
.SH FILES
.PP
biosystem.dll
.PP
