.\" man page create by R# package system.
.TH SABIORK 1 2000-1月 "parseSbml" "parseSbml"
.SH NAME
parseSbml \- parse the sbml xml document text as kineticis data
.SH SYNOPSIS
\fIparseSbml(\fBdata\fR as string);\fR
.SH DESCRIPTION
.PP
parse the sbml xml document text as kineticis data
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- 
 the xml document text or the file path to the sbml xml document file.
. 
.PP
.SH VALUE
.PP
a SBML document data that contains list of reactions and list of the lambda formula expression
.PP
.SH SEE ALSO
sabiork
.SH FILES
.PP
biosystem.dll
.PP
