.\" man page create by R# package system.
.TH SABIORK 1 2000-1月 "sbmlReader" "sbmlReader"
.SH NAME
sbmlReader \- Create a helper reader for load element model from the sbml document
.SH SYNOPSIS
\fIsbmlReader(\fBsbml\fR as <generic> SbmlDocument);\fR
.SH DESCRIPTION
.PP
Create a helper reader for load element model from the sbml document
.PP
.SH OPTIONS
.PP
\fBsbml\fB \fR\- -. 
.PP
.SH SEE ALSO
sabiork
.SH FILES
.PP
biosystem.dll
.PP
