.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "average" "average"
.SH NAME
average \- calculate average value of the gene expression for
.SH SYNOPSIS
\fIaverage(\fBmatrix\fR as <generic> Matrix, 
\fBsampleinfo\fR as <generic> SampleInfo[] = \fB<NULL>\fR, 
\fBstrict\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
calculate average value of the gene expression for
 each sample group.
 
 this method can be apply for reduce data size when 
 create some plot for visualize the gene expression
 patterns across the sample groups.
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- a gene expression matrix. 
.PP
.PP
\fBsampleinfo\fB \fR\- The sample group data. 
.PP
.PP
\fBstrict\fB \fR\- 
 will try to ignores of the missing sample if strict option is off.
. 
.PP
.SH VALUE
.PP
this function return value is determined based on the sampleinfo parameter:
 
 1. for sampleinfo not nothing, a matrix with sample group as the sample feature data will be returns
 2. for missing sampleinfo data, a numeric vector of average value for each gene feature will be returns
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
