.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "expression_vector" "expression_vector"
.SH NAME
expression_vector \- get gene expression vector data
.SH SYNOPSIS
\fIexpression_vector(\fBx\fR as <generic> Matrix, 
\fBgeneId\fR as string);\fR
.SH DESCRIPTION
.PP
get gene expression vector data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a gene expression matrix object. 
.PP
.PP
\fBgeneId\fB \fR\- 
 the gene feature id, which should be exists in the row names of the given 
 expression matrix object.
. 
.PP
.SH VALUE
.PP
a named numeric vector of the target gene expression across multiple 
 samples, the name of each element is the corresponding sample id;
 
 NULL will be returns if the given gene id is not exists in the input 
 expression matrix object.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
