.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "expression_groups" "expression_groups"
.SH NAME
expression_groups \- 从表达矩阵之中按照表达值的分布特征拆分出每一个品种的基因组基因集合
.SH SYNOPSIS
\fIexpression_groups(\fBx\fR as <generic> Matrix, 
\fBsampleinfo\fR as any, 
\fBgroup\fR as string = \fB<NULL>\fR, 
\fBraw_count\fR as any = \fB<NULL>\fR, 
\fBpresence_quantile\fR as double = 0.5, 
\fBkMAD\fR as double = 3, 
\fBlogBase\fR as double = 2, 
\fBminAbsentFraction\fR as double = 0.01, 
\fBminGap\fR as double = 1.5, 
\fBabsFloor\fR as double = 0, 
\fBverbose\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
从表达矩阵之中按照表达值的分布特征拆分出每一个品种的基因组基因集合
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 基因在行，样本在列的表达矩阵. 
.PP
.PP
\fBsampleinfo\fB \fR\- 样本的元数据信息. 
.PP
.PP
\fBgroup\fB \fR\- 用于进行样本分组的元数据键名，例如"line". 
.PP
.PP
\fBraw_count\fB \fR\- 
 输入的数据模式：TRUE表示原始count矩阵，FALSE表示已经归一化之后的矩阵，
 默认为空值，即自动检测。
. 
.PP
.PP
\fBpresence_quantile\fB \fR\- 
 品种内部的生物学重复的汇总分位数，默认取中位数；0为最严格(所有的重复都要检出)，
 1为最宽松(只要有一个重复检出即可)。
. 
.PP
.PP
\fBkMAD\fB \fR\- 判定阈值相对于低表达本底的MAD的倍数. 
.PP
.PP
\fBlogBase\fB \fR\- 表达值分布变换所使用的对数底数. 
.PP
.PP
\fBminAbsentFraction\fB \fR\- 双峰检验之中的最小缺失组分占比. 
.PP
.PP
\fBminGap\fB \fR\- 双峰检验之中的最小峰间分离度. 
.PP
.PP
\fBabsFloor\fB \fR\- 判定为存在所要求的原始表达量下限. 
.PP
.PP
\fBverbose\fB \fR\- 是否输出阈值诊断信息？. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a key-value tuple list of key name is the group or [SampleGroup.sample_info](cref:P:SMRUCC.genomics.GCModeller.Workbench.ExperimentDesigner.SampleGroup.sample_info) and the value is the geneset of the corresponding group.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
