.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "minmax01Norm" "minmax01Norm"
.SH NAME
minmax01Norm \- min max normalization
.SH SYNOPSIS
\fIminmax01Norm(\fBx\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
min max normalization
 
 (row - min(row)) / (max(row) - min(row))
 
 this normalization method is usually used for the metabolomics data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a gene expression matrix object. 
.PP
.SH VALUE
.PP
a new expression matrix object that the expression value of each gene 
 feature row has been scaled into the range \fB[0, 1]\fR via the min-max 
 normalization.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
