.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "relative" "relative"
.SH NAME
relative \- normalize data by feature rows
.SH SYNOPSIS
\fIrelative(\fBmatrix\fR as <generic> Matrix, 
\fBmedian\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
normalize data by feature rows
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- a gene expression matrix. 
.PP
.PP
\fBmedian\fB \fR\- 
 normalize the matrix row by median value of each row?
. 
.PP
.SH VALUE
.PP
a new expression matrix object which is normalized by the relative scale 
 of each gene feature row: each expression value in a gene feature row is 
 divided by the max value(or the median value when the \fBmedian\fR parameter 
 is TRUE) of the corresponding gene feature row, the tag of the generated 
 matrix is formatted as \fBrelative_scaale({tag})\fR.
.PP
.SH DETAILS
.PP
row/max(row)
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
