.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "tr" "tr"
.SH NAME
tr \- do matrix transpose
.SH SYNOPSIS
\fItr(\fBmat\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
do matrix transpose
.PP
.SH OPTIONS
.PP
\fBmat\fB \fR\- 
 the target gene expression matrix object for make transpose.
. 
.PP
.SH VALUE
.PP
a transposed matrix object: the sample columns of the input matrix will 
 become the gene feature rows of the generated matrix and vice versa.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
