.\" man page create by R# package system.
.TH VCELLKIT.DEBUGGER 2 2020-07-22 "vcell.summary" "vcell.summary"
.SH NAME
vcell.summary \- 
.SH SYNOPSIS
\fIvcell.summary(\fBinits\fR as <generic> Definition, 
\fBmodel\fR as <generic> CellularModule, 
\fBdir\fR as string);\fR
.SH SEE ALSO
vcellkit.debugger
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
