.\" man page create by R# package system.
.TH MATH 1 2020-11-02 "abs" "abs"
.SH NAME
abs \- abs(x) computes the absolute value of x
.SH SYNOPSIS
\fIabs(\fBx\fR as <generic> Array);\fR
.SH DESCRIPTION
.PP
abs(x) computes the absolute value of x
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a numeric Or complex vector Or array.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
