.\" man page create by R# package system.
.TH MATH 1 2020-10-29 "cluster_1D" "cluster_1D"
.SH NAME
cluster_1D \- grouping data input by given numeric tolerance
.SH SYNOPSIS
\fIcluster_1D(\fBsequence\fR as <generic> Object, 
\fBeval\fR as <generic> Object, 
\fBoffset\fR as double = 0, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
grouping data input by given numeric tolerance
.PP
.SH OPTIONS
.PP
\fBsequence\fB \fR\- -
.PP
.PP
\fBeval\fB \fR\- -
.PP
.PP
\fBoffset\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
