.\" man page create by R# package system.
.TH MATH 1 2020-10-29 "exp" "exp"
.SH NAME
exp \- Logarithms and Exponentials
.SH SYNOPSIS
\fIexp(\fBx\fR as <generic> Array);\fR
.SH DESCRIPTION
.PP
Logarithms and Exponentials
 
 computes the exponential function.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a numeric or complex vector.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
