.\" man page create by R# package system.
.TH MATH 1 2020-12-15 "mean" "mean"
.SH NAME
mean \- Arithmetic Mean
.SH SYNOPSIS
\fImean(\fBx\fR as <generic> Array, 
\fBna_rm\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Arithmetic Mean
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- An R object. Currently there are methods for numeric/logical 
 vectors and date, date-time and time interval objects. Complex vectors are 
 allowed for trim = 0, only.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
