.\" man page create by R# package system.
.TH MATH 1 2020-10-29 "min" "min"
.SH NAME
min \- 
.SH SYNOPSIS
\fImin(\fBx\fR as <generic> Array, 
\fBna_rm\fR as boolean = FALSE);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -
.PP
.PP
\fBna_rm\fB \fR\- a logical indicating whether missing values should be removed.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
