.\" man page create by R# package system.
.TH MATH 1 2020-12-15 "pearson" "pearson"
.SH NAME
pearson \- 
.SH SYNOPSIS
\fIpearson(\fBx\fR as <generic> Array, 
\fBy\fR as <generic> Array, 
\fBMAXIT\fR as integer = 5000);\fR
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
