.\" man page create by R# package system.
.TH MATH 1 2020-10-29 "rnorm" "rnorm"
.SH NAME
rnorm \- 
.SH SYNOPSIS
\fIrnorm(\fBn\fR as integer, 
\fBmean\fR as double = 0, 
\fBsd\fR as double = 1);\fR
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
