.\" man page create by R# package system.
.TH MATH 1 2020-11-09 "runif" "runif"
.SH NAME
runif \- runif generates random deviates.
.SH SYNOPSIS
\fIrunif(\fBn\fR as string, 
\fBmin\fR as double = 0, 
\fBmax\fR as double = 1);\fR
.SH DESCRIPTION
.PP
runif generates random deviates.
.PP
.SH OPTIONS
.PP
\fBn\fB \fR\- 
 number of observations. If length(n) > 1, the length is taken to be the number required.

.PP
.PP
\fBmin\fB \fR\- lower And upper limits of the distribution. Must be finite.
.PP
.PP
\fBmax\fB \fR\- lower And upper limits of the distribution. Must be finite.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
