.\" man page create by R# package system.
.TH MATH 1 2020-10-29 "sample" "sample"
.SH NAME
sample \- Random Samples and Permutations
.SH SYNOPSIS
\fIsample(\fBx\fR as <generic> Object, 
\fBsize\fR as integer, 
\fBreplace\fR as boolean = FALSE, 
\fBprob\fR as <generic> Object = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Random Samples and Permutations
 
 \fBsample\fR takes a sample of the specified size from the elements 
 of x using either with or without replacement.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 either a vector Of one Or more elements from which To choose, Or a positive Integer. See 'Details.’

.PP
.PP
\fBsize\fB \fR\- a non-negative integer giving the number of items to choose.
.PP
.PP
\fBreplace\fB \fR\- should sampling be with replacement?
.PP
.PP
\fBprob\fB \fR\- 
 a vector Of probability weights For obtaining the elements Of the vector being sampled.

.PP
.SH VALUE
.PP
For sample a vector of length size with elements drawn from either \fBx\fR or from the 
 integers \fB1:x\fR.
.PP
.SH DETAILS
.PP
If x has length 1, is numeric (in the sense of is.numeric) and \fBx >= 1\fR, sampling 
 via sample takes place from \fB1:x\fR. Note that this convenience feature may lead to 
 undesired behaviour when x is of varying length in calls such as sample(x). 
 See the examples.

 Otherwise x can be any R Object For which length And subsetting by integers make sense: 
 S3 Or S4 methods for these operations will be dispatched as appropriate.

 For sample the default for size Is the number of items inferred from the first argument, 
 so that sample(x) generates a random permutation of the elements of x (Or 1:x).

 It Is allowed to ask for size = 0 samples with n = 0 Or a length-zero x, but otherwise 
 \fBn > 0\fR Or positive length(x) Is required.

 Non-integer positive numerical values of n Or x will be truncated to the next smallest 
 integer, which has to be no larger than \fB.Machine$integer.max\fR.

 The optional prob argument can be used to give a vector of weights for obtaining the elements 
 of the vector being sampled. They need Not sum to one, but they should be non-negative And 
 Not all zero. If replace Is true, Walker's alias method (Ripley, 1987) is used when there 
 are more than 200 reasonably probable values: this gives results incompatible with those 
 from \fBR < 2.2.0\fR.

 If replace Is False, these probabilities are applied sequentially, that Is the probability 
 Of choosing the Next item Is proportional To the weights amongst the remaining items. The 
 number Of nonzero weights must be at least size In this Case.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
