.\" man page create by R# package system.
.TH MATH 1 2020-11-09 "sample.int" "sample.int"
.SH NAME
sample.int \- 
.SH SYNOPSIS
\fIsample.int(\fBn\fR as integer, 
\fBsize\fR as <generic> Object = "n", 
\fBreplace\fR as boolean = FALSE, 
\fBprob\fR as <generic> Object = \fB<NULL>\fR);\fR
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
