.\" man page create by R# package system.
.TH MATH 1 2020-12-15 "sd" "sd"
.SH NAME
sd \- Standard Deviation
.SH SYNOPSIS
\fIsd(\fBx\fR as <generic> Array, 
\fBsample\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Standard Deviation
 
 This function computes the standard deviation of the values in x. 
 If na.rm is TRUE then missing values are removed before computation 
 proceeds.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a numeric vector or an R object but not a factor coercible to numeric by as.double(x)

.PP
.PP
\fBsample\fB \fR\- 
 sample or population

.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
