.\" man page create by R# package system.
.TH MATH 1 2020-12-15 "set.seed" "set.seed"
.SH NAME
set.seed \- set.seed is the recommended way to specify seeds.
.SH SYNOPSIS
\fIset.seed(\fBseed\fR as integer);\fR
.SH DESCRIPTION
.PP
set.seed is the recommended way to specify seeds.
.PP
.SH OPTIONS
.PP
\fBseed\fB \fR\- a single value, interpreted as an integer, or NULL (see ‘Details’).
.PP
.SH DETAILS
.PP
set.seed returns NULL, invisibly.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
