.\" man page create by R# package system.
.TH MATH 1 2020-12-15 "sum" "sum"
.SH NAME
sum \- Sum of Vector Elements
.SH SYNOPSIS
\fIsum(\fBx\fR as <generic> Object, 
\fBnarm\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Sum of Vector Elements
 
 sum returns the sum of all the values present in its arguments.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- numeric or complex or logical vectors.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
