.\" man page create by R# package system.
.TH R.SERIALIZATION 4 2000-01-01 "RStream.Load" "RStream.Load"
.SH NAME
RStream.Load \- Needs your manual type casting in your program.
.SH SYNOPSIS
\fIRStream.Load(\fBRData\fR as <generic> SymbolicExpression, 
\fBType\fR as <generic> Type);\fR
.SH DESCRIPTION
.PP
Needs your manual type casting in your program.
.PP
.SH OPTIONS
.PP
\fBRData\fB \fR\- -
.PP
.PP
\fBType\fB \fR\- -
.PP
.SH SEE ALSO
R.Serialization
.SH FILES
.PP
RDotNET.Extensions.VisualBasic.dll
.PP
.SH AUTHOR
Written by \fBxieguigang@gcmodeller.org\fR
.SH COPYRIGHT
Copyright ©  2015
