.\" man page create by R# package system.
.TH METATRAITS 2 2000-1月 "load.trait_annotations" "load.trait_annotations"
.SH NAME
load.trait_annotations \- 读取表型标注的原始表格（每一行是一个物种的一种表型标注）
.SH SYNOPSIS
\fIload.trait_annotations(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
读取表型标注的原始表格（每一行是一个物种的一种表型标注）
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- ncbi/gtdb species summary tsv 表文件. 
.PP
.SH SEE ALSO
metaTraits
.SH FILES
.PP
metagenomics_kit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
