.\" man page create by R# package system.
.TH MODEL 4 2000-01-01 "GC_content" "GC_content"
.SH NAME
GC_content \- creates the \fBGC%\fR content for circos plots.
.SH SYNOPSIS
\fIGC_content(\fBnt\fR as <generic> FastaSeq, 
\fBwin_size\fR as integer, 
\fBsteps\fR as integer);\fR
.SH DESCRIPTION
.PP
creates the \fBGC%\fR content for circos plots.
.PP
.SH OPTIONS
.PP
\fBnt\fB \fR\- 
 The original nt sequence in the fasta format for the calculation of the 
 \fBGC%\fR content in each slidewindow

.PP
.PP
\fBwin_size%\fB \fR\- -
.PP
.PP
\fBsteps%\fB \fR\- -
.PP
.SH SEE ALSO
model
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
