.\" man page create by R# package system.
.TH MODEL 4 2000-01-01 "gcSkew" "gcSkew"
.SH NAME
gcSkew \- Creates the circos circle plots of the genome gcskew.
.SH SYNOPSIS
\fIgcSkew(\fBnt\fR as <generic> IPolymerSequenceModel, 
\fBwin_size\fR as integer, 
\fBsteps\fR as integer);\fR
.SH DESCRIPTION
.PP
Creates the circos circle plots of the genome gcskew.
.PP
.SH OPTIONS
.PP
\fBnt\fB \fR\- -
.PP
.PP
\fBwin_size\fB \fR\- -
.PP
.PP
\fBsteps\fB \fR\- -
.PP
.SH SEE ALSO
model
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
