.\" man page create by R# package system.
.TH GENBANK 4 2000-Jan "accession_id" "accession_id"
.SH NAME
accession_id \- get current genbank assembly accession id
.SH SYNOPSIS
\fIaccession_id(\fBgenbank\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get current genbank assembly accession id
.PP
.SH OPTIONS
.PP
\fBgenbank\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
