.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "add.feature" "add.feature"
.SH NAME
add.feature \- 
.SH SYNOPSIS
\fIadd.feature(\fBgb\fR as <generic> File, 
\fBfeature\fR as <generic> Feature);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
