.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "as.genbank" "as.genbank"
.SH NAME
as.genbank \- converts tabular data file to genbank assembly object
.SH SYNOPSIS
\fIas.genbank(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
converts tabular data file to genbank assembly object
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
