.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "assembly_level" "assembly_level"
.SH NAME
assembly_level \- 
.SH SYNOPSIS
\fIassembly_level(\fBgb\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
