.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "enumerateFeatures" "enumerateFeatures"
.SH NAME
enumerateFeatures \- enumerate all features in the given NCBI genbank database object
.SH SYNOPSIS
\fIenumerateFeatures(\fBgb\fR as <generic> File, 
\fBkeys\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
enumerate all features in the given NCBI genbank database object
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- a NCBI genbank database object. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
