.\" man page create by R# package system.
.TH GENBANK 4 2000-01-01 "featureKeys" "featureKeys"
.SH NAME
featureKeys \- 
.SH SYNOPSIS
\fIfeatureKeys(\fBfeatures\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
