.\" man page create by R# package system.
.TH GENBANK 4 2000-Jan "load_genbanks" "load_genbanks"
.SH NAME
load_genbanks \- populate a list of genbank data objects from a given list of files or stream.
.SH SYNOPSIS
\fIload_genbanks(\fBfiles\fR as any, 
\fBautoClose\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
populate a list of genbank data objects from a given list of files or stream.
.PP
.SH OPTIONS
.PP
\fBfiles\fB \fR\- a list of files or file stream. 
.PP
.PP
\fBautoClose\fB \fR\- 
 auto close of the @\fBT:System.IO.Stream\fR if the **`files`** contains stream object?
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function supports of read assembly data directly from *.gz genbank archive file.
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
