.\" man page create by R# package system.
.TH GENBANK 4 2000-01-01 "protein.fasta" "protein.fasta"
.SH NAME
protein.fasta \- get or set fasta sequence of all CDS feature in the given genbank assembly file.
.SH SYNOPSIS
\fIprotein.fasta(\fBgb\fR as <generic> File, 
\fBproteins\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get or set fasta sequence of all CDS feature in the given genbank assembly file.
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- -. 
.PP
.PP
\fBproteins\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
