.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "taxon_id" "taxon_id"
.SH NAME
taxon_id \- get ncbi taxonomy id from the given genbank assembly file.
.SH SYNOPSIS
\fItaxon_id(\fBgb\fR as <generic> File);\fR
.SH DESCRIPTION
.PP
get ncbi taxonomy id from the given genbank assembly file.
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
