.\" man page create by R# package system.
.TH GENBANK 4 2000-1月 "taxonomy_lineage" "taxonomy_lineage"
.SH NAME
taxonomy_lineage \- extract the taxonomy lineage information from the genbank file
.SH SYNOPSIS
\fItaxonomy_lineage(\fBgb\fR as <generic> File);\fR
.SH DESCRIPTION
.PP
extract the taxonomy lineage information from the genbank file
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
