.\" man page create by R# package system.
.TH GENBANK 4 2000-Jan "write.genbank" "write.genbank"
.SH NAME
write.genbank \- save the modified genbank file
.SH SYNOPSIS
\fIwrite.genbank(\fBgb\fR as <generic> File, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the modified genbank file
.PP
.SH OPTIONS
.PP
\fBgb\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- the file path of the genbank assembly file to write data.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GenBank
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
