.\" man page create by R# package system.
.TH WAV 4 2000-01-01 "read.wav" "read.wav"
.SH NAME
read.wav \- 
.SH SYNOPSIS
\fIread.wav(\fBfile\fR as <generic> Object, 
\fBlazy\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.PP
\fBlazy\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
wav
.SH FILES
.PP
signalKit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
