.\" man page create by R# package system.
.TH UMAP 1 2020-12-15 "as.graph" "as.graph"
.SH NAME
as.graph \- 
.SH SYNOPSIS
\fIas.graph(\fBumap\fR as <generic> Umap, 
\fBlabels\fR as <generic> Object, 
\fBgroups\fR as <generic> Object = \fB<NULL>\fR, 
\fBthreshold\fR as double = 0, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
umap
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
