.\" man page create by R# package system.
.TH UMAP 1 2020-12-15 "umap" "umap"
.SH NAME
umap \- UMAP: Uniform Manifold Approximation and Projection for Dimension Reduction
.SH SYNOPSIS
\fIumap(\fBdata\fR as <generic> Object, 
\fBdimension\fR as integer = 2, 
\fBnumberOfNeighbors\fR as integer = 15, 
\fBlocalConnectivity\fR as double = 1, 
\fBKnnIter\fR as integer = 64, 
\fBbandwidth\fR as double = 1, 
\fBcustomNumberOfEpochs\fR as integer = \fB<NULL>\fR, 
\fBcustomMapCutoff\fR as double = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
UMAP: Uniform Manifold Approximation and Projection for Dimension Reduction
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -
.PP
.PP
\fBdimension\fB \fR\- -
.PP
.PP
\fBcustomMapCutoff\fB \fR\- 
 cutoff value in range \fB[0,1]\fR

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
umap
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
