'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EbiWS.WsDbfetchSOAP
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.ebi.ac.uk/ws/services/WSDbfetch", ConfigurationName:="EbiWS.WsDbfetchSOAP.WSDBFetchServer")>  _
    Public Interface WSDBFetchServer
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getDbFormats()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getDbFormatsAsync()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub fetchData()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub fetchDataAsync()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub fetchBatch()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub fetchBatchAsync()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getSupportedDBs()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getSupportedDBsAsync()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getSupportedFormats()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getSupportedFormatsAsync()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getFormatStyles()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getFormatStylesAsync()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getSupportedStyles()
        
        <System.ServiceModel.OperationContractAttribute()>  _
        Sub getSupportedStylesAsync()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSDBFetchServerChannel
        Inherits EbiWS.WsDbfetchSOAP.WSDBFetchServer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSDBFetchServerClient
        Inherits System.ServiceModel.ClientBase(Of EbiWS.WsDbfetchSOAP.WSDBFetchServer)
        Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub getDbFormats() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getDbFormats
            MyBase.Channel.getDbFormats
        End Sub
        
        Public Sub getDbFormatsAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getDbFormatsAsync
            MyBase.Channel.getDbFormatsAsync
        End Sub
        
        Public Sub fetchData() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.fetchData
            MyBase.Channel.fetchData
        End Sub
        
        Public Sub fetchDataAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.fetchDataAsync
            MyBase.Channel.fetchDataAsync
        End Sub
        
        Public Sub fetchBatch() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.fetchBatch
            MyBase.Channel.fetchBatch
        End Sub
        
        Public Sub fetchBatchAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.fetchBatchAsync
            MyBase.Channel.fetchBatchAsync
        End Sub
        
        Public Sub getSupportedDBs() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getSupportedDBs
            MyBase.Channel.getSupportedDBs
        End Sub
        
        Public Sub getSupportedDBsAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getSupportedDBsAsync
            MyBase.Channel.getSupportedDBsAsync
        End Sub
        
        Public Sub getSupportedFormats() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getSupportedFormats
            MyBase.Channel.getSupportedFormats
        End Sub
        
        Public Sub getSupportedFormatsAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getSupportedFormatsAsync
            MyBase.Channel.getSupportedFormatsAsync
        End Sub
        
        Public Sub getFormatStyles() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getFormatStyles
            MyBase.Channel.getFormatStyles
        End Sub
        
        Public Sub getFormatStylesAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getFormatStylesAsync
            MyBase.Channel.getFormatStylesAsync
        End Sub
        
        Public Sub getSupportedStyles() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getSupportedStyles
            MyBase.Channel.getSupportedStyles
        End Sub
        
        Public Sub getSupportedStylesAsync() Implements EbiWS.WsDbfetchSOAP.WSDBFetchServer.getSupportedStylesAsync
            MyBase.Channel.getSupportedStylesAsync
        End Sub
    End Class
End Namespace
