.\" man page create by R# package system.
.TH REGPRECISE 1 2000-1月 "join" "join"
.SH NAME
join \- 
.SH SYNOPSIS
\fIjoin(\fBblast\fR as any, 
\fBregulators\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
regprecise
.SH FILES
.PP
TRNtoolkit.dll
.PP
.SH AUTHOR
Written by \fBPSNovichkov@lbl.gov; <br />
                        rodionov@burnham.org\fR
