.\" man page create by R# package system.
.TH REGPRECISE 1 2000-1月 "match_taxonomy" "match_taxonomy"
.SH NAME
match_taxonomy \- 
.SH SYNOPSIS
\fImatch_taxonomy(\fBncbi\fR as <generic> AssemblySummaryGenbank, 
\fBregprecise\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBncbi\fB \fR\- -. 
.PP
.PP
\fBregprecise\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
regprecise
.SH FILES
.PP
TRNtoolkit.dll
.PP
.SH AUTHOR
Written by \fBPSNovichkov@lbl.gov; <br />
                        rodionov@burnham.org\fR
