.\" man page create by R# package system.
.TH REGPRECISE 1 2000-Jan "read.regulators" "read.regulators"
.SH NAME
read.regulators \- 
.SH SYNOPSIS
\fIread.regulators(\fBfile\fR as string);\fR
.SH SEE ALSO
regprecise
.SH FILES
.PP
TRNtoolkit.dll
.PP
.SH AUTHOR
Written by \fBPSNovichkov@lbl.gov; <br />
                        rodionov@burnham.org\fR
