.\" man page create by R# package system.
.TH WGCNA 1 2000-1月 "interations" "interations"
.SH NAME
interations \- append protein iteration network based on the WGCNA weights.
.SH SYNOPSIS
\fIinterations(\fBg\fR as <generic> NetworkGraph, 
\fBWGCNA\fR as <generic> WGCNAWeight, 
\fBmodules\fR as list, 
\fBthreshold\fR as double = 0.3);\fR
.SH DESCRIPTION
.PP
append protein iteration network based on the WGCNA weights.
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBWGCNA\fB \fR\- -. 
.PP
.PP
\fBmodules\fB \fR\- -. 
.PP
.PP
\fBthreshold\fB \fR\- -. 
.PP
.SH SEE ALSO
WGCNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
