.\" man page create by R# package system.
.TH WGCNA 1 2000-Jan "interations" "interations"
.SH NAME
interations \- 
.SH SYNOPSIS
\fIinterations(\fBg\fR as <generic> NetworkGraph, 
\fBWGCNA\fR as <generic> WGCNAWeight, 
\fBmodules\fR as list, 
\fBthreshold\fR as double = 0.3);\fR
.SH SEE ALSO
WGCNA
.SH FILES
.PP
TRNtoolkit.dll
.PP
