.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "as.deg" "as.deg"
.SH NAME
as.deg \- 
.SH SYNOPSIS
\fIas.deg(\fBx\fR as <generic> Object, 
\fBlogFC\fR as string = "logFC", 
\fBpvalue\fR as string = "pvalue", 
\fBlabel\fR as string = "id", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
