'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Analysis.RNA_Seq.TSSAR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dskellam &lt;- function(x, lambda1, lambda2=lambda1, log=FALSE){
        ''' # density (PMF) of Skellam distriubition (difference of Poissons)
        '''    if (missing(x)|missing(lambda1)) stop(&quot;first 2 arguments are required&quot;)
        '''    lambdas &lt;- c(lambda1,lambda2)
        '''    oops &lt;- !(is.finite(lambdas)&amp;(lambdas&gt;=0))
        '''    if(any(oops)) {
        '''        warning(&quot;NaNs produced&quot;)
        '''        lambdas[oops] &lt;- NaN
        '''        lambda1 &lt;- lambdas[1:length(lambda1)]
        '''        lambda2 &lt;- lambdas[(length(lambda1)+1):length(lambdas)]
        '''    }
        '''   # make all args the same  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dskellam() As String
            Get
                Return ResourceManager.GetString("dskellam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dskellam.sp &lt;- function(x, lambda1, lambda2=lambda1, log=FALSE){
        ''' # saddlepoint density (PMF) for Skellam distribution
        '''  terms=1
        '''    if (missing(x)|missing(lambda1)) stop(&quot;first 2 arguments are required&quot;)
        '''    s &lt;- log(0.5*(x+sqrt(x^2+4*lambda1*lambda2))/lambda1)# the saddlepoint
        '''    K &lt;- lambda1*(exp(s)-1)+lambda2*(exp(-s)-1)	# CGF(s)
        '''    K2 &lt;- lambda1*exp(s)+lambda2*exp(-s)        # CGF&apos;&apos;(s)
        '''    if (terms&lt;1) {
        '''        ret &lt;- exp(K-x*s)/sqrt(2*pi*K2)         # saddlepoint density
        '''    } else {
        '''        c &lt;- ( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dskellam_sp() As String
            Get
                Return ResourceManager.GetString("dskellam_sp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pskellam &lt;- function(q, lambda1, lambda2=lambda1, lower.tail=TRUE, log.p=FALSE){
        ''' # CDF of Skellam distriubition (difference of Poissons)
        '''    if (missing(q)|missing(lambda1)) stop(&quot;first 2 arguments are required&quot;)
        '''    lambdas &lt;- c(lambda1,lambda2)
        '''    oops &lt;- !(is.finite(lambdas)&amp;(lambdas&gt;=0))
        '''    if(any(oops)) {
        '''        warning(&quot;NaNs produced&quot;)
        '''        lambdas[oops] &lt;- NaN
        '''        lambda1 &lt;- lambdas[1:length(lambda1)]
        '''        lambda2 &lt;- lambdas[(length(lambda1)+1):length(lambdas)]
        '''    }
        '''   # CDF is a step  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property pskellam() As String
            Get
                Return ResourceManager.GetString("pskellam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pskellam.sp &lt;- function(q, lambda1, lambda2=lambda1, lower.tail=TRUE, log.p=FALSE) {
        ''' # Luganni-Rice saddlepoint CDF with Butler&apos;s 2nd continuity correction
        '''    if (missing(q)|missing(lambda1)) stop(&quot;first 2 arguments are required&quot;)
        '''    if (lower.tail) {
        '''        xm &lt;- -floor(q)-0.5                                     # continuity corrected x
        '''       # distribution specific variables
        '''        s &lt;- log(0.5*(xm+sqrt(xm^2+4*lambda2*lambda1))/lambda2) # the saddlepoint
        '''        K &lt;- lambda2*(exp(s)-1)+lambda1*(exp( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property pskellam_sp() As String
            Get
                Return ResourceManager.GetString("pskellam_sp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qskellam &lt;- function(p, lambda1, lambda2=lambda1, lower.tail=TRUE, log.p=FALSE){
        ''' # inverse CDF of Skellam distriubition (difference of Poissons)
        '''    if (missing(p)|missing(lambda1)) stop(&quot;first 2 arguments are required&quot;)
        '''   # make all args the same length (for subsetting)
        '''    lens &lt;- c(length(p),length(lambda1),length(lambda2))
        '''    len &lt;- max(lens)
        '''    if(len&gt;min(lens)) {
        '''        if (all(len/lens!=len%/%lens)) warning(&quot;longer object length is not a multiple of shorter object length&quot;, domain=NA)
        '''        p &lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property qskellam() As String
            Get
                Return ResourceManager.GetString("qskellam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rskellam &lt;- function(n, lambda1, lambda2=lambda1){
        ''' # Skellam random variables
        '''    if (missing(n)|missing(lambda1)) stop(&quot;first 2 arguments are required&quot;)
        '''    if (length(n)&gt;1) n &lt;- length(n)
        '''    lambda1 &lt;- rep(lambda1,length.out=n)
        '''    lambda2 &lt;- rep(lambda2,length.out=n)
        '''    oops &lt;- !(is.finite(lambda1)&amp;(lambda1&gt;=0)&amp;is.finite(lambda2)&amp;(lambda2&gt;=0))
        '''    if(any(oops)) warning(&quot;NaNs produced&quot;)
        '''    ret &lt;- rep(NaN,length.out=n)
        '''    n &lt;- n-sum(oops)
        '''    ret[!oops] &lt;- rpois(n,lambda1[!oops])-rpois(n,lambda2[!oops [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property rskellam() As String
            Get
                Return ResourceManager.GetString("rskellam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #!/usr/bin/perl
        '''#Last changed Time-stamp: &lt;2013-06-10 17:00:35 fabian&gt;
        '''    
        '''use strict;
        '''use warnings;
        '''use Getopt::Long;
        '''use Data::Dumper;
        '''use Pod::Usage;
        '''use File::Basename;
        '''use File::Temp qw(tempfile);
        '''use vars qw/ %READS @TSS_plus @TSS_minus %coverage/;
        '''
        '''my $call = join(&quot; &quot;, $0, @ARGV);
        '''
        '''# set variables and default parameters
        '''my $ctdir =&apos;./&apos;;
        '''
        '''my $SamFile_Library_P =&apos;&apos;;
        '''my $SamFile_Library_M =&apos;&apos;;
        '''
        '''my $verbose = 0;
        '''my $clean = 1;
        '''my $score_mode = &apos;d&apos;;
        '''my $cluster = 1;
        '''my $prorata = 0;
        '''my $consecutiv_range  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TSSAR() As String
            Get
                Return ResourceManager.GetString("TSSAR", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
