.\" man page create by R# package system.
.TH BIOM_KIT 1 2000-1月 "read.matrix" "read.matrix"
.SH NAME
read.matrix \- 
.SH SYNOPSIS
\fIread.matrix(\fBfile\fR as any, 
\fBdenseMatrix\fR as boolean = TRUE, 
\fBsuppressErr\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
BIOM_kit
.SH FILES
.PP
metagenomics_kit.dll
.PP
