.\" man page create by R# package system.
.TH PROPERTY_EDIT 1 2000-1月 "Reversion.Plus" "Reversion.Plus"
.SH NAME
Reversion.Plus \- 
.SH SYNOPSIS
\fIReversion.Plus(\fBmodel\fR as <generic> ModelBaseType);\fR
.SH SEE ALSO
property_edit
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
