.\" man page create by R# package system.
.TH PROPERTY_EDIT 1 2000-1月 "Write.DBLinks" "Write.DBLinks"
.SH NAME
Write.DBLinks \- 
.SH SYNOPSIS
\fIWrite.DBLinks(\fBmodel\fR as <generic> ModelBaseType, 
\fBvalue\fR as <generic> IEnumerable`1);\fR
.SH SEE ALSO
property_edit
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
