.\" man page create by R# package system.
.TH OBO 1 2000-1月 "filter.is_obsolete" "filter.is_obsolete"
.SH NAME
filter.is_obsolete \- removes all terms which is \fBis_obsolete\fR
.SH SYNOPSIS
\fIfilter.is_obsolete(\fBobo\fR as <generic> GO_OBO);\fR
.SH DESCRIPTION
.PP
removes all terms which is \fBis_obsolete\fR
.PP
.SH OPTIONS
.PP
\fBobo\fB \fR\- -. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
