.\" man page create by R# package system.
.TH OBO 1 2000-1月 "filter_properties" "filter_properties"
.SH NAME
filter_properties \- make data filter of the \fBproperty_value\fR in a term
.SH SYNOPSIS
\fIfilter_properties(\fBobo\fR as <generic> GO_OBO, 
\fBexcludes\fR as string);\fR
.SH DESCRIPTION
.PP
make data filter of the \fBproperty_value\fR in a term
.PP
.SH OPTIONS
.PP
\fBobo\fB \fR\- -. 
.PP
.PP
\fBexcludes\fB \fR\- 
 the property name list for make excludes
. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
