.\" man page create by R# package system.
.TH OBO 1 2000-1月 "lineage_term" "lineage_term"
.SH NAME
lineage_term \- 
.SH SYNOPSIS
\fIlineage_term(\fBterm\fR as <generic> TermTree`1);\fR
.SH OPTIONS
.PP
\fBterm\fB \fR\- 
 \fB@\fRP:SMRUCC.genomics.Data.GeneOntology.obographs.DAGTree.dag\fB which could be build from the \fRontologyTree`` function.
. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
