.\" man page create by R# package system.
.TH OBO 1 2000-1月 "open.obo" "open.obo"
.SH NAME
open.obo \- open the ontology obo file reader
.SH SYNOPSIS
\fIopen.obo(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open the ontology obo file reader
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
This obo file reader object could be used as the data source for read 
 other database
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
