.\" man page create by R# package system.
.TH OBO 1 2000-01-01 "read.obo" "read.obo"
.SH NAME
read.obo \- parse the obo file
.SH SYNOPSIS
\fIread.obo(\fBpath\fR as string);\fR
.SH DESCRIPTION
.PP
parse the obo file
.PP
.SH OPTIONS
.PP
\fBpath\fB \fR\- -. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
