.\" man page create by R# package system.
.TH OBO 1 2000-1月 "set_namespace" "set_namespace"
.SH NAME
set_namespace \- set the namespace of the obo terms
.SH SYNOPSIS
\fIset_namespace(\fBobo\fR as <generic> GO_OBO, 
\fBdag\fR as <generic> DAGTree, 
\fBnamespace\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set the namespace of the obo terms
.PP
.SH OPTIONS
.PP
\fBobo\fB \fR\- -. 
.PP
.PP
\fBdag\fB \fR\- -. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
