.\" man page create by R# package system.
.TH OBO 1 2000-1月 "set_remarks" "set_remarks"
.SH NAME
set_remarks \- set remakrs comment text into the header of the obo file object.
.SH SYNOPSIS
\fIset_remarks(\fBobo\fR as <generic> GO_OBO, 
\fBremarks\fR as string, 
\fBappend\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
set remakrs comment text into the header of the obo file object.
.PP
.SH OPTIONS
.PP
\fBobo\fB \fR\- -. 
.PP
.PP
\fBremarks\fB \fR\- -. 
.PP
.PP
\fBappend\fB \fR\- -. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
