.\" man page create by R# package system.
.TH OBO 1 2000-1月 "write.obo" "write.obo"
.SH NAME
write.obo \- write ontology file as ascii plant text file
.SH SYNOPSIS
\fIwrite.obo(\fBobo\fR as <generic> GO_OBO, 
\fBpath\fR as string, 
\fBexcludes\fR as string = \fB<NULL>\fR, 
\fBstrip_namespace_prefix\fR as string = \fB<NULL>\fR, 
\fBstrip_property_unit\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
write ontology file as ascii plant text file
.PP
.SH OPTIONS
.PP
\fBobo\fB \fR\- -. 
.PP
.PP
\fBpath\fB \fR\- -. 
.PP
.PP
\fBexcludes\fB \fR\- -. 
.PP
.SH SEE ALSO
OBO
.SH FILES
.PP
annotationKit.dll
.PP
