.\" man page create by R# package system.
.TH FILE 1 2020-12-15 "buffer" "buffer"
.SH NAME
buffer \- create a new buffer object
.SH SYNOPSIS
\fIbuffer(\fBtype\fR as <integer> BufferObjects = [raw], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a new buffer object
.PP
.SH OPTIONS
.PP
\fBtype\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
