.\" man page create by R# package system.
.TH FILE 1 2020-12-15 "dir.create" "dir.create"
.SH NAME
dir.create \- 
.SH SYNOPSIS
\fIdir.create(\fBpath\fR as string, 
\fBshowWarnings\fR as boolean = TRUE, 
\fBrecursive\fR as boolean = FALSE, 
\fBmode\fR as string = "0777");\fR
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
