.\" man page create by R# package system.
.TH FILE 1 2020-12-15 "dir.exists" "dir.exists"
.SH NAME
dir.exists \- dir.exists returns a logical vector of TRUE or FALSE values (without names).
.SH SYNOPSIS
\fIdir.exists(\fBpaths\fR as string);\fR
.SH DESCRIPTION
.PP
dir.exists returns a logical vector of TRUE or FALSE values (without names).
.PP
.SH OPTIONS
.PP
\fBpaths\fB \fR\- 
 character vectors containing file or directory paths. 
 Tilde expansion (see path.expand) is done.

.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
