.\" man page create by R# package system.
.TH FILE 1 2020-11-02 "file.info" "file.info"
.SH NAME
file.info \- Extract File Information
.SH SYNOPSIS
\fIfile.info(\fBfiles\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Extract File Information
 
 Utility function to extract information about files on the user's file systems.
.PP
.SH OPTIONS
.PP
\fBfiles\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
