.\" man page create by R# package system.
.TH FILE 1 2020-12-15 "file.remove" "file.remove"
.SH NAME
file.remove \- Delete files or directories
.SH SYNOPSIS
\fIfile.remove(\fBx\fR as string);\fR
.SH DESCRIPTION
.PP
Delete files or directories
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
