.\" man page create by R# package system.
.TH FILE 1 2020-11-02 "getwd" "getwd"
.SH NAME
getwd \- getwd returns an absolute filepath representing the current working directory of the R process;
.SH SYNOPSIS
\fIgetwd();\fR
.SH DESCRIPTION
.PP
getwd returns an absolute filepath representing the current working directory of the R process;
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
