.\" man page create by R# package system.
.TH FILE 1 2020-11-09 "list.dirs" "list.dirs"
.SH NAME
list.dirs \- List the Files in a Directory/Folder
.SH SYNOPSIS
\fIlist.dirs(\fBdir\fR as string = "./", 
\fBfullNames\fR as boolean = TRUE, 
\fBrecursive\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
List the Files in a Directory/Folder
.PP
.SH OPTIONS
.PP
\fBdir\fB \fR\- 
 a character vector of full path names; the default corresponds to the working directory, \fBgetwd()\fR. 
 Tilde expansion (see path.expand) is performed. Missing values will be ignored.

.PP
.PP
\fBfullNames\fB \fR\- -
.PP
.PP
\fBrecursive\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
