.\" man page create by R# package system.
.TH FILE 1 2020-12-15 "open.gzip" "open.gzip"
.SH NAME
open.gzip \- decompression of a gzip file and get the deflate file data stream.
.SH SYNOPSIS
\fIopen.gzip(\fBfile\fR as <generic> Object, 
\fBtmpfileWorker\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
decompression of a gzip file and get the deflate file data stream.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path or file stream data.

.PP
.PP
\fBtmpfileWorker\fB \fR\- 
 using tempfile for process the large data file which its file length 
 is greater then the memorystream its upbound capacity.

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
