.\" man page create by R# package system.
.TH FILE 1 2020-10-29 "R.home" "R.home"
.SH NAME
R.home \- Return the R Home Directory
.SH SYNOPSIS
\fIR.home();\fR
.SH DESCRIPTION
.PP
Return the R Home Directory
 
 Return the R home directory, or the full path to a 
 component of the R installation.
 
 The R home directory is the top-level directory of the R installation being run.

 The R home directory Is often referred To As R_HOME, And Is the value Of an 
 environment variable Of that name In an R session. It can be found outside 
 an R session by R RHOME.
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
