.\" man page create by R# package system.
.TH FILE 1 2020-11-09 "readText" "readText"
.SH NAME
readText \- 
.SH SYNOPSIS
\fIreadText(\fBcon\fR as string, 
\fBencoding\fR as <integer> Encodings = [UTF8]);\fR
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
