.\" man page create by R# package system.
.TH FILE 1 2020-11-02 "readLines" "readLines"
.SH NAME
readLines \- Read Text Lines from a Connection
.SH SYNOPSIS
\fIreadLines(\fBcon\fR as string, 
\fBencoding\fR as <integer> Encodings = [UTF8]);\fR
.SH DESCRIPTION
.PP
Read Text Lines from a Connection
 
 Read some or all text lines from a connection.
.PP
.SH OPTIONS
.PP
\fBcon\fB \fR\- a connection object or a character string.
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
