.\" man page create by R# package system.
.TH FILE 1 2020-11-02 "read.list" "read.list"
.SH NAME
read.list \- read list from a given json file
.SH SYNOPSIS
\fIread.list(\fBfile\fR as string, 
\fBmode\fR as string = "character", 
\fBofVector\fR as boolean = FALSE, 
\fBencoding\fR as <integer> Encodings = [UTF8], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read list from a given json file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- A json file path
.PP
.PP
\fBmode\fB \fR\- The value mode of the loaded list object in \fBR#\fR
.PP
.PP
\fBofVector\fB \fR\- 
 Is a list of vector?

.PP
.PP
\fBenvir\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
