.\" man page create by R# package system.
.TH FILE 1 2020-11-09 "save.list" "save.list"
.SH NAME
save.list \- Save a R# object list in json file format
.SH SYNOPSIS
\fIsave.list(\fBlist\fR as <generic> Object, 
\fBfile\fR as string, 
\fBencodings\fR as <integer> Encodings = [UTF8], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Save a R# object list in json file format
.PP
.SH OPTIONS
.PP
\fBlist\fB \fR\- -
.PP
.PP
\fBfile$\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
