.\" man page create by R# package system.
.TH FILE 1 2020-11-02 "setwd" "setwd"
.SH NAME
setwd \- setwd(dir) is used to set the working directory to dir.
.SH SYNOPSIS
\fIsetwd(\fBdir\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
setwd(dir) is used to set the working directory to dir.
.PP
.SH OPTIONS
.PP
\fBdir\fB \fR\- A character String: tilde expansion will be done.
.PP
.PP
\fBenvir\fB \fR\- -
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
