.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "as_causalmodel" "as_causalmodel"
.SH NAME
as_causalmodel \- 
.SH SYNOPSIS
\fIas_causalmodel(\fBdata\fR as any, 
\fBpath\fR as any, 
\fBlatents\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
