.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "make_full_path" "make_full_path"
.SH NAME
make_full_path \- make full connected path for PLS-PM latent symbols
.SH SYNOPSIS
\fImake_full_path(\fBmanifest\fR as any, 
\fBfrom\fR as any, 
\fBto\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make full connected path for PLS-PM latent symbols
.PP
.SH OPTIONS
.PP
\fBmanifest\fB \fR\- -. 
.PP
.PP
\fBfrom\fB \fR\- class name of the from node. 
.PP
.PP
\fBto\fB \fR\- class name of the to node. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
