.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "make_path" "make_path"
.SH NAME
make_path \- 
.SH SYNOPSIS
\fImake_path(..., 
\fBfrom\fR as any = \fB<NULL>\fR, 
\fBto\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
