.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "measurement_model" "measurement_model"
.SH NAME
measurement_model \- 
.SH SYNOPSIS
\fImeasurement_model(\fBresult\fR as <generic> PLSPMResult, 
\fBas_dataframe\fR as boolean = TRUE);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
