.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "enrichment" "enrichment"
.SH NAME
enrichment \- 
.SH SYNOPSIS
\fIenrichment(\fBbackground\fR as any, 
\fBgeneSet\fR as any, 
\fBexpression\fR as any = \fB<NULL>\fR, 
\fBcut_size\fR as integer = 3, 
\fBoutputAll\fR as boolean = TRUE, 
\fBresize\fR as integer = -1, 
\fBshowProgress\fR as boolean = FALSE, 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
