.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "enrichment.go" "enrichment.go"
.SH NAME
enrichment.go \- do GO GSEA enrichment analysis
.SH SYNOPSIS
\fIenrichment.go(\fBbackground\fR as <generic> Background, 
\fBgeneSet\fR as string, 
\fBgo\fR as any, 
\fBshowProgress\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do GO GSEA enrichment analysis
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.PP
\fBgeneSet\fB \fR\- -. 
.PP
.PP
\fBgo\fB \fR\- the go database object can be the raw go obo data or the DAG graph model.. 
.PP
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
