.\" man page create by R# package system.
.TH GSEA 2 2000-1月 "fisher" "fisher"
.SH NAME
fisher \- 
.SH SYNOPSIS
\fIfisher(\fBlist\fR as string, 
\fBgeneSet\fR as string, 
\fBbackground\fR as any, 
\fBterm\fR as string = "unknown", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
GSEA
.SH FILES
.PP
gseakit.dll
.PP
