.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "Compile.CAI" "Compile.CAI"
.SH NAME
Compile.CAI \- 
.SH SYNOPSIS
\fICompile.CAI(\fBgenes\fR as <generic> FastaFile, 
\fBWorkTemp\fR as string = "./CAI_Xml");\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
