.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "compile.delta_query" "compile.delta_query"
.SH NAME
compile.delta_query \- 
.SH SYNOPSIS
\fIcompile.delta_query(\fBsource\fR as string, 
\fBsaveCsv\fR as string);\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
