.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "genome.sigma_diff" "genome.sigma_diff"
.SH NAME
genome.sigma_diff \- 并行版本的计算函数
.SH SYNOPSIS
\fIgenome.sigma_diff(\fBgenome\fR as <generic> FastaSeq, 
\fBcompare\fR as <generic> FastaSeq, 
\fBwindowsSize\fR as integer = 1000);\fR
.SH DESCRIPTION
.PP
并行版本的计算函数
.PP
.SH OPTIONS
.PP
\fBgenome\fB \fR\- -. 
.PP
.PP
\fBwindowsSize\fB \fR\- 默认为1kb的长度. 
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
