.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "Partition.Similarity.Calculates" "Partition.Similarity.Calculates"
.SH NAME
Partition.Similarity.Calculates \- 计算基因组之中的不同的功能分段之间的同质性
.SH SYNOPSIS
\fIPartition.Similarity.Calculates(\fBdata\fR as <generic> IEnumerable`1);\fR
.SH DESCRIPTION
.PP
计算基因组之中的不同的功能分段之间的同质性
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
