.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "Partitions.Creates" "Partitions.Creates"
.SH NAME
Partitions.Creates \- 
.SH SYNOPSIS
\fIPartitions.Creates(\fBPartitionRaw\fR as <generic> DataFrame, 
\fBTagCol\fR as string, 
\fBStartTag\fR as string, 
\fBStopTag\fR as string, 
\fBNt\fR as <generic> FastaSeq);\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
