.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "partition_data.create" "partition_data.create"
.SH NAME
partition_data.create \- 
.SH SYNOPSIS
\fIpartition_data.create(\fBbesthit\fR as <generic> SpeciesBesthit, 
\fBpartitions\fR as <generic> IEnumerable`1, 
\fBallCDSInfo\fR as <generic> IEnumerable`1, 
\fBfaDIR\fR as string);\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
