.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "Read.Csv.Chromsome_Partitioning" "Read.Csv.Chromsome_Partitioning"
.SH NAME
Read.Csv.Chromsome_Partitioning \- 
.SH SYNOPSIS
\fIRead.Csv.Chromsome_Partitioning(\fBpath\fR as string);\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
