.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "read.csv.genome_partition_data" "read.csv.genome_partition_data"
.SH NAME
read.csv.genome_partition_data \- 
.SH SYNOPSIS
\fIread.csv.genome_partition_data(\fBpath\fR as string);\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
