.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "rendering_merge.delta_source" "rendering_merge.delta_source"
.SH NAME
rendering_merge.delta_source \- 要求所有的文件都必须要为同一个基因组比对不同的基因组，不可以改动输出文件的文件名
.SH SYNOPSIS
\fIrendering_merge.delta_source(\fBsource\fR as string, 
\fBquery\fR as <generic> IEnumerable`1, 
\fBrender_source\fR as string, 
\fBsaveto\fR as string, 
\fBsamples\fR as integer = 1);\fR
.SH DESCRIPTION
.PP
要求所有的文件都必须要为同一个基因组比对不同的基因组，不可以改动输出文件的文件名
.PP
.SH OPTIONS
.PP
\fBsource\fB \fR\- -. 
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
