.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "sigma_diff.query" "sigma_diff.query"
.SH NAME
sigma_diff.query \- 
.SH SYNOPSIS
\fIsigma_diff.query(\fBquery\fR as string, 
\fBsbjDIR\fR as string, 
\fBEXPORT\fR as string, 
\fBwindowsSize\fR as integer = 1000);\fR
.SH OPTIONS
.PP
\fBquery\fB \fR\- Query基因组的fasta序列的文件路径. 
.PP
.PP
\fBsbjDIR\fB \fR\- 将要进行比较的基因组的fasta序列文件的存放文件夹. 
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
