.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-Jan "write.csv.genome_partition_data" "write.csv.genome_partition_data"
.SH NAME
write.csv.genome_partition_data \- 
.SH SYNOPSIS
\fIwrite.csv.genome_partition_data(\fBdat\fR as <generic> IEnumerable`1, 
\fBsaveto\fR as string);\fR
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
