.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-01-01 "Assemble.of" "Assemble.of"
.SH NAME
Assemble.of \- Do short reads assembling
.SH SYNOPSIS
\fIAssemble.of(\fBreads\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do short reads assembling
.PP
.SH OPTIONS
.PP
\fBreads\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
