.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "chars" "chars"
.SH NAME
chars \- get alphabets represents of the fasta sequence
.SH SYNOPSIS
\fIchars(\fBtype\fR as <integer> SeqTypes = [Protein]);\fR
.SH DESCRIPTION
.PP
get alphabets represents of the fasta sequence
.PP
.SH OPTIONS
.PP
\fBtype\fB \fR\- 
 the sequence data type.
. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
