.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "cut_seq.linear" "cut_seq.linear"
.SH NAME
cut_seq.linear \- 
.SH SYNOPSIS
\fIcut_seq.linear(\fBseq\fR as any, 
\fBloci\fR as any, 
\fBdoNtAutoReverse\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
