.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "fasta.headers" "fasta.headers"
.SH NAME
fasta.headers \- get/set the fasta headers title
.SH SYNOPSIS
\fIfasta.headers(\fBfa\fR as <generic> FastaSeq, 
\fBheaders\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
get/set the fasta headers title
.PP
.SH OPTIONS
.PP
\fBfa\fB \fR\- -. 
.PP
.PP
\fBheaders\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
