.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "fasta.titles" "fasta.titles"
.SH NAME
fasta.titles \- get the fasta titles from a collection of fasta sequence
.SH SYNOPSIS
\fIfasta.titles(\fBfa\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get the fasta titles from a collection of fasta sequence
.PP
.SH OPTIONS
.PP
\fBfa\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
