.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "fasta" "fasta"
.SH NAME
fasta \- Create a new fasta sequence objects
.SH SYNOPSIS
\fIfasta(\fBseq\fR as string, 
\fBattrs\fR as string);\fR
.SH DESCRIPTION
.PP
Create a new fasta sequence objects
.PP
.SH OPTIONS
.PP
\fBseq\fB \fR\- -. 
.PP
.PP
\fBattrs\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
