.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "fasta" "fasta"
.SH NAME
fasta \- Create a new fasta sequence objects
.SH SYNOPSIS
\fIfasta(\fBseq\fR as string, 
\fBattrs\fR as string);\fR
.SH DESCRIPTION
.PP
Create a new fasta sequence objects
.PP
.SH OPTIONS
.PP
\fBseq\fB \fR\- the raw sequence data text of the target fasta sequence.. 
.PP
.PP
\fBattrs\fB \fR\- 
 a character vector of the fasta headers data: the first element of this 
 vector is the sequence id, and the other elements are the description 
 information of the target sequence.
. 
.PP
.SH VALUE
.PP
a new @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR sequence object.
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
