.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "list_index" "list_index"
.SH NAME
list_index \- make sequence list index
.SH SYNOPSIS
\fIlist_index(\fBx\fR as any, 
\fBids\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make sequence list index
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBids\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
