.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "make_clusterTree" "make_clusterTree"
.SH NAME
make_clusterTree \- 
.SH SYNOPSIS
\fImake_clusterTree(\fBfingerprints\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
