.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "mass" "mass"
.SH NAME
mass \- evaluate the molecule mass of the given sequence
.SH SYNOPSIS
\fImass(\fBseqs\fR as any, 
\fBtype\fR as <integer> SeqTypes = [Generic], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
evaluate the molecule mass of the given sequence
.PP
.SH OPTIONS
.PP
\fBseqs\fB \fR\- -. 
.PP
.PP
\fBtype\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
