.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "MSA.of" "MSA.of"
.SH NAME
MSA.of \- Do multiple sequence alignment
.SH SYNOPSIS
\fIMSA.of(\fBseqs\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do multiple sequence alignment
.PP
.SH OPTIONS
.PP
\fBseqs\fB \fR\- A fasta sequence collection. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
