.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "open.fasta" "open.fasta"
.SH NAME
open.fasta \- 
.SH SYNOPSIS
\fIopen.fasta(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
