.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "open.fasta" "open.fasta"
.SH NAME
open.fasta \- open the fasta sequence file
.SH SYNOPSIS
\fIopen.fasta(\fBfile\fR as string, 
\fBread\fR as boolean = TRUE, 
\fBline_break\fR as integer = -1, 
\fBdelimiter\fR as string = "|", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open the fasta sequence file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBread\fB \fR\- 
 load a set of fasta sequence data in lazy mode? default is yes.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a lazy collection of the fasta sequence data
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
