.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "parse.fasta" "parse.fasta"
.SH NAME
parse.fasta \- parse the fasta sequence object from the given text data
.SH SYNOPSIS
\fIparse.fasta(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
parse the fasta sequence object from the given text data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
