.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "read.fasta" "read.fasta"
.SH NAME
read.fasta \- read a fasta sequence collection file
.SH SYNOPSIS
\fIread.fasta(\fBfile\fR as string, 
\fBlazyStream\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
read a fasta sequence collection file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
