.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "read_stockholm" "read_stockholm"
.SH NAME
read_stockholm \- read stockholm MSA file.
.SH SYNOPSIS
\fIread_stockholm(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read stockholm MSA file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path of the stockholm format multiple sequence alignment file.
. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.Analysis.SequenceAlignment.MSA.Tabular.Stockholm\fR alignment object that contains the 
 aligned sequence data of the target stockholm file.
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
