.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-01-01 "read.seq" "read.seq"
.SH NAME
read.seq \- Read a single fasta sequence file
.SH SYNOPSIS
\fIread.seq(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Read a single fasta sequence file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 Just contains one sequence
. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
