.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "read.seq" "read.seq"
.SH NAME
read.seq \- Read a single fasta sequence file
.SH SYNOPSIS
\fIread.seq(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Read a single fasta sequence file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path of the target sequence file, Just contains one sequence
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR object that read from the given sequence file;
 
 this function returns a R# error message object if the given file is not a 
 valid fasta sequence file or a genbank database file.
.PP
.SH DETAILS
.PP
for input a genbank database file, this function will extract the origin sequence fasta object
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
