.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "read.fingerprint_bson" "read.fingerprint_bson"
.SH NAME
read.fingerprint_bson \- 
.SH SYNOPSIS
\fIread.fingerprint_bson(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
