.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "seq_vector" "seq_vector"
.SH NAME
seq_vector \- embedding the given fasta sequence as vector
.SH SYNOPSIS
\fIseq_vector(\fBsgt\fR as <generic> CreateMatrix, 
\fBseqs\fR as any, 
\fBas_dataframe\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
embedding the given fasta sequence as vector
.PP
.SH OPTIONS
.PP
\fBsgt\fB \fR\- -. 
.PP
.PP
\fBseqs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH EXAMPLES
.PP
imports "bioseq.fasta" from "seqtoolkit";
 
 # get fasta sequence data
 let seqs = read.fasta("./proteins.fa");
 let sgt = seq_sgt(moltype = "prot");
 let vec = sgt |> seq_vector(seqs);
 
 # run data analysis on the generated embedding vectors
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
