.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-Jan "seq_sgt" "seq_sgt"
.SH NAME
seq_sgt \- Create algorithm for make sequence embedding
.SH SYNOPSIS
\fIseq_sgt(\fBmoltype\fR as <integer> SeqTypes = [Protein], 
\fBkappa\fR as double = 1, 
\fBlengthsensitive\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Create algorithm for make sequence embedding
.PP
.SH OPTIONS
.PP
\fBmoltype\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
