.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "takes" "takes"
.SH NAME
takes \- 
.SH SYNOPSIS
\fItakes(\fBx\fR as any, 
\fBgene_ids\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
