.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "write.fasta" "write.fasta"
.SH NAME
write.fasta \- write a fasta sequence or a collection of fasta sequence object
.SH SYNOPSIS
\fIwrite.fasta(\fBseq\fR as any, 
\fBfile\fR as string, 
\fBlineBreak\fR as integer = -1, 
\fBdelimiter\fR as string = " ", 
\fBencoding\fR as <integer> Encodings = [ASCII], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
write a fasta sequence or a collection of fasta sequence object
.PP
.SH OPTIONS
.PP
\fBseq\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBlineBreak\fB \fR\- 
 The sequence length in one line, negative value or ZERo means no line break.
. 
.PP
.PP
\fBencoding\fB \fR\- The text encoding value of the generated fasta file.. 
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
