.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "write.fasta" "write.fasta"
.SH NAME
write.fasta \- write a fasta sequence or a collection of fasta sequence object
.SH SYNOPSIS
\fIwrite.fasta(\fBseq\fR as any, 
\fBfile\fR as any, 
\fBlineBreak\fR as integer = -1, 
\fBdelimiter\fR as string = " ", 
\fBfilter_empty\fR as boolean = FALSE, 
\fBencoding\fR as <integer> Encodings = [ASCII], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
write a fasta sequence or a collection of fasta sequence object
.PP
.SH OPTIONS
.PP
\fBseq\fB \fR\- 
 the fasta sequence data for write into the target file, which can be a 
 single @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR object, a @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaFile\fR object, a 
 collection of the @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR object, a character vector of the 
 raw sequence data, a fastq sequence collection, or a pipeline object that 
 produces a set of the @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR sequence data.
. 
.PP
.PP
\fBfile\fB \fR\- 
 the output target: a file path of the generated fasta sequence file, a file 
 stream object, or a fasta stream writer object that is created by the 
 \fBopen.fasta\fR api in write mode.
. 
.PP
.PP
\fBlineBreak\fB \fR\- 
 The sequence length in one line, negative value or ZERo means no line break.
. 
.PP
.PP
\fBdelimiter\fB \fR\- 
 the delimiter character for merge the fasta headers title of the sequence 
 data.
. 
.PP
.PP
\fBfilter_empty\fB \fR\- 
 skip write sequence if the sequence object has no sequence data
. 
.PP
.PP
\fBencoding\fB \fR\- The text encoding value of the generated fasta file.. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a boolean value of the file save result: TRUE means the sequence data has 
 been written into the target file successfully;
 
 this function returns a R# error message object if the given sequence data 
 can not be cast to a fasta sequence collection, or the target file can not 
 be opened for write.
.PP
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
