.\" man page create by R# package system.
.TH BIOSEQ.FASTA 4 2000-1月 "write_fingerprint" "write_fingerprint"
.SH NAME
write_fingerprint \- 
.SH SYNOPSIS
\fIwrite_fingerprint(\fBfile\fR as <generic> FingerprintMatrixWriter, 
\fBseqs\fR as any, 
\fBdebug\fR as integer = -1, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.fasta
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
