.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "context" "context"
.SH NAME
context \- 
.SH SYNOPSIS
\fIcontext(\fBloci\fR as any, 
\fBdistance\fR as integer, 
\fBnote\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
