.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "filter_strand" "filter_strand"
.SH NAME
filter_strand \- 
.SH SYNOPSIS
\fIfilter_strand(\fBgenes\fR as any, 
\fBstrand\fR as any = "+", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
