.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "set_context" "set_context"
.SH NAME
set_context \- set genomics context of the matched motif site
.SH SYNOPSIS
\fIset_context(\fBsites\fR as any, 
\fBgenomics\fR as <generic> GFFTable, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set genomics context of the matched motif site
.PP
.SH OPTIONS
.PP
\fBsites\fB \fR\- a collection of the motif sites. 
.PP
.PP
\fBgenomics\fB \fR\- the genomics feature information as the context for make location assignment.. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the [VirtualFootprint](cref:T:SMRUCC.genomics.Model.Network.VirtualFootprint.DocumentFormat.VirtualFootprint) motif site object that 
 its location region data has been assigned with the genomics context 
 information;
 
 this function returns a R# error message object if the input motif 
 sites data can not be cast to a collection of the 
 [VirtualFootprint](cref:T:SMRUCC.genomics.Model.Network.VirtualFootprint.DocumentFormat.VirtualFootprint) object.
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
