.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "TSS_upstream" "TSS_upstream"
.SH NAME
TSS_upstream \- 
.SH SYNOPSIS
\fITSS_upstream(\fBgenome\fR as any, 
\fBgenes\fR as any = \fB<NULL>\fR, 
\fBupstream_len\fR as integer = 150, 
\fBsimple_title\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
