.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "TSS_upstream" "TSS_upstream"
.SH NAME
TSS_upstream \- get TSS upstream site sequence data
.SH SYNOPSIS
\fITSS_upstream(\fBgenome\fR as any, 
\fBgenes\fR as any = \fB<NULL>\fR, 
\fBupstream_len\fR as integer = 150, 
\fBsimple_title\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get TSS upstream site sequence data
.PP
.SH OPTIONS
.PP
\fBgenome\fB \fR\- 
 the genome reference sequence data source, which can be a 
 [File](cref:T:SMRUCC.genomics.Assembly.NCBI.GenBank.GBFF.File) ncbi genbank assembly object or a 
 [FastaSeq](cref:T:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq) nucleotide sequence object.
. 
.PP
.PP
\fBgenes\fB \fR\- 
 gene list could be omit if the input genome data is a ncbi genbank model object. 
 then all gene features inside the input genbank assembly will be used for export of 
 the TSS upstream site.. 
.PP
.PP
\fBupstream_len\fB \fR\- 
 the length in nucleotide of the TSS upstream region.
. 
.PP
.PP
\fBsimple_title\fB \fR\- 
 generate the fasta headers title of the output sequence in a simple 
 format?
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the [FastaSeq](cref:T:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq) TSS upstream region nucleotide 
 sequence data, one sequence element for each of the target gene;
 
 this function returns NULL if the input genome data is nothing, or a R# 
 error message object if the given genome data type is not supported.
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
