.\" man page create by R# package system.
.TH BIOMODELS.STRINGDB.PPI 1 2000-1月 "as.network" "as.network"
.SH NAME
as.network \- 
.SH SYNOPSIS
\fIas.network(\fBstringNetwork\fR as <generic> InteractExports[], 
\fBuniprot\fR as any, 
\fBcoordinates\fR as <generic> Coordinates[] = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioModels.stringdb.ppi
.SH FILES
.PP
cytoscape.dll
.PP
