.\" man page create by R# package system.
.TH BIOMODELS.STRINGDB.PPI 1 2000-1月 "read.string_interactions" "read.string_interactions"
.SH NAME
read.string_interactions \- 
.SH SYNOPSIS
\fIread.string_interactions(\fBstring_interactions\fR as string);\fR
.SH SEE ALSO
bioModels.stringdb.ppi
.SH FILES
.PP
cytoscape.dll
.PP
