.\" man page create by R# package system.
.TH BIOMODELS.STRINGDB.PPI 1 2000-1月 "read.string_db" "read.string_db"
.SH NAME
read.string_db \- 
.SH SYNOPSIS
\fIread.string_db(\fBfile\fR as string, 
\fBremove_taxonomyId\fR as boolean = TRUE, 
\fBlink_matrix\fR as boolean = FALSE, 
\fBcombine_score\fR as double = -1);\fR
.SH SEE ALSO
bioModels.stringdb.ppi
.SH FILES
.PP
cytoscape.dll
.PP
