.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "analysis" "analysis"
.SH NAME
analysis \- run pan-genome analysis
.SH SYNOPSIS
\fIanalysis(\fBpangenome\fR as <generic> GenomeAnalyzer, 
\fBorthologSet\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run pan-genome analysis
.PP
.SH OPTIONS
.PP
\fBpangenome\fB \fR\- context data for run pan-genome analysis. 
.PP
.PP
\fBorthologSet\fB \fR\- gene ortholog data table, usually be the bi-direction best hit of the blast result. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
