.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "scatter_set" "scatter_set"
.SH NAME
scatter_set \- 
.SH SYNOPSIS
\fIscatter_set(\fBresult\fR as <generic> PanGenomeResult);\fR
.SH OPTIONS
.PP
\fBresult\fB \fR\- -. 
.PP
.SH VALUE
.PP
a tuple list that contains three elements:
 
 1. \fBstats\fR: @\fBT:SMRUCC.genomics.Analysis.PanGenome.ReportJSON.GenomeStatRow\fR
 2. \fBpca\fR: @\fBT:SMRUCC.genomics.Analysis.PanGenome.ReportJSON.PCAScatterDataset\fR
 3. \fBentropy\fR: @\fBT:SMRUCC.genomics.Analysis.PanGenome.ReportJSON.GenomeEntropyDataset\fR
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
