.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "set_ortho_group" "set_ortho_group"
.SH NAME
set_ortho_group \- set orthology group for make gene family
.SH SYNOPSIS
\fIset_ortho_group(\fBx\fR as any, 
\fBuf\fR as <generic> UnionFind, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set orthology group for make gene family
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBuf\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
