.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "source_id" "source_id"
.SH NAME
source_id \- set species name to the genome gff3 context model
.SH SYNOPSIS
\fIsource_id(\fBgenome\fR as <generic> GFFTable, 
\fBsource_name\fR as string);\fR
.SH DESCRIPTION
.PP
set species name to the genome gff3 context model
.PP
.SH OPTIONS
.PP
\fBgenome\fB \fR\- -. 
.PP
.PP
\fBsource_name\fB \fR\- -. 
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
