.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "sv_entropy" "sv_entropy"
.SH NAME
sv_entropy \- get the SV structural variation information entropy scatter data and the kmeans clustering result
.SH SYNOPSIS
\fIsv_entropy(\fBresult\fR as <generic> PanGenomeResult, 
\fBcluster_count\fR as integer = 4);\fR
.SH DESCRIPTION
.PP
get the SV structural variation information entropy scatter data and the kmeans clustering result
.PP
.SH OPTIONS
.PP
\fBresult\fB \fR\- -. 
.PP
.PP
\fBcluster_count\fB \fR\- the k value of the kmeans clustering, default is 4. 
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
