.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "sv_median_matrix" "sv_median_matrix"
.SH NAME
sv_median_matrix \- export the SV Median matrix of the structural variations
.SH SYNOPSIS
\fIsv_median_matrix(\fBresult\fR as <generic> PanGenomeResult);\fR
.SH DESCRIPTION
.PP
export the SV Median matrix of the structural variations
 (rows are gene families which have at least one SV event, columns are genomes)
.PP
.SH OPTIONS
.PP
\fBresult\fB \fR\- -. 
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
