.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "sv_table" "sv_table"
.SH NAME
sv_table \- 
.SH SYNOPSIS
\fIsv_table(\fBresult\fR as <generic> PanGenomeResult, 
\fBindex\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
pangenome
.SH FILES
.PP
comparative_toolkit.dll
.PP
