.\" man page create by R# package system.
.TH OTU_TABLE 1 2000-1月 "core_microbiome" "core_microbiome"
.SH NAME
core_microbiome \- evaluate the core microbiome species across all sample data
.SH SYNOPSIS
\fIcore_microbiome(\fBx\fR as any, 
\fBprevalence\fR as double = 0.8, 
\fBabundance\fR as double = 0.0001, 
\fBdetectionLimit\fR as double = 1E-05, 
\fBsampleinfo\fR as any = \fB<NULL>\fR, 
\fBtop_n\fR as <generic> Int32 = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
evaluate the core microbiome species across all sample data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBprevalence\fB \fR\- -. 
.PP
.PP
\fBabundance\fB \fR\- -. 
.PP
.PP
\fBdetectionLimit\fB \fR\- -. 
.PP
.PP
\fBsampleinfo\fB \fR\- -. 
.PP
.PP
\fBtop_n\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
OTU_table
.SH FILES
.PP
metagenomics_kit.dll
.PP
