.\" man page create by R# package system.
.TH OTU_TABLE 1 2000-Jan "make_otu_table" "make_otu_table"
.SH NAME
make_otu_table \- 
.SH SYNOPSIS
\fImake_otu_table(\fBsamples\fR as any, 
\fBtaxonomy_tree\fR as <generic> NcbiTaxonomyTree, 
\fBfilter_missing\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
OTU_table
.SH FILES
.PP
metagenomics_kit.dll
.PP
