.\" man page create by R# package system.
.TH DUNNART 1 2000-1月 "as.graphObj" "as.graphObj"
.SH NAME
as.graphObj \- 
.SH SYNOPSIS
\fIas.graphObj(\fBnetwork\fR as <generic> NetworkGraph, 
\fBcolorSet\fR as string = "Paired:c12", 
\fBgroup_key\fR as string = "map", 
\fBfillOpacity\fR as double = 0.5, 
\fBlighten\fR as double = 0.1);\fR
.SH SEE ALSO
dunnart
.SH FILES
.PP
cytoscape.dll
.PP
