.\" man page create by R# package system.
.TH DUNNART 1 2000-1月 "network_map" "network_map"
.SH NAME
network_map \- 
.SH SYNOPSIS
\fInetwork_map(\fBtemplate\fR as <generic> NetworkGraph, 
\fBmaps\fR as <generic> Pathway[], 
\fBdesc\fR as boolean = FALSE, 
\fBcolorSet\fR as string = "Paired:c12", 
\fBfillOpacity\fR as double = 0.5, 
\fBlighten\fR as double = 0.1, 
\fBisConnected\fR as boolean = TRUE);\fR
.SH SEE ALSO
dunnart
.SH FILES
.PP
cytoscape.dll
.PP
