<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Library</OutputType>
    <RootNamespace>circoskit</RootNamespace>
    <AssemblyName>circos</AssemblyName>
    <OutputPath>../../../../assembly/</OutputPath>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	 <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;Rsharp_app_release</Configurations>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GCModeller\core\Bio.Assembly\biocore-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\interops\visualize\Circos\Circos\Circos.vbproj" />
    <ProjectReference Include="..\..\..\R-sharp\Library\shares\graphics.common_runtime\R_graphics.common_runtime.vbproj" />
    <ProjectReference Include="..\..\..\R-sharp\R#\Rsharp-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
  </ItemGroup>

  <Import Project="..\..\..\R-sharp\Library\shares\R_graphic.interop\R_graphic.interop.projitems" Label="Shared" />
 
</Project>