.\" man page create by R# package system.
.TH STRINGDB.WEB_API 1 2000-1月 "downloads.genomics.interactions" "downloads.genomics.interactions"
.SH NAME
downloads.genomics.interactions \- 
.SH SYNOPSIS
\fIdownloads.genomics.interactions(\fBPTT\fR as <generic> PTT, 
\fBEXPORT\fR as string = "./");\fR
.SH SEE ALSO
stringdb.web_api
.SH FILES
.PP
cytoscape.dll
.PP
