.\" man page create by R# package system.
.TH TRACK.PLOTS 1 2000-01-01 "fill_color" "fill_color"
.SH NAME
fill_color \- Invoke set the color of the circle element on the circos plots.
.SH SYNOPSIS
\fIfill_color(\fBtrack\fR as <generic> ITrackPlot, 
\fBcolor\fR as string);\fR
.SH DESCRIPTION
.PP
Invoke set the color of the circle element on the circos plots.
.PP
.SH OPTIONS
.PP
\fBtrack\fB \fR\- -
.PP
.PP
\fBcolor\fB \fR\- The name of the color in the circos program.
.PP
.SH SEE ALSO
track.plots
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
