.\" man page create by R# package system.
.TH TRACK.PLOTS 1 2000-01-01 "radius01" "radius01"
.SH NAME
radius01 \- 
.SH SYNOPSIS
\fIradius01(\fBtrack\fR as <generic> ITrackPlot, 
\fBr1\fR as double, 
\fBr0\fR as double);\fR
.SH OPTIONS
.PP
\fBtrack\fB \fR\- -
.PP
.PP
\fBr1\fB \fR\- The radius value of the outside for this circle element.
.PP
.PP
\fBr0\fB \fR\- The radius value of the inner circle of this element.
.PP
.SH SEE ALSO
track.plots
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
