.\" man page create by R# package system.
.TH TRACK.PLOTS 1 2000-01-01 "text" "text"
.SH NAME
text \- The value For a text track Is interpreted As a text label
.SH SYNOPSIS
\fItext(\fBstart\fR as integer, 
\fBend\fR as integer, 
\fBtext\fR as string, 
\fBchr\fR as string = "chr1");\fR
.SH DESCRIPTION
.PP
The value For a text track Is interpreted As a text label 
 (other tracks require that this field be a floating point 
 number).
 
 \fB
 # value for text tracks Is interpreted as text
 chr12 1000 5000 geneA
 \fR`
.PP
.SH OPTIONS
.PP
\fBstart\fB \fR\- -
.PP
.PP
\fBend\fB \fR\- -
.PP
.PP
\fBtext\fB \fR\- -
.PP
.PP
\fBchr\fB \fR\- -
.PP
.SH SEE ALSO
track.plots
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
