.\" man page create by R# package system.
.TH TRACK.PLOTS 1 2000-01-01 "track.highlight" "track.highlight"
.SH NAME
track.highlight \- 
.SH SYNOPSIS
\fItrack.highlight(\fBhighlights\fR as <generic> Highlights, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
track.plots
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
