.\" man page create by R# package system.
.TH TRACK.PLOTS 1 2000-01-01 "track.histogram" "track.histogram"
.SH NAME
track.histogram \- 
.SH SYNOPSIS
\fItrack.histogram(\fBvalues\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
track.plots
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
