.\" man page create by R# package system.
.TH TRACK.PLOTS 1 2000-01-01 "value" "value"
.SH NAME
value \- Tracks such As scatter plot, line plot, histogram Or heat map,
.SH SYNOPSIS
\fIvalue(\fBstart\fR as integer, 
\fBend\fR as integer, 
\fBvalue\fR as double, 
\fBchr\fR as string = "chr1");\fR
.SH DESCRIPTION
.PP
Tracks such As scatter plot, line plot, histogram Or heat map, 
 associate a value With Each range. The input To this kind Of 
 track would be
 
 \fB
 # scatter, line, histogram And heat maps require a value
 chr12 1000 5000 0.25
 \fR`
.PP
.SH OPTIONS
.PP
\fBstart\fB \fR\- -
.PP
.PP
\fBend\fB \fR\- -
.PP
.PP
\fBvalue\fB \fR\- -
.PP
.PP
\fBchr\fB \fR\- -
.PP
.SH SEE ALSO
track.plots
.SH FILES
.PP
circoskit.dll
.PP
.SH COPYRIGHT
Copyright ©  2019
