.\" man page create by R# package system.
.TH R 1 2000-01-01 "push" "push"
.SH NAME
push \- push any .NET object into R runtime environment
.SH SYNOPSIS
\fIpush(\fBany\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
push any .NET object into R runtime environment
.PP
.SH OPTIONS
.PP
\fBany\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
R
.SH FILES
.PP
bioconductor.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC genomics. 2020
