.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "build_context" "build_context"
.SH NAME
build_context \- Load the pangenome analysis context
.SH SYNOPSIS
\fIbuild_context(\fBgenomes\fR as any, 
\fBsoft_core_threshold\fR as double = 0.95, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Load the pangenome analysis context
.PP
.SH OPTIONS
.PP
\fBgenomes\fB \fR\- should be a collection of the genome GFF feature tables. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
pangenome
.SH FILES
.PP
seqtoolkit.dll
.PP
