.\" man page create by R# package system.
.TH PANGENOME 1 2000-1月 "pav_table" "pav_table"
.SH NAME
pav_table \- 
.SH SYNOPSIS
\fIpav_table(\fBresult\fR as <generic> PanGenomeResult, 
\fBindex\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
pangenome
.SH FILES
.PP
seqtoolkit.dll
.PP
