.\" man page create by R# package system.
.TH CHARTS 4 2000-01-01 "volinPlot" "volinPlot"
.SH NAME
volinPlot \- 
.SH SYNOPSIS
\fIvolinPlot(\fBdataset\fR as <generic> Array, 
\fBsize\fR as <generic> Object = "3600,2400", 
\fBmargin\fR as <generic> Object = "padding:400px 150px 300px 300px;", 
\fBbg\fR as string = "white", 
\fBcolorSet\fR as string = "TSF", 
\fBylab\fR as string = "y axis", 
\fBtitle\fR as string = "Volin Plot", 
\fBlabelAngle\fR as double = -45, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
charts
.SH FILES
.PP
R.plot.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
