.\" man page create by R# package system.
.TH SVM 1 2020-10-29 "append.trainingSet" "append.trainingSet"
.SH NAME
append.trainingSet \- append problem data into current problem dataset
.SH SYNOPSIS
\fIappend.trainingSet(\fBproblem\fR as <generic> Problem, 
\fBtag\fR as string, 
\fBdata\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
append problem data into current problem dataset
.PP
.SH OPTIONS
.PP
\fBproblem\fB \fR\- -
.PP
.PP
\fBtag\fB \fR\- -
.PP
.PP
\fBdata\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
