.\" man page create by R# package system.
.TH SVM 1 2020-11-02 "join.problems" "join.problems"
.SH NAME
join.problems \- merge two problem table by row append.
.SH SYNOPSIS
\fIjoin.problems(\fBx\fR as <generic> ProblemTable, 
\fBy\fR as <generic> ProblemTable);\fR
.SH DESCRIPTION
.PP
merge two problem table by row append. 
 (this api is usually apply for join 
 positive set and negative set.)
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- positive set or negative set
.PP
.PP
\fBy\fB \fR\- positive set or negative set
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
