.\" man page create by R# package system.
.TH SVM 1 2020-11-09 "parse.SVM_json" "parse.SVM_json"
.SH NAME
parse.SVM_json \- 
.SH SYNOPSIS
\fIparse.SVM_json(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
