.\" man page create by R# package system.
.TH SVM 1 2020-11-02 "problem.validateLabels" "problem.validateLabels"
.SH NAME
problem.validateLabels \- extract the classify labels part from the
.SH SYNOPSIS
\fIproblem.validateLabels(\fBproblem\fR as <generic> ProblemTable);\fR
.SH DESCRIPTION
.PP
extract the classify labels part from the 
 validation set object.
.PP
.SH OPTIONS
.PP
\fBproblem\fB \fR\- -
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
