.\" man page create by R# package system.
.TH SVM 1 2020-11-09 "problem.trim" "problem.trim"
.SH NAME
problem.trim \- removes all columns that will all value equals to each other
.SH SYNOPSIS
\fIproblem.trim(\fBmodel\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
removes all columns that will all value equals to each other
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
