.\" man page create by R# package system.
.TH SVM 1 2020-12-15 "svm_json" "svm_json"
.SH NAME
svm_json \- serialize the SVM model as json string for save to a file
.SH SYNOPSIS
\fIsvm_json(\fBsvm\fR as <generic> Object, 
\fBfileModel\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
serialize the SVM model as json string for save to a file
.PP
.SH OPTIONS
.PP
\fBsvm\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
