.\" man page create by R# package system.
.TH SVM 1 2020-10-29 "svm_validates" "svm_validates"
.SH NAME
svm_validates \- SVM model validation
.SH SYNOPSIS
\fIsvm_validates(\fBsvm\fR as <generic> Object, 
\fBvalidateSet\fR as <generic> Object, 
\fBlabels\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
SVM model validation
.PP
.SH OPTIONS
.PP
\fBsvm\fB \fR\- a trained SVM model
.PP
.PP
\fBvalidateSet\fB \fR\- 
 a dataframe object which contains the validate set data, 
 each column should be exists in the dimensin name of 
 the trainingSet.

.PP
.PP
\fBlabels\fB \fR\- a dataframe object which contains 
 the classify label result corresponding to the input 
 \fBvalidateSet\fR rows.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH VALUE
.PP
\fBPerformanceEvaluator\fR dataset for draw a ROC curve.
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
