.\" man page create by R# package system.
.TH SVM 1 2020-10-29 "svm_classify" "svm_classify"
.SH NAME
svm_classify \- 
.SH SYNOPSIS
\fIsvm_classify(\fBsvm\fR as <generic> Object, 
\fBdata\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
