.\" man page create by R# package system.
.TH SVM 1 2020-11-09 "trainSVMModel" "trainSVMModel"
.SH NAME
trainSVMModel \- train SVM model
.SH SYNOPSIS
\fItrainSVMModel(\fBproblem\fR as <generic> Object, 
\fBsvmType\fR as <integer> SvmType = [C_SVC], 
\fBkernelType\fR as <integer> KernelType = [RBF], 
\fBdegree\fR as integer = 3, 
\fBgamma\fR as double = 0.5, 
\fBcoefficient0\fR as double = 0, 
\fBnu\fR as double = 0.5, 
\fBcacheSize\fR as integer = 40, 
\fBC\fR as double = 1, 
\fBEPS\fR as double = 0.001, 
\fBP\fR as double = 0.1, 
\fBshrinking\fR as boolean = TRUE, 
\fBprobability\fR as boolean = FALSE, 
\fBweights\fR as list = \fB<NULL>\fR, 
\fBverbose\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
train SVM model
.PP
.SH OPTIONS
.PP
\fBproblem\fB \fR\- -
.PP
.PP
\fBsvmType\fB \fR\- Type of SVM (default C-SVC)
.PP
.PP
\fBkernelType\fB \fR\- Type of kernel function (default Polynomial)
.PP
.PP
\fBdegree\fB \fR\- Degree in kernel function (default 3).
.PP
.PP
\fBgamma\fB \fR\- Gamma in kernel function (default 1/k)
.PP
.PP
\fBcoefficient0\fB \fR\- Zeroeth coefficient in kernel function (default 0)
.PP
.PP
\fBnu\fB \fR\- The parameter nu of nu-SVC, one-class SVM, and nu-SVR (default 0.5)
.PP
.PP
\fBcacheSize\fB \fR\- Cache memory size in MB (default 100)
.PP
.PP
\fBC\fB \fR\- The parameter C of C-SVC, epsilon-SVR, and nu-SVR (default 1)
.PP
.PP
\fBEPS\fB \fR\- Tolerance of termination criterion (default 0.001)
.PP
.PP
\fBP\fB \fR\- The epsilon in loss function of epsilon-SVR (default 0.1)
.PP
.PP
\fBshrinking\fB \fR\- Whether to use the shrinking heuristics, (default True)
.PP
.PP
\fBprobability\fB \fR\- 
 Whether to train an SVC or SVR model for probability estimates, (default False)

.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
