.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "prodigal" "prodigal"
.SH NAME
prodigal \- 
.SH SYNOPSIS
\fIprodigal(\fBx\fR as any, 
\fBmin_ORF_len\fR as integer = 90, 
\fBmodel\fR as <generic> TrainingModel = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
