<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
   
    <OutputType>Library</OutputType>
    <StartupObject>
    </StartupObject>
    <RootNamespace>Microsoft.VisualBasic.Math.Statistics.Hypothesis.mHG</RootNamespace>
    <AssemblyName>Microsoft.VisualBasic.Math.Statistics.Hypothesis.mHG</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <TargetFramework>net10.0</TargetFramework>
    <UseApplicationFramework>True</UseApplicationFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyTitle>Minimum-hypergeometric test</AssemblyTitle>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>

  
  </PropertyGroup>

	<ItemGroup>
	  <Compile Remove="test\**" />
	  <EmbeddedResource Remove="test\**" />
	  <None Remove="test\**" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
	  <ProjectReference Include="..\Math\Math.NET5.vbproj" />
	</ItemGroup>
  
</Project>