<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
   
    <OutputType>Library</OutputType>
    <StartupObject>
    </StartupObject>
    <RootNamespace>mHG</RootNamespace>
    <AssemblyName>mHG</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <TargetFramework>net10.0</TargetFramework>
    <UseApplicationFramework>True</UseApplicationFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>

  
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\Microsoft.VisualBasic.Core\src\Core.vbproj" />
	</ItemGroup>
  
</Project>