.\" man page create by R# package system.
.TH RHEA 1 2000-1月 "reactions" "reactions"
.SH NAME
reactions \- Load reaction models from rhea rdf database file
.SH SYNOPSIS
\fIreactions(\fBrhea\fR as <generic> RheaRDF);\fR
.SH DESCRIPTION
.PP
Load reaction models from rhea rdf database file
.PP
.SH OPTIONS
.PP
\fBrhea\fB \fR\- -. 
.PP
.SH EXAMPLES
.PP
imports "rhea" from "annotationKit";
 
 # wget https://ftp.expasy.org/databases/rhea/rdf/rhea.rdf.gz
 # gunzip -k rhea.rdf.gz

 let rhea = rhea::open.rdf("./rhea.rdf");
 rhea = rheareactions(rhea);
.PP
.SH SEE ALSO
rhea
.SH FILES
.PP
annotationKit.dll
.PP
