.\" man page create by R# package system.
.TH PHENOGRAPH 1 2000-01-01 "phenograph" "phenograph"
.SH NAME
phenograph \- PhenoGraph algorithm
.SH SYNOPSIS
\fIphenograph(\fBmatrix\fR as <generic> Matrix, 
\fBk\fR as integer = 30, 
\fBcutoff\fR as double = 0);\fR
.SH DESCRIPTION
.PP
PhenoGraph algorithm
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBcutoff\fB \fR\- -. 
.PP
.SH SEE ALSO
phenograph
.SH FILES
.PP
phenotype_kit.dll
.PP
