.\" man page create by R# package system.
.TH METABOLIQ 1 2000-1月 "new" "new"
.SH NAME
new \- 
.SH SYNOPSIS
\fInew(\fBgraph\fR as <generic> MetabolicNetworkGraph, 
\fBmode\fR as <integer> LiquidMode = [LTC], 
\fBsolver\fR as string = "rk4");\fR
.SH SEE ALSO
Metaboliq
.SH FILES
.PP
biosystem.dll
.PP
