.\" man page create by R# package system.
.TH METABOLIQ 1 2000-1月 "predict" "predict"
.SH NAME
predict \- 
.SH SYNOPSIS
\fIpredict(\fBmodel\fR as <generic> MetabolicTrainer, 
\fBh0\fR as <generic> Tensor, 
\fBtimes\fR as any, 
\fBenzymeSeries\fR as <generic> Tensor, 
\fBboundarySeries\fR as <generic> Tensor);\fR
.SH SEE ALSO
Metaboliq
.SH FILES
.PP
biosystem.dll
.PP
