.\" man page create by R# package system.
.TH METABOLIQ 1 2000-1月 "read_metabolic_graph" "read_metabolic_graph"
.SH NAME
read_metabolic_graph \- 
.SH SYNOPSIS
\fIread_metabolic_graph(\fBfile\fR as string, 
\fBexplicit_boundary\fR as any = \fB<NULL>\fR);\fR
.SH SEE ALSO
Metaboliq
.SH FILES
.PP
biosystem.dll
.PP
