.\" man page create by R# package system.
.TH METABOLIQ 1 2000-1月 "read_timedata" "read_timedata"
.SH NAME
read_timedata \- read metabolome/enzyme expression time serials data matrix
.SH SYNOPSIS
\fIread_timedata(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read metabolome/enzyme expression time serials data matrix
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
Metaboliq
.SH FILES
.PP
biosystem.dll
.PP
