.\" man page create by R# package system.
.TH JSON 4 2020-11-09 "parseJSON" "parseJSON"
.SH NAME
parseJSON \- 
.SH SYNOPSIS
\fIparseJSON(\fBstr\fR as string, 
\fBraw\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
JSON
.SH FILES
.PP
R.base.dll
.PP
.SH AUTHOR
Written by \fBi@xieguigang.me\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
