.\" man page create by R# package system.
.TH MESH 1 2000-1月 "read.mesh_xml" "read.mesh_xml"
.SH NAME
read.mesh_xml \- Parse the ncbi pubmed mesh term dataset
.SH SYNOPSIS
\fIread.mesh_xml(\fBfile\fR as string, 
\fBtqdm\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
Parse the ncbi pubmed mesh term dataset
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBtqdm\fB \fR\- 
 show the tqdm progress display?
. 
.PP
.SH DETAILS
.PP
the pubmed mesh term dataset could be download from:
 
 https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/xmlmesh/desc2024.zip
.PP
.SH SEE ALSO
mesh
.SH FILES
.PP
kb.dll
.PP
