.\" man page create by R# package system.
.TH NETWORK 1 2000-1月 "assignKeggClass" "assignKeggClass"
.SH NAME
assignKeggClass \- assign kegg class to the graph nodes
.SH SYNOPSIS
\fIassignKeggClass(\fBg\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
assign kegg class to the graph nodes
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- 
 a network graph data model, with nodes label id must 
 be the kegg pathway id and compounds id or kegg KO id
. 
.PP
.SH SEE ALSO
network
.SH FILES
.PP
kegg_kit.dll
.PP
