.\" man page create by R# package system.
.TH METATRAITS 2 2000-1月 "load.meta_traits" "load.meta_traits"
.SH NAME
load.meta_traits \- 读取表型标注数据并按物种组织为表型谱
.SH SYNOPSIS
\fIload.meta_traits(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
读取表型标注数据并按物种组织为表型谱
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- ncbi/gtdb species summary tsv 表文件. 
.PP
.SH SEE ALSO
metaTraits
.SH FILES
.PP
annotationKit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
