.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-1月 "analysis_domains" "analysis_domains"
.SH NAME
analysis_domains \- analysis the functional domain on the protein sequence
.SH SYNOPSIS
\fIanalysis_domains(\fBblastp\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
analysis the functional domain on the protein sequence
.PP
.SH OPTIONS
.PP
\fBblastp\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
