.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-Jan "kmer_fingerprint" "kmer_fingerprint"
.SH NAME
kmer_fingerprint \- 
.SH SYNOPSIS
\fIkmer_fingerprint(\fBgraph\fR as <generic> KMerGraph, 
\fBradius\fR as integer = 3, 
\fBlen\fR as integer = 4096);\fR
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
