.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-1月 "parse_pdb" "parse_pdb"
.SH NAME
parse_pdb \- parse the pdb struct data from a given document text data
.SH SYNOPSIS
\fIparse_pdb(\fBpdb_txt\fR as string, 
\fBsafe\fR as boolean = FALSE, 
\fBverbose\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
parse the pdb struct data from a given document text data
.PP
.SH OPTIONS
.PP
\fBpdb_txt\fB \fR\- -. 
.PP
.PP
\fBsafe\fB \fR\- -. 
.PP
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
