.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-1月 "pdb_models" "pdb_models"
.SH NAME
pdb_models \- get structure models inside the given pdb object
.SH SYNOPSIS
\fIpdb_models(\fBpdb\fR as <generic> PDB);\fR
.SH DESCRIPTION
.PP
get structure models inside the given pdb object
.PP
.SH OPTIONS
.PP
\fBpdb\fB \fR\- -. 
.PP
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
