.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-Jan "read.pdb" "read.pdb"
.SH NAME
read.pdb \- read the protein database file
.SH SYNOPSIS
\fIread.pdb(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read the protein database file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
