.\" man page create by R# package system.
.TH HTTP 4 2000-01-01 "cookies" "cookies"
.SH NAME
cookies \- parse cookies data from the http web request result
.SH SYNOPSIS
\fIcookies(\fBdata\fR as <generic> WebResponseResult);\fR
.SH DESCRIPTION
.PP
parse cookies data from the http web request result
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -
.PP
.SH SEE ALSO
http
.SH FILES
.PP
R.web.dll
.PP
.SH COPYRIGHT
Copyright © Microsoft 2019
