.\" man page create by R# package system.
.TH HTTP 4 2000-01-01 "requests.get" "requests.get"
.SH NAME
requests.get \- http get request
.SH SYNOPSIS
\fIrequests.get(\fBurl\fR as string, 
\fBheaders\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
http get request
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- -
.PP
.PP
\fBheaders\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
http
.SH FILES
.PP
R.web.dll
.PP
.SH COPYRIGHT
Copyright © Microsoft 2019
