.\" man page create by R# package system.
.TH HTTP 4 2000-01-01 "upload" "upload"
.SH NAME
upload \- upload files through http post
.SH SYNOPSIS
\fIupload(\fBurl\fR as string, 
\fBfiles\fR as <generic> Object, 
\fBheaders\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
upload files through http post
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- the target network location.
.PP
.PP
\fBfiles\fB \fR\- a list of file path for upload to the specific network location.
.PP
.PP
\fBheaders\fB \fR\- set cookies or other http headers at here.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
http
.SH FILES
.PP
R.web.dll
.PP
.SH COPYRIGHT
Copyright © Microsoft 2019
