.\" man page create by R# package system.
.TH HTTP 4 2000-01-01 "urlencode" "urlencode"
.SH NAME
urlencode \- URL-encodes string
.SH SYNOPSIS
\fIurlencode(\fBdata\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
URL-encodes string
 
 This function is convenient when encoding a string to be 
 used in a query part of a URL, as a convenient way to 
 pass variables to the next page.
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- The string to be encoded.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH VALUE
.PP
Returns a string in which all non-alphanumeric characters except \fB-_.\fR 
 have been replaced with a percent (%) sign followed by two hex digits and 
 spaces encoded as plus (+) signs. It is encoded the same way that the 
 posted data from a WWW form is encoded, that is the same way as in 
 \fBapplication/x-www-form-urlencoded\fR media type. This differs from the 
 RFC 3986 encoding (see rawurlencode()) in that for historical reasons, 
 spaces are encoded as plus (+) signs.
.PP
.SH DETAILS
.PP
Be careful about variables that may match HTML entities. Things like 
 \fB&amp\fR, \fB&copy\fR and \fB&pound\fR are parsed by the browser and 
 the actual entity is used instead of the desired variable name. 
 
 This is an obvious hassle that the W3C has been telling people about for 
 years. The reference is here: 
 http://www.w3.org/TR/html4/appendix/notes.html#h-B.2.2.
.PP
.SH SEE ALSO
http
.SH FILES
.PP
webKit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
