.\" man page create by R# package system.
.TH HTTP 4 2000-01-01 "wget" "wget"
.SH NAME
wget \- Do file download
.SH SYNOPSIS
\fIwget(\fBurl\fR as string, 
\fBsaveAs\fR as string);\fR
.SH DESCRIPTION
.PP
Do file download
.PP
.SH OPTIONS
.PP
\fBurl$\fB \fR\- -
.PP
.PP
\fBsaveAs$\fB \fR\- -
.PP
.SH SEE ALSO
http
.SH FILES
.PP
webKit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
