.\" man page create by R# package system.
.TH CIRCOS 2 2000-01-01 "backbone" "backbone"
.SH NAME
backbone \- 
.SH SYNOPSIS
\fIbackbone(\fBcircos\fR as <generic> Circos, 
\fBsource\fR as <generic> FastaSeq, 
\fBloophole\fR as integer = 512);\fR
.SH SEE ALSO
circos
.SH FILES
.PP
circoskit.dll
.PP
.SH AUTHOR
Written by \fBmartink@bcgsc.ca\fR
.SH COPYRIGHT
Copyright ©  2019
