.\" man page create by R# package system.
.TH CIRCOS 2 2000-01-01 "circos" "circos"
.SH NAME
circos \- Creats a new @\fBT:SMRUCC.genomics.Visualize.Circos.Configurations.Circos\fR plots configuration document.
.SH SYNOPSIS
\fIcircos(\fBgenome\fR as string = "", 
\fBuse_rules\fR as string = "yes", 
\fBchromosomes_units\fR as integer = 5000, 
\fBchromosomes_display_default\fR as string = "yes", 
\fBchromosomes\fR as string = "", 
\fBchromosomes_reverse\fR as string = "", 
\fBchromosomes_radius\fR as string = "", 
\fBchromosomes_scale\fR as string = "", 
\fBchromosomes_color\fR as string = "", 
\fBchromosomes_order\fR as string = "", 
\fBchromosomes_breaks\fR as string = "", 
\fBshow_scatter\fR as string = "yes", 
\fBshow_line\fR as string = "yes", 
\fBshow_histogram\fR as string = "yes", 
\fBshow_heatmap\fR as string = "yes", 
\fBshow_tile\fR as string = "yes", 
\fBshow_highlight\fR as string = "yes", 
\fBshow_links\fR as string = "yes", 
\fBshow_highlights\fR as string = "yes", 
\fBshow_text\fR as string = "yes", 
\fBshow_heatmaps\fR as string = "yes", 
\fBtrack_width\fR as string = "", 
\fBtrack_start\fR as string = "", 
\fBtrack_step\fR as string = "");\fR
.SH DESCRIPTION
.PP
Creats a new @\fBT:SMRUCC.genomics.Visualize.Circos.Configurations.Circos\fR plots configuration document.
.PP
.SH OPTIONS
.PP
\fBgenome\fB \fR\- -
.PP
.PP
\fBuse_rules\fB \fR\- -
.PP
.PP
\fBchromosomes_units\fB \fR\- -
.PP
.PP
\fBchromosomes_display_default\fB \fR\- -
.PP
.PP
\fBchromosomes\fB \fR\- -
.PP
.PP
\fBchromosomes_reverse\fB \fR\- -
.PP
.PP
\fBchromosomes_radius\fB \fR\- -
.PP
.PP
\fBchromosomes_scale\fB \fR\- -
.PP
.PP
\fBchromosomes_color\fB \fR\- -
.PP
.PP
\fBchromosomes_order\fB \fR\- -
.PP
.PP
\fBchromosomes_breaks\fB \fR\- -
.PP
.PP
\fBshow_scatter\fB \fR\- -
.PP
.PP
\fBshow_line\fB \fR\- -
.PP
.PP
\fBshow_histogram\fB \fR\- -
.PP
.PP
\fBshow_heatmap\fB \fR\- -
.PP
.PP
\fBshow_tile\fB \fR\- -
.PP
.PP
\fBshow_highlight\fB \fR\- -
.PP
.PP
\fBshow_links\fB \fR\- -
.PP
.PP
\fBshow_highlights\fB \fR\- -
.PP
.PP
\fBshow_text\fB \fR\- -
.PP
.PP
\fBshow_heatmaps\fB \fR\- -
.PP
.PP
\fBtrack_width\fB \fR\- -
.PP
.PP
\fBtrack_start\fB \fR\- -
.PP
.PP
\fBtrack_step\fB \fR\- -
.PP
.SH SEE ALSO
circos
.SH FILES
.PP
circoskit.dll
.PP
.SH AUTHOR
Written by \fBmartink@bcgsc.ca\fR
.SH COPYRIGHT
Copyright ©  2019
