.\" man page create by R# package system.
.TH CIRCOS 2 2000-01-01 "ideogram" "ideogram"
.SH NAME
ideogram \- Gets the ideogram configuration node in the circos document object.
.SH SYNOPSIS
\fIideogram(\fBdoc\fR as <generic> Circos, 
\fBthickness\fR as string = "30p", 
\fBstroke_thickness\fR as integer = 0, 
\fBstroke_color\fR as string = "black", 
\fBfill\fR as string = "yes", 
\fBfill_color\fR as string = "black", 
\fBradius\fR as string = "0.85r", 
\fBshow_label\fR as string = "no", 
\fBlabel_font\fR as string = "default", 
\fBlabel_radius\fR as string = "dims(ideogram,radius) + 0.05r", 
\fBlabel_size\fR as integer = 36, 
\fBlabel_parallel\fR as string = "yes", 
\fBlabel_case\fR as string = "upper", 
\fBband_stroke_thickness\fR as integer = 0, 
\fBshow_bands\fR as string = "yes", 
\fBfill_bands\fR as string = "yes");\fR
.SH DESCRIPTION
.PP
Gets the ideogram configuration node in the circos document object.
.PP
.SH OPTIONS
.PP
\fBdoc\fB \fR\- -
.PP
.SH DETAILS
.PP
(还没有ideogram文档的时候，则会返回一个新的文档)
.PP
.SH SEE ALSO
circos
.SH FILES
.PP
circoskit.dll
.PP
.SH AUTHOR
Written by \fBmartink@bcgsc.ca\fR
.SH COPYRIGHT
Copyright ©  2019
