.\" man page create by R# package system.
.TH BACKGROUND 2 2000-1月 "background.id_mapping" "background.id_mapping"
.SH NAME
background.id_mapping \- do id mapping of the members in the background cluster
.SH SYNOPSIS
\fIbackground.id_mapping(\fBbackground\fR as <generic> Background, 
\fBmapping\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do id mapping of the members in the background cluster
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.PP
\fBmapping\fB \fR\- 
 do id translation via this id source list
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
