.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "clusterIDs" "clusterIDs"
.SH NAME
clusterIDs \- get all of the cluster id set from the given background model object
.SH SYNOPSIS
\fIclusterIDs(\fBbackground\fR as <generic> Background);\fR
.SH DESCRIPTION
.PP
get all of the cluster id set from the given background model object
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
