.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "compoundBrite" "compoundBrite"
.SH NAME
compoundBrite \- get kegg compound class brite background model
.SH SYNOPSIS
\fIcompoundBrite();\fR
.SH DESCRIPTION
.PP
get kegg compound class brite background model
.PP
.SH DETAILS
.PP
this function generates a background model from the internal
 kegg resource database, the generated background model which 
 could be used for the compound class category annotation.
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
