.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "cut_background" "cut_background"
.SH NAME
cut_background \- make gsea background dynamic cut
.SH SYNOPSIS
\fIcut_background(\fBbackground\fR as <generic> Background, 
\fBannotated\fR as any);\fR
.SH DESCRIPTION
.PP
make gsea background dynamic cut
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.PP
\fBannotated\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
