.\" man page create by R# package system.
.TH BACKGROUND 2 2000-1月 "fromList" "fromList"
.SH NAME
fromList \- cast the cluster data as the enrichment background
.SH SYNOPSIS
\fIfromList(\fBgeneSet\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
cast the cluster data as the enrichment background
.PP
.SH OPTIONS
.PP
\fBgeneSet\fB \fR\- 
 a collection of the gene feature clusters, usualy be a tuple list in format of:
 cluster id as the list name and the corresponding tuple list value should be
 the gene id character vector.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
