.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "geneSet.annotations" "geneSet.annotations"
.SH NAME
geneSet.annotations \- make gene set annotation via a given gsea background model
.SH SYNOPSIS
\fIgeneSet.annotations(\fBbackground\fR as <generic> Background, 
\fBgeneSet\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make gene set annotation via a given gsea background model
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.PP
\fBgeneSet\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
