.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "KO.background" "KO.background"
.SH NAME
KO.background \- create kegg background model
.SH SYNOPSIS
\fIKO.background(\fBgenes\fR as any, 
\fBmaps\fR as any, 
\fBsize\fR as integer = -1, 
\fBgenomeName\fR as string = "unknown", 
\fBid_map\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create kegg background model
.PP
.SH OPTIONS
.PP
\fBgenes\fB \fR\- -. 
.PP
.PP
\fBmaps\fB \fR\- -. 
.PP
.PP
\fBsize%\fB \fR\- -. 
.PP
.PP
\fBgenomeName$\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
