.\" man page create by R# package system.
.TH BACKGROUND 2 2000-1月 "KO.table" "KO.table"
.SH NAME
KO.table \- convert the background model to a data table
.SH SYNOPSIS
\fIKO.table(\fBbackground\fR as <generic> Background);\fR
.SH DESCRIPTION
.PP
convert the background model to a data table
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
