.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "KO_reference" "KO_reference"
.SH NAME
KO_reference \- gene/protein KO id background
.SH SYNOPSIS
\fIKO_reference();\fR
.SH DESCRIPTION
.PP
gene/protein KO id background
.PP
.SH VALUE
.PP
A reference background of the kegg pathway by parse the internal resource file.
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
