.\" man page create by R# package system.
.TH BACKGROUND 2 2000-Jan "moleculeIDs" "moleculeIDs"
.SH NAME
moleculeIDs \- get all of the molecule id set from the given background model object
.SH SYNOPSIS
\fImoleculeIDs(\fBbackground\fR as <generic> Background);\fR
.SH DESCRIPTION
.PP
get all of the molecule id set from the given background model object
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
