.\" man page create by R# package system.
.TH BACKGROUND 2 2000-01-01 "read.background" "read.background"
.SH NAME
read.background \- Load GSEA background model from a xml file.
.SH SYNOPSIS
\fIread.background(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
Load GSEA background model from a xml file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
