.\" man page create by R# package system.
.TH BACKGROUND 2 2000-01-01 "write.background" "write.background"
.SH NAME
write.background \- Save GSEA background model as xml file
.SH SYNOPSIS
\fIwrite.background(\fBbackground\fR as <generic> Background, 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
Save GSEA background model as xml file
.PP
.SH OPTIONS
.PP
\fBbackground\fB \fR\- -. 
.PP
.PP
\fBfile$\fB \fR\- -. 
.PP
.SH SEE ALSO
background
.SH FILES
.PP
gseakit.dll
.PP
