.\" man page create by R# package system.
.TH DEVKIT.CODE 1 2000-01-01 "R.highlights" "R.highlights"
.SH NAME
R.highlights \- generate R code highlights
.SH SYNOPSIS
\fIR.highlights(\fBscriptText\fR as string, 
\fBdebug\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
generate R code highlights
.PP
.SH OPTIONS
.PP
\fBscriptText\fB \fR\- -
.PP
.PP
\fBdebug\fB \fR\- -
.PP
.SH SEE ALSO
devkit.code
.SH FILES
.PP
R.code.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
