.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "compoundsId" "compoundsId"
.SH NAME
compoundsId \- get a vector of kegg compound id from the kegg reaction_class/pathway maps data repository
.SH SYNOPSIS
\fIcompoundsId(\fBrepo\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get a vector of kegg compound id from the kegg reaction_class/pathway maps data repository
.PP
.SH OPTIONS
.PP
\fBrepo\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
