.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "compound" "compound"
.SH NAME
compound \- 
.SH SYNOPSIS
\fIcompound(\fBentry\fR as string, 
\fBname\fR as string, 
\fBformula\fR as string, 
\fBexactMass\fR as double, 
\fBreaction\fR as string, 
\fBenzyme\fR as string, 
\fBremarks\fR as string, 
\fBKCF\fR as string, 
\fBDBLinks\fR as <generic> dataframe, 
\fBpathway\fR as <generic> dataframe, 
\fBmodules\fR as <generic> dataframe);\fR
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
