.\" man page create by R# package system.
.TH REPOSITORY 1 2000-01-01 "keggMap" "keggMap"
.SH NAME
keggMap \- 
.SH SYNOPSIS
\fIkeggMap(\fBid\fR as string, 
\fBname\fR as string, 
\fBdescription\fR as string, 
\fBimg\fR as string, 
\fBurl\fR as string, 
\fBarea\fR as <generic> Area[]);\fR
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
