.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "load.pathways" "load.pathways"
.SH NAME
load.pathways \- load kegg pathway maps from a given repository data directory.
.SH SYNOPSIS
\fIload.pathways(\fBrepository\fR as string, 
\fBreferenceMap\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load kegg pathway maps from a given repository data directory.
.PP
.SH OPTIONS
.PP
\fBrepository\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
