.\" man page create by R# package system.
.TH REPOSITORY 1 2000-Jan "load.maps" "load.maps"
.SH NAME
load.maps \- load list of kegg reference @\fBT:SMRUCC.genomics.Assembly.KEGG.WebServices.Map\fR.
.SH SYNOPSIS
\fIload.maps(\fBrepository\fR as any, 
\fBrawMaps\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
load list of kegg reference @\fBT:SMRUCC.genomics.Assembly.KEGG.WebServices.Map\fR.
.PP
.SH OPTIONS
.PP
\fBrepository\fB \fR\- 
 a directory of repository data for kegg reference @\fBT:SMRUCC.genomics.Assembly.KEGG.WebServices.Map\fR.
. 
.PP
.SH VALUE
.PP
a kegg reference map object vector, which can be indexed 
 via @\fBP:SMRUCC.genomics.ComponentModel.Annotation.PathwayBrief.EntryId\fR.
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
