.\" man page create by R# package system.
.TH REPOSITORY 1 2000-Jan "load.reactions" "load.reactions"
.SH NAME
load.reactions \- load reaction data from the given kegg reaction data repository
.SH SYNOPSIS
\fIload.reactions(\fBrepository\fR as any, 
\fBraw\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load reaction data from the given kegg reaction data repository
.PP
.SH OPTIONS
.PP
\fBrepository\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
