.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "pathway" "pathway"
.SH NAME
pathway \- 
.SH SYNOPSIS
\fIpathway(\fBid\fR as string, 
\fBname\fR as string, 
\fBdescription\fR as string, 
\fBmodules\fR as <generic> dataframe, 
\fBDBLinks\fR as <generic> dataframe, 
\fBKO_pathway\fR as string, 
\fBreferences\fR as <generic> dataframe, 
\fBcompounds\fR as <generic> dataframe, 
\fBdrugs\fR as <generic> dataframe, 
\fBgenes\fR as <generic> dataframe, 
\fBorganism\fR as list, 
\fBdisease\fR as <generic> dataframe, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
