.\" man page create by R# package system.
.TH REPOSITORY 1 2000-01-01 "reaction_class" "reaction_class"
.SH NAME
reaction_class \- create a new data model of kegg reaction_class
.SH SYNOPSIS
\fIreaction_class(\fBid\fR as string, 
\fBdefinition\fR as string, 
\fBreactions\fR as string, 
\fBenzyme\fR as string, 
\fBpathways\fR as <generic> dataframe, 
\fBKO\fR as <generic> dataframe, 
\fBtransforms\fR as <generic> dataframe, 
\fBrmodules\fR as <generic> dataframe);\fR
.SH DESCRIPTION
.PP
create a new data model of kegg reaction_class
.PP
.SH OPTIONS
.PP
\fBid\fB \fR\- -. 
.PP
.PP
\fBdefinition\fB \fR\- -. 
.PP
.PP
\fBreactions\fB \fR\- -. 
.PP
.PP
\fBenzyme\fB \fR\- -. 
.PP
.PP
\fBpathways\fB \fR\- -. 
.PP
.PP
\fBKO\fB \fR\- -. 
.PP
.PP
\fBtransforms\fB \fR\- -. 
.PP
.PP
\fBrmodules\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
