.\" man page create by R# package system.
.TH REPOSITORY 1 2000-Jan "reaction_class.repo" "reaction_class.repo"
.SH NAME
reaction_class.repo \- load stream of the reaction_class data model from kegg data repository.
.SH SYNOPSIS
\fIreaction_class.repo(\fBrepo\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load stream of the reaction_class data model from kegg data repository.
.PP
.SH OPTIONS
.PP
\fBrepo\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
