.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "reactions.table" "reactions.table"
.SH NAME
reactions.table \- load kegg reaction table from a given repository model or resource file on your filesystem.
.SH SYNOPSIS
\fIreactions.table(\fBrepo\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load kegg reaction table from a given repository model or resource file on your filesystem.
.PP
.SH OPTIONS
.PP
\fBrepo\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
