.\" man page create by R# package system.
.TH REPOSITORY 1 2000-01-01 "reaction" "reaction"
.SH NAME
reaction \- 
.SH SYNOPSIS
\fIreaction(\fBid\fR as string, 
\fBname\fR as string, 
\fBdefinition\fR as string, 
\fBequation\fR as string, 
\fBcomment\fR as string, 
\fBreaction_class\fR as <generic> dataframe, 
\fBenzyme\fR as string, 
\fBpathways\fR as <generic> dataframe, 
\fBmodules\fR as <generic> dataframe, 
\fBKO\fR as <generic> dataframe, 
\fBlinks\fR as <generic> dataframe);\fR
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
