.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "read.KEGG_pathway" "read.KEGG_pathway"
.SH NAME
read.KEGG_pathway \- read the kegg pathway annotation result data.
.SH SYNOPSIS
\fIread.KEGG_pathway(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read the kegg pathway annotation result data.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
