.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "save.kegg_organism" "save.kegg_organism"
.SH NAME
save.kegg_organism \- save the kegg organism data as data table file.
.SH SYNOPSIS
\fIsave.kegg_organism(\fBorganism\fR as <generic> Prokaryote[], 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the kegg organism data as data table file.
.PP
.SH OPTIONS
.PP
\fBorganism\fB \fR\- -. 
.PP
.PP
\fBfile$\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
