.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "shapeAreas" "shapeAreas"
.SH NAME
shapeAreas \- create shape area data for kegg graph rendering
.SH SYNOPSIS
\fIshapeAreas(\fBdata\fR as <generic> dataframe);\fR
.SH DESCRIPTION
.PP
create shape area data for kegg graph rendering
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
