.\" man page create by R# package system.
.TH REPOSITORY 1 2000-1月 "write.msgpack" "write.msgpack"
.SH NAME
write.msgpack \- a generic method for write kegg data stream as messagepack
.SH SYNOPSIS
\fIwrite.msgpack(\fBdata\fR as any, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
a generic method for write kegg data stream as messagepack
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
repository
.SH FILES
.PP
kegg_kit.dll
.PP
