.\" man page create by R# package system.
.TH GSVA 1 2000-01-01 "diff" "diff"
.SH NAME
diff \- different analysis of the gsva result
.SH SYNOPSIS
\fIdiff(\fBgsva\fR as <generic> Matrix, 
\fBcompares\fR as <generic> DataAnalysis);\fR
.SH DESCRIPTION
.PP
different analysis of the gsva result
.PP
.SH OPTIONS
.PP
\fBgsva\fB \fR\- the gsva analysis result. 
.PP
.PP
\fBcompares\fB \fR\- 
 the analysis comparision
. 
.PP
.SH SEE ALSO
GSVA
.SH FILES
.PP
gseakit.dll
.PP
