.\" man page create by R# package system.
.TH MICROBIOME 1 2000-1月 "build.PICRUSt_db" "build.PICRUSt_db"
.SH NAME
build.PICRUSt_db \- 
.SH SYNOPSIS
\fIbuild.PICRUSt_db(\fBggtax\fR as <generic> otu_taxonomy[], 
\fBcopyNumbers_16s\fR as list, 
\fBko_13_5_precalculated\fR as <generic> Stream, 
\fBsave\fR as <generic> Stream, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
