.\" man page create by R# package system.
.TH MICROBIOME 1 2000-1月 "compound_origins" "compound_origins"
.SH NAME
compound_origins \- 
.SH SYNOPSIS
\fIcompound_origins(\fBannotations\fR as list, 
\fBtree\fR as <generic> NcbiTaxonomyTree, 
\fBrank\fR as <integer> TaxonomyRanks = [Family], 
\fBranges\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
