.\" man page create by R# package system.
.TH FTP 4 2000-01-01 "ftp.get" "ftp.get"
.SH NAME
ftp.get \- download file via ftp
.SH SYNOPSIS
\fIftp.get(\fBftp\fR as <generic> FtpContext, 
\fBfile\fR as string, 
\fBsave\fR as string = "./", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
download file via ftp
.PP
.SH OPTIONS
.PP
\fBftp\fB \fR\- -
.PP
.PP
\fBfile\fB \fR\- -
.PP
.PP
\fBsave\fB \fR\- 
 a directory path or actual file path for save the given file that download from the remote ftp server.

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
ftp
.SH FILES
.PP
webKit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
