.\" man page create by R# package system.
.TH FTP 4 2000-01-01 "list.ftp_dirs" "list.ftp_dirs"
.SH NAME
list.ftp_dirs \- list file names in the given ftp directory.
.SH SYNOPSIS
\fIlist.ftp_dirs(\fBftp\fR as <generic> FtpContext, 
\fBdir\fR as string, 
\fBthrowEx\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
list file names in the given ftp directory.
.PP
.SH OPTIONS
.PP
\fBftp\fB \fR\- -
.PP
.PP
\fBdir\fB \fR\- -
.PP
.PP
\fBthrowEx\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
ftp
.SH FILES
.PP
R.web.dll
.PP
.SH COPYRIGHT
Copyright © Microsoft 2019
