.\" man page create by R# package system.
.TH SET 1 2020-11-02 "index.of" "index.of"
.SH NAME
index.of \- 
.SH SYNOPSIS
\fIindex.of(\fBx\fR as <generic> Object, 
\fBgetKey\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
set
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
