<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sitemap</RootNamespace>
    <AssemblyName>Sitemap</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <OutputPath>../../tools</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <AssemblyTitle>Sitemap Generator</AssemblyTitle>
    <Description>A command line sitemap.xml and sitemap.xsl generator for static websites.</Description>
    <Company>GCModeller</Company>
    <Version>1.0.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="build.log" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\sciBASIC#\mime\text%html\html_netcore5.vbproj" />
  </ItemGroup>

</Project>
