.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "effect_decomposition" "effect_decomposition"
.SH NAME
effect_decomposition \- 
.SH SYNOPSIS
\fIeffect_decomposition(\fBsem_result\fR as <generic> SEMResult, 
\fBas_dataframe\fR as boolean = TRUE);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
