.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "endogenous_latents" "endogenous_latents"
.SH NAME
endogenous_latents \- 
.SH SYNOPSIS
\fIendogenous_latents(\fBresult\fR as <generic> PLSPMResult, 
\fBas_dataframe\fR as boolean = TRUE);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
