.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "indirect_effect" "indirect_effect"
.SH NAME
indirect_effect \- 
.SH SYNOPSIS
\fIindirect_effect(\fBsem_result\fR as <generic> SEMResult, 
\fBboot_result\fR as <generic> BootstrapResult, 
\fBas_dataframe\fR as boolean = TRUE);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
