.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "make_latent" "make_latent"
.SH NAME
make_latent \- 
.SH SYNOPSIS
\fImake_latent(\fBlatentName\fR as string, 
\fBmanifestNames\fR as any, 
\fBmode\fR as <integer> MeasurementModels = [A]);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
