.\" man page create by R# package system.
.TH CAUSAL_MODELING 1 2000-1月 "significance_test" "significance_test"
.SH NAME
significance_test \- 
.SH SYNOPSIS
\fIsignificance_test(\fBsem_result\fR as <generic> SEMResult, 
\fBboot_result\fR as <generic> BootstrapResult, 
\fBas_dataframe\fR as boolean = TRUE);\fR
.SH SEE ALSO
causal_modeling
.SH FILES
.PP
phenotype_kit.dll
.PP
