.\" man page create by R# package system.
.TH CONSOLE 1 2020-07-19 "log" "log"
.SH NAME
log \- Writes the specified string value to the standard output stream.
.SH SYNOPSIS
\fIlog(\fBmessage\fR as string, 
\fBfore_color\fR as <integer> ConsoleColor = \fB<NULL>\fR, 
\fBback_color\fR as <integer> ConsoleColor = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
Writes the specified string value to the standard output stream.
.PP
.SH OPTIONS
.PP
\fBmessage\fB \fR\- The message text value to write.
.PP
.PP
\fBfore_color\fB \fR\- sets the foreground color of the console.
.PP
.PP
\fBback_color\fB \fR\- sets the background color of the console.
.PP
.SH VALUE
.PP
The message text value
.PP
.SH SEE ALSO
console
.SH FILES
.PP
R.base.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
