.\" man page create by R# package system.
.TH CONSOLE 1 2020-11-02 "password" "password"
.SH NAME
password \- Input password on console. only works on windows
.SH SYNOPSIS
\fIpassword(\fBmaxLen\fR as integer = 64);\fR
.SH DESCRIPTION
.PP
Input password on console. only works on windows
.PP
.SH SEE ALSO
console
.SH FILES
.PP
R.base.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
