.\" man page create by R# package system.
.TH CONSOLE 1 2020-12-15 "progressbar.pin.top" "progressbar.pin.top"
.SH NAME
progressbar.pin.top \- Pin the top of progress bar
.SH SYNOPSIS
\fIprogressbar.pin.top(\fBtop\fR as integer = -1);\fR
.SH DESCRIPTION
.PP
Pin the top of progress bar
.PP
.SH OPTIONS
.PP
\fBtop\fB \fR\- -
.PP
.SH SEE ALSO
console
.SH FILES
.PP
R.base.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
