Imports Microsoft.VisualBasic.Serialization
Imports Microsoft.VisualBasic.Serialization.JSON

Namespace DESeq2

    ''' <summary>
    ''' for htseq-count: a data.frame with three or more columns.                               
    ''' Each row describes one sample. The first column Is the sample name, the second column the file name of the count file generated by htseq-count,                               
    ''' And the remaining columns are sample metadata which will be stored in colData
    ''' </summary>
    Public Class SampleTable
        Public Property sampleName As String
        Public Property fileName As String
        Public Property condition As String

        Public Overrides Function ToString() As String
            Return Me.GetJson
        End Function
    End Class
End Namespace