.\" man page create by R# package system.
.TH PUBMED 1 2000-1月 "article" "article"
.SH NAME
article \- Parse the document text as a set of article object
.SH SYNOPSIS
\fIarticle(\fBtext\fR as string, 
\fBxml\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Parse the document text as a set of article object
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- 
 the pubmed database in flat file format, or the xml document content of 
 the pubmed article metadata.
. 
.PP
.SH SEE ALSO
pubmed
.SH FILES
.PP
kb.dll
.PP
