.\" man page create by R# package system.
.TH PUBMED 1 2000-Jan "article" "article"
.SH NAME
article \- Parse the document text as a set of article object
.SH SYNOPSIS
\fIarticle(\fBtext\fR as string);\fR
.SH DESCRIPTION
.PP
Parse the document text as a set of article object
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- 
 the pubmed database in flat file format
. 
.PP
.SH SEE ALSO
pubmed
.SH FILES
.PP
kb.dll
.PP
