.\" man page create by R# package system.
.TH PUBMED 1 2000-1月 "citation_list" "citation_list"
.SH NAME
citation_list \- get the citation list about current article object
.SH SYNOPSIS
\fIcitation_list(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get the citation list about current article object
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a collection of the citation object
.PP
.SH SEE ALSO
pubmed
.SH FILES
.PP
kb.dll
.PP
