.\" man page create by R# package system.
.TH PUBMED 1 2000-1月 "parse" "parse"
.SH NAME
parse \- parse the text data as the article information
.SH SYNOPSIS
\fIparse(\fBtext\fR as any);\fR
.SH DESCRIPTION
.PP
parse the text data as the article information
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- text data in pubmed flat file format. 
.PP
.SH SEE ALSO
pubmed
.SH FILES
.PP
kb.dll
.PP
