.\" man page create by R# package system.
.TH PUBMED 1 2000-1月 "parse.article_set" "parse.article_set"
.SH NAME
parse.article_set \- Parse the pubmed article set xml stream data
.SH SYNOPSIS
\fIparse.article_set(\fBfile\fR as any, 
\fBtqdm\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Parse the pubmed article set xml stream data
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 a single file that contains the pubmed article set data, data could be download from the pubmed ftp server in batch.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
batch download of the pubmed data from ncbi ftp server:
 
 > ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/
.PP
.SH SEE ALSO
pubmed
.SH FILES
.PP
kb.dll
.PP
