.\" man page create by R# package system.
.TH VCELLKIT.COMPILER 1 2020-12-15 "assembling.metabolic" "assembling.metabolic"
.SH NAME
assembling.metabolic \- add metabolism network information for the virtual cell model
.SH SYNOPSIS
\fIassembling.metabolic(\fBcell\fR as <generic> CellularModule, 
\fBgeneKO\fR as list[string], 
\fBrepo\fR as <generic> RepositoryArguments);\fR
.SH DESCRIPTION
.PP
add metabolism network information for the virtual cell model
.PP
.SH OPTIONS
.PP
\fBcell\fB \fR\- -
.PP
.PP
\fBgeneKO\fB \fR\- -
.PP
.PP
\fBrepo\fB \fR\- -
.PP
.SH SEE ALSO
vcellkit.compiler
.SH FILES
.PP
vcellkit.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
