<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WebSocketTest</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>WebSocketTest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Flute\Flute.NET5.vbproj" />
  </ItemGroup>

</Project>
