.\" man page create by R# package system.
.TH CHROMOSOME_MAP 2 2000-1月 "draw" "draw"
.SH NAME
draw \- 
.SH SYNOPSIS
\fIdraw(\fBgenome\fR as any, 
\fBconfig\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBgenome\fB \fR\- -. 
.PP
.PP
\fBconfig\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
chromosome_map
.SH FILES
.PP
visualkit.dll
.PP
