.\" man page create by R# package system.
.TH CHROMOSOME_MAP 2 2000-1月 "config" "config"
.SH NAME
config \- load configuration file or create default configuration.
.SH SYNOPSIS
\fIconfig(\fBconf\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
load configuration file or create default configuration.
.PP
.SH OPTIONS
.PP
\fBconf\fB \fR\- -. 
.PP
.SH SEE ALSO
chromosome_map
.SH FILES
.PP
visualkit.dll
.PP
