.\" man page create by R# package system.
.TH FBA 1 2000-1月 "lpsolve" "lpsolve"
.SH NAME
lpsolve \- Solve a FBA matrix model
.SH SYNOPSIS
\fIlpsolve(\fBmodel\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
Solve a FBA matrix model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.SH VALUE
.PP
a tuple list of the FBA lpp solver result:
 
 + objective, target objective function value
 + flux, the flux distribution result tuple list, key name is the flux id and the value is the flux value. 
 
 additional, the original .NET CLR @\fBT:Microsoft.VisualBasic.Math.LinearAlgebra.LinearProgramming.LPPSolution\fR object is attached inside the result object attribute \fBlpp\fR, which could be get from the result object via \fBattr(x)\fR function..
.PP
.SH SEE ALSO
FBA
.SH FILES
.PP
biosystem.dll
.PP
