.\" man page create by R# package system.
.TH FBA 1 2000-1月 "matrix" "matrix"
.SH NAME
matrix \- create FBA model matrix
.SH SYNOPSIS
\fImatrix(\fBmodel\fR as any, 
\fBterms\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create FBA model matrix
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- should be a GCModeller @\fBT:SMRUCC.genomics.GCModeller.Assembly.GCMarkupLanguage.v2.VirtualCell\fR or @\fBT:SMRUCC.genomics.GCModeller.ModellingEngine.Model.Cellular.CellularModule\fR model object, or a collection of the kegg @\fBT:SMRUCC.genomics.Assembly.KEGG.DBGET.bGetObject.Reaction\fR.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
FBA
.SH FILES
.PP
biosystem.dll
.PP
