.\" man page create by R# package system.
.TH STRINGWEBAPI 1 2000-Jan "downloads.gene_ids.interaction" "downloads.gene_ids.interaction"
.SH NAME
downloads.gene_ids.interaction \- 
.SH SYNOPSIS
\fIdownloads.gene_ids.interaction(\fBidList\fR as <generic> IEnumerable`1, 
\fBEXPORT\fR as string = "./");\fR
.SH SEE ALSO
stringWebApi
.SH FILES
.PP
cytoscape.dll
.PP
