.\" man page create by R# package system.
.TH STRINGWEBAPI 1 2000-Jan "downloads.genomics.interactions" "downloads.genomics.interactions"
.SH NAME
downloads.genomics.interactions \- 
.SH SYNOPSIS
\fIdownloads.genomics.interactions(\fBPTT\fR as <generic> PTT, 
\fBEXPORT\fR as string = "./");\fR
.SH SEE ALSO
stringWebApi
.SH FILES
.PP
cytoscape.dll
.PP
