.\" man page create by R# package system.
.TH TRN 1 2000-1月 "write_bicor" "write_bicor"
.SH NAME
write_bicor \- 
.SH SYNOPSIS
\fIwrite_bicor(\fBx\fR as <generic> Matrix, 
\fBrepo\fR as string, 
\fBtype\fR as <integer> CorrelationEncodings = [Float32], 
\fBwgcnaOpts\fR as <generic> WGCNAConfig = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
TRN
.SH FILES
.PP
cytoscape.dll
.PP
