.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-1月 "predict_sequence" "predict_sequence"
.SH NAME
predict_sequence \- 
.SH SYNOPSIS
\fIpredict_sequence(\fBmodel\fR as <generic> TransformerModel, 
\fBec_number\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
