.\" man page create by R# package system.
.TH PROTEINKIT 1 2000-1月 "read.pfam_string" "read.pfam_string"
.SH NAME
read.pfam_string \- read the table file of pfam protein domain annotation data, and return the [PfamString](cref:T:SMRUCC.genomics.Data.Xfam.Pfam.PfamString.PfamString) object model
.SH SYNOPSIS
\fIread.pfam_string(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the table file of pfam protein domain annotation data, and return the [PfamString](cref:T:SMRUCC.genomics.Data.Xfam.Pfam.PfamString.PfamString) object model
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path of the pfam protein domain annotation csv table file.
. 
.PP
.SH VALUE
.PP
a vector of the [PfamString](cref:T:SMRUCC.genomics.Data.Xfam.Pfam.PfamString.PfamString) protein domain annotation 
 object that loaded from the given table file.
.PP
.SH SEE ALSO
proteinKit
.SH FILES
.PP
seqtoolkit.dll
.PP
