.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "as.data.frame" "as.data.frame"
.SH NAME
as.data.frame \- 
.SH SYNOPSIS
\fIas.data.frame(\fBresult\fR as <generic> PredictionResult[], 
\fBargs\fR as list, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
