.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "as.genes" "as.genes"
.SH NAME
as.genes \- Extract the gene sequences from the gene prediction result, and return as FASTA format. The sequence ID is in the format of "seqid_geneindex". For example, "contig1_5" means the 5th predicted gene on contig1. The sequence description is in the format of "start-end(strand)". For example, "100-900(+)" means the gene starts at position 100, ends at position 900, and is on the forward strand.
.SH SYNOPSIS
\fIas.genes(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Extract the gene sequences from the gene prediction result, and return as FASTA format. The sequence ID is in the format of "seqid_geneindex". For example, "contig1_5" means the 5th predicted gene on contig1. The sequence description is in the format of "start-end(strand)". For example, "100-900(+)" means the gene starts at position 100, ends at position 900, and is on the forward strand.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 the gene prediction result, which can be the output of the "prodigal" 
 function, or a pipeline that produces @\fBT:SMRUCC.genomics.Annotation.Prodigal.PredictionResult\fR 
 objects.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a collection of the @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR nucleotide sequence data, one 
 sequence object for each of the predicted gene, the sequence data is the 
 nucleotide sequence of the corresponding predicted gene region on the 
 contigs assembly sequence, and the sequence title is formatted as: 
 \fB{seq_id}_{gene_index} {start-end(strand)} ID=gene_{gene_index};partial={partial_type}\fR.
 
 this function returns a R# error message object if the input data can not 
 be cast to a collection of the @\fBT:SMRUCC.genomics.Annotation.Prodigal.PredictionResult\fR object.
.PP
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
