.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "prodigal" "prodigal"
.SH NAME
prodigal \- Prodigal (PROkaryotic DYnamic programming Gene-finding ALgorithm)
.SH SYNOPSIS
\fIprodigal(\fBx\fR as any, 
\fBmin_ORF_len\fR as integer = 90, 
\fBmodel\fR as <generic> TrainingModel = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Prodigal (PROkaryotic DYnamic programming Gene-finding ALgorithm)
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 the target MAGs contigs assembly sequence for run the gene prediction, 
 which can be a @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaFile\fR object, a collection of the 
 @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR object, or a file path of the fasta sequence file, 
 or even a character vector of the raw sequence data.
. 
.PP
.PP
\fBmin_ORF_len\fB \fR\- 
 the minimum ORF length in bp of the predicted gene, any of the candidate 
 ORF that its length is less than this threshold value will be ignored in 
 the gene prediction.
. 
.PP
.PP
\fBmodel\fB \fR\- 
 the prodigal training model, which is the output of the 
 \fBprodigal_training\fR function. If this parameter is nothing(the default 
 value), then the model will be trained from the input contigs assembly 
 sequence in an unsupervised manner automatically.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a collection of the gene prediction result: each element in the 
 collection(@\fBT:SMRUCC.genomics.Annotation.Prodigal.PredictionResult\fR) is the gene prediction result 
 of the corresponding contigs sequence in the input fasta sequence data.
 
 this function returns a R# error message object if the input sequence 
 data is nothing or can not be cast to a fasta sequence collection.
.PP
.SH DETAILS
.PP
The prodigal gene prediction pipeline is implemented in an ab-initio 
 manner: a training model will be learned from the input contigs assembly 
 sequence at first(when the \fBmodel\fR parameter is not specified), and 
 then the gene finding algorithm is running based on the dynamic programming 
 score of the coding/non-coding hexamer and the RBS motif of the trained 
 model.
.PP
.SH EXAMPLES
.PP
imports "bioseq.fasta" from "seqtoolkit";
 imports "bifrost" from "seqtoolkit";
 imports "annotation.genomics" from "seqtoolkit";
 
 # an example workflow script for run prodigal gene prediction on MAGs contigs assembly sequence, 
 # and export the result to files. The input contigs assembly sequence is in FASTA format, 
 # and the output gene prediction result is in PredictionResult format, which can be further 
 # converted to GFF3 format, or gene/protein FASTA format. The example workflow script is 
 # as follows:
 
 # read the contigs assembly sequence from a FASTA file
 let MAGs <- "MAGs_contigs.fasta";
 let contigs <- read.fasta(MAGs);
 # predict genes on the contigs assembly sequence 
 let result <- prodigal(contigs, min.ORF.len = 90);
 
 # export result to files
 write.csv(as.data.frame(result), file = "gene_predicts.csv");
 # export the gene prediction result to GFF3 format
 write.gff3(as.gff3(result), file = "gene_predicts.gff3");
 # export gene/protein fasta sequence to file
 write.fasta(as.genes(result), file = "gene_predicts.fna");
 write.fasta(as.proteins(result), file = "protein_predicts.faa");
.PP
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
