.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "prodigal" "prodigal"
.SH NAME
prodigal \- Prodigal (PROkaryotic DYnamic programming Gene-finding ALgorithm)
.SH SYNOPSIS
\fIprodigal(\fBx\fR as any, 
\fBmin_ORF_len\fR as integer = 90, 
\fBmodel\fR as <generic> TrainingModel = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Prodigal (PROkaryotic DYnamic programming Gene-finding ALgorithm)
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBmin_ORF_len\fB \fR\- -. 
.PP
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
