.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "prodigal_training" "prodigal_training"
.SH NAME
prodigal_training \- Train the gene prediction model in an unsupervised manner
.SH SYNOPSIS
\fIprodigal_training(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Train the gene prediction model in an unsupervised manner
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 input target fasta sequence collection for make prodigal training, it 
 should be a set of the genomics contigs assembly sequence, which can be 
 a @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaFile\fR object, a collection of the 
 @\fBT:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq\fR object, or a file path of the fasta sequence file, 
 or even a character vector of the raw sequence data.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a trained \fBprodigal\fR @\fBT:SMRUCC.genomics.Annotation.Prodigal.TrainingModel\fR object, which can be 
 used for the gene prediction of the other genomics contigs assembly 
 sequence that come from the same or a close related species, via the 
 \fBmodel\fR parameter of the \fBprodigal\fR function.
 
 this function returns a R# error message object if the input sequence 
 data is nothing or can not be cast to a fasta sequence collection.
.PP
.SH EXAMPLES
.PP
imports "bioseq.fasta" from "seqtoolkit";
 imports "bifrost" from "seqtoolkit";
 
 # train the gene prediction model from a well assembled 
 # genomics contigs sequence, and then apply the trained 
 # model on the other MAGs contigs of the same species
 let model <- prodigal_training(read.fasta("./genome.fasta"));
 let genes <- prodigal(read.fasta("./MAGs_contigs.fasta"), model = model);
.PP
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
