.\" man page create by R# package system.
.TH BIFROST 1 2000-1月 "prodigal" "prodigal"
.SH NAME
prodigal \- Prodigal (PROkaryotic DYnamic programming Gene-finding ALgorithm)
.SH SYNOPSIS
\fIprodigal(\fBx\fR as any, 
\fBmin_ORF_len\fR as integer = 90, 
\fBmodel\fR as <generic> TrainingModel = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Prodigal (PROkaryotic DYnamic programming Gene-finding ALgorithm)
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBmin_ORF_len\fB \fR\- -. 
.PP
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH EXAMPLES
.PP
imports "bioseq.fasta" from "seqtoolkit";
 imports "bifrost" from "seqtoolkit";
 imports "annotation.genomics" from "seqtoolkit";
 
 # an example workflow script for run prodigal gene prediction on MAGs contigs assembly sequence, 
 # and export the result to files. The input contigs assembly sequence is in FASTA format, 
 # and the output gene prediction result is in PredictionResult format, which can be further 
 # converted to GFF3 format, or gene/protein FASTA format. The example workflow script is 
 # as follows:
 
 # read the contigs assembly sequence from a FASTA file
 let MAGs <- "MAGs_contigs.fasta";
 let contigs <- read.fasta(MAGs);
 # predict genes on the contigs assembly sequence 
 let result <- prodigal(contigs, min.ORF.len = 90);
 
 # export result to files
 write.csv(as.data.frame(result), file = "gene_predicts.csv");
 # export the gene prediction result to GFF3 format
 write.gff3(as.gff3(result), file = "gene_predicts.gff3");
 # export gene/protein fasta sequence to file
 write.fasta(as.genes(result), file = "gene_predicts.fna");
 write.fasta(as.proteins(result), file = "protein_predicts.faa");
.PP
.SH SEE ALSO
bifrost
.SH FILES
.PP
seqtoolkit.dll
.PP
