.\" man page create by R# package system.
.TH STATS 1 2020-07-26 "as.dist" "as.dist"
.SH NAME
as.dist \- 
.SH SYNOPSIS
\fIas.dist(\fBx\fR as <generic> dataframe, 
\fBis_matrix\fR as boolean = TRUE, 
..., 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -
.PP
.PP
\fBis_matrix\fB \fR\- -
.PP
.PP
\fBprojection\fB \fR\- 
 argument for extract data from the given data object, this parameter is depends 
 on the **`is_matrix`** argument, for:
 
 + is_matrix: means the given data is a matrix liked data, then \fBtype\fR should be exists.
 + not is_matrix: means the given data is a tabular data for represents the data matrix, 
                  then slots \fBf1\fR, \fBf2\fR, and \fBval\fR should be exists.

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
