.\" man page create by R# package system.
.TH STATS 1 2020-12-15 "corr" "corr"
.SH NAME
corr \- matrix correlation
.SH SYNOPSIS
\fIcorr(\fBx\fR as <generic> dataframe, 
\fBspearman\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
matrix correlation
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- evaluate correlation for each row elements
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
