.\" man page create by R# package system.
.TH STATS 1 2020-10-29 "fisher.test" "fisher.test"
.SH NAME
fisher.test \- Fisher's Exact Test for Count Data
.SH SYNOPSIS
\fIfisher.test(\fBa\fR as integer, 
\fBb\fR as integer, 
\fBc\fR as integer, 
\fBd\fR as integer);\fR
.SH DESCRIPTION
.PP
Fisher's Exact Test for Count Data
 
 Performs Fisher's exact test for testing the null of independence 
 of rows and columns in a contingency table with fixed marginals.
.PP
.SH OPTIONS
.PP
\fBa%\fB \fR\- -
.PP
.PP
\fBb%\fB \fR\- -
.PP
.PP
\fBc%\fB \fR\- -
.PP
.PP
\fBd%\fB \fR\- -
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
