.\" man page create by R# package system.
.TH STATS 1 2020-07-26 "spline" "spline"
.SH NAME
spline \- Interpolating Splines
.SH SYNOPSIS
\fIspline(\fBdata\fR as <generic> Object, 
\fBalgorithm\fR as <integer> SplineAlgorithms = [BSpline], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Interpolating Splines
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
R.math.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
