.\" man page create by R# package system.
.TH UNIPROT 1 2000-01-01 "extract_fasta" "extract_fasta"
.SH NAME
extract_fasta \- extract fasta data from a HDS stream database
.SH SYNOPSIS
\fIextract_fasta(\fBpack\fR as <generic> ECNumberReader, 
\fBenzyme\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
extract fasta data from a HDS stream database
.PP
.SH OPTIONS
.PP
\fBpack\fB \fR\- -. 
.PP
.PP
\fBenzyme\fB \fR\- -. 
.PP
.SH SEE ALSO
UniProt
.SH FILES
.PP
annotationKit.dll
.PP
