.\" man page create by R# package system.
.TH UNIPROT 1 2000-Jan "rest_query" "rest_query"
.SH NAME
rest_query \- make query of the proteins from the uniprot rest api
.SH SYNOPSIS
\fIrest_query(\fBq\fR as string);\fR
.SH DESCRIPTION
.PP
make query of the proteins from the uniprot rest api
.PP
.SH OPTIONS
.PP
\fBq\fB \fR\- -. 
.PP
.SH SEE ALSO
UniProt
.SH FILES
.PP
annotationKit.dll
.PP
