.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-1月 "besthit.filter" "besthit.filter"
.SH NAME
besthit.filter \- 
.SH SYNOPSIS
\fIbesthit.filter(\fBbesthits\fR as <generic> pipeline, 
\fBevalue\fR as double = 1E-05, 
\fBdelNohits\fR as boolean = TRUE, 
\fBpickTop\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
