.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-01-01 "read.blast" "read.blast"
.SH NAME
read.blast \- Open the blast output text file for parse data result.
.SH SYNOPSIS
\fIread.blast(\fBfile\fR as string, 
\fBtype\fR as string = "nucl", 
\fBfastMode\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Open the blast output text file for parse data result.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBtype\fB \fR\- \fBnucl\fR or \fBprot\fR. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
