.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-1月 "read.outfmt6" "read.outfmt6"
.SH NAME
read.outfmt6 \- read ncbi blast output format 6 (tabular) file for blastn result mapping to genome sequence
.SH SYNOPSIS
\fIread.outfmt6(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read ncbi blast output format 6 (tabular) file for blastn result mapping to genome sequence
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
