.\" man page create by R# package system.
.TH ANNOTATION.WORKFLOW 2 2000-Jan "stream.flush" "stream.flush"
.SH NAME
stream.flush \- 
.SH SYNOPSIS
\fIstream.flush(\fBdata\fR as <generic> pipeline, 
\fBstream\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.workflow
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
