.\" man page create by R# package system.
.TH KMERS 1 2000-1月 "tfidf_vectorizer" "tfidf_vectorizer"
.SH NAME
tfidf_vectorizer \- 
.SH SYNOPSIS
\fItfidf_vectorizer(\fBx\fR as any, 
\fBtype\fR as <integer> SeqTypes = [Protein], 
\fBk\fR as integer = 6, 
\fBL2_norm\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
kmers
.SH FILES
.PP
seqtoolkit.dll
.PP
