.\" man page create by R# package system.
.TH PROFILES 1 2000-1月 "category_labels" "category_labels"
.SH NAME
category_labels \- get category labels for a given id set
.SH SYNOPSIS
\fIcategory_labels(\fBcategory\fR as <generic> ClassProfiles, 
\fBidSet\fR as string, 
\fBlevel\fR as integer = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get category labels for a given id set
.PP
.SH OPTIONS
.PP
\fBcategory\fB \fR\- -. 
.PP
.PP
\fBidSet\fB \fR\- 
 a character vector of the target id set
. 
.PP
.PP
\fBlevel\fB \fR\- level1 or level2. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
