.\" man page create by R# package system.
.TH PROFILES 1 2000-1月 "dag_enrichment_profile" "dag_enrichment_profile"
.SH NAME
dag_enrichment_profile \- 
.SH SYNOPSIS
\fIdag_enrichment_profile(\fBenrichments\fR as any, 
\fBobo\fR as <generic> GO_OBO, 
\fBroot\fR as string, 
\fBtop\fR as integer = 10, 
\fBpvalue_cut\fR as double = 1, 
\fBsort\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBenrichments\fB \fR\- -. 
.PP
.PP
\fBobo\fB \fR\- -. 
.PP
.PP
\fBroot\fB \fR\- 
 the root term id
. 
.PP
.PP
\fBtop\fB \fR\- -. 
.PP
.PP
\fBpvalue_cut\fB \fR\- -. 
.PP
.PP
\fBsort\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
