.\" man page create by R# package system.
.TH PROFILES 1 2000-01-01 "GO.enrichment.profile" "GO.enrichment.profile"
.SH NAME
GO.enrichment.profile \- Create catalog profiles data for GO enrichment result its data visualization.
.SH SYNOPSIS
\fIGO.enrichment.profile(\fBenrichments\fR as <generic> EnrichmentTerm[], 
\fBgoDb\fR as <generic> GO_OBO, 
\fBtop\fR as integer = 10);\fR
.SH DESCRIPTION
.PP
Create catalog profiles data for GO enrichment result its data visualization.
.PP
.SH OPTIONS
.PP
\fBenrichments\fB \fR\- -. 
.PP
.PP
\fBgoDb\fB \fR\- -. 
.PP
.PP
\fBtop\fB \fR\- display the top n enriched GO terms.. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
