.\" man page create by R# package system.
.TH PROFILES 1 2000-01-01 "KEGG.enrichment.profile" "KEGG.enrichment.profile"
.SH NAME
KEGG.enrichment.profile \- 
.SH SYNOPSIS
\fIKEGG.enrichment.profile(\fBenrichments\fR as <generic> EnrichmentTerm[], 
\fBtop\fR as integer = 10);\fR
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
