.\" man page create by R# package system.
.TH PROFILES 1 2000-1月 "KEGG.enrichment.profile" "KEGG.enrichment.profile"
.SH NAME
KEGG.enrichment.profile \- A method for cast the kegg enrichment result to the
.SH SYNOPSIS
\fIKEGG.enrichment.profile(\fBenrichments\fR as any, 
\fBtop\fR as integer = 10, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
A method for cast the kegg enrichment result to the 
 category profiles for run data visualization
.PP
.SH OPTIONS
.PP
\fBenrichments\fB \fR\- -. 
.PP
.PP
\fBtop%\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
