.\" man page create by R# package system.
.TH PROFILES 1 2000-01-01 "no_catagory_profile" "no_catagory_profile"
.SH NAME
no_catagory_profile \- 
.SH SYNOPSIS
\fIno_catagory_profile(\fBenrichments\fR as <generic> EnrichmentTerm[], 
\fBname\fR as string, 
\fBtop\fR as integer = 30);\fR
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
