.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "add_gauss" "add_gauss"
.SH NAME
add_gauss \- add random gauss noise to the matrix
.SH SYNOPSIS
\fIadd_gauss(\fBx\fR as <generic> Matrix, 
\fBscale\fR as double = 0.1);\fR
.SH DESCRIPTION
.PP
add random gauss noise to the matrix
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBscale\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
