.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "aggregate_samples" "aggregate_samples"
.SH NAME
aggregate_samples \- function alias of the \fBgeneExpression::average\fR function
.SH SYNOPSIS
\fIaggregate_samples(\fBmatrix\fR as <generic> Matrix, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
function alias of the \fBgeneExpression::average\fR function
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- -. 
.PP
.PP
\fBgroups\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
