.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "aggregate" "aggregate"
.SH NAME
aggregate \- merge row or column where the tag is identical
.SH SYNOPSIS
\fIaggregate(\fBx\fR as <generic> Matrix, 
\fBbyrow\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
merge row or column where the tag is identical
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBbyrow\fB \fR\- 
 default by gene feature row means merge the duplicated genes with the idential gene id as tag.
 otherwise will merge the duplicated samples with the identical sample id name.
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
