.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "as.abundance_matrix" "as.abundance_matrix"
.SH NAME
as.abundance_matrix \- 
.SH SYNOPSIS
\fIas.abundance_matrix(\fBsamples\fR as any, 
\fBnormalized\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
