.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "as.deg" "as.deg"
.SH NAME
as.deg \- create gene expression DEG model
.SH SYNOPSIS
\fIas.deg(\fBx\fR as any, 
\fBlogFC\fR as string = "logFC", 
\fBpvalue\fR as string = "pvalue", 
\fBlabel\fR as string = "id", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create gene expression DEG model
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- usually be a dataframe object of the different expression analysis result. 
.PP
.PP
\fBlogFC\fB \fR\- the column name of the log2 fold change data in the input dataframe.. 
.PP
.PP
\fBpvalue\fB \fR\- the column name of the p-value data in the input dataframe.. 
.PP
.PP
\fBlabel\fB \fR\- the column name of the gene id label data in the input dataframe.. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.GCModeller.Workbench.ExperimentDesigner.DEGModel\fR deg result data that is created from 
 the given dataframe columns;
 
 this function returns a R# error message object if the input data is not a 
 dataframe object.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
