.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "as.deg" "as.deg"
.SH NAME
as.deg \- create gene expression DEG model
.SH SYNOPSIS
\fIas.deg(\fBx\fR as any, 
\fBlogFC\fR as string = "logFC", 
\fBpvalue\fR as string = "pvalue", 
\fBlabel\fR as string = "id", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create gene expression DEG model
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBlogFC\fB \fR\- -. 
.PP
.PP
\fBpvalue\fB \fR\- -. 
.PP
.PP
\fBlabel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
