.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "as.expr_list" "as.expr_list"
.SH NAME
as.expr_list \- convert the matrix into row gene list
.SH SYNOPSIS
\fIas.expr_list(\fBexpr0\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
convert the matrix into row gene list
.PP
.SH OPTIONS
.PP
\fBexpr0\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
