.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "as.generic" "as.generic"
.SH NAME
as.generic \- cast the HTS matrix object to the general dataset
.SH SYNOPSIS
\fIas.generic(\fBmatrix\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
cast the HTS matrix object to the general dataset
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- a gene expression matrix. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
