.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "deg.class" "deg.class"
.SH NAME
deg.class \- set deg class label
.SH SYNOPSIS
\fIdeg.class(\fBdeg\fR as <generic> DEGModel[], 
\fBclass_labels\fR as any = \fB<NULL>\fR, 
\fBlogFC\fR as double = 1, 
\fBpval_cutoff\fR as double = 0.05);\fR
.SH DESCRIPTION
.PP
set deg class label
.PP
.SH OPTIONS
.PP
\fBdeg\fB \fR\- -. 
.PP
.PP
\fBclass_labels\fB \fR\- 
 set deg class label manually
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
