.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "deg.t.test" "deg.t.test"
.SH NAME
deg.t.test \- do t-test across specific analysis comparision
.SH SYNOPSIS
\fIdeg.t.test(\fBx\fR as <generic> Matrix, 
\fBsampleinfo\fR as <generic> SampleInfo[], 
\fBtreatment\fR as string, 
\fBcontrol\fR as string, 
\fBlevel\fR as double = 1.5, 
\fBpvalue\fR as double = 0.05, 
\fBFDR\fR as double = 0.05, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do t-test across specific analysis comparision
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a gene expression matrix object. 
.PP
.PP
\fBsampleinfo\fB \fR\- 
 the sample group information data, which is used for get the sample id 
 list of the treatment group and the control group.
. 
.PP
.PP
\fBtreatment\fB \fR\- group name of the treatment group. 
.PP
.PP
\fBcontrol\fB \fR\- group name of the control group. 
.PP
.PP
\fBlevel\fB \fR\- log2FC cutoff level. 
.PP
.PP
\fBpvalue\fB \fR\- the t-test pvalue cutoff. 
.PP
.PP
\fBFDR\fB \fR\- the FDR cutoff. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.Analysis.HTS.Proteomics.DEP_iTraq\fR deg result data of the t-test 
 analysis, which is filtered by the given log2FC, p-value and FDR cutoff 
 value.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
