.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "dims" "dims"
.SH NAME
dims \- get summary information about the HTS matrix dimensions
.SH SYNOPSIS
\fIdims(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get summary information about the HTS matrix dimensions
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a HTS data matrix of samples in column and gene features in row
. 
.PP
.SH VALUE
.PP
a tuple list that contains the dimension information of the 
 gene expression matrix data:
 
 + feature_size: the number of the matrix rows, or count of genes in matrix
 + feature_names: a character vector of the gene ids for each rows
 + sample_size: the number of the samples, or number of the matrix columns
 + sample_names: the matrix column names, the sample id set
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
