.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "dims" "dims"
.SH NAME
dims \- get summary information about the HTS matrix dimensions
.SH SYNOPSIS
\fIdims(\fBmat\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
get summary information about the HTS matrix dimensions
.PP
.SH OPTIONS
.PP
\fBmat\fB \fR\- 
 a HTS data matrix of samples in column and gene features in row
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
