.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "expr_ranking" "expr_ranking"
.SH NAME
expr_ranking \- 
.SH SYNOPSIS
\fIexpr_ranking(\fBx\fR as <generic> Matrix, 
\fBsampleinfo\fR as <generic> SampleInfo[]);\fR
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
