.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "expression_vector" "expression_vector"
.SH NAME
expression_vector \- get gene expression vector data
.SH SYNOPSIS
\fIexpression_vector(\fBx\fR as <generic> Matrix, 
\fBgeneId\fR as string);\fR
.SH DESCRIPTION
.PP
get gene expression vector data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBgeneId\fB \fR\- -. 
.PP
.SH VALUE
.PP
a numeric vector of the target gene expression across multiple samples
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
