.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "expression.cmeans3D" "expression.cmeans3D"
.SH NAME
expression.cmeans3D \- run cmeans clustering in 3 patterns
.SH SYNOPSIS
\fIexpression.cmeans3D(\fBmatrix\fR as <generic> Matrix, 
\fBfuzzification\fR as double = 2, 
\fBthreshold\fR as double = 0.001);\fR
.SH DESCRIPTION
.PP
run cmeans clustering in 3 patterns
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- a gene expression matrix object. 
.PP
.PP
\fBfuzzification\fB \fR\- the cmeans fuzzification parameter. 
.PP
.PP
\fBthreshold\fB \fR\- the cmeans threshold parameter. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
