.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "filterNaNMissing" "filterNaNMissing"
.SH NAME
filterNaNMissing \- set the NaN missing value to default value
.SH SYNOPSIS
\fIfilterNaNMissing(\fBx\fR as <generic> Matrix, 
\fBmissingDefault\fR as double = 0, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set the NaN missing value to default value
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBmissingDefault\fB \fR\- 
 set NA missing value to zero by default
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
