.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "filter" "filter"
.SH NAME
filter \- Filter the geneID rows
.SH SYNOPSIS
\fIfilter(\fBHTS\fR as <generic> Matrix, 
\fBgeneId\fR as string, 
\fBexclude\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Filter the geneID rows
.PP
.SH OPTIONS
.PP
\fBHTS\fB \fR\- -. 
.PP
.PP
\fBgeneId\fB \fR\- -. 
.PP
.PP
\fBexclude\fB \fR\- matrix a subset of the data matrix excepts the 
 input **`geneId`** features or just make a subset which 
 just contains the input **`geneId`** features.
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
