.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "filterZeroGenes" "filterZeroGenes"
.SH NAME
filterZeroGenes \- removes the rows which all gene expression result is ZERO
.SH SYNOPSIS
\fIfilterZeroGenes(\fBmat\fR as <generic> Matrix, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
removes the rows which all gene expression result is ZERO
.PP
.SH OPTIONS
.PP
\fBmat\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
