.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "filterZeroSamples" "filterZeroSamples"
.SH NAME
filterZeroSamples \- filter out all samples columns which its expression vector is ZERO!
.SH SYNOPSIS
\fIfilterZeroSamples(\fBmat\fR as <generic> Matrix, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
filter out all samples columns which its expression vector is ZERO!
.PP
.SH OPTIONS
.PP
\fBmat\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
