.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "geneId" "geneId"
.SH NAME
geneId \- get gene Id list
.SH SYNOPSIS
\fIgeneId(\fBdep\fR as <generic> DEP_iTraq[]);\fR
.SH DESCRIPTION
.PP
get gene Id list
.PP
.SH OPTIONS
.PP
\fBdep\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
