.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "impute_missing" "impute_missing"
.SH NAME
impute_missing \- set the zero value to the half of the min positive value
.SH SYNOPSIS
\fIimpute_missing(\fBx\fR as <generic> Matrix, 
\fBby_features\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
set the zero value to the half of the min positive value
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- an expression matrix object that may contains zero. 
.PP
.SH VALUE
.PP
An expression data matrix with missing data filled
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
