.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "joinFeatures" "joinFeatures"
.SH NAME
joinFeatures \- merge multiple gene expression matrix by gene features
.SH SYNOPSIS
\fIjoinFeatures(\fBx\fR as any, 
\fBstrict\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
merge multiple gene expression matrix by gene features
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBstrict\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
