.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "joinSample" "joinSample"
.SH NAME
joinSample \- do matrix join by samples
.SH SYNOPSIS
\fIjoinSample(\fBsamples\fR as <generic> Matrix[], 
\fBstrict\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
do matrix join by samples
.PP
.SH OPTIONS
.PP
\fBsamples\fB \fR\- 
 matrix in multiple batches data should be normalized at
 first before calling this data batch merge function.
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
