.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "limma" "limma"
.SH NAME
limma \- The limma algorithm (Linear Models for Microarray Data) is a widely used statistical framework in R/Bioconductor
.SH SYNOPSIS
\fIlimma(\fBx\fR as <generic> Matrix, 
\fBdesign\fR as <generic> DataAnalysis);\fR
.SH DESCRIPTION
.PP
The limma algorithm (Linear Models for Microarray Data) is a widely used statistical framework in R/Bioconductor 
 for differential expression (DE) analysis of RNA-seq data. Originally designed for microarray studies, its 
 flexibility and robustness have extended its utility to RNA-seq through the voomtransformation.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBdesign\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
