.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "limma" "limma"
.SH NAME
limma \- The limma algorithm (Linear Models for Microarray Data) is a widely used statistical framework in R/Bioconductor
.SH SYNOPSIS
\fIlimma(\fBx\fR as <generic> Matrix, 
\fBdesign\fR as <generic> DataAnalysis);\fR
.SH DESCRIPTION
.PP
The limma algorithm (Linear Models for Microarray Data) is a widely used statistical framework in R/Bioconductor 
 for differential expression (DE) analysis of RNA-seq data. Originally designed for microarray studies, its 
 flexibility and robustness have extended its utility to RNA-seq through the voomtransformation.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a gene expression matrix object. 
.PP
.PP
\fBdesign\fB \fR\- 
 the experiment design data of the RNA-seq dataset, which describes the 
 sample group information and the linear model design of the limma 
 analysis.
. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.Analysis.HTS.DataFrame.LimmaTable\fR differential expression analysis 
 result: the \fBlogFC\fR, \fBAveExpr\fR, \fBt\fR, \fBP_Value\fR, \fBadj_P_Val\fR and 
 \fBB\fR data of each gene feature.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
