.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "limma_table" "limma_table"
.SH NAME
limma_table \- 
.SH SYNOPSIS
\fIlimma_table(\fBid\fR as any, 
\fBlogFC\fR as any, 
\fBaveExpr\fR as any, 
\fBt\fR as any, 
\fBpval\fR as any, 
\fBadj_pval\fR as any, 
\fBb\fR as any);\fR
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
