.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "limma_impactsort" "limma_impactsort"
.SH NAME
limma_impactsort \- 
.SH SYNOPSIS
\fIlimma_impactsort(\fBx\fR as any, 
\fBtop\fR as integer = 2147483647, 
\fBlogfc_impact\fR as boolean = FALSE, 
\fBclass\fR as list = \fB<NULL>\fR, 
\fBnames\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBtop\fB \fR\- -. 
.PP
.PP
\fBlogfc_impact\fB \fR\- -. 
.PP
.PP
\fBclass\fB \fR\- 
 the id class data, example as: 
 list(class1 = c(...), class2 = c(...), class3 = c(...))
. 
.PP
.PP
\fBnames\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
