.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "limma_table" "limma_table"
.SH NAME
limma_table \- build limma table model from the dataframe columns
.SH SYNOPSIS
\fIlimma_table(\fBid\fR as any, 
\fBlogFC\fR as any, 
\fBaveExpr\fR as any, 
\fBt\fR as any, 
\fBpval\fR as any, 
\fBadj_pval\fR as any, 
\fBb\fR as any);\fR
.SH DESCRIPTION
.PP
build limma table model from the dataframe columns
.PP
.SH OPTIONS
.PP
\fBid\fB \fR\- -. 
.PP
.PP
\fBlogFC\fB \fR\- -. 
.PP
.PP
\fBaveExpr\fB \fR\- -. 
.PP
.PP
\fBt\fB \fR\- -. 
.PP
.PP
\fBpval\fB \fR\- -. 
.PP
.PP
\fBadj_pval\fB \fR\- -. 
.PP
.PP
\fBb\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
