.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "limma_impactsort" "limma_impactsort"
.SH NAME
limma_impactsort \- 
.SH SYNOPSIS
\fIlimma_impactsort(\fBx\fR as any, 
\fBtop\fR as integer = 2147483647, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
