.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "load.expr0" "load.expr0"
.SH NAME
load.expr0 \- read the binary matrix data file
.SH SYNOPSIS
\fIload.expr0(\fBfile\fR as any, 
\fBlazy\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read the binary matrix data file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a HTS data matrix of samples in column and gene features in row
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
