.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "load.expr" "load.expr"
.SH NAME
load.expr \- load an expressin matrix data
.SH SYNOPSIS
\fIload.expr(\fBfile\fR as any, 
\fBexclude_samples\fR as string = \fB<NULL>\fR, 
\fBrm_ZERO\fR as boolean = FALSE, 
\fBmakeNames\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load an expressin matrix data
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path or the file stream data of the target 
 expression matrix table file.
. 
.PP
.PP
\fBexclude_samples\fB \fR\- 
 will removes some sample column data from the expression
 matrix which is specificed by this parameter value.
. 
.PP
.SH DETAILS
.PP
the table file format that handled by this function
 could be a csv table file or tsv table file.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
