.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "log" "log"
.SH NAME
log \- log scale of the HTS raw matrix
.SH SYNOPSIS
\fIlog(\fBexpr\fR as any, 
\fBbase\fR as double = 2.718281828459045);\fR
.SH DESCRIPTION
.PP
log scale of the HTS raw matrix
.PP
.SH OPTIONS
.PP
\fBexpr\fB \fR\- should be a HTS expression matrix object. 
.PP
.PP
\fBbase\fB \fR\- -. 
.PP
.SH VALUE
.PP
this function may produce negative expression value if the value number is less than 1.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
