.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "mad" "mad"
.SH NAME
mad \- evaluate the MAD value for each gene features
.SH SYNOPSIS
\fImad(\fBx\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
evaluate the MAD value for each gene features
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
