.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "matrix_info" "matrix_info"
.SH NAME
matrix_info \- get matrix summary information
.SH SYNOPSIS
\fImatrix_info(\fBfile\fR as any);\fR
.SH DESCRIPTION
.PP
get matrix summary information
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 could be a file path or the HTS matrix data object
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
