.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "minmax01Norm" "minmax01Norm"
.SH NAME
minmax01Norm \- min max normalization
.SH SYNOPSIS
\fIminmax01Norm(\fBx\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
min max normalization
 
 (row - min(row)) / (max(row) - min(row))
 
 this normalization method is usually used for the metabolomics data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
