.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "pattern_representatives" "pattern_representatives"
.SH NAME
pattern_representatives \- get the top n representatives genes in each expression pattern
.SH SYNOPSIS
\fIpattern_representatives(\fBpattern\fR as <generic> ExpressionPattern, 
\fBtop\fR as integer = 3);\fR
.SH DESCRIPTION
.PP
get the top n representatives genes in each expression pattern
.PP
.SH OPTIONS
.PP
\fBpattern\fB \fR\- -. 
.PP
.PP
\fBtop\fB \fR\- top n cmeans membership items. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
