.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "pca" "pca"
.SH NAME
pca \- do PCA on a gene expressin matrix
.SH SYNOPSIS
\fIpca(\fBx\fR as <generic> Matrix, 
\fBnpc\fR as integer = 3);\fR
.SH DESCRIPTION
.PP
do PCA on a gene expressin matrix
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a gene expression matrix. 
.PP
.PP
\fBnpc\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
