.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "project" "project"
.SH NAME
project \- make matrix samples column projection
.SH SYNOPSIS
\fIproject(\fBx\fR as <generic> Matrix, 
\fBsampleIds\fR as any);\fR
.SH DESCRIPTION
.PP
make matrix samples column projection
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBsampleIds\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
