.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "readPattern" "readPattern"
.SH NAME
readPattern \- read the cmeans expression pattern result from file
.SH SYNOPSIS
\fIreadPattern(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the cmeans expression pattern result from file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
