.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "readPattern" "readPattern"
.SH NAME
readPattern \- read the cmeans expression pattern result from file
.SH SYNOPSIS
\fIreadPattern(\fBfile\fR as string, 
\fBsamples\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
read the cmeans expression pattern result from file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- a binary data pack file that contains the expression pattern raw data.
 if this file is given by a csv file, then this csv file should be the cmeans cluster 
 membership matrix outtput.. 
.PP
.PP
\fBsamples\fB \fR\- 
 should be a csv file path to the sample matrix data if the input **`file`**
 is a csv membership matrix file.
. 
.PP
.SH DETAILS
.PP
this function can also read the csv matrix file and 
 then cast as the expression pattern data object.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
