.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "relative" "relative"
.SH NAME
relative \- normalize data by feature rows
.SH SYNOPSIS
\fIrelative(\fBmatrix\fR as <generic> Matrix);\fR
.SH DESCRIPTION
.PP
normalize data by feature rows
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- -. 
.PP
.SH DETAILS
.PP
row/max(row)
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
