.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "sample_auc" "sample_auc"
.SH NAME
sample_auc \- Calculate the sum of the sample data with time-series information across all time points to obtain the area under the curve (AUC) of the time-series curve.
.SH SYNOPSIS
\fIsample_auc(\fBx\fR as <generic> Matrix, 
\fBsampleinfo\fR as any, 
\fBsample\fR as string = "sample", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Calculate the sum of the sample data with time-series information across all time points to obtain the area under the curve (AUC) of the time-series curve.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBsampleinfo\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
