.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "savePattern" "savePattern"
.SH NAME
savePattern \- save the cmeans expression pattern result to local file
.SH SYNOPSIS
\fIsavePattern(\fBpattern\fR as <generic> ExpressionPattern, 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
save the cmeans expression pattern result to local file
.PP
.SH OPTIONS
.PP
\fBpattern\fB \fR\- 
 an @\fBT:SMRUCC.genomics.Visualize.ExpressionPattern.ExpressionPattern\fR object that is created by the 
 \fBexpression.cmeans_pattern\fR or \fBpeakCMeans\fR api.
. 
.PP
.PP
\fBfile\fB \fR\- 
 the file path of the binary data pack file for save the expression pattern 
 result.
. 
.PP
.SH VALUE
.PP
a boolean value for indicates that the expression pattern data has been 
 saved into the target file successfully or not.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
