.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "savePattern" "savePattern"
.SH NAME
savePattern \- save the cmeans expression pattern result to local file
.SH SYNOPSIS
\fIsavePattern(\fBpattern\fR as <generic> ExpressionPattern, 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
save the cmeans expression pattern result to local file
.PP
.SH OPTIONS
.PP
\fBpattern\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
