.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "setFeatures" "setFeatures"
.SH NAME
setFeatures \- set new gene id list to the matrix rows
.SH SYNOPSIS
\fIsetFeatures(\fBx\fR as any, 
\fBgene_ids\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set new gene id list to the matrix rows
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- target gene expression matrix object. 
.PP
.PP
\fBgene_ids\fB \fR\- 
 a collection of the new gene ids to set to the feature
 rows of the gene expression matrix.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
it is kind of \fBrownames\fR liked function for dataframe object.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
