.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "setTag" "setTag"
.SH NAME
setTag \- set a new tag string to the matrix
.SH SYNOPSIS
\fIsetTag(\fBexpr0\fR as <generic> Matrix, 
\fBtag\fR as string);\fR
.SH DESCRIPTION
.PP
set a new tag string to the matrix
.PP
.SH OPTIONS
.PP
\fBexpr0\fB \fR\- the target gene expression matrix object. 
.PP
.PP
\fBtag\fB \fR\- 
 a new tag label text for set to the given expression matrix object.
. 
.PP
.SH VALUE
.PP
the input matrix object that its tag data has been modified.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
