.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "setTag" "setTag"
.SH NAME
setTag \- set a new tag string to the matrix
.SH SYNOPSIS
\fIsetTag(\fBexpr0\fR as <generic> Matrix, 
\fBtag\fR as string);\fR
.SH DESCRIPTION
.PP
set a new tag string to the matrix
.PP
.SH OPTIONS
.PP
\fBexpr0\fB \fR\- -. 
.PP
.PP
\fBtag\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
