.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "setZero" "setZero"
.SH NAME
setZero \- set the expression value to zero
.SH SYNOPSIS
\fIsetZero(\fBexpr0\fR as <generic> Matrix, 
\fBq\fR as double = 0.1);\fR
.SH DESCRIPTION
.PP
set the expression value to zero 
 
 if the expression value is less than a given threshold
.PP
.SH OPTIONS
.PP
\fBexpr0\fB \fR\- -. 
.PP
.PP
\fBq\fB \fR\- -. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
