.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "sort_mad" "sort_mad"
.SH NAME
sort_mad \- take top n expression feature by rank expression MAD value desc
.SH SYNOPSIS
\fIsort_mad(\fBx\fR as <generic> Matrix, 
\fBtop\fR as integer = 10000);\fR
.SH DESCRIPTION
.PP
take top n expression feature by rank expression MAD value desc
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBtop\fB \fR\- take top N gene features. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
