.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "split.cmeans_clusters" "split.cmeans_clusters"
.SH NAME
split.cmeans_clusters \- split the cmeans cluster output
.SH SYNOPSIS
\fIsplit.cmeans_clusters(\fBcmeans\fR as <generic> EntityClusterModel[]);\fR
.SH DESCRIPTION
.PP
split the cmeans cluster output
 
 split the cmeans cluster output into multiple parts based on the cluster tags
.PP
.SH OPTIONS
.PP
\fBcmeans\fB \fR\- the cmeans cluster result. 
.PP
.SH VALUE
.PP
A list object that contains the input cluster result 
 data is split into multiple cluster parts.
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
