.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "time_pattern_label" "time_pattern_label"
.SH NAME
time_pattern_label \- Make time pattern label for a specific cmeans expression pattern
.SH SYNOPSIS
\fItime_pattern_label(\fBexpr_z\fR as <generic> dataframe);\fR
.SH DESCRIPTION
.PP
Make time pattern label for a specific cmeans expression pattern
.PP
.SH OPTIONS
.PP
\fBexpr_z\fB \fR\- A specifc cmeans epxression pattern, row is gene and column is the expression data in a time point, should be sort in asc order.. 
.PP
.SH VALUE
.PP
A character of the pattern label name
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
