.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-1月 "totalSumNorm" "totalSumNorm"
.SH NAME
totalSumNorm \- normalize data by sample column
.SH SYNOPSIS
\fItotalSumNorm(\fBmatrix\fR as <generic> Matrix, 
\fBscale\fR as double = 10000);\fR
.SH DESCRIPTION
.PP
normalize data by sample column
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- a gene expression matrix. 
.PP
.PP
\fBscale\fB \fR\- 
 the total sum scale of each sample column after the normalization, by 
 default is 10000.
. 
.PP
.SH VALUE
.PP
a new expression matrix object which is normalized by the total sum value 
 of each sample column: each expression value in a sample column is divided 
 by the sum of the sample column and then multiplied by the given scale 
 value.
.PP
.SH DETAILS
.PP
apply for the metabolomics data usually
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
