.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-Jan "totalSumNorm" "totalSumNorm"
.SH NAME
totalSumNorm \- normalize data by sample column
.SH SYNOPSIS
\fItotalSumNorm(\fBmatrix\fR as <generic> Matrix, 
\fBscale\fR as double = 10000);\fR
.SH DESCRIPTION
.PP
normalize data by sample column
.PP
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- a gene expression matrix. 
.PP
.SH DETAILS
.PP
apply for the metabolomics data usually
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
