.\" man page create by R# package system.
.TH GENEEXPRESSION 1 2000-01-01 "write.expr_matrix" "write.expr_matrix"
.SH NAME
write.expr_matrix \- write the gene expression data matrix file
.SH SYNOPSIS
\fIwrite.expr_matrix(\fBexpr\fR as <generic> Matrix, 
\fBfile\fR as string, 
\fBid\fR as string = "geneID", 
\fBbinary\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
write the gene expression data matrix file
.PP
.SH OPTIONS
.PP
\fBexpr\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBid\fB \fR\- -. 
.PP
.PP
\fBbinary\fB \fR\- 
 write matrix data in binary data format? default value 
 is False means write matrix as csv matrix file.
. 
.PP
.SH SEE ALSO
geneExpression
.SH FILES
.PP
phenotype_kit.dll
.PP
