.\" man page create by R# package system.
.TH UNIPROT 4 2000-1月 "get_description" "get_description"
.SH NAME
get_description \- get the protein full name and function description text from the given
.SH SYNOPSIS
\fIget_description(\fBprot\fR as <generic> entry);\fR
.SH DESCRIPTION
.PP
get the protein full name and function description text from the given 
 uniprot protein entry object
.PP
.SH OPTIONS
.PP
\fBprot\fB \fR\- 
 the uniprot protein [entry](cref:T:SMRUCC.genomics.Assembly.Uniprot.XML.entry) object for extract its 
 description text.
. 
.PP
.SH VALUE
.PP
a character vector of the protein description text: the protein full 
 name and the function description text.
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
