.\" man page create by R# package system.
.TH UNIPROT 4 2000-1月 "parseHeader" "parseHeader"
.SH NAME
parseHeader \- Parse the uniprot fasta header text
.SH SYNOPSIS
\fIparseHeader(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Parse the uniprot fasta header text
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a character vector of the uniprot fasta headers title text, or a 
 collection of the [FastaSeq](cref:T:SMRUCC.genomics.SequenceModel.FASTA.FastaSeq) sequence object.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the [FastaHeader](cref:T:SMRUCC.genomics.Assembly.Uniprot.FastaHeader) uniprot fasta headers object.
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
