.\" man page create by R# package system.
.TH UNIPROT 4 2000-1月 "protein.seqs" "protein.seqs"
.SH NAME
protein.seqs \- 
.SH SYNOPSIS
\fIprotein.seqs(\fBuniprot\fR as any, 
\fBextractAll\fR as boolean = FALSE, 
\fBtitle\fR as string = "<uniprot_id> <fullname>", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
