.\" man page create by R# package system.
.TH KEGG_API 1 2000-Jan "listing" "listing"
.SH NAME
listing \- 
.SH SYNOPSIS
\fIlisting(\fBdatabase\fR as string, 
\fBoption\fR as string = \fB<NULL>\fR, 
\fBcache\fR as <generic> IHttpGet = \fB<NULL>\fR);\fR
.SH SEE ALSO
kegg_api
.SH FILES
.PP
kegg_kit.dll
.PP
