.\" man page create by R# package system.
.TH FASTQ 1 2000-1月 "random_sampling" "random_sampling"
.SH NAME
random_sampling \- make reads data random sampling
.SH SYNOPSIS
\fIrandom_sampling(\fBfq\fR as <generic> FastQFile, 
\fBn\fR as integer, 
\fBlazy\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
make reads data random sampling
.PP
.SH OPTIONS
.PP
\fBfq\fB \fR\- -. 
.PP
.PP
\fBn\fB \fR\- -. 
.PP
.SH SEE ALSO
FastQ
.SH FILES
.PP
rnaseq.dll
.PP
