.\" man page create by R# package system.
.TH FASTQ 1 2000-1月 "write.fastq" "write.fastq"
.SH NAME
write.fastq \- 
.SH SYNOPSIS
\fIwrite.fastq(\fBreads\fR as any, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBreads\fB \fR\- a collection of the fastq reads data. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
FastQ
.SH FILES
.PP
rnaseq.dll
.PP
