<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SMRUCC.genomics.Analysis.SpikingLoop</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SMRUCC.genomics.Analysis.SpikingLoop</AssemblyName>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Gene regulatory network based on the Spiking Neuron Network Model</Title>
    <PackageTags>snn;deeplearning;tensorflow;gcmodeller;regulatory</PackageTags>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Data_science\MachineLearning\SNN\SNN.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Data_science\MachineLearning\TensorFlow\TensorFlow.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Data_science\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\workbench\modules\ExperimentDesigner\designer-netcore5.vbproj" />
    <ProjectReference Include="..\..\analysis\HTS_matrix\HTS_matrix-netcore5.vbproj" />
    <ProjectReference Include="..\..\core\Bio.Assembly\biocore-netcore5.vbproj" />
    <ProjectReference Include="..\..\core\Bio.InteractionModel\InteractionModel.NET5.vbproj" />
    <ProjectReference Include="..\BNLearn\BNLearn.vbproj" />
  </ItemGroup>

</Project>
