.\" man page create by R# package system.
.TH ETC 1 2020-10-29 "contributors" "contributors"
.SH NAME
contributors \- \fBR#\fR Project Contributors
.SH SYNOPSIS
\fIcontributors([\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
\fBR#\fR Project Contributors
 
 The R# Who-is-who, describing who made significant contributions to the development of R#.
.PP
.SH SEE ALSO
etc
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
