.\" man page create by R# package system.
.TH ETC 1 2020-12-15 "license" "license"
.SH NAME
license \- The R# License Terms
.SH SYNOPSIS
\fIlicense([\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
The R# License Terms
 
 The license terms under which R# is distributed.
.PP
.SH SEE ALSO
etc
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
