.\" man page create by R# package system.
.TH ETC 1 2020-12-15 "sessionInfo" "sessionInfo"
.SH NAME
sessionInfo \- Collect Information About the Current R Session
.SH SYNOPSIS
\fIsessionInfo([\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Collect Information About the Current R Session
 
 Print version information about R, the OS and attached or 
 loaded packages.
.PP
.SH VALUE
.PP
sessionInfo() returns an object of class "sessionInfo" which has 
 print and toLatex methods. This is a list with components
.PP
.SH SEE ALSO
etc
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
