.\" man page create by R# package system.
.TH UNIPROT 4 2000-01-01 "cache.ptf" "cache.ptf"
.SH NAME
cache.ptf \- 
.SH SYNOPSIS
\fIcache.ptf(\fBuniprot\fR as <generic> Object, 
\fBfile\fR as <generic> Object, 
\fBcacheTaxonomy\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC/GCModeller 2020
