.\" man page create by R# package system.
.TH UNIPROT 4 2000-01-01 "open.uniprot" "open.uniprot"
.SH NAME
open.uniprot \- open a uniprot database file
.SH SYNOPSIS
\fIopen.uniprot(\fBfile\fR as string, 
\fBisUniParc\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
open a uniprot database file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -
.PP
.PP
\fBisUniParc\fB \fR\- -
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC/GCModeller 2020
