.\" man page create by R# package system.
.TH UNIPROT 1 2000-01-01 "open.uniprot" "open.uniprot"
.SH NAME
open.uniprot \- 
.SH SYNOPSIS
\fIopen.uniprot(\fBfile\fR as string, 
\fBisUniParc\fR as boolean = FALSE);\fR
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC/GCModeller 2020
