.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-1月 "assign.COG" "assign.COG"
.SH NAME
assign.COG \- assign the COG functional category for each query gene by keeping the
.SH SYNOPSIS
\fIassign.COG(\fBalignment\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
assign the COG functional category for each query gene by keeping the 
 best identity COG hit
.PP
.SH OPTIONS
.PP
\fBalignment\fB \fR\- 
 a vector of the COG hits([MyvaCOG](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.Pipeline.COG.MyvaCOG)) alignment result data 
 for make the COG category assignment.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the [MyvaCOG](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.Pipeline.COG.MyvaCOG) COG assignment result, one best 
 hit element for each query gene;
 
 this function returns a R# error message object if the input alignment 
 data is not a collection of the [MyvaCOG](cref:T:SMRUCC.genomics.Interops.NCBI.Extensions.Pipeline.COG.MyvaCOG) object.
.PP
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
