.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-1月 "geneNames" "geneNames"
.SH NAME
geneNames \- try parse gene names from the product description strings
.SH SYNOPSIS
\fIgeneNames(\fBdescriptions\fR as any);\fR
.SH DESCRIPTION
.PP
try parse gene names from the product description strings
.PP
.SH OPTIONS
.PP
\fBdescriptions\fB \fR\- 
 the gene functional product description strings.
. 
.PP
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
