#Region "Microsoft.VisualBasic::4c9d006feafc57b5c1735f88f7aba42b, src\Flute\HttpMessage\Protocol\HttpHeader.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 41
    '    Code Lines: 35 (85.37%)
    ' Comment Lines: 0 (0.00%)
    '    - Xml Docs: 0.00%
    ' 
    '   Blank Lines: 6 (14.63%)
    '     File Size: 1.73 KB


    '     Class RequestHeaders
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    '     Class ResponseHeaders
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Namespace Core.Message.HttpHeader

    Public NotInheritable Class RequestHeaders

        Private Sub New()
        End Sub

        Public Const Accept As String = "Accept"
        Public Const AcceptEncoding As String = "Accept-Encoding"
        Public Const AcceptLanguage As String = "Accept-Language"
        Public Const CacheControl As String = "Cache-Control"
        Public Const Connection As String = "Connection"
        Public Const Cookie As String = "Cookie"
        Public Const Host As String = "Host"
        Public Const Pragma As String = "Pragma"
        Public Const UpgradeInsecureRequests As String = "Upgrade-Insecure-Requests"
        Public Const ContentType As String = "Content-Type"
        Public Const UserAgent As String = "User-Agent"

        ''' <summary>
        ''' the protocol name that the client want to switch to, ``websocket`` for
        ''' the RFC6455 websocket handshake request.
        ''' </summary>
        Public Const Upgrade As String = "Upgrade"
        ''' <summary>
        ''' a base64 encoded random 16 bytes nonce which is generated by the websocket client
        ''' </summary>
        Public Const SecWebSocketKey As String = "Sec-WebSocket-Key"
        ''' <summary>
        ''' the websocket sub-protocol candidates list which is offered by the client,
        ''' multiple values are separated by comma.
        ''' </summary>
        Public Const SecWebSocketProtocol As String = "Sec-WebSocket-Protocol"
        ''' <summary>
        ''' the websocket protocol version, only version ``13`` is supported.
        ''' </summary>
        Public Const SecWebSocketVersion As String = "Sec-WebSocket-Version"
        ''' <summary>
        ''' the websocket protocol extensions which is offered by the client
        ''' </summary>
        Public Const SecWebSocketExtensions As String = "Sec-WebSocket-Extensions"
    End Class

    Public NotInheritable Class ResponseHeaders

        Private Sub New()
        End Sub

        Public Const CacheControl As String = "Cache-Control"
        Public Const Connection As String = "Connection"
        Public Const ContentEncoding As String = "Content-Encoding"
        Public Const ContentLength As String = "Content-Length"
        Public Const ContentType As String = "Content-Type"
        Public Const [Date] As String = "Date"
        Public Const Expires As String = "Expires"
        Public Const KeepAlive As String = "Keep-Alive"
        Public Const Pragma As String = "Pragma"
        Public Const Server As String = "Server"
        Public Const SetCookie As String = "Set-Cookie"
        Public Const Vary As String = "Vary"
        Public Const XFrameOptions As String = "X-Frame-Options"
        Public Const XPoweredBy As String = "X-Powered-By"

        ''' <summary>
        ''' echo back the protocol name that the server switch to: ``websocket``
        ''' </summary>
        Public Const Upgrade As String = "Upgrade"
        ''' <summary>
        ''' ``base64(sha1(Sec-WebSocket-Key + <see cref="WebSocketGuid"/>))``
        ''' </summary>
        Public Const SecWebSocketAccept As String = "Sec-WebSocket-Accept"
        ''' <summary>
        ''' the negotiated websocket sub-protocol, only a single value is allowed here.
        ''' </summary>
        Public Const SecWebSocketProtocol As String = "Sec-WebSocket-Protocol"
        ''' <summary>
        ''' the websocket protocol version which is supported by this server
        ''' </summary>
        Public Const SecWebSocketVersion As String = "Sec-WebSocket-Version"
    End Class

    ''' <summary>
    ''' the websocket protocol constant value which is defined in RFC6455
    ''' </summary>
    Public NotInheritable Class WebSocketProtocol

        Private Sub New()
        End Sub

        ''' <summary>
        ''' the globally unique identifier(GUID) that defined in RFC6455 section-1.3,
        ''' this magic string is concat to the ``Sec-WebSocket-Key`` value for
        ''' generates the ``Sec-WebSocket-Accept`` handshake response value.
        ''' </summary>
        Public Const WebSocketGuid As String = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

        ''' <summary>
        ''' the only websocket protocol version that supported by this server
        ''' </summary>
        Public Const SupportedVersion As String = "13"

        ''' <summary>
        ''' the protocol token value of the ``Upgrade`` http header
        ''' </summary>
        Public Const UpgradeToken As String = "websocket"

        ''' <summary>
        ''' the token value of the ``Connection`` http header
        ''' </summary>
        Public Const ConnectionToken As String = "Upgrade"
    End Class
End Namespace
