#Region "Microsoft.VisualBasic::c6e46896b0c5795e0d328c208241e916, src\Flute\HttpMessage\Protocol\HttpHeader.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 112
    '    Code Lines: 52 (46.43%)
    ' Comment Lines: 46 (41.07%)
    '    - Xml Docs: 100.00%
    ' 
    '   Blank Lines: 14 (12.50%)
    '     File Size: 4.80 KB


    '     Class RequestHeaders
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    '     Class ResponseHeaders
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    '     Class WebSocketProtocol
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    ' 
    ' /********************************************************************************/

#End Region

Namespace Core.Message.HttpHeader

    ''' <summary>
    ''' the well known http request header names, used as constants so callers
    ''' do not have to hard-code the (case-sensitive) header strings.
    ''' </summary>
    Public NotInheritable Class RequestHeaders

        Private Sub New()
        End Sub

        ''' <summary>the media types the client is able to understand.</summary>
        Public Const Accept As String = "Accept"
        ''' <summary>the content encodings the client can decode.</summary>
        Public Const AcceptEncoding As String = "Accept-Encoding"
        ''' <summary>the preferred natural languages for the response.</summary>
        Public Const AcceptLanguage As String = "Accept-Language"
        ''' <summary>directives that control caching behaviour.</summary>
        Public Const CacheControl As String = "Cache-Control"
        ''' <summary>the connection options, e.g. keep-alive or close.</summary>
        Public Const Connection As String = "Connection"
        ''' <summary>the cookies previously sent by the server in Set-Cookie.</summary>
        Public Const Cookie As String = "Cookie"
        ''' <summary>the domain name of the server (and optional port).</summary>
        Public Const Host As String = "Host"
        ''' <summary>implementation specific directives that may affect caching.</summary>
        Public Const Pragma As String = "Pragma"
        ''' <summary>indicates the client prefers an upgrade to a secure transport.</summary>
        Public Const UpgradeInsecureRequests As String = "Upgrade-Insecure-Requests"
        ''' <summary>the media type of the request body.</summary>
        Public Const ContentType As String = "Content-Type"
        ''' <summary>the user agent string identifying the client software.</summary>
        Public Const UserAgent As String = "User-Agent"

        ''' <summary>
        ''' the protocol name that the client want to switch to, ``websocket`` for
        ''' the RFC6455 websocket handshake request.
        ''' </summary>
        Public Const Upgrade As String = "Upgrade"
        ''' <summary>
        ''' a base64 encoded random 16 bytes nonce which is generated by the websocket client
        ''' </summary>
        Public Const SecWebSocketKey As String = "Sec-WebSocket-Key"
        ''' <summary>
        ''' the websocket sub-protocol candidates list which is offered by the client,
        ''' multiple values are separated by comma.
        ''' </summary>
        Public Const SecWebSocketProtocol As String = "Sec-WebSocket-Protocol"
        ''' <summary>
        ''' the websocket protocol version, only version ``13`` is supported.
        ''' </summary>
        Public Const SecWebSocketVersion As String = "Sec-WebSocket-Version"
        ''' <summary>
        ''' the websocket protocol extensions which is offered by the client
        ''' </summary>
        Public Const SecWebSocketExtensions As String = "Sec-WebSocket-Extensions"
    End Class

    ''' <summary>
    ''' the well known http response header names, used as constants so callers
    ''' do not have to hard-code the (case-sensitive) header strings.
    ''' </summary>
    Public NotInheritable Class ResponseHeaders

        Private Sub New()
        End Sub

        ''' <summary>directives that control caching behaviour.</summary>
        Public Const CacheControl As String = "Cache-Control"
        ''' <summary>the connection options, e.g. keep-alive or close.</summary>
        Public Const Connection As String = "Connection"
        ''' <summary>the content encodings applied to the response body.</summary>
        Public Const ContentEncoding As String = "Content-Encoding"
        ''' <summary>the byte length of the response body.</summary>
        Public Const ContentLength As String = "Content-Length"
        ''' <summary>the media type of the response body.</summary>
        Public Const ContentType As String = "Content-Type"
        ''' <summary>the date and time the message was sent.</summary>
        Public Const [Date] As String = "Date"
        ''' <summary>the date/time after which the response is considered stale.</summary>
        Public Const Expires As String = "Expires"
        ''' <summary>parameters for keeping the connection alive.</summary>
        Public Const KeepAlive As String = "Keep-Alive"
        ''' <summary>implementation specific directives that may affect caching.</summary>
        Public Const Pragma As String = "Pragma"
        ''' <summary>the name of the server application handling the request.</summary>
        Public Const Server As String = "Server"
        ''' <summary>instructs the client to store one or more cookies.</summary>
        Public Const SetCookie As String = "Set-Cookie"
        ''' <summary>specifies which request headers influence the cached response.</summary>
        Public Const Vary As String = "Vary"
        ''' <summary>indicates whether the browser should be allowed to render in a frame.</summary>
        Public Const XFrameOptions As String = "X-Frame-Options"
        ''' <summary>a custom header advertising the framework that powers the server.</summary>
        Public Const XPoweredBy As String = "X-Powered-By"

        ''' <summary>
        ''' echo back the protocol name that the server switch to: ``websocket``
        ''' </summary>
        Public Const Upgrade As String = "Upgrade"
        ''' <summary>
        ''' ``base64(sha1(Sec-WebSocket-Key + WebSocketGuid))``
        ''' </summary>
        Public Const SecWebSocketAccept As String = "Sec-WebSocket-Accept"
        ''' <summary>
        ''' the negotiated websocket sub-protocol, only a single value is allowed here.
        ''' </summary>
        Public Const SecWebSocketProtocol As String = "Sec-WebSocket-Protocol"
        ''' <summary>
        ''' the websocket protocol version which is supported by this server
        ''' </summary>
        Public Const SecWebSocketVersion As String = "Sec-WebSocket-Version"
    End Class

    ''' <summary>
    ''' the websocket protocol constant value which is defined in RFC6455
    ''' </summary>
    Public NotInheritable Class WebSocketProtocol

        Private Sub New()
        End Sub

        ''' <summary>
        ''' the globally unique identifier(GUID) that defined in RFC6455 section-1.3,
        ''' this magic string is concat to the ``Sec-WebSocket-Key`` value for
        ''' generates the ``Sec-WebSocket-Accept`` handshake response value.
        ''' </summary>
        Public Const WebSocketGuid As String = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

        ''' <summary>
        ''' the only websocket protocol version that supported by this server
        ''' </summary>
        Public Const SupportedVersion As String = "13"

        ''' <summary>
        ''' the protocol token value of the ``Upgrade`` http header
        ''' </summary>
        Public Const UpgradeToken As String = "websocket"

        ''' <summary>
        ''' the token value of the ``Connection`` http header
        ''' </summary>
        Public Const ConnectionToken As String = "Upgrade"
    End Class
End Namespace
