.\" man page create by R# package system.
.TH BIOSEQ.BLAST 1 2000-1月 "align.needleman_wunsch" "align.needleman_wunsch"
.SH NAME
align.needleman_wunsch \- 
.SH SYNOPSIS
\fIalign.needleman_wunsch(\fBquery\fR as <generic> FastaSeq, 
\fBref\fR as <generic> FastaSeq);\fR
.SH SEE ALSO
bioseq.blast
.SH FILES
.PP
seqtoolkit.dll
.PP
