.\" man page create by R# package system.
.TH BIOSEQ.BLAST 1 2000-1月 "HSP" "HSP"
.SH NAME
HSP \- 
.SH SYNOPSIS
\fIHSP(\fBalign\fR as <generic> SmithWaterman, 
\fBcutoff\fR as double, 
\fBminW\fR as integer, 
\fBas_dataframe\fR as boolean = TRUE);\fR
.SH SEE ALSO
bioseq.blast
.SH FILES
.PP
seqtoolkit.dll
.PP
