.\" man page create by R# package system.
.TH UNIPROT 4 2000-01-01 "cache.ptf" "cache.ptf"
.SH NAME
cache.ptf \- 
.SH SYNOPSIS
\fIcache.ptf(\fBuniprot\fR as any, 
\fBfile\fR as any, 
\fBcacheTaxonomy\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
