.\" man page create by R# package system.
.TH UNIPROT 4 2000-1月 "get_subcellularlocation" "get_subcellularlocation"
.SH NAME
get_subcellularlocation \- get subcellular location of current protein
.SH SYNOPSIS
\fIget_subcellularlocation(\fBprot\fR as <generic> entry);\fR
.SH DESCRIPTION
.PP
get subcellular location of current protein
.PP
.SH OPTIONS
.PP
\fBprot\fB \fR\- -. 
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
