.\" man page create by R# package system.
.TH UNIPROT 4 2000-01-01 "id_unify" "id_unify"
.SH NAME
id_unify \- id unify mapping
.SH SYNOPSIS
\fIid_unify(\fBuniprot\fR as any, 
\fBid\fR as any, 
\fBtarget\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
id unify mapping
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- a uniprot dataabse pipeline stream. 
.PP
.PP
\fBid\fB \fR\- -. 
.PP
.PP
\fBtarget\fB \fR\- the database name for map to. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
