.\" man page create by R# package system.
.TH UNIPROT 4 2000-1月 "open.uniprot" "open.uniprot"
.SH NAME
open.uniprot \- open a uniprot database file
.SH SYNOPSIS
\fIopen.uniprot(\fBfiles\fR as any, 
\fBisUniParc\fR as boolean = FALSE, 
\fBignoreError\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open a uniprot database file
.PP
.SH OPTIONS
.PP
\fBfiles\fB \fR\- -. 
.PP
.PP
\fBisUniParc\fB \fR\- -. 
.PP
.SH VALUE
.PP
this function returns a pipeline stream of the uniprot protein entries.
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
