.\" man page create by R# package system.
.TH UNIPROT 4 2000-Jan "proteinTable" "proteinTable"
.SH NAME
proteinTable \- export protein annotation data as data frame.
.SH SYNOPSIS
\fIproteinTable(\fBuniprot\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
export protein annotation data as data frame.
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
