.\" man page create by R# package system.
.TH UNIPROT 4 2000-1月 "read.proteinTable" "read.proteinTable"
.SH NAME
read.proteinTable \- read uniprot protein export output tsv file
.SH SYNOPSIS
\fIread.proteinTable(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read uniprot protein export output tsv file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
uniprot
.SH FILES
.PP
seqtoolkit.dll
.PP
