.\" man page create by R# package system.
.TH HMP_PORTAL 1 2000-01-01 "fetch" "fetch"
.SH NAME
fetch \- run file downloads
.SH SYNOPSIS
\fIfetch(\fBfiles\fR as any, 
\fBoutputdir\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run file downloads
.PP
.SH OPTIONS
.PP
\fBfiles\fB \fR\- -. 
.PP
.PP
\fBoutputdir\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
HMP_portal
.SH FILES
.PP
metagenomics_kit.dll
.PP
