.\" man page create by R# package system.
.TH MATH 2 2020-11-09 "hist" "hist"
.SH NAME
hist \- Do fixed width cut bins
.SH SYNOPSIS
\fIhist(\fBdata\fR as <generic> Object, 
\fBstep\fR as double = 1);\fR
.SH DESCRIPTION
.PP
Do fixed width cut bins
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- A numeric vector data sequence
.PP
.PP
\fBstep\fB \fR\- The width of the bin box.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
R.math.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
