.\" man page create by R# package system.
.TH MATH 2 2020-07-26 "lm" "lm"
.SH NAME
lm \- do linear modelling
.SH SYNOPSIS
\fIlm(\fBformula\fR as <generic> Object, 
\fBdata\fR as <generic> Object, 
\fBweights\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do linear modelling
.PP
.SH OPTIONS
.PP
\fBformula\fB \fR\- -
.PP
.PP
\fBdata\fB \fR\- A dataframe for provides the data source for doing the linear modelling.
.PP
.PP
\fBweights\fB \fR\- A numeric vector for provides weight value for the points in the linear modelling processing.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
math
.SH FILES
.PP
R.math.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
