.\" man page create by R# package system.
.TH SIMULATOR 2 2000-1月 "apply.module_profile" "apply.module_profile"
.SH NAME
apply.module_profile \- 
.SH SYNOPSIS
\fIapply.module_profile(\fBengine\fR as <generic> Engine, 
\fBprofile\fR as list[double], 
\fBsystem\fR as <integer> ModuleSystemLevels = [Transcriptome]);\fR
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
