.\" man page create by R# package system.
.TH SIMULATOR 2 2000-01-01 "dynamics.default" "dynamics.default"
.SH NAME
dynamics.default \- Create the default cell dynamics parameters
.SH SYNOPSIS
\fIdynamics.default();\fR
.SH DESCRIPTION
.PP
Create the default cell dynamics parameters
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
