.\" man page create by R# package system.
.TH SIMULATOR 2 2000-01-01 "engine.load" "engine.load"
.SH NAME
engine.load \- create a new virtual cell engine
.SH SYNOPSIS
\fIengine.load(\fBvcell\fR as <generic> CellularModule, 
\fBinits\fR as <generic> Definition = \fB<NULL>\fR, 
\fBiterations\fR as integer = 100, 
\fBtime_resolutions\fR as integer = 10000, 
\fBdeletions\fR as string = \fB<NULL>\fR, 
\fBdynamics\fR as <generic> FluxBaseline = \fB<NULL>\fR, 
\fBshowProgress\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
create a new virtual cell engine
.PP
.SH OPTIONS
.PP
\fBinits\fB \fR\- -. 
.PP
.PP
\fBvcell\fB \fR\- -. 
.PP
.PP
\fBiterations%\fB \fR\- -. 
.PP
.PP
\fBtime_resolutions%\fB \fR\- -. 
.PP
.PP
\fBdeletions$\fB \fR\- -. 
.PP
.PP
\fBdynamics\fB \fR\- -. 
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
