.\" man page create by R# package system.
.TH SIMULATOR 2 2000-1月 "kegg_mass" "kegg_mass"
.SH NAME
kegg_mass \- Create a new status profile data object with unify mass contents.
.SH SYNOPSIS
\fIkegg_mass(\fBvcell\fR as <generic> VirtualCell, 
\fBmass\fR as double = 5000);\fR
.SH DESCRIPTION
.PP
Create a new status profile data object with unify mass contents.
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.PP
\fBmass\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function works for the data model which is based on the kegg database model
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
