.\" man page create by R# package system.
.TH SIMULATOR 2 2000-1月 "set_status" "set_status"
.SH NAME
set_status \- set the omics data from this function
.SH SYNOPSIS
\fIset_status(\fBdef\fR as <generic> Definition, 
...);\fR
.SH DESCRIPTION
.PP
set the omics data from this function
.PP
.SH OPTIONS
.PP
\fBdef\fB \fR\- -. 
.PP
.PP
\fBenv_set\fB \fR\- -. 
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
