.\" man page create by R# package system.
.TH SIMULATOR 2 2000-Jan "vcell.model" "vcell.model"
.SH NAME
vcell.model \- create a generic vcell object model from a loaded vcell xml file model
.SH SYNOPSIS
\fIvcell.model(\fBvcell\fR as <generic> VirtualCell);\fR
.SH DESCRIPTION
.PP
create a generic vcell object model from a loaded vcell xml file model
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- the file model data of the GCModeller vcell. 
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
