.\" man page create by R# package system.
.TH SIMULATOR 2 2000-Jan "vcell.mass.kegg" "vcell.mass.kegg"
.SH NAME
vcell.mass.kegg \- Create a new status profile data object with unify mass contents.
.SH SYNOPSIS
\fIvcell.mass.kegg(\fBvcell\fR as <generic> VirtualCell, 
\fBmass\fR as double = 5000);\fR
.SH DESCRIPTION
.PP
Create a new status profile data object with unify mass contents.
.PP
.SH OPTIONS
.PP
\fBvcell\fB \fR\- -. 
.PP
.PP
\fBmass#\fB \fR\- -. 
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
