.\" man page create by R# package system.
.TH SIMULATOR 2 2000-1月 "vcell.snapshot" "vcell.snapshot"
.SH NAME
vcell.snapshot \- make a snapshot of the mass and flux data
.SH SYNOPSIS
\fIvcell.snapshot(\fBengine\fR as <generic> Engine, 
\fBmassIndex\fR as <generic> OmicsTuple`1, 
\fBfluxIndex\fR as <generic> OmicsTuple`1, 
\fBsave\fR as string);\fR
.SH DESCRIPTION
.PP
make a snapshot of the mass and flux data
.PP
.SH OPTIONS
.PP
\fBengine\fB \fR\- -. 
.PP
.PP
\fBmassIndex\fB \fR\- -. 
.PP
.PP
\fBfluxIndex\fB \fR\- -. 
.PP
.PP
\fBsave$\fB \fR\- -. 
.PP
.SH SEE ALSO
simulator
.SH FILES
.PP
vcellkit.dll
.PP
