.\" man page create by R# package system.
.TH TAXONOMY_KIT 4 2000-1月 "LCA" "LCA"
.SH NAME
LCA \- 
.SH SYNOPSIS
\fILCA(\fBtree\fR as <generic> NcbiTaxonomyTree, 
\fBncbi_taxid\fR as any, 
\fBmin_supports\fR as double = 0.5, 
\fBas_list\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
taxonomy_kit
.SH FILES
.PP
metagenomics_kit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
