<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SMRUCC.genomics.Model.Metabolic.RouterAdapter</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>SMRUCC.genomics.Model.Metabolic.RouterAdapter</AssemblyName>
    <AssemblyTitle>Metabolic Pathway Router</AssemblyTitle>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Metabolic Pathway Router</Title>
    <Configurations>Debug;Release;Rsharp_app_release</Configurations>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>False</Optimize>
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Optimize>False</Optimize>
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Rsharp_app_release|AnyCPU'">
    <DefineTrace>True</DefineTrace>
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Rsharp_app_release|x64'">
    <DefineTrace>True</DefineTrace>
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <RemoveIntegerChecks>True</RemoveIntegerChecks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Data\DataFrame\dataframework-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Data_science\Graph\graph-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Data_science\Mathematica\Math\Math\Math.NET5.vbproj" />
    <ProjectReference Include="..\..\..\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\analysis\MetabolicRouter\RetroPath.vbproj" />
    <ProjectReference Include="..\..\core\Bio.Assembly\biocore-netcore5.vbproj" />
    <ProjectReference Include="..\BioCyc\BioCyc.vbproj" />
  </ItemGroup>

</Project>
