.\" man page create by R# package system.
.TH ENV 1 2020-12-15 "export" "export"
.SH NAME
export \- get a .NET type model from a given VB.NET type full name
.SH SYNOPSIS
\fIexport(\fBfullName\fR as string);\fR
.SH DESCRIPTION
.PP
get a .NET type model from a given VB.NET type full name
.PP
.SH OPTIONS
.PP
\fBfullName\fB \fR\- -
.PP
.SH SEE ALSO
env
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
