.\" man page create by R# package system.
.TH ENV 1 2020-10-29 "ls" "ls"
.SH NAME
ls \- List Objects
.SH SYNOPSIS
\fIls(\fBname\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
List Objects
 
 \fBls\fR and \fBobjects\fR return a vector of character strings giving 
 the names of the objects in the specified environment. When invoked 
 with no argument at the top level prompt, ls shows what data sets 
 and functions a user has defined. When invoked with no argument inside 
 a function, ls returns the names of the function's local variables: 
 this is useful in conjunction with \fBbrowser\fR.
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- The package name, which environment to use in 
 listing the available objects. Defaults to the current environment. 
 Although called name for back compatibility, in fact this argument 
 can specify the environment in any form.
.PP
.PP
\fBenv\fB \fR\- 
 an alternative argument to name for specifying the environment. 
 Mostly there for back compatibility.

.PP
.SH SEE ALSO
env
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
