.\" man page create by R# package system.
.TH ENV 1 2020-12-15 "output_device" "output_device"
.SH NAME
output_device \- Get the standard output device name string
.SH SYNOPSIS
\fIoutput_device([\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get the standard output device name string
.PP
.SH OPTIONS
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
env
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
