.\" man page create by R# package system.
.TH ENV 1 2020-11-02 "traceback" "traceback"
.SH NAME
traceback \- Get and Print Call Stacks
.SH SYNOPSIS
\fItraceback([\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get and Print Call Stacks
 
 By default traceback() prints the call stack of the last uncaught 
 error, i.e., the sequence of calls that lead to the error. This 
 is useful when an error occurs with an unidentifiable error message. 
 It can also be used to print the current stack or arbitrary lists 
 of deparsed calls.
.PP
.SH OPTIONS
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
env
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
