#Region "Microsoft.VisualBasic::51bbca4c74312ebd32c55200def5d47e, GCModeller\models\ncbi-BioSystems\My Project\Resources.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 1221
    '    Code Lines: 287
    ' Comment Lines: 875
    '   Blank Lines: 59
    '     File Size: 58.69 KB


    '     Module Resources
    ' 
    '         Properties: Culture, EMBL_General_mod, EMBL_General_mod1, GenBank_General_mod, GenBank_General_mod1
    '                     NCBI_Biblio_mod, NCBI_Biblio_mod1, NCBI_BioSource_mod, NCBI_BioSource_mod1, NCBI_Entity_mod
    '                     NCBI_Gene_mod, NCBI_Gene_mod1, NCBI_General_mod, NCBI_General_mod1, NCBI_Medline_mod
    '                     NCBI_Medline_mod1, NCBI_Organism_mod, NCBI_Organism_mod1, NCBI_Protein_mod, NCBI_Protein_mod1
    '                     NCBI_Pub_mod, NCBI_Pub_mod1, NCBI_RNA_mod, NCBI_RNA_mod1, NCBI_Rsite_mod
    '                     NCBI_Rsite_mod1, NCBI_Seqalign_mod, NCBI_Seqalign_mod1, NCBI_Seqfeat_mod, NCBI_Seqfeat_mod1
    '                     NCBI_Seqloc_mod, NCBI_Seqloc_mod1, NCBI_Seqres_mod, NCBI_Seqres_mod1, NCBI_SeqTable_mod
    '                     NCBI_SeqTable_mod1, NCBI_Sequence_mod, NCBI_Sequence_mod1, NCBI_Systems, NCBI_Systems_mod
    '                     NCBI_Systems_mod1, NCBI_Systems1, NCBI_TxInit_mod, NCBI_TxInit_mod1, PDB_General_mod
    '                     PDB_General_mod1, PIR_General_mod, PIR_General_mod1, PRF_General_mod, PRF_General_mod1
    '                     ResourceManager, SP_General_mod, SP_General_mod1
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Model.NCBI.BioSystems.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.1
        '''     ::DATATOOL:: on 01/18/2007 23:07:18
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;EMBL-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 6.0 $
        '''*********************************************************************
        '''
        ''' 1990 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EMBL_General_mod() As String
            Get
                Return ResourceManager.GetString("EMBL_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EMBL_General_mod1() As String
            Get
                Return ResourceManager.GetString("EMBL_General_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;GenBank-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''*********************************************************************
        '''
        '''  GenBank specific  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GenBank_General_mod() As String
            Get
                Return ResourceManager.GetString("GenBank_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GenBank_General_mod1() As String
            Get
                Return ResourceManager.GetString("GenBank_General_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;biblio.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Biblio&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 6.2 $
        '''****************************************************************
        '''
        '''  NCBI Biblio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Biblio_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Biblio_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;biblio.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefault [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Biblio_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Biblio_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 08/18/2008 23:06:55
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-BioSource&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  NCBI BioSource
        '''  b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_BioSource_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_BioSource_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 08/18/2008 23:06:56
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_BioSource_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_BioSource_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ======================== --&gt;
        '''&lt;!-- NCBI DTD                 --&gt;
        '''&lt;!-- NCBI ASN.1 mapped to XML --&gt;
        '''&lt;!-- ======================== --&gt;
        ''' 
        '''&lt;!-- Entities used to give specificity to #PCDATA --&gt;
        '''&lt;!ENTITY % INTEGER &apos;#PCDATA&apos;&gt;
        '''&lt;!ENTITY % ENUM &apos;EMPTY&apos;&gt;
        '''&lt;!ENTITY % BOOLEAN &apos;EMPTY&apos;&gt;
        '''&lt;!ENTITY % NULL &apos;EMPTY&apos;&gt;
        '''&lt;!ENTITY % REAL &apos;#PCDATA&apos;&gt;
        '''&lt;!ENTITY % OCTETS &apos;#PCDATA&apos;&gt;
        '''&lt;!-- ============================================ --&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property NCBI_Entity_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Entity_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 10/09/2008 23:08:21
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Gene&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  NCBI Genes
        '''  by James O [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Gene_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Gene_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 10/09/2008 23:08:21
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Gene_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Gene_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;general.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 99135 $
        '''**********************************************************************
        '''
        '''  N [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_General_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;general.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_General_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_General_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;medline.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Medline&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 6.0 $
        '''**********************************************************************
        '''
        '''  MED [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Medline_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Medline_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;medline.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Medline_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Medline_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Organism&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  NCBI Organism
        '''  by  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Organism_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Organism_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Organism_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Organism_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Protein&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  NCBI Protein
        '''  by Ja [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Protein_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Protein_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Protein_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Protein_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;pub.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Pub&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 6.0 $
        '''********************************************************************
        '''
        '''  Publication c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Pub_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Pub_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;pub.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefault=&quot;u [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Pub_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Pub_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 09/15/2008 23:08:25
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-RNA&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  NCBI RNAs
        '''  by James Ost [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_RNA_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_RNA_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 09/15/2008 23:08:26
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_RNA_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_RNA_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Rsite&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  NCBI Restriction Sites [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Rsite_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Rsite_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Rsite_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Rsite_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqalign.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.2
        '''     ::DATATOOL:: on 06/02/2009 23:05:02
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Seqalign&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 161965 $
        '''**********************************************************************
        '''
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqalign_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqalign_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqalign.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.2
        '''     ::DATATOOL:: on 06/02/2009 23:05:02
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqalign_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqalign_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.2
        '''     ::DATATOOL:: on 04/27/2009 23:05:20
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Seqfeat&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 158548 $
        '''**********************************************************************
        '''
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqfeat_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqfeat_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.2
        '''     ::DATATOOL:: on 04/27/2009 23:05:21
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqfeat_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqfeat_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqloc.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 09/15/2008 23:08:25
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Seqloc&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 140157 $
        '''**********************************************************************
        '''
        '''  NC [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqloc_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqloc_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqloc.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 09/15/2008 23:08:26
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefault [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqloc_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqloc_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqres.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Seqres&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 6.0 $
        '''**********************************************************************
        '''
        '''  NCBI  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqres_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqres_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqres.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefault [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Seqres_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Seqres_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqtable.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-SeqTable&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 115572 $
        '''  
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''                            PUBLIC DOMAIN NOTICE
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_SeqTable_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_SeqTable_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqtable.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 12/14/2007 23:37:20
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_SeqTable_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_SeqTable_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seq.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 08/26/2008 23:06:32
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Sequence&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''$Revision: 138450 $
        '''**********************************************************************
        '''
        '''  NCB [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Sequence_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Sequence_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seq.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 08/26/2008 23:06:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefault=&quot;u [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Sequence_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Sequence_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;systems.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.3
        '''     ::DATATOOL:: on 09/17/2009 11:55:41
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- NCBI_Systems.dtd
        '''  This file is built from a series of basic modules.
        '''  The actual ELEMENT and ENTITY declarations are in the modules.
        '''  This file is used to put them together.
        '''--&gt;
        '''
        '''&lt;!ENTITY % NCBI_Entity_module PUBLIC &quot;-//NCBI//NCBI Entity Module//EN&quot; &quot;NCBI [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Systems() As String
            Get
                Return ResourceManager.GetString("NCBI_Systems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;systems.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.3
        '''     ::DATATOOL:: on 09/17/2009 11:55:41
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-Systems&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        '''
        '''  Biomolecular Syste [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Systems_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_Systems_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;systems.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.3
        '''     ::DATATOOL:: on 09/17/2009 11:55:37
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Systems_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_Systems_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;systems.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.3
        '''     ::DATATOOL:: on 09/17/2009 11:55:37
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_Systems1() As String
            Get
                Return ResourceManager.GetString("NCBI_Systems1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;NCBI-TxInit&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''********************************************************************
        '''
        '''  Transcription Initiatio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_TxInit_mod() As String
            Get
                Return ResourceManager.GetString("NCBI_TxInit_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqfeat.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefaul [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NCBI_TxInit_mod1() As String
            Get
                Return ResourceManager.GetString("NCBI_TxInit_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;PDB-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''*********************************************************************
        '''
        '''  PDB specific data
        '''  T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PDB_General_mod() As String
            Get
                Return ResourceManager.GetString("PDB_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PDB_General_mod1() As String
            Get
                Return ResourceManager.GetString("PDB_General_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;PIR-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''*********************************************************************
        '''
        '''  PIR specific data
        '''  T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PIR_General_mod() As String
            Get
                Return ResourceManager.GetString("PIR_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PIR_General_mod1() As String
            Get
                Return ResourceManager.GetString("PIR_General_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.1
        '''     ::DATATOOL:: on 01/18/2007 23:07:18
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;PRF-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''**********************************************************************
        ''' PRF specific definitio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PRF_General_mod() As String
            Get
                Return ResourceManager.GetString("PRF_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PRF_General_mod1() As String
            Get
                Return ResourceManager.GetString("PRF_General_mod1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.9.0
        '''     ::DATATOOL:: on 04/10/2008 16:04:22
        '''     ============================================ --&gt;
        '''
        '''&lt;!-- ============================================ --&gt;
        '''&lt;!-- This section is mapped from module &quot;SP-General&quot;
        '''================================================= --&gt;
        '''
        '''&lt;!--
        '''*********************************************************************
        '''
        '''  SWISSPROT specific dat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SP_General_mod() As String
            Get
                Return ResourceManager.GetString("SP_General_mod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        '''&lt;!-- ============================================
        '''     ::DATATOOL:: Generated from &quot;seqblock.asn&quot;
        '''     ::DATATOOL:: by application DATATOOL version 1.8.7
        '''     ::DATATOOL:: on 10/04/2007 23:07:33
        '''     ============================================ --&gt;
        '''
        '''&lt;xs:schema
        '''  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        '''  xmlns:ncbi=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  xmlns=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  targetNamespace=&quot;http://www.ncbi.nlm.nih.gov&quot;
        '''  elementFormDefault=&quot;qualified&quot;
        '''  attributeFormDefau [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SP_General_mod1() As String
            Get
                Return ResourceManager.GetString("SP_General_mod1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
