.\" man page create by R# package system.
.TH PROPERTY_EDIT 1 2000-1月 "write.species" "write.species"
.SH NAME
write.species \- write organism species information into the model
.SH SYNOPSIS
\fIwrite.species(\fBmodel\fR as <generic> ModelBaseType, 
\fBvalue\fR as string);\fR
.SH DESCRIPTION
.PP
write organism species information into the model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBvalue\fB \fR\- -. 
.PP
.SH SEE ALSO
property_edit
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
