.\" man page create by R# package system.
.TH PROPERTY_EDIT 1 2000-1月 "write.comment" "write.comment"
.SH NAME
write.comment \- 
.SH SYNOPSIS
\fIwrite.comment(\fBmodel\fR as <generic> ModelBaseType, 
\fBvalue\fR as string);\fR
.SH SEE ALSO
property_edit
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
