.\" man page create by R# package system.
.TH IGRAPH.BUILDER 1 2020-12-15 "correlation.graph" "correlation.graph"
.SH NAME
correlation.graph \- 
.SH SYNOPSIS
\fIcorrelation.graph(\fBx\fR as <generic> DistanceMatrix, 
\fBthreshold\fR as double = 0.65, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph.builder
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
