.\" man page create by R# package system.
.TH PROFILES 1 2000-1月 "category_labels" "category_labels"
.SH NAME
category_labels \- 
.SH SYNOPSIS
\fIcategory_labels(\fBcategory\fR as <generic> ClassProfiles, 
\fBidSet\fR as string, 
\fBlevel\fR as integer = 1, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
