.\" man page create by R# package system.
.TH PROFILES 1 2000-1月 "GO.enrichment.profile" "GO.enrichment.profile"
.SH NAME
GO.enrichment.profile \- 
.SH SYNOPSIS
\fIGO.enrichment.profile(\fBenrichments\fR as any, 
\fBgoDb\fR as <generic> GO_OBO, 
\fBtop\fR as integer = 10, 
\fBpvalue_cut\fR as double = 1, 
\fBsort\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
profiles
.SH FILES
.PP
gseakit.dll
.PP
