.\" man page create by R# package system.
.TH CLUSTERING 2 2020-12-15 "btree" "btree"
.SH NAME
btree \- do btree clustering
.SH SYNOPSIS
\fIbtree(\fBd\fR as <generic> Object, 
\fBequals\fR as double = 0.9, 
\fBgt\fR as double = 0.7, 
\fBhclust\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do btree clustering
.PP
.SH OPTIONS
.PP
\fBd\fB \fR\- -
.PP
.PP
\fBequals\fB \fR\- -
.PP
.PP
\fBgt\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
