.\" man page create by R# package system.
.TH CLUSTERING 2 2020-10-29 "cmeans" "cmeans"
.SH NAME
cmeans \- the cmeans algorithm module
.SH SYNOPSIS
\fIcmeans(\fBdataset\fR as <generic> Object, 
\fBcenters\fR as integer = 3, 
\fBfuzzification\fR as double = 2, 
\fBthreshold\fR as double = 0.001, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
the cmeans algorithm module
 
 **Fuzzy clustering** (also referred to as **soft clustering**) is a form of clustering in which 
 each data point can belong to more than one cluster.

 Clustering Or cluster analysis involves assigning data points to clusters (also called buckets, 
 bins, Or classes), Or homogeneous classes, such that items in the same class Or cluster are as 
 similar as possible, while items belonging to different classes are as dissimilar as possible. 
 Clusters are identified via similarity measures. These similarity measures include distance, 
 connectivity, And intensity. Different similarity measures may be chosen based on the data Or 
 the application.
 
 > https://en.wikipedia.org/wiki/Fuzzy_clustering
.PP
.SH OPTIONS
.PP
\fBdataset\fB \fR\- -
.PP
.PP
\fBcenters\fB \fR\- -
.PP
.PP
\fBfuzzification\fB \fR\- -
.PP
.PP
\fBthreshold\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2020
