.\" man page create by R# package system.
.TH GRAPHICS 1 2020-10-29 "bitmap" "bitmap"
.SH NAME
bitmap \- save image data as bitmap image file
.SH SYNOPSIS
\fIbitmap(\fBimage\fR as <generic> Object, 
\fBfile\fR as <generic> Object = \fB<NULL>\fR, 
\fBformat\fR as <integer> ImageFormats = [Png], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save image data as bitmap image file
.PP
.SH OPTIONS
.PP
\fBimage\fB \fR\- -
.PP
.PP
\fBfile\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
