.\" man page create by R# package system.
.TH GRAPHICS 1 2020-10-29 "plot" "plot"
.SH NAME
plot \- Generic function for plotting of R objects.
.SH SYNOPSIS
\fIplot(\fBobject\fR as <generic> Object, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Generic function for plotting of R objects.
.PP
.SH OPTIONS
.PP
\fB[object]\fB \fR\- -
.PP
.PP
\fBargs\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
