.\" man page create by R# package system.
.TH QC 1 2000-Jan "trim_reads_headers" "trim_reads_headers"
.SH NAME
trim_reads_headers \- trim the primers or adapters sequence at read header region
.SH SYNOPSIS
\fItrim_reads_headers(\fBreads\fR as any, 
\fBheaders\fR as any, 
\fBexact_match\fR as boolean = TRUE, 
\fBcutoff\fR as double = 0.85, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
trim the primers or adapters sequence at read header region
.PP
.SH OPTIONS
.PP
\fBreads\fB \fR\- -. 
.PP
.PP
\fBheaders\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
QC
.SH FILES
.PP
rnaseq.dll
.PP
