.\" man page create by R# package system.
.TH MIXOMICS 1 2000-1月 "nearZeroVar" "nearZeroVar"
.SH NAME
nearZeroVar \- 
.SH SYNOPSIS
\fInearZeroVar(\fBexpr_mat\fR as <generic> Matrix, 
\fBfreqCut\fR as double = 19, 
\fBuniqueCut\fR as double = 10);\fR
.SH SEE ALSO
mixOmics
.SH FILES
.PP
phenotype_kit.dll
.PP
