.\" man page create by R# package system.
.TH MOFA 1 2000-1月 "create_mofa" "create_mofa"
.SH NAME
create_mofa \- 
.SH SYNOPSIS
\fIcreate_mofa(..., 
\fBopts\fR as <generic> MOFAOptions = \fB<NULL>\fR, 
\fBenv\fR as <generic> Environment = \fB<NULL>\fR);\fR
.SH SEE ALSO
MOFA
.SH FILES
.PP
phenotype_kit.dll
.PP
