<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>tsar_e2e</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <StartupObject>tsar_e2e.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GCModeller\analysis\RNA-Seq\TSSAR\TSSAR.vbproj" />
  </ItemGroup>

</Project>
