.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "as.seq_graph" "as.seq_graph"
.SH NAME
as.seq_graph \- 
.SH SYNOPSIS
\fIas.seq_graph(\fBfasta\fR as any, 
\fBmol_type\fR as <integer> SeqTypes = [DNA], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
