.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "as.seq_graph" "as.seq_graph"
.SH NAME
as.seq_graph \- 
.SH SYNOPSIS
\fIas.seq_graph(\fBfasta\fR as any, 
\fBmol_type\fR as <integer> SeqTypes = [DNA], 
\fBparallel\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBfasta\fB \fR\- -. 
.PP
.PP
\fBmol_type\fB \fR\- -. 
.PP
.PP
\fBparallel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
the sequence graph embedding vector data is generates from different method 
 based on the **mol_type** data:
 
 + [SeqTypes.DNA](cref:F:SMRUCC.genomics.SequenceModel.SeqTypes.DNA): [Builder.DNAGraph()](cref:M:SMRUCC.genomics.Model.MotifGraph.Builder.DNAGraph(SMRUCC.genomics.SequenceModel.FASTA.FastaSeq))
 + [SeqTypes.Protein](cref:F:SMRUCC.genomics.SequenceModel.SeqTypes.Protein): [Builder.PolypeptideGraph()](cref:M:SMRUCC.genomics.Model.MotifGraph.Builder.PolypeptideGraph(SMRUCC.genomics.SequenceModel.FASTA.FastaSeq))
 + [SeqTypes.RNA](cref:F:SMRUCC.genomics.SequenceModel.SeqTypes.RNA): [Builder.RNAGraph()](cref:M:SMRUCC.genomics.Model.MotifGraph.Builder.RNAGraph(SMRUCC.genomics.SequenceModel.FASTA.FastaSeq))
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
