.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "create.seeds" "create.seeds"
.SH NAME
create.seeds \- 
.SH SYNOPSIS
\fIcreate.seeds(\fBfasta\fR as any, 
\fBsaveto\fR as <generic> ScanFile, 
\fBminw\fR as integer = 8, 
\fBmaxw\fR as integer = 20, 
\fBseedingCutoff\fR as double = 0.95, 
\fBscanMinW\fR as integer = 6, 
\fBscanCutoff\fR as double = 0.8, 
\fBsignificant_sites\fR as integer = 4, 
\fBdebug\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
