.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "find_motifs" "find_motifs"
.SH NAME
find_motifs \- find possible motifs of the given sequence collection
.SH SYNOPSIS
\fIfind_motifs(\fBfasta\fR as any, 
\fBminw\fR as integer = 8, 
\fBmaxw\fR as integer = 20, 
\fBnmotifs\fR as integer = -1, 
\fBnoccurs\fR as integer = 6, 
\fBseedingCutoff\fR as double = 0.99, 
\fBscanMinW\fR as integer = 6, 
\fBscanCutoff\fR as double = 0.8, 
\fBcleanMotif\fR as double = 0.5, 
\fBsignificant_sites\fR as integer = 4, 
\fBseeds\fR as any = \fB<NULL>\fR, 
\fBdebug\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
find possible motifs of the given sequence collection
.PP
.SH OPTIONS
.PP
\fBfasta\fB \fR\- should contains multiple sequence. 
.PP
.PP
\fBminw%\fB \fR\- -. 
.PP
.PP
\fBmaxw%\fB \fR\- -. 
.PP
.PP
\fBnmotifs\fB \fR\- 
 A number for limit the number of motif outputs:
 
 + negative integer/zero: no limits[default]
 + positive value: top motifs with score desc
. 
.PP
.PP
\fBnoccurs%\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
