.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-01-01 "palindrome.mirror" "palindrome.mirror"
.SH NAME
palindrome.mirror \- Search mirror palindrome sites for a given seed sequence
.SH SYNOPSIS
\fIpalindrome.mirror(\fBsequence\fR as string, 
\fBseed\fR as string);\fR
.SH DESCRIPTION
.PP
Search mirror palindrome sites for a given seed sequence
.PP
.SH OPTIONS
.PP
\fBsequence\fB \fR\- -. 
.PP
.PP
\fBseed\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
