.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "plot.seqLogo" "plot.seqLogo"
.SH NAME
plot.seqLogo \- Drawing the sequence logo just simply modelling this motif site
.SH SYNOPSIS
\fIplot.seqLogo(\fBMSA\fR as any, 
\fBtitle\fR as string = "", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Drawing the sequence logo just simply modelling this motif site 
 from the clustal multiple sequence alignment.
.PP
.SH OPTIONS
.PP
\fBMSA\fB \fR\- -. 
.PP
.PP
\fBtitle\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
