.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "read.motifs" "read.motifs"
.SH NAME
read.motifs \- read sequence motif json file.
.SH SYNOPSIS
\fIread.motifs(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read sequence motif json file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH DETAILS
.PP
apply for search by @\fBM:seqtoolkit.patterns.matchSites(System.Object,System.Object,System.Double,System.Double,System.Double,System.Double,System.Boolean,System.String,SMRUCC.Rsharp.Runtime.Environment)\fR
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
