.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "read.scans" "read.scans"
.SH NAME
read.scans \- read the motif match scan result table file
.SH SYNOPSIS
\fIread.scans(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the motif match scan result table file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- should be a file path to a csv table file.. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
