.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "read.meme_xml" "read.meme_xml"
.SH NAME
read.meme_xml \- read the xml motif data model output from the meme program
.SH SYNOPSIS
\fIread.meme_xml(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the xml motif data model output from the meme program
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
