.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "scaffold.orthogonality" "scaffold.orthogonality"
.SH NAME
scaffold.orthogonality \- analyses orthogonality of two DNA-Origami scaffold strands.
.SH SYNOPSIS
\fIscaffold.orthogonality(\fBscaffolds\fR as any, 
\fBsegment_len\fR as integer = 7, 
\fBis_linear\fR as boolean = FALSE, 
\fBrev_compl\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
analyses orthogonality of two DNA-Origami scaffold strands.
 Multiple criteria For orthogonality Of the two sequences can be specified
 to determine the level of orthogonality.
.PP
.SH OPTIONS
.PP
\fBscaffolds\fB \fR\- -. 
.PP
.PP
\fBsegment_len\fB \fR\- segment length. 
.PP
.PP
\fBis_linear\fB \fR\- scaffolds are not circular. 
.PP
.PP
\fBrev_compl\fB \fR\- also count reverse complementary sequences. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
