.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "seeds" "seeds"
.SH NAME
seeds \- Create seeds
.SH SYNOPSIS
\fIseeds(\fBsize\fR as integer, 
\fBbase\fR as string);\fR
.SH DESCRIPTION
.PP
Create seeds
.PP
.SH OPTIONS
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBbase\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
