.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "split_match_source" "split_match_source"
.SH NAME
split_match_source \- split the motif matches result in parts by its gene source
.SH SYNOPSIS
\fIsplit_match_source(\fBmatches\fR as any, 
\fBgff\fR as <generic> GFFTable, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
split the motif matches result in parts by its gene source
.PP
.SH OPTIONS
.PP
\fBmatches\fB \fR\- -. 
.PP
.PP
\fBgff\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
