.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-Jan "toPWM" "toPWM"
.SH NAME
toPWM \- convert the meme document to motif PWM model object
.SH SYNOPSIS
\fItoPWM(\fBmeme\fR as <generic> MEMEXml);\fR
.SH DESCRIPTION
.PP
convert the meme document to motif PWM model object
.PP
.SH OPTIONS
.PP
\fBmeme\fB \fR\- -. 
.PP
.SH VALUE
.PP
a vector of the PWM clr object.
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
