.\" man page create by R# package system.
.TH BIOSEQ.PATTERNS 2 2000-1月 "view.sites" "view.sites"
.SH NAME
view.sites \- 
.SH SYNOPSIS
\fIview.sites(\fBsites\fR as any, 
\fBseq\fR as any, 
\fBdeli\fR as string = ", ", 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBsites\fB \fR\- -. 
.PP
.PP
\fBseq\fB \fR\- -. 
.PP
.PP
\fBdeli\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bioseq.patterns
.SH FILES
.PP
seqtoolkit.dll
.PP
