.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "environment" "environment"
.SH NAME
environment \- 
.SH SYNOPSIS
\fIenvironment(\fBkernel\fR as <generic> Kernel, 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
