.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "kernel" "kernel"
.SH NAME
kernel \- 
.SH SYNOPSIS
\fIkernel(\fBsnapshot\fR as <generic> DataSnapshot, 
\fBmodel\fR as <generic> Model = \fB<NULL>\fR);\fR
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
