.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "run" "run"
.SH NAME
run \- 
.SH SYNOPSIS
\fIrun(\fBkernel\fR as <generic> Kernel, 
\fBticks\fR as integer = 100, 
\fBresolution\fR as double = 0.1);\fR
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
