.\" man page create by R# package system.
.TH S.SYSTEM 1 2000-01-01 "s.system" "s.system"
.SH NAME
s.system \- 
.SH SYNOPSIS
\fIs.system(\fBkernel\fR as <generic> Kernel, 
\fBssystem\fR as <generic> DeclareLambdaFunction[], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
S.system
.SH FILES
.PP
simulators.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
