.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "cai_bias_table" "cai_bias_table"
.SH NAME
cai_bias_table \- Compile the CAI w weight table of one reference gene collection and export
.SH SYNOPSIS
\fIcai_bias_table(\fBgenes\fR as <generic> FastaFile);\fR
.SH DESCRIPTION
.PP
Compile the CAI w weight table of one reference gene collection and export
 the codon usage csv table. (legacy batch compilation entry)
.PP
.SH OPTIONS
.PP
\fBgenes\fB \fR\- the reference gene collection of one species. 
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
