.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "codon.bias_B.gC" "codon.bias_B.gC"
.SH NAME
codon.bias_B.gC \- The \fBB(g|C)\fR codon usage bias difference of one single gene g against the
.SH SYNOPSIS
\fIcodon.bias_B.gC(\fBgene\fR as <generic> FastaSeq, 
\fBreference\fR as <generic> CodonUsageProfile);\fR
.SH DESCRIPTION
.PP
The \fBB(g|C)\fR codon usage bias difference of one single gene g against the
 reference class C.
.PP
.SH OPTIONS
.PP
\fBgene\fB \fR\- the query CDS gene sequence. 
.PP
.PP
\fBreference\fB \fR\- the reference codon usage profile (class C). 
.PP
.SH VALUE
.PP
the B(g|C) value
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
