.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "Read.Csv.Chromsome_Partitioning" "Read.Csv.Chromsome_Partitioning"
.SH NAME
Read.Csv.Chromsome_Partitioning \- Load the chromosome partitioning entries from their csv document.
.SH SYNOPSIS
\fIRead.Csv.Chromsome_Partitioning(\fBpath\fR as string);\fR
.SH DESCRIPTION
.PP
Load the chromosome partitioning entries from their csv document.
.PP
.SH OPTIONS
.PP
\fBpath\fB \fR\- the csv file path. 
.PP
.SH VALUE
.PP
the chromosome partitioning entries
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
