.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "read.csv.genome_partition_data" "read.csv.genome_partition_data"
.SH NAME
read.csv.genome_partition_data \- Load the partitioning data collection from its csv document.
.SH SYNOPSIS
\fIread.csv.genome_partition_data(\fBpath\fR as string);\fR
.SH DESCRIPTION
.PP
Load the partitioning data collection from its csv document.
.PP
.SH OPTIONS
.PP
\fBpath\fB \fR\- the csv file path. 
.PP
.SH VALUE
.PP
the partitioning data collection
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
