.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "read.site_delta" "read.site_delta"
.SH NAME
read.site_delta \- Load one sliding window \fBdelta*\fR profile from its csv document.
.SH SYNOPSIS
\fIread.site_delta(\fBpath\fR as string);\fR
.SH DESCRIPTION
.PP
Load one sliding window \fBdelta*\fR profile from its csv document.
.PP
.SH OPTIONS
.PP
\fBpath\fB \fR\- the csv file path of one [WindowDelta](cref:T:SMRUCC.genomics.Analysis.SequenceTools.DNA_Comparative.WindowDelta) profile. 
.PP
.SH VALUE
.PP
the profile rows ordered by the site position
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
