.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "tau_star.profile" "tau_star.profile"
.SH NAME
tau_star.profile \- The \fBtau*\fR tetranucleotide relative abundance profile of all 256
.SH SYNOPSIS
\fItau_star.profile(\fBnt\fR as <generic> FastaSeq);\fR
.SH DESCRIPTION
.PP
The \fBtau*\fR tetranucleotide relative abundance profile of all 256
 tetranucleotides.
.PP
.SH OPTIONS
.PP
\fBnt\fB \fR\- the genome nucleotide sequence. 
.PP
.SH VALUE
.PP
the \fB{word, tau*}\fR dictionary (only the present words are included)
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
