.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "word.count" "word.count"
.SH NAME
word.count \- Count the absolute occurrences of one oligonucleotide word in the genome
.SH SYNOPSIS
\fIword.count(\fBnt\fR as <generic> FastaSeq, 
\fBword\fR as string);\fR
.SH DESCRIPTION
.PP
Count the absolute occurrences of one oligonucleotide word in the genome
 sequence (e.g. the CTAG rarity report).
.PP
.SH OPTIONS
.PP
\fBnt\fB \fR\- the genome nucleotide sequence. 
.PP
.PP
\fBword\fB \fR\- the oligonucleotide word to be counted. 
.PP
.SH VALUE
.PP
the number of occurrences
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
