.\" man page create by R# package system.
.TH SIGMA_DIFFERENCE 1 2000-1月 "write.csv.genome_partition_data" "write.csv.genome_partition_data"
.SH NAME
write.csv.genome_partition_data \- Save the partitioning data collection as a csv document.
.SH SYNOPSIS
\fIwrite.csv.genome_partition_data(\fBdat\fR as <generic> IEnumerable`1, 
\fBsaveto\fR as string);\fR
.SH DESCRIPTION
.PP
Save the partitioning data collection as a csv document.
.PP
.SH OPTIONS
.PP
\fBdat\fB \fR\- the partitioning data collection. 
.PP
.PP
\fBsaveto\fB \fR\- the csv output file path. 
.PP
.SH VALUE
.PP
true when the csv document has been saved
.PP
.SH SEE ALSO
sigma_difference
.SH FILES
.PP
comparative_toolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
