.\" man page create by R# package system.
.TH GRDEVICES 4 2020-12-15 "alpha" "alpha"
.SH NAME
alpha \- adjust color alpha value
.SH SYNOPSIS
\fIalpha(\fBcolor\fR as <generic> Object, 
\fBalpha\fR as double, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
adjust color alpha value
.PP
.SH OPTIONS
.PP
\fBcolor\fB \fR\- -
.PP
.PP
\fBalpha\fB \fR\- the color alpha value should be in range \fB[0,1]\fR.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
