.\" man page create by R# package system.
.TH GRDEVICES 4 2020-12-15 "colors" "colors"
.SH NAME
colors \- get color set
.SH SYNOPSIS
\fIcolors(\fBterm\fR as <generic> Object, 
\fBn\fR as integer = 256, 
\fBcharacter\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get color set
.PP
.SH OPTIONS
.PP
\fBterm\fB \fR\- the color set name
.PP
.PP
\fBn\fB \fR\- number of colors from the given color set
.PP
.PP
\fBcharacter\fB \fR\- function returns a color object sequence 
 or html color code string vector if this parameter value is set to \fBTRUE\fR

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
