.\" man page create by R# package system.
.TH GRDEVICES 4 2020-07-22 "dev.off" "dev.off"
.SH NAME
dev.off \- returns the number and name of the new active device
.SH SYNOPSIS
\fIdev.off(\fBwhich\fR as integer = -1);\fR
.SH DESCRIPTION
.PP
returns the number and name of the new active device 
 (after the specified device has been shut down).
.PP
.SH OPTIONS
.PP
\fBwhich\fB \fR\- An integer specifying a device number.
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
