.\" man page create by R# package system.
.TH GRDEVICES 4 2020-12-15 "graphics.attrs" "graphics.attrs"
.SH NAME
graphics.attrs \- 
.SH SYNOPSIS
\fIgraphics.attrs(\fBimage\fR as <generic> GraphicsData, 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
grDevices
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
