.\" man page create by R# package system.
.TH GRDEVICES 4 2020-06-09 "line2D" "line2D"
.SH NAME
line2D \- 
.SH SYNOPSIS
\fIline2D(\fBa\fR as <generic> Object, 
\fBb\fR as <generic> Object, 
\fBstroke\fR as <generic> Object = "stroke: black; stroke-width: 5px; stroke-dash: solid;");\fR
.SH SEE ALSO
grDevices
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
