.\" man page create by R# package system.
.TH GRDEVICES 4 2020-11-09 "save.graphics" "save.graphics"
.SH NAME
save.graphics \- save the graphics plot object as image file
.SH SYNOPSIS
\fIsave.graphics(\fBgraphics\fR as <generic> Object, 
\fBfile\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the graphics plot object as image file
.PP
.SH OPTIONS
.PP
\fBgraphics\fB \fR\- a graphics plot object
.PP
.PP
\fBfile\fB \fR\- the file path for save the image file. 
 (if this file path parameter is nothing, then the resulted 
 image object will be flush to the standard output stream 
 of R# environment.)

.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
