.\" man page create by R# package system.
.TH GCMODELLER.PROPERTY 1 2000-1月 "EMail.Add" "EMail.Add"
.SH NAME
EMail.Add \- 
.SH SYNOPSIS
\fIEMail.Add(\fBmodel\fR as <generic> ModelBaseType, 
\fBvalue\fR as string);\fR
.SH SEE ALSO
GCModeller.Property
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
