.\" man page create by R# package system.
.TH GCMODELLER.PROPERTY 1 2000-Jan "Publication.Add" "Publication.Add"
.SH NAME
Publication.Add \- 
.SH SYNOPSIS
\fIPublication.Add(\fBmodel\fR as <generic> ModelBaseType, 
\fBvalue\fR as string);\fR
.SH SEE ALSO
GCModeller.Property
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
