.\" man page create by R# package system.
.TH GCMODELLER.PROPERTY 1 2000-01-01 "Write.Name" "Write.Name"
.SH NAME
Write.Name \- 
.SH SYNOPSIS
\fIWrite.Name(\fBmodel\fR as <generic> ModelBaseType, 
\fBvalue\fR as string);\fR
.SH SEE ALSO
GCModeller.Property
.SH FILES
.PP
vcellkit.dll
.PP
.SH AUTHOR
Written by \fBGCModeller Virtual Cell System\fR
