.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "context_location" "context_location"
.SH NAME
context_location \- 
.SH SYNOPSIS
\fIcontext_location(\fBblastn\fR as any, 
\fBeval_thres\fR as double = 1.7976931348623157E+308, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
