.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-Jan "filter_strand" "filter_strand"
.SH NAME
filter_strand \- filter genes by given strand direction
.SH SYNOPSIS
\fIfilter_strand(\fBgenes\fR as any, 
\fBstrand\fR as any = "+", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
filter genes by given strand direction
.PP
.SH OPTIONS
.PP
\fBgenes\fB \fR\- a collection of the gene model object which is subclass of @\fBT:SMRUCC.genomics.ComponentModel.Annotation.IGeneBrief\fR. 
.PP
.PP
\fBstrand\fB \fR\- the nucleotide sequence strand direction, value could be +, -, forward, reverse.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
