.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-Jan "is.forward" "is.forward"
.SH NAME
is.forward \- assert that does the given nucleotide location is in forward direction?
.SH SYNOPSIS
\fIis.forward(\fBloci\fR as <generic> NucleotideLocation);\fR
.SH DESCRIPTION
.PP
assert that does the given nucleotide location is in forward direction?
.PP
.SH OPTIONS
.PP
\fBloci\fB \fR\- a target nucleotide location. 
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
