.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-Jan "location" "location"
.SH NAME
location \- create a new nucleotide location object
.SH SYNOPSIS
\fIlocation(\fBleft\fR as integer, 
\fBright\fR as integer, 
\fBstrand\fR as any = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
create a new nucleotide location object
.PP
.SH OPTIONS
.PP
\fBleft\fB \fR\- -. 
.PP
.PP
\fBright\fB \fR\- -. 
.PP
.PP
\fBstrand\fB \fR\- -. 
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
