.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "primer_coverage" "primer_coverage"
.SH NAME
primer_coverage \- 
.SH SYNOPSIS
\fIprimer_coverage(\fBtargetHits\fR as <generic> NucleotideLocation[], 
\fBchr\fR as <generic> GenomeContext`1, 
\fBchr_seq\fR as <generic> FastaSeq);\fR
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
