.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-Jan "set_context" "set_context"
.SH NAME
set_context \- 
.SH SYNOPSIS
\fIset_context(\fBsites\fR as any, 
\fBgenomics\fR as <generic> GFFTable, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
