.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-1月 "set_context" "set_context"
.SH NAME
set_context \- set genomics context of the matched motif site
.SH SYNOPSIS
\fIset_context(\fBsites\fR as any, 
\fBgenomics\fR as <generic> GFFTable, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set genomics context of the matched motif site
.PP
.SH OPTIONS
.PP
\fBsites\fB \fR\- a collection of the motif sites. 
.PP
.PP
\fBgenomics\fB \fR\- the genomics feature information as the context for make location assignment.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
