.\" man page create by R# package system.
.TH GENOMICS_CONTEXT 2 2000-Jan "TSS_upstream" "TSS_upstream"
.SH NAME
TSS_upstream \- get TSS upstream site sequence data
.SH SYNOPSIS
\fITSS_upstream(\fBgenome\fR as any, 
\fBgenes\fR as any, 
\fBupstream_len\fR as integer = 150, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get TSS upstream site sequence data
.PP
.SH OPTIONS
.PP
\fBgenome\fB \fR\- -. 
.PP
.PP
\fBgenes\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
genomics_context
.SH FILES
.PP
seqtoolkit.dll
.PP
