.\" man page create by R# package system.
.TH GRAPHICS2D 1 2020-10-29 "draw.circle" "draw.circle"
.SH NAME
draw.circle \- 
.SH SYNOPSIS
\fIdraw.circle(\fBg\fR as <generic> IGraphics, 
\fBcenter\fR as <generic> PointF, 
\fBr\fR as double, 
\fBcolor\fR as <generic> Object = "black", 
\fBborder\fR as <generic> Object = "stroke: lightgray; stroke-width: 2px; stroke-dash: dash;");\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
