.\" man page create by R# package system.
.TH GRAPHICS2D 1 2020-10-29 "line" "line"
.SH NAME
line \- 
.SH SYNOPSIS
\fIline(\fBa\fR as <generic> Object, 
\fBb\fR as <generic> Object, 
\fBstroke\fR as <generic> Object = "stroke: black; stroke-width: 5px; stroke-dash: solid;");\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
