.\" man page create by R# package system.
.TH GRAPHICS2D 1 2020-11-09 "rect" "rect"
.SH NAME
rect \- 
.SH SYNOPSIS
\fIrect(\fBx\fR as double, 
\fBy\fR as double, 
\fBw\fR as double, 
\fBh\fR as double, 
\fBfloat\fR as boolean = TRUE);\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
R.graphics.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
