.\" man page create by R# package system.
.TH APPLYS 1 2020-12-15 "parSapply" "parSapply"
.SH NAME
parSapply \- parallel sapply
.SH SYNOPSIS
\fIparSapply(\fBX\fR as <generic> Object, 
\fBFUN\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parallel sapply
.PP
.SH SEE ALSO
applys
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
