.\" man page create by R# package system.
.TH STRINGS 1 2020-11-09 "asc" "asc"
.SH NAME
asc \- Returns an Integer value representing the character code corresponding to a character.
.SH SYNOPSIS
\fIasc(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Returns an Integer value representing the character code corresponding to a character.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 Required. Any valid Char or String expression. If [String] is a String expression,
 only the first character of the string is used for input. If [String] is Nothing
 or contains no characters, an System.ArgumentException error occurs.

.PP
.PP
\fBenvir\fB \fR\- -
.PP
.SH VALUE
.PP
Returns an Integer value representing the character code corresponding to a character.
.PP
.SH SEE ALSO
strings
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
