.\" man page create by R# package system.
.TH STRINGS 1 2020-10-29 "lcase" "lcase"
.SH NAME
lcase \- Returns a string or character converted to lowercase.
.SH SYNOPSIS
\fIlcase(\fBstrings\fR as string);\fR
.SH DESCRIPTION
.PP
Returns a string or character converted to lowercase.
.PP
.SH OPTIONS
.PP
\fBstrings\fB \fR\- Required. Any valid String or Char expression.
.PP
.SH VALUE
.PP
Returns a string or character converted to lowercase.
.PP
.SH SEE ALSO
strings
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
