.\" man page create by R# package system.
.TH STRINGS 1 2020-11-09 "ucase" "ucase"
.SH NAME
ucase \- Returns a string or character containing the specified string converted to uppercase.
.SH SYNOPSIS
\fIucase(\fBstrings\fR as string);\fR
.SH DESCRIPTION
.PP
Returns a string or character containing the specified string converted to uppercase.
.PP
.SH OPTIONS
.PP
\fBstrings\fB \fR\- Required. Any valid String or Char expression.
.PP
.SH VALUE
.PP
Returns a string or character containing the specified string converted to uppercase.
.PP
.SH SEE ALSO
strings
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
