.\" man page create by R# package system.
.TH FILE 1 2000-1月 "is_a" "is_a"
.SH NAME
is_a \- parse the term is_a relationship
.SH SYNOPSIS
\fIis_a(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parse the term is_a relationship
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
gokit.dll
.PP
