.\" man page create by R# package system.
.TH FILE 1 2000-1月 "read.go_obo" "read.go_obo"
.SH NAME
read.go_obo \- read the GO database file
.SH SYNOPSIS
\fIread.go_obo(\fBgoDb\fR as string);\fR
.SH DESCRIPTION
.PP
read the GO database file
.PP
.SH OPTIONS
.PP
\fBgoDb\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
gokit.dll
.PP
