.\" man page create by R# package system.
.TH METABOLISM 2 2000-01-01 "filter.invalid_keggIds" "filter.invalid_keggIds"
.SH NAME
filter.invalid_keggIds \- Removes invalid kegg compound id
.SH SYNOPSIS
\fIfilter.invalid_keggIds(\fBidentified\fR as string);\fR
.SH DESCRIPTION
.PP
Removes invalid kegg compound id
.PP
.SH OPTIONS
.PP
\fBidentified\fB \fR\- -. 
.PP
.SH SEE ALSO
metabolism
.SH FILES
.PP
kegg_kit.dll
.PP
