.\" man page create by R# package system.
.TH METABOLISM 2 2000-Jan "kegg.reconstruction" "kegg.reconstruction"
.SH NAME
kegg.reconstruction \- do kegg pathway reconstruction by given protein annotation data
.SH SYNOPSIS
\fIkegg.reconstruction(\fBreference\fR as any, 
\fBreactions\fR as any, 
\fBannotations\fR as any, 
\fBmin_cov\fR as double = 0.3, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do kegg pathway reconstruction by given protein annotation data
.PP
.SH OPTIONS
.PP
\fBreference\fB \fR\- 
 the kegg reference maps
. 
.PP
.PP
\fBreactions\fB \fR\- 
 a list of the kegg reaction data models
. 
.PP
.PP
\fBannotations\fB \fR\- -. 
.PP
.PP
\fBmin_cov\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
metabolism
.SH FILES
.PP
kegg_kit.dll
.PP
