.\" man page create by R# package system.
.TH METABOLISM 2 2000-1月 "related.compounds" "related.compounds"
.SH NAME
related.compounds \- Get compounds kegg id which is related to the given KO id list
.SH SYNOPSIS
\fIrelated.compounds(\fBenzymes\fR as string, 
\fBreactions\fR as <generic> ReactionRepository);\fR
.SH DESCRIPTION
.PP
Get compounds kegg id which is related to the given KO id list
.PP
.SH OPTIONS
.PP
\fBenzymes\fB \fR\- KO id list. 
.PP
.PP
\fBreactions\fB \fR\- -. 
.PP
.SH SEE ALSO
metabolism
.SH FILES
.PP
kegg_kit.dll
.PP
