.\" man page create by R# package system.
.TH IGRAPH.DIJKSTRA 1 2020-11-02 "betweenness_centrality" "betweenness_centrality"
.SH NAME
betweenness_centrality \- 
.SH SYNOPSIS
\fIbetweenness_centrality(\fBg\fR as <generic> Object, 
\fBundirect\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph.dijkstra
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
