.\" man page create by R# package system.
.TH IGRAPH.DIJKSTRA 1 2020-07-26 "routine.min_cost" "routine.min_cost"
.SH NAME
routine.min_cost \- 
.SH SYNOPSIS
\fIroutine.min_cost(\fBrouter\fR as <generic> DijkstraRouter, 
\fBfrom\fR as <generic> Object, 
\fBto\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph.dijkstra
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
