.\" man page create by R# package system.
.TH IGRAPH.DIJKSTRA 1 2020-11-09 "router.dijkstra" "router.dijkstra"
.SH NAME
router.dijkstra \- 
.SH SYNOPSIS
\fIrouter.dijkstra(\fBg\fR as <generic> NetworkGraph, 
\fBundirected\fR as boolean = FALSE);\fR
.SH SEE ALSO
igraph.dijkstra
.SH FILES
.PP
R.graph.dll
.PP
.SH COPYRIGHT
Copyright © SMRUCC 2019
