.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "category_profiles.plot" "category_profiles.plot"
.SH NAME
category_profiles.plot \- Do plot of the given catalog profiles data
.SH SYNOPSIS
\fIcategory_profiles.plot(\fBprofiles\fR as <generic> CatalogProfiles, 
\fBtitle\fR as string = "KEGG Orthology Profiling", 
\fBaxis_title\fR as string = "Number Of Proteins", 
\fBsize\fR as any = "2300,2000", 
\fBtick\fR as double = -1, 
\fBcolors\fR as any = "#E41A1C,#377EB8,#4DAF4A,#984EA3,#FF7F00,#CECE00", 
\fBdpi\fR as integer = 300, 
\fBformat\fR as string = "F2", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do plot of the given catalog profiles data
.PP
.SH OPTIONS
.PP
\fBprofiles\fB \fR\- -. 
.PP
.PP
\fBtitle\fB \fR\- -. 
.PP
.PP
\fBaxis_title\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- the size of the image. 
.PP
.PP
\fBtick\fB \fR\- axis ticks, default value -1 for auto generated.. 
.PP
.PP
\fBcolors\fB \fR\- the color schema name. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
