.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "erase" "erase"
.SH NAME
erase \- delete a set of the category data from the input profiles
.SH SYNOPSIS
\fIerase(\fBprofiles\fR as <generic> CatalogProfiles, 
\fBcatalogs\fR as string);\fR
.SH DESCRIPTION
.PP
delete a set of the category data from the input profiles
.PP
.SH OPTIONS
.PP
\fBprofiles\fB \fR\- -. 
.PP
.PP
\fBcatalogs\fB \fR\- -. 
.PP
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
