.\" man page create by R# package system.
.TH VISUALPLOT 2 2000-1月 "kegg.enrichment.bubble2" "kegg.enrichment.bubble2"
.SH NAME
kegg.enrichment.bubble2 \- 
.SH SYNOPSIS
\fIkegg.enrichment.bubble2(\fBterms\fR as <generic> EnrichmentResult[], 
\fBsize\fR as any = "12000,10000", 
\fBpadding\fR as any = "padding:300px 2500px 500px 300px;", 
\fBcolorset\fR as string = "YlGnBu:c9", 
\fBtop_n\fR as integer = 9, 
\fBmapLevels\fR as integer = 25, 
\fBlabel_font\fR as string = "font-style: normal; font-size: 42; font-family: Verdana;", 
\fBtick_font\fR as string = "font-style: normal; font-size: 36; font-family: Verdana;", 
\fBaxis_stroke\fR as string = "stroke: black; stroke-width: 10px; stroke-dash: solid;", 
\fBlegend_title_font\fR as string = "font-style: normal; font-size: 50; font-family: Verdana;", 
\fBgrid_stroke\fR as string = "stroke: lightgray; stroke-width: 10px; stroke-dash: dash;", 
\fBdpi\fR as integer = 300, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
visualPlot
.SH FILES
.PP
visualkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
