.\" man page create by R# package system.
.TH UNIPROT 1 2000-1月 "add_ecNumbers" "add_ecNumbers"
.SH NAME
add_ecNumbers \- 
.SH SYNOPSIS
\fIadd_ecNumbers(\fBpack\fR as <generic> ECNumberWriter, 
\fBuniprot\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
UniProt
.SH FILES
.PP
annotationKit.dll
.PP
