.\" man page create by R# package system.
.TH CYTOSCAPE.KEGG 2 2000-Jan "pathway_class" "pathway_class"
.SH NAME
pathway_class \- 
.SH SYNOPSIS
\fIpathway_class(\fBgraph\fR as <generic> NetworkGraph, 
\fBmaps\fR as <generic> Map[], 
\fBtop3\fR as boolean = TRUE, 
\fBexcludesGlobalAndOverviewMaps\fR as boolean = TRUE);\fR
.SH SEE ALSO
cytoscape.kegg
.SH FILES
.PP
cytoscape.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
