'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Visualize.Circos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 # RGB color definition. Colors are refered to within configuration files
        '''# by their name. In order to use a color, you must define it here. 
        '''#
        '''# Common colors (red, green, blue, etc) are already defined in 7
        '''# tones, based on 7 color Brewer palettes, where available.
        '''#
        '''# vvlHUE (very very light HUE, e.g. vvlred)
        '''# vlHUE (very light HUE, e.g. vlred)
        '''# lHUE  (light HUE, e.g. red)
        '''# HUE   (e.g. red)
        '''# dHUE  (dark HUE, e.g. dred)
        '''# vdHUE (very dark HUE, e.g. vdred))
        '''# vvdHUE (very very dark HUE, e.g [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property colors() As String
            Get
                Return ResourceManager.GetString("colors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 # Colors from www.ColorBrewer.org by Cynthia A. Brewer, Geography, Pennsylvania State University.
        '''# See www.colorbrewer.org for details.
        '''#
        '''# Color names are formatted as PALETTE-NUMCOLORS-TYPE-COLORCODE
        '''#
        '''# where PALETTE is the palette name, NUMCOLORS is the number of colors in the palette, TYPE is the palette type (div, seq, qual) and COLORCODE is the color index within the palette (another versison of the color is defined where COLORCODE is the color&apos;s letter, unique to a combination of PALETTE and T [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property colors_brewer() As String
            Get
                Return ResourceManager.GetString("colors_brewer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 reds-3-seq = reds-3-seq-(\d+)
        '''reds-3-seq-rev = rev(reds-3-seq-(\d+))
        '''reds-4-seq = reds-4-seq-(\d+)
        '''reds-4-seq-rev = rev(reds-4-seq-(\d+))
        '''reds-5-seq = reds-5-seq-(\d+)
        '''reds-5-seq-rev = rev(reds-5-seq-(\d+))
        '''reds-6-seq = reds-6-seq-(\d+)
        '''reds-6-seq-rev = rev(reds-6-seq-(\d+))
        '''reds-7-seq = reds-7-seq-(\d+)
        '''reds-7-seq-rev = rev(reds-7-seq-(\d+))
        '''reds-8-seq = reds-8-seq-(\d+)
        '''reds-8-seq-rev = rev(reds-8-seq-(\d+))
        '''reds-9-seq = reds-9-seq-(\d+)
        '''reds-9-seq-rev = rev(reds-9-seq-(\d+))
        '''pastel1-3-qual  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property colors_brewer_lists() As String
            Get
                Return ResourceManager.GetString("colors_brewer_lists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 hue000 = hsv(0,1,1)
        '''hue001 = hsv(1,1,1)
        '''hue002 = hsv(2,1,1)
        '''hue003 = hsv(3,1,1)
        '''hue004 = hsv(4,1,1)
        '''hue005 = hsv(5,1,1)
        '''hue006 = hsv(6,1,1)
        '''hue007 = hsv(7,1,1)
        '''hue008 = hsv(8,1,1)
        '''hue009 = hsv(9,1,1)
        '''hue010 = hsv(10,1,1)
        '''hue011 = hsv(11,1,1)
        '''hue012 = hsv(12,1,1)
        '''hue013 = hsv(13,1,1)
        '''hue014 = hsv(14,1,1)
        '''hue015 = hsv(15,1,1)
        '''hue016 = hsv(16,1,1)
        '''hue017 = hsv(17,1,1)
        '''hue018 = hsv(18,1,1)
        '''hue019 = hsv(19,1,1)
        '''hue020 = hsv(20,1,1)
        '''hue021 = hsv(21,1,1)
        '''hue022 = hsv(22,1,1)
        '''hue023 = hsv(23, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property colors_hsv() As String
            Get
                Return ResourceManager.GetString("colors_hsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 # Karyotype band colors for ideograms
        '''
        '''gpos100 = 0,0,0
        '''gpos    = 0,0,0
        '''gpos75  = 130,130,130
        '''gpos66  = 160,160,160
        '''gpos50  = 200,200,200
        '''gpos33  = 210,210,210
        '''gpos25  = 200,200,200
        '''gvar    = 220,220,220
        '''gneg    = 255,255,255
        '''acen    = 217,47,39
        '''stalk   = 100,127,164
        '''
        '''# Default UCSC color scheme for chromosome colors. 
        '''
        '''chr1  = 153,102,0
        '''chr2  = 102,102,0
        '''chr3  = 153,153,30
        '''chr4  = 204,0,0
        '''chr5  = 255,0,0
        '''chr6  = 255,0,204
        '''chr7  = 255,204,204
        '''chr8  = 255,153,0
        '''chr9  = 255,204,0
        '''chr10 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property colors_ucsc() As String
            Get
                Return ResourceManager.GetString("colors_ucsc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 alice_blue = 240,248,255
        '''aliceblue = 240,248,255
        '''antique_white = 250,235,215
        '''antiquewhite = 250,235,215
        '''antiquewhite1 = 255,239,219
        '''antiquewhite2 = 238,223,204
        '''antiquewhite3 = 205,192,176
        '''antiquewhite4 = 139,131,120
        '''aquamarine = 127,255,212
        '''aquamarine1 = 127,255,212
        '''aquamarine2 = 118,238,198
        '''aquamarine3 = 102,205,170
        '''aquamarine4 = 69,139,116
        '''azure = 240,255,255
        '''azure1 = 240,255,255
        '''azure2 = 224,238,238
        '''azure3 = 193,205,205
        '''azure4 = 131,139,139
        '''beige = 245,245,220
        '''bisque = 255,228,196
        '''bis [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property colors_unix() As String
            Get
                Return ResourceManager.GetString("colors_unix", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
