.\" man page create by R# package system.
.TH MICROBIOME 1 2000-01-01 "compounds.origin.profile" "compounds.origin.profile"
.SH NAME
compounds.origin.profile \- 
.SH SYNOPSIS
\fIcompounds.origin.profile(\fBtaxonomy\fR as <generic> NcbiTaxonomyTree, 
\fBorganism\fR as string);\fR
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
