.\" man page create by R# package system.
.TH MICROBIOME 1 2000-01-01 "compounds.origin" "compounds.origin"
.SH NAME
compounds.origin \- create compound origin profile dataset
.SH SYNOPSIS
\fIcompounds.origin(\fBannotations\fR as list, 
\fBtree\fR as <generic> NcbiTaxonomyTree, 
\fBrank\fR as <integer> TaxonomyRanks = [Family], 
\fBranges\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create compound origin profile dataset
.PP
.SH OPTIONS
.PP
\fBannotations\fB \fR\- a list of multiple organism protein functional annotation dataset.. 
.PP
.PP
\fBtree\fB \fR\- the ncbi taxonomy tree. 
.PP
.PP
\fBrank\fB \fR\- minimal rank for takes the most abondance taxonomy from the raw dataset.. 
.PP
.PP
\fBranges\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
