.\" man page create by R# package system.
.TH MICROBIOME 1 2000-01-01 "diff.entropy" "diff.entropy"
.SH NAME
diff.entropy \- evaluate the similarity of two taxonomy data vector
.SH SYNOPSIS
\fIdiff.entropy(\fBv1\fR as list, 
\fBv2\fR as list, 
\fBrank\fR as <integer> TaxonomyRanks = [Genus], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
evaluate the similarity of two taxonomy data vector
.PP
.SH OPTIONS
.PP
\fBv1\fB \fR\- 
 the names of the list should be the BIOM taxonomy string, 
 content value of the list is the relative abundance data.
. 
.PP
.PP
\fBv2\fB \fR\- 
 the names of the list should be the BIOM taxonomy string, 
 content value of the list is the relative abundance data.
. 
.PP
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
