.\" man page create by R# package system.
.TH MICROBIOME 1 2000-1月 "make_vfdb_model" "make_vfdb_model"
.SH NAME
make_vfdb_model \- make vfdb gsea background model for run enrichment analysis
.SH SYNOPSIS
\fImake_vfdb_model(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
make vfdb gsea background model for run enrichment analysis
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
