.\" man page create by R# package system.
.TH MICROBIOME 1 2000-1月 "predict_metagenomes" "predict_metagenomes"
.SH NAME
predict_metagenomes \- creates the final metagenome functional predictions. It
.SH SYNOPSIS
\fIpredict_metagenomes(\fBPICRUSt\fR as <generic> MetaBinaryReader, 
\fBtable\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
creates the final metagenome functional predictions. It 
 multiplies each normalized OTU abundance by each predicted 
 functional trait abundance to produce a table of functions 
 (rows) by samples (columns).
.PP
.SH OPTIONS
.PP
\fBtable\fB \fR\- 
 should be a merged OTU dataframe object, that should be in format like:
 
 1. the colnames should be the sample name, and the column field value is the relative abundance value of each otu in each sample
 2. the rows in this dataframe should be the otu expression value across samples
 
 the GCModeller internal @\fBT:SMRUCC.genomics.Analysis.HTS.DataFrame.Matrix\fR is also avaiable 
 for this parameter.
. 
.PP
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
