.\" man page create by R# package system.
.TH MICROBIOME 1 2000-Jan "read_PICRUSt" "read_PICRUSt"
.SH NAME
read_PICRUSt \- read the compiled PICRUSt binary database file
.SH SYNOPSIS
\fIread_PICRUSt(\fBfile\fR as <generic> Stream);\fR
.SH DESCRIPTION
.PP
read the compiled PICRUSt binary database file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
