.\" man page create by R# package system.
.TH MICROBIOME 1 2000-01-01 "save.PICRUSt_matrix" "save.PICRUSt_matrix"
.SH NAME
save.PICRUSt_matrix \- 
.SH SYNOPSIS
\fIsave.PICRUSt_matrix(\fBggtax\fR as <generic> otu_taxonomy[], 
\fBko_13_5_precalculated\fR as <generic> Stream, 
\fBsave\fR as <generic> Stream);\fR
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
