.\" man page create by R# package system.
.TH MICROBIOME 1 2000-Jan "taxonomy.rank_table" "taxonomy.rank_table"
.SH NAME
taxonomy.rank_table \- Generate a serials of the otu table in different rank level
.SH SYNOPSIS
\fItaxonomy.rank_table(\fBotus\fR as any, 
\fBas_matrix\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Generate a serials of the otu table in different rank level
.PP
.SH OPTIONS
.PP
\fBotus\fB \fR\- 
 the otu table data
. 
.PP
.SH VALUE
.PP
a tuple list of the @\fBT:SMRUCC.genomics.Analysis.Metagenome.RankLevelView\fR in different taxonomy
 rank levels.
.PP
.SH SEE ALSO
microbiome
.SH FILES
.PP
metagenomics_kit.dll
.PP
