.\" man page create by R# package system.
.TH BRITE 1 2000-1月 "brite.as.table" "brite.as.table"
.SH NAME
brite.as.table \- Convert the kegg brite htext tree to plant table
.SH SYNOPSIS
\fIbrite.as.table(\fBhtext\fR as any, 
\fBentryId_pattern\fR as string = "[a-z]+\d+", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Convert the kegg brite htext tree to plant table
.PP
.SH OPTIONS
.PP
\fBhtext\fB \fR\- a htex object. 
.PP
.PP
\fBentryId_pattern\fB \fR\- -. 
.PP
.SH SEE ALSO
brite
.SH FILES
.PP
kegg_kit.dll
.PP
