.\" man page create by R# package system.
.TH BRITE 1 2000-Jan "briteMaps" "briteMaps"
.SH NAME
briteMaps \- 
.SH SYNOPSIS
\fIbriteMaps(\fBhtext\fR as <generic> htext, 
\fBgeneId\fR as string, 
\fBlevel\fR as string = "class");\fR
.SH OPTIONS
.PP
\fBhtext\fB \fR\- -. 
.PP
.PP
\fBgeneId\fB \fR\- -. 
.PP
.PP
\fBlevel\fB \fR\- 
 class|category|subcategory
. 
.PP
.SH SEE ALSO
brite
.SH FILES
.PP
kegg_kit.dll
.PP
