.\" man page create by R# package system.
.TH BRITE 1 2000-1月 "brite.parseJSON" "brite.parseJSON"
.SH NAME
brite.parseJSON \- Do parse of the kegg brite json file.
.SH SYNOPSIS
\fIbrite.parseJSON(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do parse of the kegg brite json file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- the htext json file path. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
brite
.SH FILES
.PP
kegg_kit.dll
.PP
