.\" man page create by R# package system.
.TH BRITE 1 2000-01-01 "KO.geneNames" "KO.geneNames"
.SH NAME
KO.geneNames \- Parse gene names for each KO number from the default internal htext resource.
.SH SYNOPSIS
\fIKO.geneNames();\fR
.SH DESCRIPTION
.PP
Parse gene names for each KO number from the default internal htext resource.
.PP
.SH SEE ALSO
brite
.SH FILES
.PP
kegg_kit.dll
.PP
