.\" man page create by R# package system.
.TH BRITE 1 2000-1月 "parse" "parse"
.SH NAME
parse \- Do parse of the kegg brite text file.
.SH SYNOPSIS
\fIparse(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do parse of the kegg brite text file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 The file text content, brite id or its file path, example as:
 
 1. \fBbr08901\fR could be used at here as the kegg pathway map 
    brite id, which is parsed from the internal resource data
 2. this parameter value could also be a text file its file path 
    of the kegg brite database file.  
 
. 
.PP
.SH SEE ALSO
brite
.SH FILES
.PP
kegg_kit.dll
.PP
