.\" man page create by R# package system.
.TH BRITE 1 2000-01-01 "parse" "parse"
.SH NAME
parse \- Do parse of the kegg brite text file.
.SH SYNOPSIS
\fIparse(\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do parse of the kegg brite text file.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 The file text content, brite id or its file path
. 
.PP
.SH SEE ALSO
brite
.SH FILES
.PP
kegg_kit.dll
.PP
