.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-Jan "assign_ko" "assign_ko"
.SH NAME
assign_ko \- do KO number assign based on the bbh alignment result.
.SH SYNOPSIS
\fIassign_ko(\fBforward\fR as <generic> pipeline, 
\fBreverse\fR as <generic> pipeline, 
\fBthreshold\fR as double = 0.95, 
\fBscore_cutoff\fR as double = 60, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do KO number assign based on the bbh alignment result.
.PP
.SH OPTIONS
.PP
\fBforward\fB \fR\- -. 
.PP
.PP
\fBreverse\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
