.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-1月 "rank_term" "rank_term"
.SH NAME
rank_term \- 
.SH SYNOPSIS
\fIrank_term(\fBid\fR as any, 
\fBterm\fR as any, 
\fBscore\fR as any, 
\fBsource\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
