.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-01-01 "read.id_maps" "read.id_maps"
.SH NAME
read.id_maps \- 
.SH SYNOPSIS
\fIread.id_maps(\fBfile\fR as string, 
\fBskip2ndMaps\fR as boolean = FALSE);\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBskip2ndMaps\fB \fR\- 
 set this parameter value to \fBtrue\fR for fixed for build the \fBkegg2go\fR mapping model.
. 
.PP
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
