.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-01-01 "synonym" "synonym"
.SH NAME
synonym \- 
.SH SYNOPSIS
\fIsynonym(\fBidlist\fR as string, 
\fBidmap\fR as <generic> SecondaryIDSolver, 
\fBexcludeNull\fR as boolean = FALSE);\fR
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
