.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-Jan "term_table" "term_table"
.SH NAME
term_table \- 
.SH SYNOPSIS
\fIterm_table(\fBannotations\fR as list, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
