.\" man page create by R# package system.
.TH ANNOTATION.TERMS 2 2000-Jan "write.id_maps" "write.id_maps"
.SH NAME
write.id_maps \- 
.SH SYNOPSIS
\fIwrite.id_maps(\fBmaps\fR as <generic> SecondaryIDSolver, 
\fBfile\fR as string);\fR
.SH SEE ALSO
annotation.terms
.SH FILES
.PP
seqtoolkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
