.\" man page create by R# package system.
.TH STRINGR 1 2020-12-15 "base64_decode" "base64_decode"
.SH NAME
base64_decode \- decode base64 string as text or the raw bytes buffer object.
.SH SYNOPSIS
\fIbase64_decode(\fBbase64\fR as string, 
\fBasText_encoding\fR as <generic> Object = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
decode base64 string as text or the raw bytes buffer object.
.PP
.SH OPTIONS
.PP
\fBbase64\fB \fR\- a string in base64 encode pattern
.PP
.PP
\fBasText_encoding\fB \fR\- if this parameter is not nothing, then the output will be convert as text
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
