.\" man page create by R# package system.
.TH STRINGR 1 2020-11-02 "grep" "grep"
.SH NAME
grep \- 
.SH SYNOPSIS
\fIgrep(\fBtext\fR as <generic> Object, 
\fBgreps\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
