.\" man page create by R# package system.
.TH STRINGR 1 2020-11-09 "gsub" "gsub"
.SH NAME
gsub \- Pattern Matching and Replacement
.SH SYNOPSIS
\fIgsub(\fBsubj\fR as string, 
\fBsearch\fR as string, 
\fBreplaceAs\fR as string = "", 
\fBregexp\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Pattern Matching and Replacement
.PP
.SH OPTIONS
.PP
\fBsubj$\fB \fR\- -
.PP
.PP
\fBsearch$\fB \fR\- -
.PP
.PP
\fBreplaceAs$\fB \fR\- -
.PP
.PP
\fBregexp\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
