.\" man page create by R# package system.
.TH STRINGR 1 2020-12-15 "json" "json"
.SH NAME
json \- Convert most of the R# object or VB.NET object to json string.
.SH SYNOPSIS
\fIjson(\fBx\fR as <generic> Object, 
\fBcompress\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Convert most of the R# object or VB.NET object to json string.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -
.PP
.PP
\fBcompress\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
