.\" man page create by R# package system.
.TH STRINGR 1 2020-12-15 "match" "match"
.SH NAME
match \- Searches the specified input string for the first
.SH SYNOPSIS
\fImatch(\fBregexp\fR as <generic> Regex, 
\fBstrings\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Searches the specified input string for the first 
 occurrence of the regular expression specified in 
 the System.Text.RegularExpressions.Regex 
 constructor.
.PP
.SH OPTIONS
.PP
\fBregexp\fB \fR\- Represents an immutable regular expression.
 To browse the .NET Framework source code for this type, 
 see the Reference Source.
.PP
.PP
\fBstrings\fB \fR\- The string to search for a match.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
