.\" man page create by R# package system.
.TH STRINGR 1 2020-11-02 "regexp" "regexp"
.SH NAME
regexp \- Initializes a new instance of the \fBRegularExpression\fR class
.SH SYNOPSIS
\fIregexp(\fBpattern\fR as string, 
\fBoptions\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Initializes a new instance of the \fBRegularExpression\fR class
 for the specified regular expression **`pattern`**.
.PP
.SH OPTIONS
.PP
\fBpattern\fB \fR\- the specified regular expression
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
