.\" man page create by R# package system.
.TH STRINGR 1 2020-11-02 "sprintf" "sprintf"
.SH NAME
sprintf \- Use C-style String Formatting Commands
.SH SYNOPSIS
\fIsprintf(\fBformat\fR as <generic> Array, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Use C-style String Formatting Commands
 
 A wrapper for the C function sprintf, that returns a character 
 vector containing a formatted combination of text and variable 
 values.
.PP
.SH OPTIONS
.PP
\fBformat\fB \fR\- -
.PP
.PP
\fBarguments\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
