.\" man page create by R# package system.
.TH STRINGR 1 2020-12-15 "str_pad" "str_pad"
.SH NAME
str_pad \- Pad A String.
.SH SYNOPSIS
\fIstr_pad(\fBstring\fR as string, 
\fBwidth\fR as integer, 
\fBside\fR as <integer> str_padSides = [left], 
\fBpad\fR as string =);\fR
.SH DESCRIPTION
.PP
Pad A String.
.PP
.SH OPTIONS
.PP
\fBstring\fB \fR\- A character vector.
.PP
.PP
\fBwidth\fB \fR\- Minimum width of padded strings.
.PP
.PP
\fBside\fB \fR\- Side on which padding character is added (left, right or both).
.PP
.PP
\fBpad\fB \fR\- Single padding character (default is a space).
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
