.\" man page create by R# package system.
.TH STRINGR 1 2020-11-02 "tagvalue" "tagvalue"
.SH NAME
tagvalue \- parse the string text in format like \fBtag{delimiter}value\fR
.SH SYNOPSIS
\fItagvalue(\fBstring\fR as string, 
\fBdelimiter\fR as string = " ", 
\fBtrim_value\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parse the string text in format like \fBtag{delimiter}value\fR
.PP
.SH OPTIONS
.PP
\fBstring\fB \fR\- -
.PP
.PP
\fBdelimiter\fB \fR\- -
.PP
.PP
\fBtrim_value\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
