.\" man page create by R# package system.
.TH STRINGR 1 2020-10-29 "tolower" "tolower"
.SH NAME
tolower \- Character Translation and Casefolding
.SH SYNOPSIS
\fItolower(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Character Translation and Casefolding
 
 Translate characters in character vectors, in particular 
 from upper to lower case or vice versa.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a character vector, or an object that can be coerced to character by 
 \fBas.character\fR.

.PP
.SH VALUE
.PP
A character vector of the same length and with the same attributes as 
 \fBx\fR (after possible coercion).
 
 Elements of the result will be have the encoding declared as that of 
 the current locale (see Encoding) if the corresponding input had a 
 declared encoding And the current locale Is either Latin-1 Or UTF-8. 
 The result will be in the current locale's encoding unless the 
 corresponding input was in UTF-8, when it will be in UTF-8 when the 
 system has Unicode wide characters.
.PP
.SH DETAILS
.PP
chartr translates each character in x that is specified in old 
 to the corresponding character specified in new. Ranges are 
 supported in the specifications, but character classes and 
 repeated characters are not. If old contains more characters than 
 new, an error is signaled; if it contains fewer characters, the 
 extra characters at the end of new are ignored.
 
 \fBtolower\fR And \fBtoupper\fR convert upper-case characters in a 
 character vector to lower-case, Or vice versa. Non-alphabetic 
 characters are left unchanged.
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
