.\" man page create by R# package system.
.TH STRINGR 1 2020-11-09 "toString" "toString"
.SH NAME
toString \- Convert an R Object to a Character String
.SH SYNOPSIS
\fItoString(\fBx\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Convert an R Object to a Character String
 
 This is a helper function for format to produce a 
 single character string describing an R object.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- The object to be converted.
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
