.\" man page create by R# package system.
.TH STRINGR 1 2020-11-02 "urldecode" "urldecode"
.SH NAME
urldecode \- Decodes URL-encoded string
.SH SYNOPSIS
\fIurldecode(\fBstr\fR as string);\fR
.SH DESCRIPTION
.PP
Decodes URL-encoded string
 
 Decodes any \fB%##\fR encoding in the given string. 
 Plus symbols ('+') are decoded to a space character.
.PP
.SH OPTIONS
.PP
\fBstr\fB \fR\- The string to be decoded.
.PP
.SH VALUE
.PP
Returns the decoded string.
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
Copyright © xie.guigang@gcmodeller.org 2019
