#Region "Microsoft.VisualBasic::cdd80b28a2493885d1964f5656163e8a, core\Bio.Assembly\Resources\transl_table\TranslTables.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 462
    '    Code Lines: 130 (28.14%)
    ' Comment Lines: 304 (65.80%)
    '    - Xml Docs: 7.57%
    ' 
    '   Blank Lines: 28 (6.06%)
    '     File Size: 22.04 KB


    '     Class TranslTables
    ' 
    '         Properties: Culture, Genetic_Codes, ResourceManager, transl_table_1, transl_table_10
    '                     transl_table_11, transl_table_12, transl_table_13, transl_table_14, transl_table_16
    '                     transl_table_2, transl_table_21, transl_table_22, transl_table_23, transl_table_24
    '                     transl_table_25, transl_table_3, transl_table_4, transl_table_5, transl_table_6
    '                     transl_table_9
    ' 
    '         Constructor: (+1 Overloads) Sub New
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TranslTables
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.TranslTables", GetType(TranslTables).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Genetic Codes
        '''
        '''Compiled by Andrzej (Anjay) Elzanowski and Jim Ostell at National Center for Biotechnology Information (NCBI), Bethesda, Maryland, U.S.A.
        '''
        '''Last update of the Genetic Codes: April 30, 2013
        '''
        '''
        '''
        '''NCBI takes great care to ensure that the translation for each coding sequence (CDS) present in GenBank records is correct. Central to this effort is careful checking on the taxonomy of each record and assignment of the correct genetic code (shown as a /transl_table qualifier on the CDS in the  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Genetic_Codes() As String
            Get
                Return ResourceManager.GetString("Genetic Codes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=1
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA * Ter  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu i    CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_1() As String
            Get
                Return ResourceManager.GetString("transl_table-1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=10
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA C Cys  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_10() As String
            Get
                Return ResourceManager.GetString("transl_table-10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=11
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA * Ter  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu i    CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile i    ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_11() As String
            Get
                Return ResourceManager.GetString("transl_table-11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=12
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA * Ter  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG S Ser i    CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_12() As String
            Get
                Return ResourceManager.GetString("transl_table-12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=13
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_13() As String
            Get
                Return ResourceManager.GetString("transl_table-13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=14
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA Y Tyr      TGA W Trp  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_14() As String
            Get
                Return ResourceManager.GetString("transl_table-14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=16
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA * Ter  
        '''TTG L Leu      TCG S Ser      TAG L Leu      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_16() As String
            Get
                Return ResourceManager.GetString("transl_table-16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=2
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile i    ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_2() As String
            Get
                Return ResourceManager.GetString("transl_table-2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=21
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_21() As String
            Get
                Return ResourceManager.GetString("transl_table-21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=22
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA * Ter      TAA * Ter      TGA * Ter  
        '''TTG L Leu      TCG S Ser      TAG L Leu      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_22() As String
            Get
                Return ResourceManager.GetString("transl_table-22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=23
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA * Ter      TCA S Ser      TAA * Ter      TGA * Ter  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile i    ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_23() As String
            Get
                Return ResourceManager.GetString("transl_table-23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=24
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu i    CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_24() As String
            Get
                Return ResourceManager.GetString("transl_table-24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=25
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA G Gly  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_25() As String
            Get
                Return ResourceManager.GetString("transl_table-25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=3
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT T Thr      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC T Thr      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA T Thr      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG T Thr      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_3() As String
            Get
                Return ResourceManager.GetString("transl_table-3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=4
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu i    TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu i    CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile i    ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_4() As String
            Get
                Return ResourceManager.GetString("transl_table-4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=5
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu i    TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile i    ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_5() As String
            Get
                Return ResourceManager.GetString("transl_table-5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=6
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA Q Gln      TGA * Ter  
        '''TTG L Leu      TCG S Ser      TAG Q Gln      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_6() As String
            Get
                Return ResourceManager.GetString("transl_table-6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transl_table=9
        '''
        '''TTT F Phe      TCT S Ser      TAT Y Tyr      TGT C Cys  
        '''TTC F Phe      TCC S Ser      TAC Y Tyr      TGC C Cys  
        '''TTA L Leu      TCA S Ser      TAA * Ter      TGA W Trp  
        '''TTG L Leu      TCG S Ser      TAG * Ter      TGG W Trp  
        '''
        '''CTT L Leu      CCT P Pro      CAT H His      CGT R Arg  
        '''CTC L Leu      CCC P Pro      CAC H His      CGC R Arg  
        '''CTA L Leu      CCA P Pro      CAA Q Gln      CGA R Arg  
        '''CTG L Leu      CCG P Pro      CAG Q Gln      CGG R Arg  
        '''
        '''ATT I Ile      ACT T Thr   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property transl_table_9() As String
            Get
                Return ResourceManager.GetString("transl_table-9", resourceCulture)
            End Get
        End Property
    End Class
End Namespace

