.\" man page create by R# package system.
.TH BIOMODELS.TRN 1 2000-Jan "fpkm.connections" "fpkm.connections"
.SH NAME
fpkm.connections \- 
.SH SYNOPSIS
\fIfpkm.connections(\fBfpkm\fR as <generic> DataSet[], 
\fBcutoff\fR as double = 0.65);\fR
.SH SEE ALSO
bioModels.TRN
.SH FILES
.PP
cytoscape_toolkit.dll
.PP
