.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "export_modular_response" "export_modular_response"
.SH NAME
export_modular_response \- 
.SH SYNOPSIS
\fIexport_modular_response(\fBx\fR as <generic> BlockResponseResult, 
\fBoutputdir\fR as string);\fR
.SH SEE ALSO
bnlearn
.SH FILES
.PP
biosystem.dll
.PP
