.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "overexpress" "overexpress"
.SH NAME
overexpress \- run the in silico gene overexpression experiment on the given network model
.SH SYNOPSIS
\fIoverexpress(\fBbnlearn\fR as <generic> InsilicoPerturbationExperiment, 
\fBgeneNames\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run the in silico gene overexpression experiment on the given network model
.PP
.SH OPTIONS
.PP
\fBbnlearn\fB \fR\- 
 the trained network model object, which could be created by the \fBbnlearn\fR 
 api or the \fBGEARS::new\fR api.
. 
.PP
.PP
\fBgeneNames\fB \fR\- 
 a character vector of the gene id for run the overexpression experiment, 
 one @\fBT:SMRUCC.genomics.Analysis.BNLearn.Intervention.InterventionResult\fR object will be generated for each gene.
. 
.PP
.PP
\fBenv\fB \fR\- the R# runtime environment object.. 
.PP
.SH VALUE
.PP
a vector of the @\fBT:SMRUCC.genomics.Analysis.BNLearn.Intervention.InterventionResult\fR perturbation result: the 
 \fBWildtypeMeans\fR is the wildtype expression value of each gene, the 
 \fBMutantMeans\fR is the expression value of each gene after the gene has been 
 overexpressed, and the \fBFoldChanges\fR, \fBPercentChanges\fR, \fBZScores\fR and 
 \fBIsSignificant\fR data is the differential analysis result of the 
 perturbation.
.PP
.SH SEE ALSO
bnlearn
.SH FILES
.PP
biosystem.dll
.PP
