.\" man page create by R# package system.
.TH BNLEARN 1 2000-1月 "wildtype_baseline" "wildtype_baseline"
.SH NAME
wildtype_baseline \- set wildtype baseline
.SH SYNOPSIS
\fIwildtype_baseline(\fBmodel\fR as any, 
\fBbaseline\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set wildtype baseline
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- @\fBT:SMRUCC.genomics.Analysis.BNLearn.Core.BNLearnWorkflow\fR or @\fBT:SMRUCC.genomics.Analysis.BNLearn.ModularNetwork.BlockBayesianNetwork\fR. 
.PP
.PP
\fBbaseline\fB \fR\- a value list tuple of the baseline expression value, example as list(gene1=xxx,gene2=xxx,...). 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
bnlearn
.SH FILES
.PP
biosystem.dll
.PP
