.\" man page create by R# package system.
.TH MULTI_OMICS 1 2000-1月 "map_force" "map_force"
.SH NAME
map_force \- 
.SH SYNOPSIS
\fImap_force(\fBx\fR as <generic> Matrix, 
\fBy\fR as <generic> Matrix, 
\fBmaps\fR as <generic> Background);\fR
.SH SEE ALSO
multi_omics
.SH FILES
.PP
phenotype_kit.dll
.PP
