.\" man page create by R# package system.
.TH MULTI_OMICS 1 2000-Jan "omics.2D_scatter" "omics.2D_scatter"
.SH NAME
omics.2D_scatter \- 
.SH SYNOPSIS
\fIomics.2D_scatter(\fBx\fR as any, 
\fBy\fR as any, 
\fBxlab\fR as string = "X", 
\fBylab\fR as string = "Y", 
\fBsize\fR as any = "3000,3000", 
\fBpadding\fR as any = "padding: 200px 250px 200px 100px;", 
\fBptSize\fR as double = 10, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
multi_omics
.SH FILES
.PP
phenotype_kit.dll
.PP
