.\" man page create by R# package system.
.TH SAMPLEINFO 2 2000-01-01 "guess.sample_groups" "guess.sample_groups"
.SH NAME
guess.sample_groups \- try to parse the sampleInfo data from the
.SH SYNOPSIS
\fIguess.sample_groups(\fBsample_names\fR as <generic> Array, 
\fBmaxDepth\fR as boolean = FALSE, 
\fBraw_list\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
try to parse the sampleInfo data from the
 sample labels
.PP
.SH OPTIONS
.PP
\fBsample_names\fB \fR\- -. 
.PP
.PP
\fBraw_list\fB \fR\- -. 
.PP
.SH SEE ALSO
sampleInfo
.SH FILES
.PP
phenotype_kit.dll
.PP
