.\" man page create by R# package system.
.TH SAMPLEINFO 2 2000-1月 "make.analysis" "make.analysis"
.SH NAME
make.analysis \- 
.SH SYNOPSIS
\fImake.analysis(\fBsampleinfo\fR as <generic> SampleInfo[], 
\fBcontrol\fR as string, 
\fBtreatment\fR as string);\fR
.SH SEE ALSO
sampleInfo
.SH FILES
.PP
phenotype_kit.dll
.PP
