.\" man page create by R# package system.
.TH SAMPLEINFO 2 2000-1月 "read.sampleinfo" "read.sampleinfo"
.SH NAME
read.sampleinfo \- Read the sampleinfo data table from a given csv file
.SH SYNOPSIS
\fIread.sampleinfo(\fBfile\fR as string, 
\fBtsv\fR as boolean = FALSE, 
\fBexclude_groups\fR as string = \fB<NULL>\fR, 
\fBid_makenames\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Read the sampleinfo data table from a given csv file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBtsv\fB \fR\- -. 
.PP
.PP
\fBexclude_groups\fB \fR\- -. 
.PP
.PP
\fBid_makenames\fB \fR\- -. 
.PP
.SH SEE ALSO
sampleInfo
.SH FILES
.PP
phenotype_kit.dll
.PP
