.\" man page create by R# package system.
.TH SAMPLEINFO 2 2000-1月 "sampleId" "sampleId"
.SH NAME
sampleId \- Get sample id collection from a speicifc sample data groups
.SH SYNOPSIS
\fIsampleId(\fBsampleinfo\fR as any, 
\fBgroups\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get sample id collection from a speicifc sample data groups
.PP
.SH OPTIONS
.PP
\fBsampleinfo\fB \fR\- -. 
.PP
.PP
\fBgroups\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
sampleInfo
.SH FILES
.PP
phenotype_kit.dll
.PP
