.\" man page create by R# package system.
.TH SAMPLEINFO 2 2000-Jan "sampleinfo.text.groups" "sampleinfo.text.groups"
.SH NAME
sampleinfo.text.groups \- Create sampleInfo table from text files
.SH SYNOPSIS
\fIsampleinfo.text.groups(\fBdir\fR as string);\fR
.SH DESCRIPTION
.PP
Create sampleInfo table from text files
.PP
.SH OPTIONS
.PP
\fBdir\fB \fR\- -. 
.PP
.SH SEE ALSO
sampleInfo
.SH FILES
.PP
phenotype_kit.dll
.PP
