.\" man page create by R# package system.
.TH SAMPLEINFO 2 2000-1月 "write.sampleinfo" "write.sampleinfo"
.SH NAME
write.sampleinfo \- save sampleinfo data as csv file
.SH SYNOPSIS
\fIwrite.sampleinfo(\fBsampleinfo\fR as <generic> SampleInfo[], 
\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
save sampleinfo data as csv file
.PP
.SH OPTIONS
.PP
\fBsampleinfo\fB \fR\- 
 a vector of the @\fBT:SMRUCC.genomics.GCModeller.Workbench.ExperimentDesigner.SampleInfo\fR sample information data for save 
 into the target csv table file.
. 
.PP
.PP
\fBfile\fB \fR\- 
 the file path of the generated sample information csv table file.
. 
.PP
.SH VALUE
.PP
a boolean value for indicates that the sample information data has been 
 saved into the target file successfully or not.
.PP
.SH DETAILS
.PP
You also can save the sampleinfo data directly via the \fBwrite.csv\fR function.
.PP
.SH SEE ALSO
sampleInfo
.SH FILES
.PP
phenotype_kit.dll
.PP
