.\" man page create by R# package system.
.TH PTF 1 2000-1月 "cache.ptf" "cache.ptf"
.SH NAME
cache.ptf \- create a protein annotation metadata file
.SH SYNOPSIS
\fIcache.ptf(\fBuniprot\fR as any, 
\fBfile\fR as any, 
\fBdb_xref\fR as any = ["Bgee","KEGG","KO","GO","Pfam","RefSeq","EC","InterPro","BioCyc","eggNOG","keyword"], 
\fBcacheTaxonomy\fR as boolean = FALSE, 
\fBhds_stream\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a protein annotation metadata file
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBdb_xref\fB \fR\- -. 
.PP
.PP
\fBcacheTaxonomy\fB \fR\- -. 
.PP
.PP
\fBhds_stream\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
