.\" man page create by R# package system.
.TH PTF 1 2000-01-01 "cache.ptf" "cache.ptf"
.SH NAME
cache.ptf \- 
.SH SYNOPSIS
\fIcache.ptf(\fBuniprot\fR as any, 
\fBfile\fR as any, 
\fBdb_xref\fR as any = ["KEGG","KO","GO","Pfam","RefSeq","EC","InterPro","BioCyc","eggNOG","keyword"], 
\fBcacheTaxonomy\fR as boolean = FALSE, 
\fBhds_stream\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
