.\" man page create by R# package system.
.TH PTF 1 2000-Jan "fromDataframe" "fromDataframe"
.SH NAME
fromDataframe \- Create the protein annotation data model from a given dataframe object
.SH SYNOPSIS
\fIfromDataframe(\fBx\fR as <generic> dataframe, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create the protein annotation data model from a given dataframe object
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 + gene_id
 + locus_id
 + gene_name
 + description
 + sequence
 + ...
. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
