.\" man page create by R# package system.
.TH PTF 1 2000-1月 "list.xrefs" "list.xrefs"
.SH NAME
list.xrefs \- enumerate all database name from a HDS stream
.SH SYNOPSIS
\fIlist.xrefs(\fBptf\fR as <generic> StreamPack);\fR
.SH DESCRIPTION
.PP
enumerate all database name from a HDS stream
.PP
.SH OPTIONS
.PP
\fBptf\fB \fR\- -. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
