.\" man page create by R# package system.
.TH PTF 1 2000-1月 "load_xref" "load_xref"
.SH NAME
load_xref \- load the cross reference id set
.SH SYNOPSIS
\fIload_xref(\fBptf\fR as any, 
\fBdatabase\fR as string, 
\fBflip\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load the cross reference id set
.PP
.SH OPTIONS
.PP
\fBptf\fB \fR\- a collection of the protein annotation data or the @\fBT:Microsoft.VisualBasic.DataStorage.HDSPack.FileSystem.StreamPack\fR database connection. 
.PP
.PP
\fBdatabase\fB \fR\- the database name. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
