.\" man page create by R# package system.
.TH PTF 1 2000-Jan "load_xref" "load_xref"
.SH NAME
load_xref \- load the cross reference id set
.SH SYNOPSIS
\fIload_xref(\fBptf\fR as <generic> StreamPack, 
\fBdatabase\fR as string);\fR
.SH DESCRIPTION
.PP
load the cross reference id set
.PP
.SH OPTIONS
.PP
\fBptf\fB \fR\- -. 
.PP
.PP
\fBdatabase\fB \fR\- the database name. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
