.\" man page create by R# package system.
.TH PTF 1 2000-1月 "name_xrefs" "name_xrefs"
.SH NAME
name_xrefs \- Extract gene_id to gene name mapping
.SH SYNOPSIS
\fIname_xrefs(\fBptf\fR as any, 
\fBsplit\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Extract gene_id to gene name mapping
.PP
.SH OPTIONS
.PP
\fBptf\fB \fR\- -. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
