.\" man page create by R# package system.
.TH PTF 1 2000-01-01 "read.ptf" "read.ptf"
.SH NAME
read.ptf \- read the protein annotation database
.SH SYNOPSIS
\fIread.ptf(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read the protein annotation database
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
