.\" man page create by R# package system.
.TH PTF 1 2000-Jan "write.ptf" "write.ptf"
.SH NAME
write.ptf \- create a protein annotation metadata file from the uniprot dataset
.SH SYNOPSIS
\fIwrite.ptf(\fBproteins\fR as any, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a protein annotation metadata file from the uniprot dataset
.PP
.SH OPTIONS
.PP
\fBuniprot\fB \fR\- a collection of the protein data from the uniprot database. 
.PP
.PP
\fBfile\fB \fR\- file path to save the metadata file. 
.PP
.PP
\fBdb_xref\fB \fR\- -. 
.PP
.PP
\fBcacheTaxonomy\fB \fR\- -. 
.PP
.PP
\fBhds_stream\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
ptf
.SH FILES
.PP
annotationKit.dll
.PP
