#Region "Microsoft.VisualBasic::3160d3b18fc5ab9c120521095986b66a, GCModeller\models\Networks\KEGG\My Project\Resources.Designer.vb"

    ' Author:
    ' 
    '       asuka (amethyst.asuka@gcmodeller.org)
    '       xie (genetics@smrucc.org)
    '       xieguigang (xie.guigang@live.com)
    ' 
    ' Copyright (c) 2018 GPL3 Licensed
    ' 
    ' 
    ' GNU GENERAL PUBLIC LICENSE (GPL3)
    ' 
    ' 
    ' This program is free software: you can redistribute it and/or modify
    ' it under the terms of the GNU General Public License as published by
    ' the Free Software Foundation, either version 3 of the License, or
    ' (at your option) any later version.
    ' 
    ' This program is distributed in the hope that it will be useful,
    ' but WITHOUT ANY WARRANTY; without even the implied warranty of
    ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ' GNU General Public License for more details.
    ' 
    ' You should have received a copy of the GNU General Public License
    ' along with this program. If not, see <http://www.gnu.org/licenses/>.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 136
    '    Code Lines: 37
    ' Comment Lines: 90
    '   Blank Lines: 9
    '     File Size: 4.37 KB


    '     Module Resources
    ' 
    '         Properties: CommonIgnores, Culture, ResourceManager
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.Model.Network.KEGG.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C00001
        '''C00002
        '''C00003
        '''C00004
        '''C00005
        '''C00006
        '''C00007
        '''C00008
        '''C00010
        '''C00011
        '''C00012
        '''C00014
        '''C00028
        '''C00030
        '''C00050
        '''C00138
        '''C00139
        '''C00174
        '''C00205
        '''C00215
        '''C00290
        '''C00298
        '''C00326
        '''C00338
        '''C00340
        '''C00367
        '''C00373
        '''C00377
        '''C00391
        '''C00393
        '''C00435
        '''C00464
        '''C00496
        '''C00505
        '''C00516
        '''C00551
        '''C00562
        '''C00569
        '''C00662
        '''C00667
        '''C00701
        '''C00723
        '''C00752
        '''C00759
        '''C00775
        '''C00787
        '''C00807
        '''C00816
        '''C00824
        '''C00840
        '''C00912
        '''C00917
        '''C00923
        '''C00924
        '''C00934
        '''C00949
        '''C00952
        '''C00991
        '''C00995
        '''C00996
        '''C00997
        '''C00998
        '''C00999
        '''C01000
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CommonIgnores() As String
            Get
                Return ResourceManager.GetString("CommonIgnores", resourceCulture)
            End Get
        End Property
    End Module
End Namespace

